### ISSUE TITLE
Ads package depends on Adslite?

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/GooglePlayServicesComponents#101]
why adslite library is installed when I install ads library? and i cant remove it. see the screenshot below is self-explanatory. If i remember correct, it was not the case for version 42 

![image](https://user-images.githubusercontent.com/10422347/38135904-0611f708-341b-11e8-9470-3e9d87503f20.png)

**Comment by Redth** [comment]
This is the dependency chain that Google has created for their libraries.  We have to follow what they choose here.
