### ISSUE TITLE
Firestore ProjectId is always null

### ISSUE THREAD

**Issue by Implisam** [xamarin/GooglePlayServicesComponents#104]
Xamarin.Firebase.Firestore is now available but whenever i try to:

`FirebaseFirestore.GetInstance(FireApp)`

it throws:

`FirebaseOptions.getProjectId() cannot be null`

**Comment by srujalsk** [comment]
Any idea when this defect is going to be fixed ?

**Comment by consoleit** [comment]
same problem here

**Comment by yamachu** [comment]
ref: https://github.com/xamarin/GooglePlayServicesComponents/issues/121

I'm using Xamarin.Firebase.Firestore 60.1142.1

If you are using google-service.json, try below code.

```csharp
const string AppName = "SampleAppName";

var baseOptions = Firebase.FirebaseOptions.FromResource(this);
var options = new Firebase.FirebaseOptions.Builder(baseOptions).SetProjectId(baseOptions.ApplicationId.Split('.')[0]).Build();
var app = Firebase.FirebaseApp.InitializeApp(this, options, AppName);
var firestore = FirebaseFirestore.GetInstance(app);
```

If you set some configuration value in code, try it.

```csharp
const string AppName = "SampleAppName";

var options = new Firebase.FirebaseOptions.Builder()
            .SetApplicationId("YOUR mobilesdk_app_id")
            .SetApiKey("YOUR APIKEY")
            .SetDatabaseUrl($"https://{YOUR project_id}.firebaseio.com")
            .SetGcmSenderId("YOUR project_number")
            .SetStorageBucket("YOUR storage_bucket")
            .SetProjectId("YOUR project_id")
            .Build();

var app = Firebase.FirebaseApp.InitializeApp(this, options, AppName);
var firestore = FirebaseFirestore.GetInstance(app);
```

But, we need the fundamental solution...

**Comment by Redth** [comment]
We were missing obviously project_id in our build task that maps the json file to resources.  I've add this which will be available in the next release: 723ebdc00867a4c70c51ad2d0dcbd36474ce8ff1

**Comment by Redth** [comment]
@yamachu thanks for the work around in the meantime :)

**Comment by marcogramy** [comment]
@yamachu Thank you very much for your help!
I'm also trying to integrate Firestore in my Xamarin project but without success. Perhaps do you have some piece of code that you can share with us? :)

**Comment by cfl777** [comment]
@Redth Thanks for your help - how long until this is released?

**Comment by yamachu** [comment]
@marcogramy Sorry for my late reply.
I shared wrong code... it was a code under verification

Please try below code.

```cs
var baseOptions = Firebase.FirebaseOptions.FromResource(this);
// This HACK will be not needed, fixed in https://github.com/xamarin/GooglePlayServicesComponents/commit/723ebdc00867a4c70c51ad2d0dcbd36474ce8ff1
var options = new Firebase.FirebaseOptions.Builder(baseOptions).SetProjectId(baseOptions.StorageBucket.Split('.')[0]).Build();
var app = Firebase.FirebaseApp.InitializeApp(this, options, "MYAPP");

var db = FirebaseFirestore.GetInstance(app);
```

**Comment by yamachu** [comment]
@marcogramy Here is sample project
https://github.com/yamachu/LetsStart-Firestore-Xamarin.Forms

**Comment by wolf81** [comment]
Seems this issue is still not fixed in the tooling. I have to use the first solution described by @yamachu (config manually in app).
