### ISSUE TITLE
Security issues during Android app audit

### ISSUE THREAD

**Issue by mariorasch** [xamarin/GooglePlayServicesComponents#106]
### Xamarin.Android Version (eg: 6.0):

not relevant

### Operating System & Version (eg: Mac OSX 10.11):

not relevant

### Google Play Services Version (eg: 8.4.0):

Version 60.1142.1 of the Xamarin.GooglePlayServices... NuGet packages. Alas I do not exactly know to which Google Play Services version these packages refer.

### Describe your Issue:

In our Xamarin Forms PCL solution we added the following references to the Android app in order to process push notifications:

- Xamarin.GooglePlayServices.Base
- Xamarin.GooglePlayServices.Basement
- Xamarin.GooglePlayServices.Gcm
- Xamarin.GooglePlayServices.Iid
- Xamarin.GooglePlayServices.Tasks

References are added by using version 60.1142.1 of the Xamarin.GooglePlayServices... NuGet packages.

Now a security service provider for one of our customers performed a security audit of our Android app using an unknown software tool.

I think as a side effect of the references mentioned above that tool complains about our Android app apparently using at least the following third party Google services (from which AdSense is rated as the most severe):

- Google Fit
- Google Play Games
- Google+
- Google AdSense

Of course from the assemblies we referenced we knowingly do not use any other Google Play Service than GCM.

So therefore I have the following questions:

1. Do the assemblies mentioned above indeed refer to any of the third party Google services mentioned above, either explicitly or implicitly?

2. Is there any possibility to do a custom build of the assemblies mentioned above or to configure them through the app manifest so that they only refer to the Google GCM service?

Many thanks in advance & best regards!

### Steps to Reproduce (with link to sample solution if possible):

not relevant

### Include any relevant Exception Stack traces, build logs, adb logs:

not relevant

**Comment by Redth** [comment]
These refer to Google Play Services 11.4.2.  Essentially, GCM depends on Iid and Tasks, and in turn those depend on Base and Basement.  Even though you are just using GCM, that library itself requires these others as dependencies.

I'm not sure why your tool thinks you're using Fit, Games, + and AdSense... There may be some types in those java packages which are actually inside of Base or Basement, but generally that's not the case.

It's hard to give a good answer without knowing a bit more about what this tool is looking for as a basis for its claims.

**Comment by mariorasch** [comment]
Thanks! Right now this issue is on hold as we did not get any more detailed information from the security service provider involved.

**Comment by newky2k** [comment]
Issue is on hold and not further information has been provided
