### ISSUE TITLE
No access to CurrentSession in Cast 

### ISSUE THREAD

**Issue by PSyron** [xamarin/GooglePlayServicesComponents#107]
### Xamarin.Android Version (eg: 6.0):
Target framework 8.1

### Operating System & Version (eg: Mac OSX 10.11):
Mac OSX newest

### Google Play Services Version (eg: 8.4.0):
Newest

### Describe your Issue:
Casting works fine but whenever I need CurrentSession/CurrentCastSession from SessionManager it is null, both of them. I'm trying to implement start-stop button for cast but w/o it that seems impossible. 
What is needed for CurrentSession. I've added listener for SessionManager but it never gets "SessionStarted" or any other callbacks.

### Steps to Reproduce (with link to sample solution if possible):
Cast media and try to retrieve current session.

**Comment by newky2k** [comment]
@PSyron  could you please provide a demo project to make it easier for us to replicate this issue.

Thanks in advance

**Comment by newky2k** [comment]
no response for two weeks closing
