### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/R$string;

### ISSUE THREAD

**Issue by PavanGundapanthula** [xamarin/GooglePlayServicesComponents#108]
Xamarin.Mac
Version: 4.2.1.28 (Visual Studio Community)

Xamarin.Android
Version: 8.2.0.16 (Visual Studio Community)

NuGet
Version: 4.3.1.4445

Operating System & Version (eg: Mac OSX 10.11):
MAC OS High Sierra
10.13.3 (17D47)

Getting the following error while deploying the xamarin solution on emulator : 

[AndroidRuntime] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/R$string;
[AndroidRuntime] 	at com.google.android.gms.common.internal.zzbz.<init>(Unknown Source:14)
[AndroidRuntime] 	at com.google.firebase.FirebaseOptions.fromResource(Unknown Source:2)
[AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:19)
[AndroidRuntime] 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source:4)
[AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
[AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
[AndroidRuntime] 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:23)
[AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:6285)
[AndroidRuntime] 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851)
[AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772)
[AndroidRuntime] 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:105)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:164)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6541)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
[AndroidRuntime] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.R$string" on path: DexPathList[[zip file "/data/app/com.isagenix.qualia-GIBkmFw1OBJ_Ts_u0oE7Bw==/base.apk"],nativeLibraryDirectories=[/data/app/com.isagenix.qualia-GIBkmFw1OBJ_Ts_u0oE7Bw==/lib/x86, /system/fake-libs, /data/app/com.isagenix.qualia-GIBkmFw1OBJ_Ts_u0oE7Bw==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
[AndroidRuntime] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by Qonstrukt** [comment]
This might be related: https://github.com/xamarin/GooglePlayServicesComponents/issues/69

**Comment by justintoth** [comment]
Same issue here.

**Comment by darochapires** [comment]
I'm having the same issue.

**Comment by newky2k** [comment]
@PavanGundapanthula @Qonstrukt @justintoth  sorry for the delay in looking into this for you.  Have you converted to PackageReferences instead of packages.config?  does doing so make a difference, might be a long shot, but worth a try.  

Does it matter what version of Android the simulator is running? does it occur if you build and deploy straight on to a device?

Could you provide some more specifics on the target enviroment as well as trying the lastest preview of GPS, to see if this resolves it at all for you.

Thank you for your patience

**Comment by NarrowOne** [comment]
I've run into the same issue here.
@newky2k personally, I've tried running on Android 6.0-8.0 and it hasn't worked with any and I've tried it on my phone as well with the same result.

how do I convert to PackageReferences and i can try that?

**Comment by newky2k** [comment]
@NarrowOne  this blog from @mrward give details on how to convert a non-core project to use PackageReferences -> https://lastexitcode.com/blog/2017/08/26/NuGetSupportInVisualStudioMac7-1/  current there isnt any UI to do it in VSfM.

**Comment by newky2k** [comment]
no response for two weeks.  closing
