### ISSUE TITLE
Error downloading dependencies for Marshmallow v6

### ISSUE THREAD

**Issue by nQuantPlatforms** [xamarin/GooglePlayServicesComponents#109]
I'm developing native android app and trying to implement AdMob. 

### **Android Version:**
v6.0 Marshmallow (SDK 23)
Xamarin.Android.Support.v4 (23.4.0.1)

### **IDE:**
Visual Studio 2017 (15.6.5)
Android Native (Not using Xamarin forms)
NETStandard v2.0.1

### Describe your Issue:
I have all the Google SDK 23, 24 and 25 installed.
Trying to install AdMob but was facing issues so tried only **Xamarin.GooglePlayServices.Basement**, and getting same exception below. Tried manually downloading and extracting zip file like suggested on some other issues, but nothing works. 

Also I dont see this SDK version in list for this component. I really need to to keep minimum android version to target Marshmallow. Whats the alternative?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		An error occurred trying to install required android components on Project 'xxx'.
Project 'xxx' requires the following components installed on your machine: 
Xamarin.GooglePlayServices.Basement
JavaLibraryReference: https://dl-ssl.google.com/android/repository/google_m2repository_r24.zip-m2repository/com/google/android/gms/play-services-basement/8.4.0/play-services-basement-8.4.0.aar-8.4.0
AndroidResources: https://dl-ssl.google.com/android/repository/google_m2repository_r24.zip-m2repository/com/google/android/gms/play-services-basement/8.4.0/play-services-basement-8.4.0.aar-8.4.0


Please double-click here to install it.

Intallation Errors: XA5209 Unzipping failed. Please download 'https://dl-ssl.google.com/android/repository/google_m2repository_r24.zip:m2repository/com/google/android/gms/play-services-basement/8.4.0/play-services-basement-8.4.0.aar' and extract it to the 'C:\Users\xxx\AppData\Local\Xamarin\Xamarin.GooglePlayServices.Basement\8.4.0\embedded' directory
XA5209 Reason: Could not find a part of the path 'C:\Users\xx\AppData\Local\Xamarin\Xamarin.GooglePlayServices.Basement\8.4.0\embedded\res\'.
XA5207 Please install package: 'GPS Basement' available in SDK installer. Java library file 'C:\Program Files (x86)\Android\android-sdk\extras\google\classes.jar' doesn't exist.		 	0	

```

**Comment by Redth** [comment]
Please use a newer version of Play Services nuget packages.

You can still keep your minimum version to a lower SDK version than your Target Framework.
