### ISSUE TITLE
AdMob: “IllegalStateException: Only fullscreen activities can request orientation” when targeting Android SDK 27

### ISSUE THREAD

**Issue by akamud** [xamarin/GooglePlayServicesComponents#110]
### Describe your Issue:
When using AdMob Interstitial Ads, if you target Android SDK 27, the app will crash with the message "IllegalStateException: Only fullscreen activities can request orientation".

### Steps to Reproduce (with link to sample solution if possible):
Run the AdMob test project targeting Android SDK 27.

Now, this was clearly a bug in Google's package as reported [here](https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/8zPchu8c0Ko) and [here](https://issuetracker.google.com/issues/68427483). But apparently it is fixed in Firebase packages 12.0+, which is available since March. We need an update here to bring in those new packages and fix the issues for people targeting Android SDK 27 on Xamarin.

**Comment by akamud** [comment]
Any word on this? Is the new version being worked on?

**Comment by newky2k** [comment]
@akamud there is a new preview 2 of 70.1501.0.  Could you try this and see if it resolved the issue for you.

Thank you for your patience

**Comment by newky2k** [comment]
no response for two weeks, closing
