### ISSUE TITLE
Upgrade to Google Play Services v15

### ISSUE THREAD

**Issue by csdinon** [xamarin/GooglePlayServicesComponents#112]
### Xamarin.Android Version (eg: 6.0):
N/A

### Operating System & Version (eg: Mac OSX 10.11):
N/A

### Google Play Services Version (eg: 8.4.0):
N/A

### Describe your Issue:
Google Play Services has been updated to v15.0.1, which puts this binding a couple of versions behind.
There's also a known [issue](https://issuetracker.google.com/issues/65359941) that's causing a crash when checking if Google Play Services is available. According to the issue thread we need to upgrade to at least v12 to get the fix.
https://issuetracker.google.com/issues/65359941#comment27

### Steps to Reproduce (with link to sample solution if possible):
N/A

### Include any relevant Exception Stack traces, build logs, adb logs:
Latest release notes
https://developers.google.com/android/guides/releases#march_28_2018_-_version_1201

**Comment by keithfry-gm** [comment]
We're also adding a vote for GPS and Firebase v15.0.1

**Comment by akamud** [comment]
+1. Is this being worked on? The radio silence is very worrisome. Makes you question using Xamarin for apps that have a restrict time-to-market, since there is a similar problem happening with Ads Services (#110).

**Comment by Redth** [comment]
We are actively working on this now, sorry for the silence!

**Comment by akamud** [comment]
Awesome! Thank you for the update!

**Comment by Mr-Pearce** [comment]
Is There an ETA for this? 
We especially in need of the auto Opt-In Features for the Firebase services.

**Comment by ToddThomson** [comment]
@Redth Thank-you for the update. Much needed for Google Fit API.

**Comment by Mr-Pearce** [comment]
@Redth Still no update here?

**Comment by Redth** [comment]
We are close to a preview release.

**Comment by horaciojcfilho** [comment]
Great, looking forward to it, thank you very much :)

**Comment by ThomasDhaen** [comment]
I've opened a new issue for preview release #132 
Seems like the dependencies are incorrect and I can not upgrade them in my project.

**Comment by newky2k** [comment]
a new preview has been released with a final release due in the coming weeks

**Comment by tsequeira-vhs** [comment]
I am using this new package 70.1501.0-preview2 but it gives me the following error.

Unhandled Exception:

Java.Lang.ClassNotFoundException: Didn't find class "com.google.android.gms.fitness.FitnessOptions" 
on path: DexPathList[[zip file "/data/app/com.company.name--1pxKF-8OXDvsrh0N3KfTQ==/base.apk"],
nativeLibraryDirectories=[/data/app/com.company.name--1pxKF-8OXDvsrh0N3KfTQ==/lib/arm, 
/data/app/com.company.name--1pxKF-8OXDvsrh0N3KfTQ==/base.apk!/lib/armeabi-v7a, /system/lib]]

The app compiles fine but gives the above error at run time.

**Comment by Redth** [comment]
@tsequeira-vhs can you open a separate issue with a bit more information? what packages are you referencing, what does your code look like, maybe some diagnostic build output logs?

**Comment by dpawarslb** [comment]
Hi Team,
As per recommendation (https://developers.google.com/places/android-sdk/client-migration) from January 29, 2019, Google Play Services Places is required to be upgraded to version 16.0.0.
Currently the library is using the Google Play Services Places SDK version 11.4.2, which will stop functioning from July 29, 2019.
Please upgrade the library version for using the latest Google Play Services Places SDK version 16.0.0.
Thanks.
