### ISSUE TITLE
Can't install Xamarin.Firebase.Analytics.Impl 60.1142.1 while I'm already have Xamarin.Forms installed

### ISSUE THREAD

**Issue by raphaelsilvasage** [xamarin/GooglePlayServicesComponents#113]
I can't install Xamarin.Firebase.Analytics.Impl 60.1142.1 while I'm already have Xamarin.Forms 3.0.0.446417 installed.
The error is: 
"Version conflict detected for Xamarin.GooglePlayServices.Basement. Reference the package directly from the project to resolve this issue. 
[MyXamarinAndroid].Android -> Xamarin.Firebase.Analytics 60.1142.1 -> Xamarin.GooglePlayServices.Basement 60.1142.1 -> Xamarin.Android.Support.Compat (>= 26.0.2) 
[MyXamarinAndroid].Android -> Xamarin.Forms 3.0.0.446417 -> Xamarin.Android.Support.v4 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).

### Steps to Reproduce (with link to sample solution if possible):
 - Create a .NETStandard 2.0.3 Xamarin.Forms project
 - Install last Xamarin.Forms nuget package (3.0.0.446417).
 - Try to install Xamarin.Firebase.Analytics

**Comment by Redth** [comment]
You basically need to tell the IDE which version of Xamarin.Android.Support.Compat to use (in this case it's 26.0.2, typically it's just the higher version of the two mentioned) by adding an explicit PackageReference to your project with the right version.

You may need to repeat this process with different packages a few times.

Check out this post / video for more details: https://redth.codes/how-to-fix-the-dreaded-version-conflict-nuget-error-in-your-xamarin-android-projects/
