### ISSUE TITLE
Firebase.Analytics Error - Failed resolution of: Lcom/google/android/gms/R$string;

### ISSUE THREAD

**Issue by ilanolkies** [xamarin/GooglePlayServicesComponents#117]
### Xamarin.Android Version: 
8.3.0.19 (Visual Studio Community)

### Operating System & Version: 
Mac OS X 10.13.4

### Google Play Services Version: 
48

### Description:
When I add Firebse.Analytics in my project and run it I get a `Java.Lang.NoClassDefFoundError` exception. Then, I clean the Android project and rebuild it and the error is gone.

### Steps to Reproduce:
1. Create a new project.
2. Add the Firebase.Analytics Google Pklay Service
3. Run the Android app. 

I tried to reproduce it several times and I always get the same error.

### Relevant Exception:
```
Java.Lang.NoClassDefFoundError
    Message: Failed resolution of: Lcom/google/android/gms/R$string;
```

**Comment by newky2k** [comment]
@ilanolkies sorry for the delay in looking into this for you. Have you converted to PackageReferences instead of packages.config? does doing so make a difference, might be a long shot, but worth a try.

Does it matter what version of Android the simulator is running? does it occur if you build and deploy straight on to a device?

Could you provide some more specifics on the target enviroment as well as trying the lastest preview of GPS, to see if this resolves it at all for you.

Thank you for your patience

**Comment by ilanolkies** [comment]
Here's a project reference where it: https://github.com/ilanolkies/XamarinGAExample
Reference to Firebase over here: https://github.com/ilanolkies/XamarinGAExample/blob/master/GAExample.Android/GAExample.Android.csproj#L59

It does not start in any simulator, as far as I tested.

There is no problem to 'be resolved at all for me'
>  Then, I clean the Android project and rebuild it and the error is gone.
This is an issue. I came up with this writing a simple article in my blog, and this type of 'autosolvable' errors are tedious.

Thanks for the answear.

**Comment by newky2k** [comment]
@ilanolkies  Thank you for getting back to me, i will investigate further and let you know what i find

**Comment by Redth** [comment]
This is either due to an old version of the packages, or an issue with bin/ obj/ cache.  I'd suggest updating both your Xamarin install and the nuget package version.

Please open a new issue if you're still experiencing this after.

**Comment by ilanolkies** [comment]
@Redth saying that it’s an old version package problem 6 months later is funny. Anyway, thanks for helping...

**Comment by asatya001** [comment]
giving monotouch error M1201 if iset "Link all assebly" in xamarin ios, tried with --register:static argument passing in all configurations

**Comment by asatya001** [comment]
and it works when you set don't link (its not good practice though), after uploading to testflight i got terrible email from apple that it states
" Missing Purpose String in Info.plist File
with NSContactsUsageDescription, NSMicrophoneUsageDescription, NSAppleMusicUsageDescription, NSSiriUsageDescriptionl, aps-environment even though app is not using these stuff, more about my concern is ,when i go for live apple will reject the app with complains these issues, is there any work ground for it.
