### ISSUE TITLE
Package com.google.firebase.messaging does not exist

### ISSUE THREAD

**Issue by eliasribeiro** [xamarin/GooglePlayServicesComponents#118]
### Xamarin.Android Version (eg: 6.0):
Any.

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 April Updated.

### Google Play Services Version (eg: 8.4.0):
60.1142.1, 57.1104.0-Beta1(because tutorial) and 42.1021.1

### Describe your Issue:
Error on Xamarin.Firebase.Messaging, package com.google.firebase.messaging does not exist: https://drive.google.com/open?id=1ZI5Ty52twsLX2vqie-dpXldfpAkLco-G.

### Steps to Reproduce (with link to sample solution if possible):
Follow steps of video: https://youtu.be/le2lDY22xwM. Error occurs while testing in minute 46m53s. In my pc show this screen: https://drive.google.com/open?id=1ZI5Ty52twsLX2vqie-dpXldfpAkLco-G.

Note: All library installed:
Xamarin.Build.Download (v0.4.11)
Xamarin.Firebase.Messaging
Xamarin.Firebase.Iid
Xamarin.Firebase.Common
Xamarin.GooglePlayServices.Base
Xamarin.GooglePlayServices.Basement
Xamarin.GooglePlayServices.Tasks

### Include any relevant Exception Stack traces, build logs, adb logs:
1>C:\Program Files\Java\jdk1.8.0_161\\bin\javac.exe -J-Dfile.encoding=UTF8 -d obj\Debug\android\bin\classes -classpath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v8.1\mono.android.jar;obj\Debug\lp\0\jl\formsviewgroup.jar;obj\Debug\lp\10\jl\bin\classes.jar;obj\Debug\lp\11\jl\bin\classes.jar;obj\Debug\lp\12\jl\bin\classes.jar;obj\Debug\lp\13\jl\bin\classes.jar;obj\Debug\lp\14\jl\bin\classes.jar;obj\Debug\lp\15\jl\bin\classes.jar;obj\Debug\lp\16\jl\bin\classes.jar;obj\Debug\lp\17\jl\bin\classes.jar;obj\Debug\lp\18\jl\bin\classes.jar;obj\Debug\lp\19\jl\bin\classes.jar;obj\Debug\lp\20\jl\bin\classes.jar;obj\Debug\lp\21\jl\bin\classes.jar;obj\Debug\lp\22\jl\bin\classes.jar;obj\Debug\lp\23\jl\classes.jar;obj\Debug\lp\24\jl\classes.jar;obj\Debug\lp\30\jl\classes.jar;obj\Debug\lp\31\jl\classes.jar;obj\Debug\lp\32\jl\classes.jar;obj\Debug\lp\4\jl\arch-core-common.jar;obj\Debug\lp\5\jl\arch-lifecycle-common.jar;obj\Debug\lp\6\jl\bin\classes.jar;obj\Debug\lp\7\jl\bin\classes.jar;obj\Debug\lp\9\jl\bin\classes.jar;obj\Debug\lp\8\jl\support-annotations.jar" -bootclasspath "C:\Program Files (x86)\Android\android-sdk\platforms\android-27\android.jar" -encoding UTF-8 "@C:\Users\elias\AppData\Local\Temp\tmp3A1D.tmp" 
1>obj\Debug\android\src\md51a1150f6d0c89ece238ebebc378f5c7a\MyFirebaseMessagingService.java:5: error: package com.google.firebase.messaging does not exist
1>	extends com.google.firebase.messaging.FirebaseMessagingService
1>	                                     ^
1>obj\Debug\android\src\md51a1150f6d0c89ece238ebebc378f5c7a\MyFirebaseMessagingService.java:27: error: package com.google.firebase.messaging does not exist
1>	public void onMessageReceived (com.google.firebase.messaging.RemoteMessage p0)
1>	                                                            ^
1>obj\Debug\android\src\md51a1150f6d0c89ece238ebebc378f5c7a\MyFirebaseMessagingService.java:32: error: package com.google.firebase.messaging does not exist
1>	private native void n_onMessageReceived (com.google.firebase.messaging.RemoteMessage p0);
1>	                                                                      ^

**Comment by mleatherb** [comment]
We are having a similar issue with the com.google.gms.gcm package. When building we get an error saying the package does not exist. The package is referenced properly and is in the packages folder.

**Comment by Redth** [comment]
This sounds like you are either missing a reference, or your download cache is corrupt, or your bin/obj folders need to be deleted.

Try the following:

1. Delete the `bin` and `obj` folders of all your projects in the solution.  Restart the IDE, and try building again.

2. You can try clearing your your Xamarin.Build.Download cache folder:

PC: `C:\Users\%USERPROFILE%\AppData\Local\XamarinBuildDownloadCache`
Mac: `~/Library/Caches/XamarinBuildDownload`

**Comment by mleatherb** [comment]
bin/obj have been deleted, cache is clear and references are correct. This happens on a clean clone into a brand new environment. If we take the package from one of our local machines and put it into the dir, it compiles fine.

**Comment by Redth** [comment]
Are you able to upload a .zip of the solution that reproduces this?

**Comment by mleatherb** [comment]
I can't, sorry. I could provide the log from our CI/CD platform if that would help.

**Comment by Redth** [comment]
A log would help, as well as a list of the packages referenced in your project.

I'm also trying to  understand what you mean by "If we take the package from one of our local machines and put it into the dir"... What do you mean by package, and which dir? Are you talking nuget global cache? or what exactly.

Anything you can do to help me reproduce these steps would be helpful and appreciated.

**Comment by mleatherb** [comment]
If we take the DLL from the root packages folder from one machine and put it the root packages folder of another. The build is successful. It's only when the package needs to be restored do we get the error that the package does not exist. 

[0b7c8594aacc2e18.log.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/2219904/0b7c8594aacc2e18.log.zip)

[packages.config.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/2219857/packages.config.zip)

**Comment by Redth** [comment]
This sounds like some weird race condition.  Have you tried 60.1142.1 version of the packages?

Really need to be able to reproduce this locally to figure out what's going on.

**Comment by mleatherb** [comment]
Yeah, we updated the packages. I just did it again so I could run it through CI/CD. I attached the logs. 
[59d1ed191f393a4c.log.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/2220352/59d1ed191f393a4c.log.zip)

**Comment by Redth** [comment]
I know this is an old issue, but coming back to it, I'm still not quite sure why these would be missing.  It's hard to know if the .jar for gcm is actually getting referenced in the javac invocation because we shorten path names to those files in the obj/ folders.  One thing I do see is that there's a custom intermediate output path with `Bitrise Android` in it.  I'm wondering if the space in there is causing something weird.  Might be worth trying to omit that in your project configuration.

In any case, if there's anything more on this one, please open a new issue and link back to this one.
