### ISSUE TITLE
App crash when app is in background for Android latest version.

### ISSUE THREAD

**Issue by Resham143** [xamarin/GooglePlayServicesComponents#120]
### Xamarin.Forms Version (eg: 6.0):
2.3.4.270

### Operating System & Version (eg: Mac OSX 10.11):
Android 8.0 and 8.1.0

### Google Play Services Version (eg: 8.4.0):
60.1142.1

### Describe your Issue:

java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.firebase.INSTANCE_ID_EVENT pkg=....../md5233a66268ba0262636e2bc558b77e078.MyFirebaseIIDService (has extras) }: app is in background uid UidRecord{bf6c43d u0a300 CAC bg:+2h54m59s428ms idle procs:1 seq(118,118,118)}

### Include any relevant Exception Stack traces, build logs, adb logs:

android.app.ContextImpl.startServiceCommon ContextImpl.java:1538
android.app.ContextImpl.startService ContextImpl.java:1484
android.content.ContextWrapper.startService ContextWrapper.java:663
android.support.v4.content.WakefulBroadcastReceiver.startWakefulService WakefulBroadcastReceiver.java:99
android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52226 LoadedApk.java:1319
android.os.Handler.handleCallback Handler.java:789
android.os.Handler.dispatchMessage Handler.java:98
android.os.Looper.loop Looper.java:164
android.app.ActivityThread.main ActivityThread.java:6938
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.Zygote$MethodAndArgsCaller.run Zygote.java:327
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1374

**Comment by newky2k** [comment]
@Resham143  Could you provide a sample project to demonstrate this issue please, so that we can investigate further.

Thanks

**Comment by newky2k** [comment]
No response for nearly 3 weeks. closing
