### ISSUE TITLE
Firebase Cloud Firestore error

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/GooglePlayServicesComponents#121]
_From @amitairos on July 2, 2018 19:0_

I'm trying out Firestore with Xamarin.Android.
However, after putting this:

` var db = FirebaseFirestore.Instance;`
It throws an error:

`FirebaseOptions.getProjectId() cannot be null`

I have a Google Services JSON with the right build settings, and it has a project id. What is the problem?

_Copied from original issue: xamarin/xamarin-android#1911_

**Comment by newky2k** [comment]
@jonathanpeppers  is this still and issue?  the second link seems to provide a solution?  if not could you please provide a small sample project to replicate the issue.

**Comment by jonathanpeppers** [comment]
@amitairos ^^

I used a tool to move this issue to the correct Github repo.

**Comment by newky2k** [comment]
@amitairos is this still and issue? the second link seems to provide a solution? if not could you please provide a small sample project to replicate the issue.

**Comment by newky2k** [comment]
No response for two weeks closing

**Comment by darkdoctor** [comment]
I still get the same Issue.
