### ISSUE TITLE
Firebase Crashlytics for Xamarin.Forms.

### ISSUE THREAD

**Issue by vivekshah-zymr** [xamarin/GooglePlayServicesComponents#123]
I am developing an app in xamarin forms for Android and iOS. In which I want to track the crash, So Can anyone help me, how can I integrate Firebase Crashlytics for Android and iOS both.
I found [NuGet package for iOS ](https://www.nuget.org/packages/Xamarin.Firebase.iOS.Crashlytics/), but not able to use that. So Please help me with this.

**Comment by Redth** [comment]
We're working on bindings for the Android version.  In the meantime, there's other options available like AppCenter.ms for crash reporting.

Duplicate of #93

**Comment by jrahma** [comment]
it will be great if Crashlytics will be available for Xamarin Forms too.

**Comment by me-Henok** [comment]
I need to use firebase crashlytics in my xamarin forms app any detailed documentation on how to set up  in XF
