### ISSUE TITLE
Work with Xamarin.Firebase.Perf

### ISSUE THREAD

**Issue by aoershov** [xamarin/GooglePlayServicesComponents#125]
Hello!
I try to use Xamarin.Firebase.Perf.
I added reference to this assembly to my project.
After that I can see Automatic Traces in 
adb logcat -s FirebasePerformance

But when I add AddTrace attribute to any method - no result.
Also I can not find Trace class in Xamarin.Firebase.Perf.dll
Is it possible use such code in Xamarin
Trace myTrace = FirebasePerformance.getInstance().newTrace("test_trace");
myTrace.start(); ?

Please help!

**Comment by Redth** [comment]
Unfortunately the namespace naming fix was missed in this version of Firebase packages and you can find the type under `Com.Google.Firebase.Perf`, however in future versions this will be fixed and the namespace will be named `Firebase.Perf` as you would expect.

**Comment by renefloor** [comment]
@Redth en @aoershov I am having the same problem. (On version 70.1600.0-preview2). I can find `FirebasePerformance.Instance`, but not `FirebasePerformance.Instance.NewTrace("test");` or anything similar. I couldn't find any questions or documentation about this for Xamarin Android.

**Comment by akankshajain00** [comment]
Same here I am facing the same problem. @Redth Can you please provide a documentation.

**Comment by spotwaremobileteam** [comment]
need update on this
