### ISSUE TITLE
Any plan for  com.google.firebase.ml.vision

### ISSUE THREAD

**Issue by jessejiang0214** [xamarin/GooglePlayServicesComponents#126]
Just wonder do you have a plan to binding com.google.firebase.ml.vision

**Comment by klarqkent** [comment]
Any new for this?

**Comment by Redth** [comment]
We don't have an ETA at this point.  We are working on it.

**Comment by khedherinader** [comment]
Hi @Redth , any news ?!

**Comment by mobeenbhatti** [comment]
Hi @Redth , any updates ?!

**Comment by daesang** [comment]
Hi @Redth , any news ?!

**Comment by mzaeemkhan** [comment]
I created binding for firebase-ml-vision-image-label-model-15.0.0, firebase-ml-vision-16.0.0 and firebase-ml-model-interpreter-16.0.0 as required.
Also bind these to firebase-ml-common-16.1.2 also.
I am getting an error on firebase-ml-common-16.1.2 when creating FirebaseVision.Instance as it required android.gms.internal.firebase_ml.zzjq. Can you tell me which dependency i am missing on firebase-ml-common binding as i have added all mentioned on this link https://mvnrepository.com/artifact/com.google.firebase/firebase-ml-common/16.1.2.

**Comment by mobeenbhatti** [comment]
Looks like I've achieved this.

**Comment by crazynitha** [comment]
@redth Any update regarding release ??

**Comment by talk2stephan** [comment]
@mobeenbhatti : Could you please share a sample app ?

**Comment by KthProg** [comment]
How do we get this for Xamarin? I only see it for iOS on NuGet

**Comment by avanloo01** [comment]
Is this still going?
