### ISSUE TITLE
Xamarin.Firebase.Database documentation and/or code samples

### ISSUE THREAD

**Issue by maparaschivei** [xamarin/GooglePlayServicesComponents#127]
Are there any code samples or documentation for implementing the Xamarin.Firebase.Database component?

It appears almost all other Firebase components have sample code associated with them.

I have tried implementing the firebase-database component on my own based on the code samples from the other firebase components but have run into issues do to lack of documentation.

Does the lack of documentation indicate that firebase-database is not yet ready to be used? 

Thank you,

**Comment by newky2k** [comment]
@maparaschivei at this point we don't have any samples ported for that part atm.  hopefully this is something we can do in the future

**Comment by utd-github** [comment]
Any documentation?
