### ISSUE TITLE
Package version or symbol conflict in firebase and googleservices preventing successful build targeting android 7

### ISSUE THREAD

**Issue by LeroyDL** [xamarin/GooglePlayServicesComponents#128]
### Xamarin.Android Version (eg: 6.0):
7.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version (eg: 8.4.0):
42.1021.1

### Describe your Issue:
I need to target android 7 or lower if possible, but am unable to do so with my App.
Having a package version or symbol conflict when referencing xamarin.firebase and xamarin.googleplayservices preventing successful build targeting android 7.1.

I've tried swapping in and out various versions of xamarin.forms, googleplayservices, and firebasemessaging and get a variety of errors when doing so. Most notably this issue as described, or the firebase namespace and symbols being missing despite being referenced, even after removing, deleting all build products and xamarin nuget cache, re-adding packages and rebuilding.

my target sdk is set to 7.1, and all other android sdks have been deleted.
The logs about forms v8.1 are a little worrying to me.

potentially related articles:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1892
https://github.com/googleads/googleads-mobile-unity/issues/510
https://stackoverflow.com/questions/48893523/error-package-com-google-firebase-messaging-does-not-exist
https://github.com/xamarin/GooglePlayServicesComponents/issues/77

I've tried the solutions mentioned in all of those articles above but have found none to resolve the problem.

### Steps to Reproduce (with link to sample solution if possible):

1. Create a new empty Xamarin forms mobile project
2. To the android project, Add xamarin.firebase.messaging version 42.1021.1 nuget package
3. Clean & build android project.

### Include any relevant Exception Stack traces, build logs, adb logs:
`1>------ Build started: Project: DFEApp.Android, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1429,2): warning : max res 25, skipping mipmap-anydpi-v26
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1328,2): warning : max res 25, skipping mipmap-anydpi-v26
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1328,2): warning : max res 25, skipping mipmap-anydpi-v26
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1328,2): warning : max res 25, skipping mipmap-anydpi-v26
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1328,2): warning : max res 25, skipping mipmap-anydpi-v26
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1328,2): warning : max res 25, skipping mipmap-anydpi-v26
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1328,2): warning : max res 25, skipping mipmap-anydpi-v26
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1328,2): warning : max res 25, skipping mipmap-anydpi-v26
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1328,2): warning : max res 25, skipping mipmap-anydpi-v26
1>  DFEApp.Android -> C:\Users\<redacted>\Source\Repos\DFEApp\DFEApp\DFEApp.Android\bin\Debug\DFEApp.Android.dll
1>C:\Users\<redacted>\Source\Repos\DFEApp\DFEApp\DFEApp.Android\DFEApp.Android.csproj : warning XA0105: The $(TargetFrameworkVersion) for FormsViewGroup.dll (v8.1) is greater than the $(TargetFrameworkVersion) for your project (v7.1). You need to increase the $(TargetFrameworkVersion) for your project.
1>C:\Users\<redacted>\Source\Repos\DFEApp\DFEApp\DFEApp.Android\DFEApp.Android.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Forms.Platform.Android.dll (v8.1) is greater than the $(TargetFrameworkVersion) for your project (v7.1). You need to increase the $(TargetFrameworkVersion) for your project.
1>C:\Users\<redacted>\Source\Repos\DFEApp\DFEApp\DFEApp.Android\DFEApp.Android.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Forms.Platform.dll (v8.1) is greater than the $(TargetFrameworkVersion) for your project (v7.1). You need to increase the $(TargetFrameworkVersion) for your project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1910,3): warning : Name cannot begin with the '$' character, hexadecimal value 0x24.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2007,3): warning : max res 25, skipping mipmap-anydpi-v26
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/iid/zzc;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/iid/zzd;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/iid/zze;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/iid/zzf;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/iid/zzg;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/iid/zzh;
1>  6 errors; aborting
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2254,3): error : java.lang.IllegalArgumentException: already added :  Lcom/google/firebase/iid/zzc;
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by Redth** [comment]
You should set your target framework version higher (8.1 is a good version right now to go with).

Keep in mind this doesn't mean you can't set your minimum sdk version to something lower.

You're going to have to target 8.0 at a minimum later this year anyway if you want to submit updates to your app in the play store.

**Comment by newky2k** [comment]
no response for a month, closing
