### ISSUE TITLE
Firebase support for iOS

### ISSUE THREAD

**Issue by ksachdeva** [xamarin/GooglePlayServicesComponents#13]
Hi,

First of all good work to wrap Firebase SDK in the branch (v9.0.1).

My question is - Will there be corresponding effort for Xamarin iOS ? 

Regards & thanks
Kapil

**Comment by bholmes** [comment]
We are working on iOS support.  It will be in the [GoogleAPIsForiOS][1] repo.

There is not a timeline at this point.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents
