### ISSUE TITLE
Prerelease dependencies incorrect

### ISSUE THREAD

**Issue by ThomasDhaen** [xamarin/GooglePlayServicesComponents#132]
I've tried to install the new prerelease packages, but I get dependency errors.
I think they should be updated to match NuGet version numbers and not those of Android.

Example Xamarin.GooglePlayServices.Base:
![nuget_gallery___xamarin_googleplayservices_base_70_1501_0-preview1](https://user-images.githubusercontent.com/3873860/43517069-c72418ea-9587-11e8-8675-1c7a24da1844.png)
https://www.nuget.org/packages/Xamarin.GooglePlayServices.Base/70.1501.0-preview1

**Comment by Redth** [comment]
Yep, we didn't do that correctly.  There's a new version of prerelease coming today.  Apologies for the false start!

**Comment by ThomasDhaen** [comment]
@Redth Thanks! It's working now.
