### ISSUE TITLE
How to use "FocusingProcessor"

### ISSUE THREAD

**Issue by daesang** [xamarin/GooglePlayServicesComponents#133]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android 8.1

### Operating System & Version (eg: Mac OSX 10.11):
Windows

### Google Play Services Version (eg: 8.4.0):
v70.1502.2-preview2

### Describe your Issue:
How to use "FocusingProcessor" on Xamarin.Android

https://developers.google.com/android/reference/com/google/android/gms/vision/FocusingProcessor

**Comment by newky2k** [comment]
@daesang unfortunately this is not part of the current binding and possibly not the next one.
