### ISSUE TITLE
Restart Visual Studio Mac to set the Build Action to "GoogleServicesJson" in the Android project

### ISSUE THREAD

**Issue by TheCodeTraveler** [xamarin/GooglePlayServicesComponents#135]
You need to restart Visual Studio Mac to set the Build Action to "GoogleServicesJson" in the Android project

### Xamarin.Android Version (eg: 6.0):
Xamarin.Android 8.1

### Operating System & Version (eg: Mac OSX 10.11):
macOS High Sierra

### Google Play Services Version (eg: 8.4.0):
Unknown

### Describe your Issue:
You need to restart Visual Studio Mac to set the Build Action to "GoogleServicesJson" in the Android project. 

### Steps to Reproduce (with link to sample solution if possible):
https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-android#prerequisites

1. Create a project on the Firebase console.
2. Then, press on the Android logo to create an application matching your package name.
3. Go to the settings of the application.
4. Download the google-services.json file.
5. Copy this file to your Android project.
6. Integrate Firebase in application
7. Close and reopen your solution.
8. Open context menu on google-services.json file.
9. Select GoogleServicesJson in Build Action.

### Include any relevant Exception Stack traces, build logs, adb logs:

I also noticed that it is only necessary to close/reopen the solution when using a Xamarin.Forms template; the "GoogleServicesJson" Build Action is already available without needing to close/reopen the solution when using the Xamarin.Android (not Forms) template.

**Comment by Redth** [comment]
Unfortunately I think this is a limitation of the IDE not reloading the `AvailableItemName` MSBuild ItemGroups.  This should probably get filed under VSWin and VSMac as I believe it is a problem in both IDE's.
