### ISSUE TITLE
any ETA for the MLVision lib (xamarin ios) ?  

### ISSUE THREAD

**Issue by nkhedheri** [xamarin/GooglePlayServicesComponents#137]

**Comment by newky2k** [comment]
@nkhedheri  We are working on this as part of the next version of Firebase, which is due out within the next 3-6 weeks

**Comment by nkhedheri** [comment]
@newky2k  , hi Dave , any news about the Lb ,  the new version of firebase is available , but i can't find the MLvision Lib ?!

**Comment by KthProg** [comment]
Hey, what about for Android? Thanks

**Comment by Beelzenef** [comment]
Closed issue... can we lost hope?
