### ISSUE TITLE
What is the release plan for Google Play Services v15?

### ISSUE THREAD

**Issue by jahmai** [xamarin/GooglePlayServicesComponents#138]
### Xamarin.Android Version (eg: 6.0):

N/A

### Operating System & Version (eg: Mac OSX 10.11):

N/A

### Google Play Services Version (eg: 8.4.0):

15.0.1

### Describe your Issue:

The package has been preview for over a month without any new issues raised.
When will it be released as final?

### Steps to Reproduce (with link to sample solution if possible):

N/A

### Include any relevant Exception Stack traces, build logs, adb logs:

N/A

**Comment by jahmai** [comment]
I couldn't wait and released the preview. Only issue #144 showed its face and the deprecated method still worked.

**Comment by Redth** [comment]
Please see #163
