### ISSUE TITLE
Xamarin.Firebase.Message not receiving Notifications when app is stopped, closed on not running

### ISSUE THREAD

**Issue by faceoffers28** [xamarin/GooglePlayServicesComponents#141]
### Xamarin.Android Version (eg: 6.0):

My app targets 8.1 and is compiled with 8.1.

### Operating System & Version (eg: Mac OSX 10.11):

My test device is running Android 5.1.1. This could be a device specific issue, but I have read that this has been fixed, so I thought I would open an issue to see if it can be addressed in the next release.

### Google Play Services Version (eg: 8.4.0):

Xamarin.GooglePlayServices.  = 60.1142.1
Xamarin.Firebase.Message = 60.1142.1

### Describe your Issue:

I can receive FCM Notifications when the app is in the foreground and background. When the app is closed, stopped or not running, I can not receive FCM Notifications from Azure Notification Hub. I am sending  Notifications as Data messages using the SendTemplateNotificationAsync method.

Google's documentation mentions foreground and background here https://firebase.google.com/docs/cloud-messaging/android/receive, but does not mention anything about the app not running, closed or stopped. 

### Steps to Reproduce (with link to sample solution if possible):

This issue is discussed in great detail in many different forums. It would seem from what I've been reading, the Firebase team seems to have fixed this issue. Can you check on this and either address the issue or add this to the next release? Thanks in advance!

**Comment by newky2k** [comment]
@faceoffers28 can you provide a small sample to replicate this issue so that we can investigate further

**Comment by newky2k** [comment]
@faceoffers28  From what I read of the other thread it appears to be an implementation detail of android on some devices, that stops the notifications from correctly starting the service if the app is not running.  I'll assign it @Redth to investigate further

**Comment by Redth** [comment]
My understanding is that if an app has been forcibly closed, the notifications won't be delivered to it by Android (I think at least not until the next boot).  I think this is operating as expected, unfortunately.
