### ISSUE TITLE
Not working on Huawei devices with android version 7.0 and higher

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [xamarin/GooglePlayServicesComponents#143]
### Xamarin.Android Version

Microsoft Visual Studio Community 2017 
Version 15.8.4
VisualStudio.15.Release/15.8.4+28010.2026

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)

### Operating System & Version
Windows 10: 1709 (build 16299.19)

### Google Play Services Version
Xamarin.GooglePlayServices.Vision: 60.1142.1

### Description:
I run the application on the phone Huawei P9 Lite (droid OS 6.0) and huawei tablet (droid OS 7.0). On the smartphone, everything is working fine, but on the tablet there is no result when trying to scan the qr. I found these problems on the [google forum](https://issuetracker.google.com/issues/80454351) and in [GoogleVision GitHub](https://github.com/googlesamples/android-vision/issues/352).

### Steps to Reproduce
If you have a Huawei device with a version of android 7.0 or higher, then build a simple application using this library and try to scan the qr-code

**Comment by newky2k** [comment]
@Goncharuk-Nikita  Can you please provide a small sample application that demonstrates this issue.  

Regards

**Comment by newky2k** [comment]
no resonse for over two weeks, closing
