### ISSUE TITLE
15.0.1: FirebaseInstanceId.Instance.GetInstanceId() doesn't return an InstanceIdResult

### ISSUE THREAD

**Issue by jahmai** [xamarin/GooglePlayServicesComponents#144]
### Xamarin.Android Version (eg: 6.0):

Xamarin.Android 9.0.0.19

### Operating System & Version (eg: Mac OSX 10.11):

Windows 10

### Google Play Services Version (eg: 8.4.0):

15.0.1

### Describe your Issue:

FirebaseInstanceId.Instance.GetInstanceId() should return a Task\<InstanceIdResult\>, but instead it returns a Task, so there is no way to get the Firebase token.
The obsolete FirebaseInstanceId.Instance.Token still returns a token though.

**Comment by newky2k** [comment]
@jahmai  can you please provide a sample project to demostrate the issues that you are having.

Regards

**Comment by jahmai** [comment]
@newky2k I'd rather not have to set up a Google Firebase account to demonstrate the issue (and not going to use my apps official keys). But it's easily observed from the code:

Here is the official docs:

```public Task<InstanceIdResult> getInstanceId ()```

https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.html#getInstanceId()

Here is the signature in the binding signature:

```
    [Register("getInstanceId", "()Lcom/google/android/gms/tasks/Task;", "GetGetInstanceIdHandler")]
    public virtual unsafe Task GetInstanceId()
    {
      return Java.Lang.Object.GetObject<Task>(FirebaseInstanceId._members.InstanceMethods.InvokeVirtualObjectMethod("getInstanceId.()Lcom/google/android/gms/tasks/Task;", (IJavaPeerable) this, (JniArgumentValue*) null).Handle, JniHandleOwnership.TransferLocalRef);
    }
```

**Comment by Redth** [comment]
Will be fixed in a future release.  For now, please use `JavaCast` to the correct type.

**Comment by jahmai** [comment]
@Redth Shouldn't I just use https://github.com/xamarin/GooglePlayServicesComponents/commit/b66274669ba729ac80181daf646ec571aee97c04 ?

**Comment by Redth** [comment]
Of course, if you want to build from source otherwise you'll have to wait for a new nuget release

**Comment by jahmai** [comment]
I'll just make it an extension method. Cheers.

**Comment by wcoder** [comment]
Do you have updates?
As I can see in the latest Firebase.Messaging package provides only `Task GetInstanceId()`

**Comment by jahmai** [comment]
@wcoder You can just do GetInstanceId ().AsAsync<IInstanceIdResult> ()

**Comment by bhagenow** [comment]
When I wait on GetInstanceId().AsAsync<IInstanceIdResult>(), it never returns. What might I be missing?
