### ISSUE TITLE
In-App Messaging SDK ?

### ISSUE THREAD

**Issue by ignasbagdonas** [xamarin/GooglePlayServicesComponents#145]
Hello, 

Do you have any plans to implement In-App Messaging SDK for Xamarin?
```
pod 'Firebase/InAppMessagingDisplay'
com.google.firebase:firebase-inappmessaging-display
```

**Comment by newky2k** [comment]
@ignasbagdonas  I don't believe that it is currently on the road map, but I can look into it further for you.

**Comment by Redth** [comment]
Please see #163

**Comment by dolapobabs** [comment]
Any update on this SDK?
