### ISSUE TITLE
nuspec of Xamarin.GooglePlayServices.Fido links to wrong files (Fitness instead of Fido)

### ISSUE THREAD

**Issue by dgorbach** [xamarin/GooglePlayServicesComponents#146]
https://github.com/xamarin/GooglePlayServicesComponents/blob/ec5dae01aff38588eabe70a00c52661d02bbd5a1/fido/nuget/Xamarin.GooglePlayServices.Fido.template.nuspec#L27

**Comment by newky2k** [comment]
@dgorbach  thanks for the heads up on this,  assigning @Redth
