### ISSUE TITLE
IAuthResult's AdditionalUserInfo property does not contain NewUser bool

### ISSUE THREAD

**Issue by ashleypringle** [xamarin/GooglePlayServicesComponents#148]
### Describe your Issue:
Unless I'm missing something, IAuthResult retrieved from FirebaseAuth.Instance.SignInWithCredentialAsync doesn't include an isNewUser method or boolean in AdditionalUserInfo.
According to this link, there should be an isNewUser method https://developers.google.com/android/reference/com/google/firebase/auth/AdditionalUserInfo

Profile, ProviderId, and Username are all in SignInWithCredentialAsync though, but no NewUser property.

Is NewUser available elsewhere, or is this a bug?

### Steps to Reproduce (with link to sample solution if possible):
Call FirebaseAuth.Instance.SignInWithCredentialAsync() and check the IAuthResult that is returned from it. It will have a AdditionalUserInfo property that contains Profile, ProviderId and Username properties, but no NewUser property.

**Comment by Redth** [comment]
Looks like `IsNewUser` was added in a later version of Firebase Auth (it doesn't exist in the .jar file in the .aar from 11.4.2 which is the version you're using).  Unfortunately, we have no newer stable versions currently available, but we are working on that (see #163).

For now you could use the newer prerelease versions (there might be dragons), or wait until we get a newer prerelease and ultimately stable version out of a newer Firebase Auth.

**Comment by ashleypringle** [comment]
Great, thanks for the info!
