### ISSUE TITLE
Attempting to link a phone number that's already in use doesn't throw an exception. Just hangs.

### ISSUE THREAD

**Issue by cabauman** [xamarin/GooglePlayServicesComponents#150]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Firebase.Auth: 60.1142.1
Xamarin.Android SDK: 9.0.0.19
Android Support libraries: 27.0.2.1

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version (eg: 8.4.0):
60.1142.1

### Describe your Issue:
Calling _LinkWithCredentialAsync_ with a phone auth credential that's already in use doesn't throw an exception. It just hangs and never finishes.

Expected behavior: throws a FirebaseAuthUserCollisionException

I tried linking to a Google auth credential that's already in use, and that throws an exception as expected. Other kinds of auth exceptions are throwing fine, as well. It's just this phone auth one that's acting funny.

### Steps to Reproduce (with link to sample solution if possible):

Sample repo: https://github.com/cabauman/FirebaseAuthDroid

1. Sign in anonymously
2. Link to phone number (test phone number in console)
3. Sign in anonymously as a different user
4. Try to link with the same phone number
5. Hangs indefinitely

### Include any relevant Exception Stack traces, build logs, adb logs:

> VS bug [#732437](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732437)

**Comment by Redth** [comment]
If you use the non async version of the method `LinkWithCredential` do you get an exception?

**Comment by cabauman** [comment]
Hi @Redth. I just tried out the non-async version, and that too never calls the OnComplete handler.

The good news, however, is that both async and non-async versions work in 70.1602.0-preview1 and 70.1602.0-preview2.

**Comment by Redth** [comment]
Thanks, sounds like this was a Google bug then.  Going to close it and assume the newer releases will take care of it as per your observations.
