### ISSUE TITLE
Xamarin IOS Firebase.MLKit

### ISSUE THREAD

**Issue by nkhedheri** [xamarin/GooglePlayServicesComponents#153]
the new version of firebase is available (published 10/16/2018), but i can't find the MLvision Lib ?!

**Comment by newky2k** [comment]
@nkhedheri I don;t think we currently bind to this but I believe it is on the list for a future release.

**Comment by nkhedheri** [comment]
<img width="1070" alt="screen shot 2018-10-19 at 09 59 01" src="https://user-images.githubusercontent.com/42735239/47208491-da37c800-d385-11e8-9569-b3b0817601d8.png">

i don't know how you can explain this!! i lose more than 6 weeks waiting the lib , and finally i found myself into a big problem with the customer. if i do know this from the beginning maybe i was change the plan.

[https://github.com/xamarin/GooglePlayServicesComponents/issues/137](url)

**Comment by pulmuone** [comment]
https://github.com/xamarin/GoogleApisForiOSComponents
