### ISSUE TITLE
on production sowing Test Ad ok but not with AddTestDevice - output - shows ads DLL not found....

### ISSUE THREAD

**Issue by sp-software-tk** [xamarin/GooglePlayServicesComponents#154]
<uses-sdk android:targetSdkVersion="27" />
testing on my android 5.1 device 

xamarin forms 3.1.0...
Xamarin.GooglePlayServices.Ads.Lite 60.11...
Xamarin.GooglePlayServices.Basement 60.11....

hello 
xamarin forms 3.1.0...
Xamarin.GooglePlayServices.Ads.Lite 60.11...
Xamarin.GooglePlayServices.Basement 60.11....

i am trying to show google ads with by using google admob.
looking on the output - shows ads DLL not found....

i got my ad id a few days ago.
on production sowing the General Test Ad (ca-app-pub-3940256099942544/6300978111) with no problems

but fails to show ads when using my AppID Ad unit ID with AddTestDevice.

output:

10-18 15:54:46.875 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/gms/dynamite/descriptors/com/google/android/gms/ads/dynamite/ModuleDescriptor;
10-18 15:54:46.875 W/DynamiteModule(26939): Local module descriptor class for com.google.android.gms.ads.dynamite not found.
10-18 15:54:46.877 D/ActivityThread(26939): hoder:android.app.IActivityManager$ContentProviderHolder@2a8342ca,provider,holder.Provider:android.content.ContentProviderProxy@a792c3b
10-18 15:54:46.884 D/DynamitePackage(26939): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
10-18 15:54:46.894 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/gms/ads/internal/ClientApi;
10-18 15:54:46.953 I/Ads (26939): Updating ad debug logging enablement.
10-18 15:54:47.018 I/Ads (26939): Starting ad request.
10-18 15:54:47.019 I/Ads (26939): SDK version: afma-sdk-a-v14366011.11400000.1
10-18 15:54:47.019 I/Ads (26939): This request is sent from a test device.
10-18 15:54:47.037 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/u;
10-18 15:54:47.038 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/p;
10-18 15:54:47.039 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/x;
10-18 15:54:47.056 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/v;
10-18 15:54:47.058 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/m;
10-18 15:54:47.059 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/r;
10-18 15:54:47.061 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/t;
10-18 15:54:47.066 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/ae;
10-18 15:54:47.070 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/ac;
10-18 15:54:47.085 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/w;
10-18 15:54:47.086 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/af;
10-18 15:54:47.086 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/n;
10-18 15:54:47.087 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/q;
10-18 15:54:47.088 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/z;
10-18 15:54:47.090 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/y;
10-18 15:54:47.093 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/ab;
10-18 15:54:47.094 D/AbsListView(26939): onWindowFocusChanged: hasWindowFocus=true, this=android.widget.ListView{eb6e834 V.ED.VCL ......ID 0,0-592,760 #8}
10-18 15:54:47.094 V/InputMethodManager(26939): onWindowFocus: md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer{21396798 VFE..... .F....ID 0,0-720,1184} softInputMode=288 first=true flags=#81810100
10-18 15:54:47.094 V/InputMethodManager(26939): START INPUT: md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer{21396798 VFE..... .F....ID 0,0-720,1184} ic=null tba=android.view.inputmethod.EditorInfo@30baa7cd controlFlags=#105
10-18 15:54:47.099 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/ad;
10-18 15:54:47.100 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/k;
10-18 15:54:47.102 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/o;
10-18 15:54:47.104 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/d;
10-18 15:54:47.105 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/h;
10-18 15:54:47.106 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/l;
10-18 15:54:47.106 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/a;
10-18 15:54:47.107 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/s;
10-18 15:54:47.108 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/c;
10-18 15:54:47.109 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/aa;
10-18 15:54:47.109 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/j;
10-18 15:54:47.130 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/f;
10-18 15:54:47.136 E/art (26939): ClassLinker::FindClass not found:Lcom/google/android/ads/z__/b;
10-18 15:54:47.167 D/AbsListView(26939): onSizeChanged w=592, h=710, oldw=592, oldh=760, getChildCount=9, mSyncPosition=0, mNeedSync=false, mSyncMode=0, mAdapterandroid.widget.HeaderViewListAdapter@444aa6, this=android.widget.ListView{eb6e834 V.ED.VCL ......ID 0,0-592,710 #8}, callstack=android.widget.ListView.onSizeChanged:1146 android.view.View.sizeChange:16155 android.view.View.setFrame:16120 android.widget.AbsListView.setFrame:2281 android.view.View.layout:16011 android.view.ViewGroup.layout:5185 android.support.v4.widget.SwipeRefreshLayout.onLayout:611 android.view.View.layout:16021 android.view.ViewGroup.layout:5185 md51558244f76c53b6aeda52c8a337f2c37.ListViewRenderer.n_onLayout:-2 
10-18 15:54:47.270 D/OpenGLRenderer(26939): [TaskMgr] Running thread hwuiTask1 (27056)
10-18 15:54:47.272 D/GraphicBuffer(26939): register, handle(0xd181d100) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
10-18 15:54:47.278 D/OpenGLRenderer(26939): Flushing caches (mode 0)
10-18 15:54:47.280 D/Surface (26939): Surface::disconnect(this=0xf49bdb00,api=1)
10-18 15:54:47.280 D/GraphicBuffer(26939): unregister, handle(0xd98f5240) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
10-18 15:54:47.282 D/OpenGLRenderer(26939): Flushing caches (mode 0)
10-18 15:54:47.297 W/Ads (26939): Update ad debug logging enablement as false
10-18 15:54:47.303 W/cr_CrashFileManager(26939): /data/data/Shaout.Shaout/cache/WebView/Crash Reports does not exist or is not a directory
10-18 15:54:47.308 D/GraphicBuffer(26939): register, handle(0xd181d060) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
10-18 15:54:47.313 V/ActivityThread(26939): Finishing stop of ActivityRecord{17f526cc token=android.os.BinderProxy@32fbdd15 {Shaout.Shaout/md5ad877567a4c4626596384e9776043a5d.SplashActivity}}: show=false win=com.android.internal.policy.impl.HwPhoneWindow@366779ec
10-18 15:54:47.314 V/PhoneWindow(26939): DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{1de53032 Shaout.Shaout/md5ad877567a4c4626596384e9776043a5d.SplashActivity,ident = 0}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{2e1d7d93 I.E..... R....... 0,0-720,1280}
10-18 15:54:47.560 D/libc-netbsd(26939): [getaddrinfo]: mtk hostname=googleads.g.doubleclick.net; servname=(null); cache_mode=(null), netid=0; mark=0
10-18 15:54:47.560 D/libc-netbsd(26939): getaddrinfo( app_uid:10217
10-18 15:54:47.560 D/libc-netbsd(26939): getaddrinfo() uid prop:
10-18 15:54:47.560 D/libc-netbsd(26939): getaddrinfo() getuid():10217
10-18 15:54:47.560 D/libc-netbsd(26939): [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
10-18 15:54:47.563 D/libc-netbsd(26939): getaddrinfo: googleads.g.doubleclick.net get result from proxy >>
10-18 15:54:47.800 D/OpenSSLLib(26939): OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
10-18 15:54:47.801 D/OpenSSLLib(26939): OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
10-18 15:54:47.828 W/Ads (26939): There was a problem getting an ad response. ErrorCode: 0
10-18 15:54:47.830 W/Ads (26939): Failed to load ad: 0

**Comment by newky2k** [comment]
@sp-software-tk sorry for the delay in getting back to you.  Could you please provide a small sample project that demostrates the issue that you are having.

Regards

**Comment by newky2k** [comment]
no response for two weeks, closing

**Comment by sp-software-tk** [comment]
Haha.. sorry – I have seen that mail just now.
At the end – the issue where not the code but the account configuration… needed to fill the admob payment form… and it worked.. 

Sometimes … omg! I know..





Sent from Mail for Windows 10
