### ISSUE TITLE
Tried to build on a PC using the Build.ps1 file, errored out

### ISSUE THREAD

**Issue by davefxy** [xamarin/GooglePlayServicesComponents#156]
### Operating System & Version (eg: Mac OSX 10.11):
Window 10

### Describe your Issue:
The build failed while executing the build.ps1 file with the following error:
Could not load type 'Cake.Core.CakeTaskBuilder`1' from assembly 'Cake.Core, Version=0.30.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by clakka** [comment]
I ma getting the same issue, specifically the error in -verbose is:
Error: System.AggregateException: One or more errors occurred. ---> Cake.Core.CakeException: The target 'externals' was not found.

**Comment by newky2k** [comment]
@davefxy @clakka  Could you please provide some greater detail on what you doing, the versions of GPS.  do you get the same thing on a new project.  Could you provide a small sample application that has the same problem.  Additionally, if you are able, can you check this on Mac?

Regards

**Comment by davefxy** [comment]
Yes, I downloaded the GPS version on GitHub  to my Win 10 PC a couple of days ago. Then followed the directions about using powershell to run Build.Ps1 . I don't have an apple mac so I develop entirely on PC.

**Comment by davefxy** [comment]
I should have been more explicit. My failure.
