### ISSUE TITLE
When the Android Client (Target O) is running an ChromeCast Session and the app enters from background the session is disconnected throwing an IlegalStateException

### ISSUE THREAD

**Issue by AliFarahnak** [xamarin/GooglePlayServicesComponents#157]
### Describe your Issue:
When the Android Client (Target O) is running an ChromeCast Session and the app enters background the session is disconnected throwing an IlegalStateException
This is fixed in a newer version of the SDK:
 Android Sender 16.0.2
Fixed the IllegalStateException thrown when ReconnectionService is started in background if the app targets to Android O or higher. Apps that enable reconnection service should update to use this version to avoid being affected this bug.

### Steps to Reproduce :
Start an ChromeCast session and put app to background and lock the screen. After couple of minutes then wake the app up and you will see the session is disconnected even though it is running on the Receiver side.

**Comment by AliFarahnak** [comment]
@newky2k the ChromeCast Session throws up on Reconnection when entering from Background. There is no specific code to be shared. 
https://developers.google.com/cast/v2/reconnection
The GooglePlayServices and Cast SDK needs an Xamarin update.

**Comment by newky2k** [comment]
@AliFarahnak we are working on an update to GPS as we speak and a new version should be available in the coming weeks.

Regards

**Comment by Redth** [comment]
We are working on updates.  Please see #163 
Apologies for the inconvenience :(
