### ISSUE TITLE
Firebase Messaging ANRs

### ISSUE THREAD

**Issue by LJordanCoCo** [xamarin/GooglePlayServicesComponents#158]
### Xamarin.Android Version (eg: 6.0):
Not related. See below.

### Xamarin.Firebase Version (eg: 6.0):
Xamarin.Firebase.Messaging version: 60.1142.1 (though still applies to 70.1710.0-preview2)

### Operating System & Version (eg: Mac OSX 10.11):
Android 7.1+

### Describe your Issue:
Push notifications to end users will occasionally result in a crash/ANR (and them not seeing a notification). This happens several hundred times a week for our current in-production app.

### Steps to Reproduce (with link to sample solution if possible):
Send push notifications to Android 7.1+ devices in a production application. Watch as ANR counts slowly go up. 

### Include any relevant Exception Stack traces, build logs, adb logs:

Broadcast of Intent { act=com.google.firebase.INSTANCE_ID_EVENT flg=0x14 cmp={your.package.name.here}/com.google.firebase.iid.FirebaseInstanceIdInternalReceiver (has extras) }
com.google.firebase.iid.FirebaseInstanceIdInternalReceiver

### Notes:
**This is not a Xamarin issue, except in that it appears to have been fixed by Google but the most recent Xamarin releases (and even previews) do not include this fix.**

See: [Firebase Release Notes, September 18, 2018](https://firebase.google.com/support/release-notes/android#update_-_september_18_2018)

**Comment by newky2k** [comment]
@LJordanCoCo  We are working on updates to Firebase shat should include the latest version of Messaging, which should then fix the issue for you.

Regards

**Comment by LJordanCoCo** [comment]
@newky2k That's good to know.  Is there anything I can look at to track the progress of said updates?

**Comment by bitlkoskela** [comment]
We're seeing the same issues. Are there still no updates on the release schedule of the new library versions?
