### ISSUE TITLE
FirebaseOptions.getProjectId() cannot be null.

### ISSUE THREAD

**Issue by darkdoctor** [xamarin/GooglePlayServicesComponents#162]
Greetings.

I just read "https://github.com/xamarin/GooglePlayServicesComponents/issues/104" and can anyone please update me if this is fixed.

I still get FirebaseOptions.getProjectId() cannot be null.

Google analytics works pretty fine. I have google-services.json included on my project and set build action as google services.

**Comment by schrizzity** [comment]
Look at this comment for a work around. This worked for me...

[https://github.com/xamarin/GooglePlayServicesComponents/issues/104#issuecomment-406681123](url)

**Comment by Redth** [comment]
Duplicate of #104
