### ISSUE TITLE
Update to newer versions of Google Play Services / Firebase

### ISSUE THREAD

**Issue by Redth** [xamarin/GooglePlayServicesComponents#163]
Currently the stable release is based on 11.4.2.

We are working on updating to newer versions.  This is a more challenging update as Google has stopped shipping a single version for all assemblies, and is versioning each item individually.  To help maintain dependency chains in this new world we are implementing a new build system which generates .csproj files for each binding based on a razor template.  The data for generating these projects is based on a config file and maven repository information.  This means dependencies are automatically inferred, and using SDK style projects we are able to build nuget packages with correct dependency chains more easily.

This means we have a bit of catching up to do.  Currently we have work underway on a branch: https://github.com/xamarin/GooglePlayServicesComponents/tree/15.0.1-binderate

You'll notice that most of the versions are 15.x based on that branch, yet we have previews of newer binaries already on nuget.  The prereleases on nuget were built with an old build setup which we deemed unmaintainable and then switched to the templated system mentioned above.  We focused on 15.x versions to get a baseline building, which is why you see this difference.

We'll be evaluating bumping versions on that branch for a newer set of releases.

We are working on this as fast as we can.  Thanks for your patience!

> VS bug [#732432](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732432)

**Comment by andrewtechhelp** [comment]
Hi,

Thanks very much for the update on this! I assume this new build system will also apply to the Android Support Libraries and will assist with supporting AndroidX too?

I've been getting worried for a while about how quiet everything seemed to be regarding these Google Play Services and Android Support Libraries/AndroidX as these have been the biggest gaps my team have faced in terms of what native Android supports and what Xamarin supports (everything else we've found is 1:1 in terms of capabilities across both). This matters to us, especially with Google putting so much functionality into these libraries now rather than core Android. They're basically a must have for much of Android development these days, not having them is like not having parts of the iOS SDK available.

This post helps explain what's happening and gives me confidence that these libraries will have updates coming soon, so thanks for all the work on this :)

**Comment by Redth** [comment]
We're working on this as quickly as we can.   We have a very small team and are also managing some other big changes from Google (AndroidX, Support 28.x).  Thanks for your patience!

**Comment by gabry90** [comment]
Thanks for following update, but please, some GamesClass feature not work in latest beta version, need newer version asap for my project that use Google Play Games :D

**Comment by Redth** [comment]
We're close to publishing a new set of previews, stay tuned.

**Comment by Atomosk** [comment]
Messaging sample still contains [FirebaseInstanceIdService](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService), which is deprecated at least since june 2018.

**Comment by gabry90** [comment]
no chance, too litte update, too little support, 6+ months for an update is unacepptable... currently i'll check unity for my project

**Comment by s-inagaki** [comment]
https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService
Google says that the onTokenReflesh method may become unusable unexpectedly.
When will the stable release correspond to the onNewToken method?

**Comment by akravch** [comment]
Do you guys have a date for the next stable release?

**Comment by Redth** [comment]
We have a new set of previews out now.  These should be VERY close to the next stable release version.  Please test them out and report any bugs.  After a bit more internal QA and waiting a couple of weeks for any other bug reports to roll in we will publish these packages to stable.

Immediately following this (actually we've already started the work) we will be looking at updating to newer versions already.  There are some updated versions required to bind the new Places SDK (since the Play Services one was deprecated), and a few other version bumps with bugfixes we know are needed.  The turnaround time on these updates will be MUCH faster now that we have a templated build system and a baseline set of releases in place.

Thank you everyone for your patience, and sorry for the wait on these.  Going forward should be much smoother sailing!

**Comment by andrewtechhelp** [comment]
Awesome news :D - Thanks Jonathan!

**Comment by KthProg** [comment]
Do these previews include MLKit? In an issue asking for MLKit, you linked to this one. I haven't been able to bind it myself because of the generics.

**Comment by moljac** [comment]
@KthProg 
Here they are:

https://www.nuget.org/packages?q=Xamarin.Firebase.ML

`preview3` is on its way. With updates.

I hope this answers your question.

**Comment by KthProg** [comment]
@moljac Thanks :)

**Comment by moljac** [comment]
@bitlkoskela @s-inagaki @akravch @andrewtechhelp @KthProg  

Closing this one...
