### ISSUE TITLE
GooglePlayGame missing some Clients

### ISSUE THREAD

**Issue by gabry90** [xamarin/GooglePlayServicesComponents#167]
### Describe your Issue:
The latest version of Google Play Games has implemented the new GoogleApiSignInClient. Unfortunately, by investigating thoroughly, I found no correspondence for the new AchievementClient and LeaderboardClient. In this way I am forced to still use the deprecated version of GoogleApiClient.

### Steps to Reproduce (with link to sample solution if possible):
I looked for all the assemblies in the library but I did not find the matches described above

### Include any relevant Exception Stack traces, build logs, adb logs:

> VS bug [#760351](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/760351)

**Comment by Redth** [comment]
Thanks, we'll look into this.

**Comment by moljac** [comment]
Surfaced several Client classes.

Closing this issue.

**Comment by gabry90** [comment]
surfaced where?

**Comment by gabry90** [comment]
where are the clients? namespace please? thanks :)

**Comment by gabry90** [comment]
oh thanks, finally, i'll wating for official nuget package update 👍
