### ISSUE TITLE
GamesClass.Leaderboard not work

### ISSUE THREAD

**Issue by gabry90** [xamarin/GooglePlayServicesComponents#168]
### Xamarin.Android Version (eg: 6.0):
6.0+

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version (eg: 8.4.0):
70.1501.0-preview2

### Describe your Issue:
1) By executing the following code to obtain the player's score, the variable "result" always returns the status "status_client_reconnect_required". The ApiCLient is connected during the execution of the code (using GamesClass.Api and GamesClass.ScopeGames). In this way I can not get the score data.

`public async Task<long> GetPlayerPosition()
        {
            if (accountManager?.ApiClient?.IsConnected != true)
                return 0;

            var result = await GamesClass.Leaderboards.LoadCurrentPlayerLeaderboardScoreAsync(accountManager.ApiClient,
                LEADERBOARD_ID,
                LeaderboardVariant.TimeSpanAllTime,
                LeaderboardVariant.CollectionPublic);

            var position = result?.Score?.Rank ?? 0;
            result?.Dispose();
            return position;
        }`

2) When I execute SubmitScoreAsync method  the following errors return into the "result" object:

ScoreData: System.ArgumentException: Hanlde must be valid.Parameter name:type
Status: System.ArgumentException: Handle must be valid.Parameter name:instance

(ApiClient is connected during execution code)

This is a CRITICAL bug. Because i can't use Leaderboard for my game in production.

### Steps to Reproduce (with link to sample solution if possible):

For point 2: [Example code](https://i.imgur.com/OJRqTYc.png)

### Include any relevant Exception Stack traces, build logs, adb logs:

> VS bug [#760350](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/760350)

**Comment by moljac** [comment]
In order to speed up investigation and fix of this issue - minimal repro sample would help us a lot.

Please create minimal sample, so I could test it against the bindings.

Thanks

**Comment by moljac** [comment]
@gabry90 
Did you try `preview9`?

If it is OK please close this issue and if it is not can you provide some minimal repro sample?

**Comment by moljac** [comment]
Closed due to no feedback from the user.

If the issue persists, open new issue and link to this one, please.
