### ISSUE TITLE
Cannot SetValue for Firebase Database References with object

### ISSUE THREAD

**Issue by eddydn** [xamarin/GooglePlayServicesComponents#174]
How we can use SetValue(Java.Lang.Object) with our C# class object ?

**Comment by bigworld12** [comment]
any update/workaround on this ?
do i need to serialize the class as json then pass it ?

**Comment by moljac** [comment]
@eddydn 

`SetSomething` methods are usually bound as `Something` property. Check if those are available. (`Value` property)

Otherwise I need sample to see what is going on (minimal sample)

**Comment by moljac** [comment]
Closing this issue. Please try newer versions and open new issue if the problem persits
