### ISSUE TITLE
Cannot install Xamarin.Firebase.ML.Vision

### ISSUE THREAD

**Issue by jessejiang0214** [xamarin/GooglePlayServicesComponents#180]
### Xamarin.Android Version (eg: 6.0):
9.1.5.1

### Operating System & Version (eg: Mac OSX 10.11):
Mac OS X 10.14.2

### Describe your Issue:
I want to use ML.Vision, so I switch branch https://github.com/xamarin/GooglePlayServicesComponents/tree/15.0.1-binderate and build all nugets. Then I try install these nuget from local I get error 

### Steps to Reproduce (with link to sample solution if possible):
Build all nuget from repo and install from local 

### Include any relevant Exception Stack traces, build logs, adb logs:
I get this error 
```
Xamarin.Build.Download.targets(114,3): error : Did not find reference matching RestoreAssemblyResources AssemblyName metadata 'Xamarin.Firebase.ML.Vision'
```

**Comment by moljac** [comment]
Do you have minimal sample to reproduce this error?

it would be of great help. 

I wil start porting some samples, but it will take some time.

Until then moving this to low priority

**Comment by jessejiang0214** [comment]
Hi @moljac , 
I just try to install NuGet which build by my self, if the current branch can build and install you can close this.

**Comment by moljac** [comment]
@jessejiang0214 
1st of all - use master now.

I use this one on 2 Macs:

```
sh ./build.sh --target=clean \
&& \
sh ./build.sh --target=binderate \
&& \
sh ./build.sh --target=libs \
&& \
sh ./build.sh --target=nuget \
&& \
sh ./build.sh --target=diff \
&& \
sh ./build.sh --target=samples \
```
In order to get nuget you will need `nuget` target. `diff` and `samples` are optional for you.

And please keep us informed.

Your error might have something to do with corrupt Xamarin.Build.Download cache. Try deleting it.

**Comment by jessejiang0214** [comment]
Hi @moljac ,

When will new release publish, just want to get official nuget packages.

Thanks,
Jesse
