### ISSUE TITLE
Error as 'Resource.Raw' does not contain a definition for 'gtm_analytics' after updated the package from 32.961.0 to 60.1142.1

### ISSUE THREAD

**Issue by nrb1238** [xamarin/GooglePlayServicesComponents#182]
### Describe your Issue:
Updated the package of Xamarin.GooglePlayServices.TagManager from 32.961.0 to 60.1142.1 then getting the error as Resource.Raw' does not contain a definition for 'gtm_analytics'

Please check the below code

 var tagmanager = TagManagerClass.GetInstance(this);
 var pendingResult = tagmanager.LoadContainerPreferNonDefault("XXXXXX", Resource.Raw.gtm_analytics);
 var callback = new TagManagerResultCallback();
  pendingResult.SetResultCallback(callback, 2, TimeUnit.Seconds);

Note: If rollback to 32.961.0 then no issues

**Comment by moljac** [comment]
Seems like google doesn't ship it anymore. The file `gtm_analytics` file from `res\raw` was not found in any artifact (TagManager and dependencies)

Closing this issue.

**Comment by nrb1238** [comment]
Hi @moljac 

Any alternative solution for it?
