### ISSUE TITLE
Location: "removeLocationUpdates" is missing and crashes the application.

### ISSUE THREAD

**Issue by softlion** [xamarin/GooglePlayServicesComponents#183]
I know this provider is now obsolete, but it should still work :)

### Xamarin.Android Version (eg: 6.0):
9.1.7.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 Pro 17763.316

### Google Play Services Version (eg: 8.4.0):
11.4.2 (v60.1142.1)

### Describe your Issue:
"removeLocationUpdates" is missing and crashes the application.

### Steps to Reproduce (with link to sample solution if possible):
Call RemoveLocationUpdates from an IFusedLocationProviderApiInvoker instance.

### Include any relevant Exception Stack traces, build logs, adb logs:

```
NoSuchMethodError: no non-static method "Lcom/google/android/gms/internal/zzbym;.removeLocationUpdates(Lcom/google/android/gms/common/api/GoogleApiClient;Lcom/google/android/gms/location/LocationListener;)Lcom/google/android/gms/common/api/PendingResult;"
02-22 20:01:14.965 22764 22786 I mono-stdout: #22/L4:Error:       at Java.Interop.JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <dcf74ac56ca94da99b81374dc4b0eb9f>:0
02-22 20:01:14.965 22764 22786 I mono-stdout: #22/L5:Error:  at Android.Runtime.JNIEnv.GetMethodID (System.IntPtr kls, System.String name, System.String signature) [0x00007] in <651a2758a4a24c389db940d15c81d998>:0
02-22 20:01:14.965 22764 22786 I mono-stdout: #22/L6:Error:  at Android.Gms.Location.IFusedLocationProviderApiInvoker.RemoveLocationUpdates (Android.Gms.Common.Apis.GoogleApiClient client, Android.Gms.Location.ILocationListener listener) [0x00012] in <502d2d5c12ec4f47932ad8f929707190>:0
02-22 20:01:14.966 22764 22786 I mono-stdout: #22/L7:Error:  at Android.Gms.Location.IFusedLocationProviderApiExtensions+<RemoveLocationUpdatesAsync>d__2.MoveNext () [0x0000a] in <502d2d5c12ec4f47932ad8f929707190>:0
```

> VS bug [#805954](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/805954)

**Comment by Redth** [comment]
@softlion do you have a simple repro solution you could post for this?

Thanks

**Comment by moljac** [comment]
@softlion 

Could you try with `preview6` please?

**Comment by softlion** [comment]
I rewrote the code so it does not use this obsolete method anymore. So i can't test again.

**Comment by moljac** [comment]
Closing this one. Open a new issue if this error persists.

Brief analysis of `preview7` showed `RemoveLocationUpdates` methods in `IFusedLocationProviderApi`.
