### ISSUE TITLE
Firebase SDK has not been updated

### ISSUE THREAD

**Issue by horaciojcfilho** [xamarin/GooglePlayServicesComponents#185]
For 7 months, there is no more updates to the Firebase packages in Nuget. Please, may the Components team get the Firebase packages a more cycle of updates? Many thanks in advance.

**Comment by michaelwanke** [comment]
#163 has some more detail if helpful.

**Comment by Redth** [comment]
We are working on these and are very close!

Closing as Duplicate of #163
