### ISSUE TITLE
UnsatisfiedLinkError in FirebaseMessagingService

### ISSUE THREAD

**Issue by ooikengsiang** [xamarin/GooglePlayServicesComponents#195]
### Xamarin.Android Version:
7.0 and above only.

### Operating System & Version:
Android 7.0 and above only.

### Google Play Services Version:
Xamarin.Firebase.Messaging 60.1142.1 (I tried multiple versions, it is same.)

### Describe your Issue:
Found crash reported in Google Play that was unable to produce nor make sense to me. 
I have tried several version of Xamarin.Firebase.Messaging, they are the same. 
No user complain to me about the push notification.
Only happen to Android version 7.0 and above.
No ProGuard enable.

### Steps to Reproduce (with link to sample solution if possible):
Personally unable to reproduce, all crash report and stack trace are from Google Play.

### Include any relevant Exception Stack traces, build logs, adb logs:
```
java.lang.UnsatisfiedLinkError: 
  at mono.android.Runtime.register (Native Method)
  at md5dd7a5194eb3bf67181b6a5c267c0f7e7.PushNotificationMessagingService.<clinit> (PushNotificationMessagingService.java:15)
  at java.lang.Class.newInstance (Native Method)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:3551)
  at android.app.ActivityThread.-wrap4 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1778)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6798)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
```
Below is snippet of PushNotificationMessagingService implementation.
As you can see, I wrap all my code logic with try and catch block, yet the error still happen, thus I think it is something happen in FirebaseMessagingService that I can't control.
UnsatisfiedLinkError doesn't return any additional message for all crash report so far.
```
[Service]
[IntentFilter(new[] { "com.google.firebase.MESSAGING_EVENT" })]
public class PushNotificationMessagingService : FirebaseMessagingService
{
    /// <summary>
    /// When received a notification from Firebase
    /// </summary>
    /// <param name="message">Message or notification received</param>
    public override void OnMessageReceived(RemoteMessage message)
    {
        // this function only trigger when the app in on foreground
        // in this function, we will convert the notification received and
        // group them together to prevent notification flooded the notification area
        // also we keep count how many unread notification
        try
        {
            // code implementation that process the message received
        }
        catch (Exception ex)
        {
            // ignore all exception error
        }
    }
}
```

**Comment by moljac** [comment]
@ooikengsiang 
Could you provide minimal repro sample, so I can test? That would speed up resolving the issue.

BTW. Could you try new `71.*-preview7` nugets, please?

**Comment by ooikengsiang** [comment]
> @ooikengsiang
> Could you provide minimal repro sample, so I can test? That would speed up resolving the issue.
> 
> BTW. Could you try new `71.*-preview7` nugets, please?

I would like to reproduce the problem myself or provide a repro sample, but unfortunately I never did.
Those crash log are from Google Play and it keep on bother me even I wrap all related code with try and catch.
I will give the preview nuget a try on my application next release and monitor Google Play still report the same error or not.

**Comment by ooikengsiang** [comment]
After updated to version 71, I no longer observe the same crash from Google Play. I guess this issue is solved.
