### ISSUE TITLE
Firebase Messaging 71.1502.0-preview2 Requires Targeting Android 9?

### ISSUE THREAD

**Issue by SharpMobileCode** [xamarin/GooglePlayServicesComponents#199]
This is more of a question than a bug report.  I'm trying to update Firebase Messaging 71.1502.0-preview2 to see if a bug I'm seeing is fixed with the preview version (current release version is sorely outdated and almost a year old).  The Nuget package fails to install because I'm targeting Android 8.1, but the nuget packages requires that we target Android 9.  Why is this?  In Android Native, there is no requirement to target Android 9 for Firebase Cloud messaging, so why would these binding require us to target Android 9?  We're not in a position to target Android 9, but also need to troubleshoot a crash happening with `FirebaseInstanceIdService` (which has been deprecated for quite some time now, but no bindings for us to try).

https://firebase.google.com/docs/android/setup
https://firebase.google.com/docs/cloud-messaging/android/client

Thanks!

**Comment by moljac** [comment]
No it is not a requirement. It must be my mistake. Sorry. Need to check.

**Comment by moljac** [comment]
So, the target is 9.0

https://github.com/xamarin/GooglePlayServicesComponents/blob/master/source/GooglePlayServicesProject.cshtml#L5

Because, GPS dependencies are Android.Support 28.0.0.1 which targets 9.0. We push latest support, because other products will push it too very soon (Xamarin.Forms).

Another question: why wouldn't you be able to target 9.0?

**Comment by SharpMobileCode** [comment]
> Another question: why wouldn't you be able to target 9.0?

Because we're on a very tight deadline for a release in a couple of weeks and targeting Android 9 introduces breaking changes for us.  We're in feature lock now and are in QA/BugFix mode.  Changing our targetsdk would introduce huge risks and would require us to rush fixing the breaking changes.  It's not going to happen, lol

It sounds like that the Xamarin bindings are too tightly coupled with each other.  In native Android, Firebase Messaging does not require you to compile/target Android 9:

https://firebase.google.com/docs/android/setup
https://firebase.google.com/docs/cloud-messaging/android/client

So it's a little frustrating that in order to pick up a bug fix from a library requires to to change our target, fix breaking changes because of the target change, and then re-run full regression tests when it's not necessary.  It would not be an issue in native Android as I have Kotlin projects that target Android 8.0 and Android 8.1 that use the latest FCM libraries.

**Comment by moljac** [comment]
> It sounds like that the Xamarin bindings are too tightly coupled with each other.

Partially true. The main reason is that we cannot bind ALL versions and missing bindings for certain artifacts do make our deegres of freedom reduced.

Sorry.
Closing this one.
