### ISSUE TITLE
can't use firebase APIs on xamarin forms ?

### ISSUE THREAD

**Issue by bigworld12** [xamarin/GooglePlayServicesComponents#201]
i have a .net standard library and an android project that references it,
when i try to add package `Xamarin.Firebase.Auth 71.1510.0-preview2` to the .net standard project, i get this error

`Xamarin.Firebase.Auth 71.1510.0-preview2  is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Xamarin.Firebase.Auth 71.1510.0-preview2 supports: monoandroid90 (MonoAndroid,Version=v9.0)`

does that mean i can only use firebase on android projects ? i can't find any sample that uses xamarin forms either

**Comment by moljac** [comment]
Firebase Android are Android only bindings.

Here is iOS

https://www.nuget.org/packages?q=Xamarin.Firebase.iOS

Those are platform specific libraries, so monoandroid90 and (Xamarin.iOS 1.0) and there is no common abstraciton above Android and iOS APIs (like Xamarin.Forms). This sounds like interesting opensource project idea 8).

So you will need your own dependency service (Xamarin.Forms) to use both of those GPS implementations in Forms.

Closing this one.
