### ISSUE TITLE
App Theme missing

### ISSUE THREAD

**Issue by taz4270** [xamarin/GooglePlayServicesComponents#202]
### Plugin Installed Version:
    71.1600.0-preview2

### Operating System & Version (eg: Mac OSX 10.11):
Android : 7.0

### Google Play Services Version (eg: 8.4.0):
16.0.91

### Describe your Issue:
Trying open an Activity with an Dependency but it doesnt work with your activities

### Steps to Reproduce (with link to sample solution if possible):
Follow the exemple

[Activity(Label = nameof(NativeNavigationDependency))]
    public class NativeNavigationDependency : INativeNavigate
    {
        public void Navigate()
        {
            Device.BeginInvokeOnMainThread(() =>
            {
                var e = new Android.Gms.Oss.Licenses.OssLicensesActivity();
                Intent v = new Intent(Android.App.Application.Context, typeof(Android.Gms.Oss.Licenses.OssLicensesMenuActivity));
                Android.App.Application.Context.StartActivity(v);
            });
            
        }
    }

### Include any relevant Exception Stack traces, build logs, adb logs:
Unhandled Exception:

Java.Lang.RuntimeException: Unable to start activity ComponentInfo{com.companyname.ProjectZM/com.google.android.gms.oss.licenses.OssLicensesMenuActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity. occurred

**Comment by moljac** [comment]
@taz4270 Can you provide minimal sample please?

**Comment by taz4270** [comment]
Sorry to awnser this late but i dont think i can replicate any longer :/
