### ISSUE TITLE
Upgrade to Google Play Services SDK -16.0.0

### ISSUE THREAD

**Issue by dpawarslb** [xamarin/GooglePlayServicesComponents#204]
### Operating System & Version (eg: Mac OSX 10.11):
mac OS High Sierra - 10.13.6

### Google Play Services Version (eg: 8.4.0):
Need library to be upgraded to using Google Play Services Places SDK - 16.0.0

### Describe your Issue:
Hi Team,
As per recommendation (https://developers.google.com/places/android-sdk/client-migration) from January 29, 2019, Google Play Services Places is required to be upgraded to version 16.0.0.
Currently the library is using the Google Play Services Places SDK version 11.4.2, which will stop functioning from July 29, 2019.
Please upgrade the library version for using the latest Google Play Services Places SDK version 16.0.0.
Thanks.

**Comment by Redth** [comment]
There are preview packages available already.  We are probably going to push one more preview, and then shortly after, to stable.  Thanks!

**Comment by dpawarslb** [comment]
Please confirm "71.1600.0" is the preview package upgraded to "Google Play Services Places SDK version 16.0.0" 
https://github.com/xamarin/GooglePlayServicesComponents

**Comment by dpawarslb** [comment]
Can you please let us know the schedule by when the Preview package would be migrated to Stable version, which we can adopt in our app?
Thanks.

**Comment by dpawarslb** [comment]
@Redth - Can you please let us know the schedule by when the Preview package would be migrated to Stable version, which we can adopt in our app?
Thanks.

**Comment by moljac** [comment]
@dpawarslb 
Release is matter of minutes/hours. 

https://dev.azure.com/xamarin/public/_build?definitionId=15
