### ISSUE TITLE
Manual binding to solve errors/crashes?

### ISSUE THREAD

**Issue by 61315** [xamarin/GooglePlayServicesComponents#206]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android 9.3.0.14
### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 1709 16299.1029
### Google Play Services Version (eg: 8.4.0):
Xamarin.Android Bindings for Google Play Services - Vision 71.1620.0-preview3
Xamarin.Android Bindings for Google Play Services - Vision 71.1620.0-preview4
### Describe your Issue:
Application crashes with unhandled exception. (#205)
Core functionality not accessible. (#200)
### Steps to Reproduce (with link to sample solution if possible):
`var _detector = new FaceDetector.Builder(Application.Context)
                .SetClassificationType(ClassificationType.None)
                .SetTrackingEnabled(true)
                .SetLandmarkType(LandmarkDetectionType.All)
                .SetMode(FaceDetectionMode.Fast)
                .SetProminentFaceOnly(true)
                .SetMinFaceSize(0.5f)
                .Build();`

### Include any relevant Exception Stack traces, build logs, adb logs:

> Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.vision.face.internal.client.zza>

> Unhandled Exception: Java.Lang.NoClassDefFoundError: com.google.android.gms.vision.face.internal.client.zza

I ended up using native way to utilize face contour detection feature on latest ml vision package(com.google.firebase:firebase-ml-vision:19.0.3) with Andoid Studio. 

  I prefer Cross-Platform way with Xamarin Forms tho. Writing some platform specific scripts on each platforms(Andoird and iOS) and creating dependency service to access those scripts by single shared business logic is just feels right.

To solve the issue I looked into some of the logs on Azure Pipelines build results(Preview4) and noticed there's error message related to FirebaseVision class. 

> 1>  BINDINGSGENERATOR : warning BG8102: Class Firebase.ML.Vision.Document.FirebaseVisionDocumentTextRecognizer has unknown base type com.google.android.gms.internal.firebase_ml.zzil.
1>  BINDINGSGENERATOR : warning BG8102: Class Firebase.ML.Vision.Barcode.FirebaseVisionBarcodeDetector has unknown base type com.google.android.gms.internal.firebase_ml.zzis.
1>  BINDINGSGENERATOR : warning BG8102: Class Firebase.ML.Vision.Cloud.Label.FirebaseVisionCloudLabelDetector has unknown base type com.google.android.gms.internal.firebase_ml.zzil.
1>  BINDINGSGENERATOR : warning BG8102: Class Firebase.ML.Vision.Cloud.Landmark.FirebaseVisionCloudLandmarkDetector has unknown base type com.google.android.gms.internal.firebase_ml.zzil.
1>  BINDINGSGENERATOR : warning BG8102: Class Firebase.ML.Vision.Face.FirebaseVisionFaceDetector has unknown base type com.google.android.gms.internal.firebase_ml.zzis.
1>  BINDINGSGENERATOR : warning BG8102: Class Firebase.ML.Vision.Label.FirebaseVisionLabelDetector has unknown base type com.google.android.gms.internal.firebase_ml.zzis.

There they are! The missing detector classes... 

  For some reason, the TextRecognizer was binded fine and I needed to know why this one's okay. I just don't understand what these lines mean but I de-compiled the class archive file and exposed all java classes for reference purpose anyway. Analyzed the missing detector classes from de-compiled aar and found a pattern that any detector classes import com.google.android.gms.internal.firebase_ml.zzg*/zzh* are not present on FirebaseVision.cs. Unfortunately those zzg* and zzh* classe are not presented on de-compiled aar structure and that has stopped me.

  Then I manually added some binding instructions on Metadata.xml for no good reason, build log says something about zzil and zzis though, and somehow the missing classes are now exposed.

`<attr path="/api/package[@name='com.google.android.gms.internal.firebase_ml']/class[@name='zzis']" name="obfuscated">false</attr>
  <attr path="/api/package[@name='com.google.android.gms.internal.firebase_ml']/class[@name='zzil']" name="obfuscated">false</attr>`

It is just half-measure and of course the built nuget package doesn't work.

  How do you guys cope with these kind of errors? Manually tracking down the minified(zza, zzb etc..) java code is frustrating. Does this document do any help? https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/troubleshooting-bindings/#Problem_Missing_C_types_in_generated_output. Why are there only eight items on GooglePlayServices.Tests project?

  Want to know how this automated binding system works and want to participate to resolve errors. Brief explanation of manual binding with minified java codes would be helpful. I totally understand it's on 'Preview', meaning it's not Production-Ready, but still, I don't want to wait several weeks for someone else to solve the issues.(#200) Also want to know why the AndroidX dependency would be an issue. https://github.com/xamarin/GooglePlayServicesComponents/issues/200#issuecomment-484557811 Current Xamarin Android Binding for GooglePlayService is too old(almost a year old).

Thank you.

**Comment by moljac** [comment]
@61315 
> How do you guys cope with these kind of errors? 

<joke>
psychostimulants (booze, ganja, RedBull, FightClub, extreme sports, you name it)
</joke>

Basically. Patience, reading and thinking...
 
> Manually tracking down the minified(zza, zzb etc..) java code is frustrating. 

True. Very true.

> Does this document do any help?

Basically we do not read those. We know those by heart (almost).

> Why are there only eight items on GooglePlayServices.Tests project?

Not sure what you mean. 

> Want to know how this automated binding system works 

Basically - read the doc you linked and try to do some bindings. But no GPS-FB or Android.Support/AndroidX - you will turn gray.

> and want to participate to resolve errors. 

Cool.

> Brief explanation of manual binding with minified java codes would be helpful. 

Doc you linked and then mileage... The number of bindings (AKA experience) is the only way.

> I totally understand it's on 'Preview', meaning it's not Production-Ready, 

We had few answers. API can only get better with release. Preview in case of bindings would mean "OK we have it, but we are not sure everything is surfaced"

> I don't want to wait several weeks for someone else to solve the issues.(#200) 

We are working on it.

> Also want to know why the AndroidX dependency would be an issue. #200 (comment) 

Because AndroidX infrastructure is not ready yet! Check what Google does with AndroidX and everything will be clear what we need to do.

> Current Xamarin Android Binding for GooglePlayService is too old(almost a year old).

No it is not. Only Release. We could make it Release, but if the class is missing it is missing. Until we get feedback and fix it - it is not there. For example I'm fixing right now bunch of `zz*` classes in Ads.Lite and will not jump to ML until I finish that one. Simply context switching is too much time.
Sorry for being blunt, but I hope you understand it.

**Comment by moljac** [comment]
Closing this one.
