### ISSUE TITLE
New Google Place API Nuget Package Release Date

### ISSUE THREAD

**Issue by dechosenuchenna** [xamarin/GooglePlayServicesComponents#207]
I Appreciate the Xamarin Team for all your efforts so far. It is just one month before google will totally discontinue the former and Deprecated Places SDK. There is currently no news about the new API, especially for those of us that have this as a special feature in our apps, we are getting worried already.

## I want to enquire when the new Places Nuget Package will be released

**Comment by moljac** [comment]
Closing this one and https://github.com/xamarin/GooglePlayServicesComponents/issues/184

The package was released.
