### ISSUE TITLE
Error Xamarin.Android Bindings for Google Play Services - Vision 71.1620.0-preview4

### ISSUE THREAD

**Issue by pulmuone** [xamarin/GooglePlayServicesComponents#210]
### Xamarin.Android Version (eg: 6.0):
Android Pie

### Operating System & Version (eg: Mac OSX 10.11):
win 10

### Google Play Services Version (eg: 8.4.0):
Xamarin.Android Bindings for Google Play Services - Vision 71.1620.0-preview4

### Describe your Issue:
Source : 
var detector = new BarcodeDetector.Builder (Application.Context).Build ();

Error : 
Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/vision/zzl;

05-09 02:17:06.585 I/.AndroidOverla(14329): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.vision.zzg>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/vision/zzl;

05-09 02:17:06.585 I/.AndroidOverla(14329): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.vision.zzl" on path: DexPathList[[zip file "/data/app/com.companyname.AndroidOverlay-nD2JMWxAb0PHTygSEWjObQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.AndroidOverlay-nD2JMWxAb0PHTygSEWjObQ==/lib/arm64, /data/app/com.companyname.AndroidOverlay-nD2JMWxAb0PHTygSEWjObQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]

### Include any relevant Exception Stack traces, build logs, adb logs:

Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/vision/zzl;

![Cap 2019-05-09 01-37-16-008](https://user-images.githubusercontent.com/42885949/57393969-3b7a9800-71ff-11e9-9e05-a39582d4749b.png)

**Comment by telecetera** [comment]
I have this problem also. In my VS2017 project (min 21, target 28), my Xamarin.Android.Arch.* libraries are all v1.1.1.1, my Xamarin.GooglePlayServices various v71.1*.0-preview4 (all other libraries are 28.0.0.1). If I try to downgrade the PlayServices libraries to the latest stable 60.1142.1, I get error

Unable to find a version of 'Xamarin.Android.Arch.Core.Common' that is compatible with 'Xamarin.Android.Arch.Lifecycle.LiveData 1.1.1 constraint: Xamarin.Android.Arch.Core.Common (= 1.1.1)', 'Xamarin.Android.Arch.Lifecycle.LiveData.Core 1.1.1 constraint: Xamarin.Android.Arch.Core.Common (= 1.1.1)'.

I force removed all PlayServices, then re-added with the latest stable version.

Works fine.

**Comment by dirtvipersw** [comment]
I get the same issue but slightly different error.  The error I get is: "Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/vision/face/internal/client/zza;"

The code is pretty simple so this blocks almost everything with the vision API:
        private FaceDetector stillFaceDetector;
        stillFaceDetector = new FaceDetector.Builder(Android.App.Application.Context)
                .SetTrackingEnabled(true)
                .SetMode(FaceDetectionMode.Accurate)
                .SetLandmarkType(LandmarkDetectionType.None)
                .Build();

Running on an 8.1 device.  
Target Framework = 9.0
Minimum Android version = 5.0
Target Android version = 8.1 (9.0 also gives the error)

**Comment by moljac** [comment]
@pulmuone @dirtvipersw 

Please, provide full diagnostic log. Without that I will not be able to track down the issue.

**Comment by dirtvipersw** [comment]
Here's the debug output and the full vs2019 solution, in case it helps.  https://1drv.ms/f/s!ApT67p13IJulgTRp_ZHHVb6Mi3tx

**Comment by moljac** [comment]
@dirtvipersw 
It sure helps.

**Comment by daesang** [comment]
> @pulmuone @dirtvipersw
> 
> Please, provide full diagnostic log. Without that I will not be able to track down the issue.

Please run the sample below yourself.  
https://github.com/xamarin/GooglePlayServicesComponents/tree/master/samples/com.google.android.gms/play-services-vision

Preview5 same error.

**Comment by daesang** [comment]
> @dirtvipersw
> It sure helps.

Preview5 same error.

**Comment by daesang** [comment]
> @moljac 
> 
> Please, provide full diagnostic log. Without that I will not be able to track down the issue.

Please run the sample below yourself.  
https://github.com/xamarin/GooglePlayServicesComponents/tree/master/samples/com.google.android.gms/play-services-vision

Preview5 same error.

**Comment by daesang** [comment]
@moljac

If you apply Preview5 in the formula sample provided by you, the following error occurs.
(Barcode scan)

https://github.com/xamarin/GooglePlayServicesComponents/tree/master/samples/com.google.android.gms/play-services-vision

![Cap 2019-05-27 10-48-32-451](https://user-images.githubusercontent.com/32029731/58390615-198d6c00-806d-11e9-90b4-019d6a56deb4.png)

**Comment by moljac** [comment]
@pulmuone @telecetera @dirtvipersw @daesang 

`preview6` is out. Please try it out and close this one if the issue is fixed. If not just report here.

**Comment by pulmuone** [comment]
> @pulmuone @telecetera @dirtvipersw @daesang
> 
> `preview6` is out. Please try it out and close this one if the issue is fixed. If not just report here.

This issue Fixed.
Good job ^^

**Comment by moljac** [comment]
@pulmuone 
Thanks
