### ISSUE TITLE
FirebaseAnalytics does not exist in 71.1630.0-preview3/4 nugets

### ISSUE THREAD

**Issue by dminta** [xamarin/GooglePlayServicesComponents#211]
### Xamarin.Android Version (eg: 6.0):
9.1.7.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version (eg: 8.4.0):
16.30

### Describe your Issue:
`FirebaseAnalytics` class from `Firebase.Analytics` namespace does not exist in `Xamarin.Firebase.Analytics.Impl` `71.1630.0-preview3` and `71.1630.0-preview4` nugets. Firebase Analytics cannot be initialized and used on Android.

### Steps to Reproduce (with link to sample solution if possible):
Compare `Xamarin.Firebase.Analytics.Impl.dll` assemblies with ilspy or fuget.org:
https://www.fuget.org/packages/Xamarin.Firebase.Analytics.Impl/71.1502.0-preview2
https://www.fuget.org/packages/Xamarin.Firebase.Analytics.Impl/71.1630.0-preview4

`FirebaseAnalytics` class is available in `71.1502.0-preview2` and `70.1611.0-preview2` (hidden on nuget.org).

### Include any relevant Exception Stack traces, build logs, adb logs:
n/a

**Comment by moljac** [comment]
Seems like google moved that type to another artifact - `com.google.android.gms.play-services-measurement-api`

So, please, try adding nuget (PackageReference) to `Xamarin.GooglePlayServices.Measurement.Api`

**Comment by moljac** [comment]
@dminta 

I'm pushing `preview5` right now without fix for this until I get more info.

Please, report here if adding `Xamarin.GooglePlayServices.Measurement.Api` helps.

**Comment by dminta** [comment]
Thank you for the response, I will test it again and report here. Last time VS was unable to find `FirebaseAnalytics` class in `Xamarin.GooglePlayServices.Measurement.Api` after upgrading nugets, probably it was a cache issue.

**Comment by moljac** [comment]
I did find/grep over `api.xml` and `*.cs` and this class appeared only in `Measurement.Api`.

I might need to decompile (I did but minimal effort), but that will take some time.

**Comment by dminta** [comment]
I've checked `FirebaseAnalytics` from `Xamarin.GooglePlayServices.Measurement.Api` `71.1630.0-preview5`. basic scenarios like initializing or sending events are working fine.

Thank you for your time spent on this issue, it can be closed.

**Comment by moljac** [comment]
@dminta Dominik glad to hear that. No need to thank us, that's what we do.

Closing this one. 

If you got in problems. Open new issue please.
