### ISSUE TITLE
Detector classes *still* completely missing from Firebase.ML.Vision binding

### ISSUE THREAD

**Issue by KthProg** [xamarin/GooglePlayServicesComponents#212]
I'm not sure why #200 was closed. The barcode detector classes and methods are still missing.

**Comment by moljac** [comment]
@KthProg 

It was closed, because I don't have the whole API in my head and your feedback came in later.

In such cases, just reopen it with more info about missing classes.

`preview5` is out with more surfaced classes. Please report here if there is more missing.

**Comment by KthProg** [comment]
I don't have the ability to re-open issue or I would have :(
