### ISSUE TITLE
Xamarin.GooglePlayServices.Analytics 71.1604.0-preview4 not working

### ISSUE THREAD

**Issue by phillipjt** [xamarin/GooglePlayServicesComponents#213]
### Xamarin.Android Version (eg: 6.0):
9.1.7.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version (eg: 8.4.0):
Xamarin.GooglePlayServices.Analytics 16.0.4 (71.1604.0-preview4)

### Describe your Issue:
Google Analytics Tracker fails to send data with the stack trace below. It was last working in Xamarin.GooglePlayServices.Analytics 11.4.2 (60.1142.1). Observed on Android 6 and later.

### Steps to Reproduce (with link to sample solution if possible):
Call Android.Gms.Analytics.Tracker.Send(IDictionary<string, string> p0);

### Include any relevant Exception Stack traces, build logs, adb logs:
Job execution failed: java.lang.NoSuchMethodError: No virtual method transactAndReadExceptionReturnVoid(ILandroid/os/Parcel;)V in class Lcom/google/android/gms/internal/measurement/zzq; or its super classes (declaration of 'com.google.android.gms.internal.measurement.zzq' appears in /data/app/[***REDACTED***]/base.apk!classes2.dex)

**Comment by phillipjt** [comment]
@moljac 

05-23 08:46:41.519 D/Mono    (10066): Assembly Ref addref Xamarin.GooglePlayServices.Analytics.Impl[0x7b60b4bf00] -> Java.Interop[0x7b60b47800]: 5
05-23 08:46:41.526 I/GAv4    (10066): Google Analytics 12.4.51 is starting up. To enable debug logging on a device run:
05-23 08:46:41.526 I/GAv4    (10066):   adb shell setprop log.tag.GAv4 DEBUG
05-23 08:46:41.526 I/GAv4    (10066):   adb logcat -s GAv4
05-23 08:46:41.544 W/GAv4    (10066): CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
05-23 08:46:41.546 D/Mono    (10066): DllImport searching in: '__Internal' ('(null)').
05-23 08:46:41.546 D/Mono    (10066): Searching for 'java_interop_jnienv_new_local_ref'.
05-23 08:46:41.546 D/Mono    (10066): Probing 'java_interop_jnienv_new_local_ref'.
05-23 08:46:41.546 D/Mono    (10066): Found as 'java_interop_jnienv_new_local_ref'.
05-23 08:46:41.555 E/GAv4    (10066): Job execution failed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/measurement/zzdx;
05-23 08:46:41.580 E/GAv4    (10066): Job execution failed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/measurement/zzdx;
05-23 08:46:50.302 E/GAv4    (10066): Job execution failed: java.lang.NoSuchMethodError: No virtual method transactAndReadExceptionReturnVoid(ILandroid/os/Parcel;)V in class Lcom/google/android/gms/internal/measurement/zzq; or its super classes (declaration of 'com.google.android.gms.internal.measurement.zzq' appears in /data/app/GoogleAnalyticsApp.GoogleAnalyticsApp-JIY_cpmcPFlQxybk0onV3Q==/base.apk)


[RepoSample.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/3209598/RepoSample.zip)

**Comment by dationguyen** [comment]
this sound like an IDE issue where u can't debug android device. 
have u tried to run it without debug ?

**Comment by moljac** [comment]
@phillipjt @dationguyen 
Morn
Thanks for the repro sample. This helps a lot. 

I have created even smaller ReproSample, but have completely different obfuscated classes in the log.

I'm pushing preview5 right now with some other fixes, but this is high priority and I am working on it.

**Comment by moljac** [comment]
@redth 
I was referring to this issue.

**Comment by phillipjt** [comment]
@moljac 
I am no longer seeing this issue in 71.1608.0-preview9
