### ISSUE TITLE
Compile Error When Using New Xamarin.Google.Android.Places v1.1.0.1 Package

### ISSUE THREAD

**Issue by SharpMobileCode** [xamarin/GooglePlayServicesComponents#217]
### Xamarin.Android Version (eg: 6.0):
9.0

### Operating System & Version (eg: Mac OSX 10.11):
Mac OS 10.14.5

### Google Play Services Version (eg: 8.4.0):
71.1601.0-preview3 (as required by Xamarin.Google.Android.Places v1.1.0.1)

### Describe your Issue:
When adding a reference to the [Xamarin.Google.Android.Places](https://www.nuget.org/packages/Xamarin.Google.Android.Places/1.1.0.1) Nuget Package (version 1.1.0.1), I get the following compile error on my Android application:

```
/MyUserPath/XamarinGooglePlacesBug/XamarinGooglePlacesBug/obj/Debug/android/src/mono/com/android/volley/Request_NetworkRequestCompleteListenerImplementor.java(29,29): Error:  error: NetworkRequestCompleteListener is not public in Request; cannot be accessed from outside package
		com.android.volley.Request.NetworkRequestCompleteListener
 (XamarinGooglePlacesBug)
```

### Steps to Reproduce (with link to sample solution if possible):
1. Clone the repo at [https://github.com/SharpMobileCode/XamarinGooglePlacesBug](https://github.com/SharpMobileCode/XamarinGooglePlacesBug)
2. Compile the Android application.

## Expected Result
The android application should compile without error and the Android Google Places SDK should be available to use.

## Actual Result
The android application produces an a compile error:
```
/MyUserPath/XamarinGooglePlacesBug/XamarinGooglePlacesBug/obj/Debug/android/src/mono/com/android/volley/Request_NetworkRequestCompleteListenerImplementor.java(29,29): Error:  error: NetworkRequestCompleteListener is not public in Request; cannot be accessed from outside package
		com.android.volley.Request.NetworkRequestCompleteListener
 (XamarinGooglePlacesBug)
```

## UPDATE
I figured out what the issue was.  This package references Xamarin.Android.Volley version 1.1.1.  It needs to reference the latest version, which is [version 1.1.1.1](https://www.nuget.org/packages/Xamarin.Android.Volley/1.1.1.1) .  (There's an extra ".1")

**Comment by SharpMobileCode** [comment]
Okay, nevermind this bug report.  Something weird happened on both my actual project and on my sample project in an attempt to reproduce.  Here's what happened.  

I was going through my Nuget package references in VS for Mac and noticed that it said there was an update for `Xamarin.Android.Volley` to version 1.1.1.  I though that was odd because the `Xamarin.Google.Android.Places` already has a reference to version to 1.1.1.  So I right clicked on the package entry and clicked on "Update".  VS for Mac then proceeded to update the nuget package.  I then re-compiled and all is working now!  I've been able to use what I need to use.

My apologies!  I'll go ahead and close this issue.  Thank you all for the hard work!

**Comment by SharpMobileCode** [comment]
Okay, I figured out the issue.  The Nuget package references Xamarin.Android.Volley version 1.1.1.  It needs to reference Xamarin.Android.Volley 1.1.1.1 (notice the extra .1).  I guess I'll re-open this issue. ;)

**Comment by Redth** [comment]
@SotoiGhost can you take a look at this? may need to bump the places volley reference?

**Comment by Redth** [comment]
This has been updated to 1.1.0.2 and should be fixed, thanks.
