### ISSUE TITLE
Can I switch Android Google ML Vision Sample source to Xamarin.Android?

### ISSUE THREAD

**Issue by pulmuone** [xamarin/GooglePlayServicesComponents#218]
### Xamarin.Android Version (eg: 6.0):
Android Pie

### Operating System & Version (eg: Mac OSX 10.11):
Windows 7

### Google Play Services Version (eg: 8.4.0):
Xamarin.Android Bindings for Google Play Services - Xamarin.Firebase.ML.Vision 71.1700.0-preview6
Xamarin.Android Bindings for Google Play Services - Vision 71.1702.0-preview6

### Describe your Issue:

Can I switch Android Google ML Vision Sample source to Xamarin.Android?

https://github.com/firebase/quickstart-android/tree/master/mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit

Thank you~.

**Comment by moljac** [comment]
@pulmuone 
In

> Can I switch Android Google ML Vision Sample source to Xamarin.Android?

What does "switch" mean?

Do you mean port? if yes, then sure you can port the sample...

**Comment by moljac** [comment]
Starting work on sample[s] porting.

This sample will be of higher priority.

Closing this issue.

**Comment by RealDigitApps** [comment]
Would be helpful to have https://github.com/firebase/quickstart-android/blob/a1c48f202698f74f7c68c086c714416f2271e61c/mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/common/CameraSource.java
