### ISSUE TITLE
getChannel() not available for messaging

### ISSUE THREAD

**Issue by eman1986** [xamarin/GooglePlayServicesComponents#219]
### Xamarin.Android Version (eg: 6.0):
Android 9

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version (eg: 8.4.0):
60.1142.1

### Describe your Issue:
I need a way to get the channel id and I don't see a way to get that from FCM

according to the documentation for the native version: 
https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification.html#getChannelId()

there should be a getChannelId() function in the notification object but on xamarin I'm not seeing such an item available to me. is it in the payload?

it should match how it's done on the native verbatim to avoid confusion.

**Comment by moljac** [comment]
Seems like this method is removed in newer versions of GPS.

**Comment by Redth** [comment]
@moljac Looks like it was _added_ in 17.4.0, we are on 17.3.x:
https://firebase.google.com/support/release-notes/android#version_1740

**Comment by moljac** [comment]
@redth
I referred to #213 in my slack message

Let me see if I can bump to 17.4.0 right now

**Comment by moljac** [comment]
@eman1986 The bindings were updated and method (property in C#) is surfaced.

Coming in "preview7".

Please test it and report here. If everything is OK. Close this issue please.

**Comment by moljac** [comment]
@eman1986 

Please try `preview9` and if it is fixed close this issue...

**Comment by moljac** [comment]
Closing this one.
