### ISSUE TITLE
Request: Play Core Library

### ISSUE THREAD

**Issue by kuramochia** [xamarin/GooglePlayServicesComponents#221]
I wants to use ”In-app Updates” feature in Xamarin.Android.

Do you plan to support "Play Core Library" in Xamarin?
https://developer.android.com/guide/app-bundle/in-app-updates

**Comment by Redth** [comment]
This is a lot more complex unfortunately than just us providing bindings to the library.

First of all, we have appbundle support landing in an upcoming preview of Visual Studio / Xamarin.Android.  This is the thing we need to _deliver_ apps which could eventually be capable of being used for in-app updates.

However, we currently do not support separating your xamarin.android application into separate modules.  This is something the Xamarin.Android team is aware of, and will be looking at in the future.  Once we have support for this we will look at including the binding for this library.

Hope that makes things a bit clearer!

**Comment by dev-abcdevelopers** [comment]
Hi @Redth  any update on this?

**Comment by Redth** [comment]
Sorry, no, but I'll add @jonathanpeppers and @jonpryor to this thread as well for future reference.  They may be able to comment on any future plans with supporting modules in Xamarin.Android.

**Comment by aldy-deptech** [comment]
i am ver need this :'(

**Comment by dev-abcdevelopers** [comment]
Any new info on this? It'll be great if we have this features in Xamarin.Android app too.

**Comment by caiofbpa** [comment]
Given that we are already using App Bundle, is this going forward anytime soon? It's really important to keep users up-to-date with minimal annoyance.

**Comment by tomcurran** [comment]
@Redth @jonathanpeppers @jonpryor Play Core Library has functionality in it for in-app updates which don't necessarily rely on modularity like an immediate full-screen update. A binding would be useful to use these even full module support is not included.

**Comment by BradKwon** [comment]
Any updates on this library support? In order to use App Bundle and language specific modules, I need this library to trigger downloads and listening to them for their progresses.

**Comment by Skirtek** [comment]
@Redth @jonathanpeppers @jonpryor Any plans to include this feature or library support in near future? It will be really useful for us - Xamarin developers :)

**Comment by sreenivaskavali** [comment]
Any update?

**Comment by mixelsantos** [comment]
Apparently they did not resolve this issue.

**Comment by donatellijl** [comment]
Would love to have this feature of splitting Xamarin.Android app into feature modules.

**Comment by rohitvipin** [comment]
Any reason this is closed? Is there another issue that tracks this?

**Comment by Line-** [comment]
I found this https://github.com/PatGet/XamarinPlayCoreUpdater might be of some use as a starting point. I assume by Redth's post that what those bindings offer (immediate updates) are the extent of what is possible right now until we have support for separate modules in order to support updating a running app, is that correct?

**Comment by dev-abcdevelopers** [comment]
@Line- I tested this just now and it seems to working fine for me.

**Comment by HavenDV** [comment]
We also recently implemented In-App Updates for Android as an easy to use package, maybe this will help someone.
We use this in production and are open to bug fixes/new features.
https://github.com/oscoreio/Maui.Android.InAppUpdates
