### ISSUE TITLE
[Location] FusedLocationProvider.RemoveLocationUpdatesAsync() never returns

### ISSUE THREAD

**Issue by jcmanke** [xamarin/GooglePlayServicesComponents#222]
### Xamarin.Android Version:
9.2.3.0

### Operating System & Version:
Windows 10 Enterprise
Version 1903
Build 18362.175 

### Google Play Services Version:
11.42.0

### Describe your Issue:
Calling `await FusedLocationProviderClient.RemoveLocationUpdatesAsync(LocationCallback callback)` never returns. The callback is removed, proven by calling RemoveLocationUpdatesAsync again throwing an ApiException with the StatusMessage "listener already unregistered", but the awaited Task never completes.

### Steps to Reproduce (with link to sample solution if possible):
1. Run attached sample app.
2. Click Start Tracking button. Verify Toast is displayed with "Location Updates Began" after `RequestLocationUpdatesAsync()` is completed.
3. Click Stop Tracking button. Verify Toast is not displayed with "Location Updates Ended" because awaiting `RemoveLocationUpdatesAsync()` never returns.
4. Click Stop Tracking button again. Verify toast with "Removing Location Updates Failed: listener already unregistered" upon caught ApiException.

[RemoveLocationUpdatesHanging.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/3298297/RemoveLocationUpdatesHanging.zip)

**Comment by moljac** [comment]
Seems like this is problem on Google side.

See this comment for existing sample project:

https://github.com/xamarin/GooglePlayServicesComponents/blob/master/samples/com.google.android.gms/play-services-location/LocationSample/FusedLocationClientActivity.cs#L67

I have removed `await` in your sample and everything is working fine.

More info:

https://stackoverflow.com/questions/55219622/fusedlocationproviderclient-removelocationupdatesasync-task-does-not-complete

https://developer.xamarin.com/samples/monodroid/FusedLocationProvider/
https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/location

monodroid-samples has Sample that works with `await`, but it is a little bit more complicated:

https://github.com/xamarin/monodroid-samples/blob/master/FusedLocationProvider/FusedLocationProvider

Closing this one.
