### ISSUE TITLE
FirebaseAuth.Instance always null in version 71.1605.0-preview7

### ISSUE THREAD

**Issue by thearaks** [xamarin/GooglePlayServicesComponents#223]
### Xamarin.Android Version:
9.3.0.22

### Operating System & Version:
Mac OS X 10.14.5

### Google Play Services Version:
17.4.55 (040408-248795830)

### Describe your Issue:
I've included `google-services.json` with the correct build action,
invoked `Firebase.FirebaseApp.InitializeApp(this);` in my `MainActivity.onCreate()` method.

`FirebaseAuth.Instance` is always `null`.

I think the issue is related to #216 but honestly I think I shouldn't be required to add a custom build task just to use different Firebase services in the same app.

**Comment by moljac** [comment]
@thearaks In order to speed up investigation, could you provide repro sample please?

**Comment by thearaks** [comment]
@moljac please see https://github.com/thearaks/XamarinGPSC_Issue223

Add a google-services.json file and update the Android app package name accordingly.

Checkout tag "works" to see Xamarin.Firebase.Auth working fine:
https://github.com/thearaks/XamarinGPSC_Issue223/releases/tag/works

Checkout tag "broken" to see Xamarin.Firebase.Auth failing badly after adding Xamarin.Firebase.Firestore as a dependency:
https://github.com/thearaks/XamarinGPSC_Issue223/releases/tag/broken

Thank you!
Mattia

**Comment by JPZV** [comment]
I don't know if this is related, but I have the same issue (instance = null). At least my stacktrace says "Firestore component is not present" and I had the same stacktrace from Preview1. I can't share my project as it's private (and soooooooooo big) but here is the stack trace:

`[0:] Java.Lang.NullPointerException: Firestore component is not present.
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <3beddfcb1eb547cd8ce47c3097f6eaeb>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <3beddfcb1eb547cd8ce47c3097f6eaeb>:0 
  at Firebase.Firestore.FirebaseFirestore.GetInstance (Firebase.FirebaseApp app) [0x00031] in <05c821fa8d87450c8eda76f703f264ee>:0 
  at MyProject.Droid.Core.FirestoreService.get_Instance () [0x00001] in E:\Users\winuser\Documents\Visual Studio\Projects\MyProject\MyProject.Android\Core\FirestoreService.cs:38 
  at MyProject.Droid.Core.DroidAuth.EmailLogin (System.String email, System.String pass) [0x00052] in E:\Users\winuser\Documents\Visual Studio\Projects\MyProject\MyProject.Android\Core\DroidAuth.cs:65 
  at MyProject.Core.Auth.EmailLogin (System.String Email, System.String Pass) [0x00035] in E:\Users\winuser\Documents\Visual Studio\Projects\MyProject\MyProject\Core\Auth.cs:101 
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Firestore component is not present.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:910)
	at com.google.firebase.firestore.FirebaseFirestore.zza(com.google.firebase:firebase-firestore@@17.0.5:66)
	at com.google.firebase.firestore.FirebaseFirestore.getInstance(com.google.firebase:firebase-firestore@@17.0.5:58)
	at md5f92e0daf340890c9667469657ee2ece8.ButtonRenderer.n_onClick(Native Method)
	at md5f92e0daf340890c9667469657ee2ece8.ButtonRenderer.onClick(ButtonRenderer.java:95)
	at android.view.View.performClick(View.java:6294)
	at android.view.View$PerformClick.run(View.java:24770)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

I can tell that this is a binding issue related instead of a project issue.

I hope that this help to fix this problem.

**Comment by moljac** [comment]
@thearaks @JPZV 
We found issue with some MsBuild tasks needed for this issue. We are working on it.

**Comment by ashleypringle** [comment]
Just chiming in to say I'm also experiencing this. FirebaseAuth.Instance is always null, and as a result every call to an Instance or property method throws a null exception.

**Comment by dblookup** [comment]
+1. FirebaseAuth.Instance always null in version 71.1605

**Comment by lablabla** [comment]
I'm experiencing this as well.
If I call the constructor directly, i.e 

```
var instance = FirebaseAuth.GetInstance(app);
if (instance == null)
{
    instance = new FirebaseAuth(app);
}
```

I can use this `instance` to login successfully using this instance (And I can see the user being added in the Firebase Console), but further calls which should be authenticated, such as Real time DB access will failed being unauthorized

**Comment by xamarindevelopervietnam** [comment]
FirebaseAuth.Instance always null in version 71.1605.0
VS: 16.2.3
Xamarin.Android: 9.4.1.0

**Comment by Michaelotusanya** [comment]
FirebaseAuth.Instance is always null in version 71.1605.0 only when I include any of these libraries in my solution: 
- Xamarin.FireBase.Analytics version 71.1630.0
- Xamarin.FireBase.Analytics.Impl version 71.1630.0

After further digging, here is an exception message I encountered 

> Firebase.FirebaseException: firebase-auth is not linked, please fall back to unauthenticated mode.

**Comment by sevengh** [comment]
Still wait solve this problem

**Comment by moljac** [comment]
@sevengh We are working on the fix.

**Comment by chrisfoulds** [comment]
Also experiencing this issue, it's been going on since June now - any eta ?

**Comment by coosmiyn** [comment]
Same thing for me. I am still looking into it.

**Comment by MyAlfisti** [comment]
71.1705.2でも改修されていません。
AuthとFirestoreのどちらかしか使えないなんてこのパッケージに意味がありますか？
なぜ何ヶ月も放置されているのでしょうか、.NETは開発環境としてはもう終わってしまったのでしょうか。
私はReact.Nativeを選択すべきなのでしょうか。

**Comment by MyAlfisti** [comment]
71.1705.2 has not been refurbished.
Does this package make sense that only authentication or Firestore can be used?
Why has it been left unattended for months, and has .NET already been a development environment?
Should I choose React.Native?

**Comment by xamarindevelopervietnam** [comment]
we keep waiting the fix for several months, still using version 60

**Comment by coosmiyn** [comment]
I want to downgrade but I am using Android SDK 9 and it requires latest google play services, doesn't it also need the latest Firebase version?

**Comment by nikossaperas** [comment]
+1 This is an issue for me as well - The problem occurs when I add reference to latest (preview at the moment of writing) Microsoft.Appcenter.Push nuget package.

**Comment by nikossaperas** [comment]
+1 This is an issue for me as well - The problem occurs when I add reference to latest (preview at the moment of writing) Microsoft.Appcenter.Push nuget package.

**Comment by bitzeal-johan** [comment]
This is also an issue for us, we're using Xamarin in an app with 100 000 users on Android and this is blocking us.

**Comment by iashaik** [comment]
I do hope this fix comes out soon... already been few months...

**Comment by johncharris** [comment]
There is a work around for #216 that works for this as well. https://github.com/xamarin/GooglePlayServicesComponents/issues/216#issuecomment-517740275

**Comment by iashaik** [comment]
@johncharris 
I get that the fix for [216](https://github.com/xamarin/GooglePlayServicesComponents/issues/216#issuecomment-517740275 ) works for this and that it is a build problem, but are we actually waiting on Visual Studio to actually fix this? Or Xamarin team? 

It is even being tracked?

**Comment by ashleypringle** [comment]
Still experiencing this as well.

**Comment by moljac** [comment]
@johncharris @ashleypringle @iashaik @bitzeal-johan @nikossaperas @coosmiyn @xamarindevelopervietnam @MyAlfisti @chrisfoulds @sevengh @JPZV @thearaks 

Please add nuget Xamarin.Android.ManifestMerger. It will add MSbuild targets that fix Manifest merging. 
And please provide info:
- if nuget dependency solves the problem
- whether you have more than 1 Firebase (or Google.Play.Service)  dependencies.

https://www.nuget.org/packages/Xamarin.Android.ManifestMerger/1.0.0-preview03

**Comment by nikossaperas** [comment]
@moljac 
I just added Xamarin.Android.ManifestMerger(1.0.0-preview03) and it solves the null instance issue.
I have these two firebase dependencies: Xamarin.Firebase.Database and Xamarin.Firebase.Auth. 
I also have Xamarin.GooglePlayServices.Location and Xamarin.GooglePlayServices.Maps.

Everything seems to work fine now. 
Thank you very much @moljac

**Comment by xamarindevelopervietnam** [comment]
I will keep waiting until stable version. Thanks @moljac

**Comment by moljac** [comment]
@nikossaperas Thanks a lot. Really appreciated.

**Comment by moljac** [comment]
@xamarindevelopervietnam 
It is up to you, but it might take some time. It must be added to Xamarin.Android core task, pass the tests. Expect delays.

My personal view: i would use it.

BTW our previews are in most cases release quality it is not that a lot will change (or even anything)

**Comment by iashaik** [comment]
> @xamarindevelopervietnam
> It is up to you, but it might take some time. It must be added to Xamarin.Android core task, pass the tests. Expect delays. 

That might be the exact reason why I would wait to use in prod. 

I don't mind preview during dev process to get unblocked.

**Comment by xamarindevelopervietnam** [comment]
exactly, it can make some risks for prod. Still ok with version 60. I don't know why this issue still here in last few months.

**Comment by moljac** [comment]
@iashaik @xamarindevelopervietnam 
But you are forgetting one important fact - this is build time not runtime component.

This nuget is not runtime dependency and API is not used by the App (should not be used of course everything is possible)

If it helps properly merging AndroidManifest.xml during build time, so that runtime errors are gone what else would you need as a proof of correctness?

**Comment by bitzeal-johan** [comment]
It seems like in our network environment some permissions are needed for the nuget to work. I get this;

6>  This program is blocked by group policy. For more information, contact your system administrator.
6>C:\repo\App\packages\Xamarin.Android.ManifestMerger.1.0.0-preview03\build\monoandroid\Xamarin.Android.ManifestMerger.targets(28,5): error MSB3073: The command ""C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\java.exe" -cp "C:\repo\App\packages\Xamarin.Android.ManifestMerger.1.0.0-preview03\build\monoandroid\common.jar;C:\repo\App\packages\Xamarin.Android.ManifestMerger.1.0.0-preview03\build\monoandroid\guava.jar;C:\repo\App\packages\Xamarin.Android.ManifestMerger.1.0.0-preview03\build\monoandroid\kotlin-stdlib-jdk8.jar;C:\repo\App\packages\Xamarin.Android.ManifestMerger.1.0.0-preview03\build\monoandroid\kotlin-stdlib.jar;C:\repo\App\packages\Xamarin.Android.ManifestMerger.1.0.0-preview03\build\monoandroid\kxml2.jar;C:\repo\App\packages\Xamarin.Android.ManifestMerger.1.0.0-preview03\build\monoandroid\manifest-merger.jar;C:\repo\App\packages\Xamarin.Android.ManifestMerger.1.0.0-preview03\build\monoandroid\sdk-common.jar;C:\repo\App\packages\Xamarin.Android.ManifestMerger.1.0.0-preview03\build\monoandroid\sdklib.jar" "com.android.manifmerger.Merger" --main "obj\Debug\90\android\AndroidManifest.xml" --libs "obj\Debug\90\lp\18\jl\AndroidManifest.xml;obj\Debug\90\lp\2\jl\AndroidManifest.xml;obj\Debug\90\lp\20\jl\AndroidManifest.xml;obj\Debug\90\lp\21\jl\AndroidManifest.xml;obj\Debug\90\lp\22\jl\AndroidManifest.xml;obj\Debug\90\lp\23\jl\AndroidManifest.xml;obj\Debug\90\lp\24\jl\AndroidManifest.xml;obj\Debug\90\lp\26\jl\AndroidManifest.xml;obj\Debug\90\lp\28\jl\AndroidManifest.xml;obj\Debug\90\lp\29\jl\AndroidManifest.xml;obj\Debug\90\lp\3\jl\AndroidManifest.xml;obj\Debug\90\lp\31\jl\AndroidManifest.xml;obj\Debug\90\lp\32\jl\AndroidManifest.xml;obj\Debug\90\lp\33\jl\AndroidManifest.xml;obj\Debug\90\lp\34\jl\AndroidManifest.xml;obj\Debug\90\lp\35\jl\AndroidManifest.xml;obj\Debug\90\lp\36\jl\AndroidManifest.xml;obj\Debug\90\lp\37\jl\AndroidManifest.xml;obj\Debug\90\lp\38\jl\AndroidManifest.xml;obj\Debug\90\lp\39\jl\AndroidManifest.xml;obj\Debug\90\lp\40\jl\AndroidManifest.xml;obj\Debug\90\lp\41\jl\AndroidManifest.xml;obj\Debug\90\lp\42\jl\AndroidManifest.xml;obj\Debug\90\lp\43\jl\AndroidManifest.xml;obj\Debug\90\lp\44\jl\AndroidManifest.xml;obj\Debug\90\lp\45\jl\AndroidManifest.xml;obj\Debug\90\lp\46\jl\AndroidManifest.xml;obj\Debug\90\lp\47\jl\AndroidManifest.xml;obj\Debug\90\lp\48\jl\AndroidManifest.xml;obj\Debug\90\lp\49\jl\AndroidManifest.xml;obj\Debug\90\lp\5\jl\AndroidManifest.xml;obj\Debug\90\lp\50\jl\AndroidManifest.xml;obj\Debug\90\lp\51\jl\AndroidManifest.xml;obj\Debug\90\lp\52\jl\AndroidManifest.xml;obj\Debug\90\lp\53\jl\AndroidManifest.xml;obj\Debug\90\lp\54\jl\AndroidManifest.xml;obj\Debug\90\lp\55\jl\AndroidManifest.xml;obj\Debug\90\lp\56\jl\AndroidManifest.xml;obj\Debug\90\lp\57\jl\AndroidManifest.xml;obj\Debug\90\lp\58\jl\AndroidManifest.xml;obj\Debug\90\lp\59\jl\AndroidManifest.xml;obj\Debug\90\lp\6\jl\AndroidManifest.xml;obj\Debug\90\lp\60\jl\AndroidManifest.xml;obj\Debug\90\lp\61\jl\AndroidManifest.xml;obj\Debug\90\lp\62\jl\AndroidManifest.xml;obj\Debug\90\lp\63\jl\AndroidManifest.xml;obj\Debug\90\lp\64\jl\AndroidManifest.xml;obj\Debug\90\lp\65\jl\AndroidManifest.xml;obj\Debug\90\lp\67\jl\AndroidManifest.xml;obj\Debug\90\lp\68\jl\AndroidManifest.xml;obj\Debug\90\lp\69\jl\AndroidManifest.xml;obj\Debug\90\lp\70\jl\AndroidManifest.xml;obj\Debug\90\lp\71\jl\AndroidManifest.xml;obj\Debug\90\lp\72\jl\AndroidManifest.xml;obj\Debug\90\lp\73\jl\AndroidManifest.xml;obj\Debug\90\lp\74\jl\AndroidManifest.xml;obj\Debug\90\lp\75\jl\AndroidManifest.xml;obj\Debug\90\lp\78\jl\AndroidManifest.xml" --out "obj\Debug\90\android\AndroidManifest.xml"" exited with code 1.

**Comment by ashleypringle** [comment]
> @johncharris @ashleypringle @iashaik @bitzeal-johan @nikossaperas @coosmiyn @xamarindevelopervietnam @MyAlfisti @chrisfoulds @sevengh @JPZV @thearaks
> 
> Please add nuget Xamarin.Android.ManifestMerger. It will add MSbuild targets that fix Manifest merging.
> And please provide info:
> 
> * if nuget dependency solves the problem
> * whether you have more than 1 Firebase (or Google.Play.Service)  dependencies.
> 
> https://www.nuget.org/packages/Xamarin.Android.ManifestMerger/1.0.0-preview03

Installed Manifest Merger and no longer experiencing the crash. Thanks!

**Comment by moljac** [comment]
Closing this one

**Comment by coosmiyn** [comment]
When I try to build using the ManifestMerger I get this error

`/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/Xamarin.Android.ManifestMerger.targets(5,5): Error MSB3073: The command ""/Users/coosmiyn/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25/bin/java" -cp "/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/common.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/guava.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/kotlin-stdlib-jdk8.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/kotlin-stdlib.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/kxml2.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/manifest-merger.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/sdk-common.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/sdklib.jar" "com.android.manifmerger.Merger" --main "obj/Release/android/AndroidManifest.xml" --libs "obj/Release/lp/61/jl/AndroidManifest.xml:obj/Release/lp/95/jl/AndroidManifest.xml:obj/Release/lp/59/jl/AndroidManifest.xml:obj/Release/lp/92/jl/AndroidManifest.xml:obj/Release/lp/66/jl/AndroidManifest.xml:obj/Release/lp/50/jl/AndroidManifest.xml:obj/Release/lp/68/jl/AndroidManifest.xml:obj/Release/lp/57/jl/AndroidManifest.xml:obj/Release/lp/32/jl/AndroidManifest.xml:obj/Release/lp/35/jl/AndroidManifest.xml:obj/Release/lp/102/jl/AndroidManifest.xml:obj/Release/lp/69/jl/AndroidManifest.xml:obj/Release/lp/56/jl/AndroidManifest.xml:obj/Release/lp/51/jl/AndroidManifest.xml:obj/Release/lp/58/jl/AndroidManifest.xml:obj/Release/lp/67/jl/AndroidManifest.xml:obj/Release/lp/93/jl/AndroidManifest.xml:obj/Release/lp/94/jl/AndroidManifest.xml:obj/Release/lp/60/jl/AndroidManifest.xml:obj/Release/lp/34/jl/AndroidManifest.xml:obj/Release/lp/20/jl/AndroidManifest.xml:obj/Release/lp/18/jl/AndroidManifest.xml:obj/Release/lp/29/jl/AndroidManifest.xml:obj/Release/lp/42/jl/AndroidManifest.xml:obj/Release/lp/89/jl/AndroidManifest.xml:obj/Release/lp/45/jl/AndroidManifest.xml:obj/Release/lp/73/jl/AndroidManifest.xml:obj/Release/lp/87/jl/AndroidManifest.xml:obj/Release/lp/74/jl/AndroidManifest.xml:obj/Release/lp/28/jl/AndroidManifest.xml:obj/Release/lp/1/jl/AndroidManifest.xml:obj/Release/lp/26/jl/AndroidManifest.xml:obj/Release/lp/21/jl/AndroidManifest.xml:obj/Release/lp/75/jl/AndroidManifest.xml:obj/Release/lp/86/jl/AndroidManifest.xml:obj/Release/lp/72/jl/AndroidManifest.xml:obj/Release/lp/44/jl/AndroidManifest.xml:obj/Release/lp/43/jl/AndroidManifest.xml:obj/Release/lp/88/jl/AndroidManifest.xml:obj/Release/lp/38/jl/AndroidManifest.xml:obj/Release/lp/36/jl/AndroidManifest.xml:obj/Release/lp/91/jl/AndroidManifest.xml:obj/Release/lp/65/jl/AndroidManifest.xml:obj/Release/lp/96/jl/AndroidManifest.xml:obj/Release/lp/100/jl/AndroidManifest.xml:obj/Release/lp/54/jl/AndroidManifest.xml:obj/Release/lp/98/jl/AndroidManifest.xml:obj/Release/lp/53/jl/AndroidManifest.xml:obj/Release/lp/30/jl/AndroidManifest.xml:obj/Release/lp/37/jl/AndroidManifest.xml:obj/Release/lp/39/jl/AndroidManifest.xml:obj/Release/lp/99/jl/AndroidManifest.xml:obj/Release/lp/52/jl/AndroidManifest.xml:obj/Release/lp/101/jl/AndroidManifest.xml:obj/Release/lp/55/jl/AndroidManifest.xml:obj/Release/lp/97/jl/AndroidManifest.xml:obj/Release/lp/63/jl/AndroidManifest.xml:obj/Release/lp/64/jl/AndroidManifest.xml:obj/Release/lp/90/jl/AndroidManifest.xml:obj/Release/lp/46/jl/AndroidManifest.xml:obj/Release/lp/41/jl/AndroidManifest.xml:obj/Release/lp/83/jl/AndroidManifest.xml:obj/Release/lp/77/jl/AndroidManifest.xml:obj/Release/lp/48/jl/AndroidManifest.xml:obj/Release/lp/70/jl/AndroidManifest.xml:obj/Release/lp/84/jl/AndroidManifest.xml:obj/Release/lp/24/jl/AndroidManifest.xml:obj/Release/lp/23/jl/AndroidManifest.xml:obj/Release/lp/4/jl/AndroidManifest.xml:obj/Release/lp/3/jl/AndroidManifest.xml:obj/Release/lp/85/jl/AndroidManifest.xml:obj/Release/lp/71/jl/AndroidManifest.xml:obj/Release/lp/76/jl/AndroidManifest.xml:obj/Release/lp/49/jl/AndroidManifest.xml:obj/Release/lp/40/jl/AndroidManifest.xml:obj/Release/lp/47/jl/AndroidManifest.xml:obj/Release/lp/22/jl/AndroidManifest.xml:obj/Release/lp/25/jl/AndroidManifest.xml" --out "obj/Release/android/AndroidManifest.xml"" exited with code 1. (MSB3073) (ClubHub.Android)`

**Comment by moljac** [comment]
@coosmiyn I replied in XamarinComponents issue. Thanks for opening issue there.

**Comment by mintyfusion** [comment]
After adding the ManifestManager, I'm also receiving the same error as above. @coosmiyn if you can please provide a link where you have replied in Xamarin Components.

**Comment by coosmiyn** [comment]
@mintyfusion https://github.com/xamarin/XamarinComponents/issues/734

**Comment by xamarindevelopervietnam** [comment]
same here!
