### ISSUE TITLE
FirebaseVisionBarcodeDetector missing in preview8

### ISSUE THREAD

**Issue by subsembly** [xamarin/GooglePlayServicesComponents#225]
I used to get the FirebaseVisionBarcodeDetector via FirebaseVision.Instance.GetVisionBarcodeDetector(). However, after upgrading from preview6 to preview8, neither GetVisionBarcodeDetector nor the class FirebaseVisionBarcodeDetector is bound anymore.

Xamarin.Firebase.ML.Vision 71.1700.0-preview8

Any work around possible?

**Comment by moljac** [comment]
@subsembly 

Can you check `VisionBarcodeDetector` property maybe?

I need to rebuild in order to search for the missing class and it will take few hours. So, tommorow 1st results.

**Comment by moljac** [comment]
Found it. Now I need to see the reason why it wasn't surfaced in preview8

Thanks for reporting

**Comment by moljac** [comment]
@subsembly Can you check preview9 and if this issue is fixed please close it.

Thanks

**Comment by subsembly** [comment]
Fixed with preview9
