### ISSUE TITLE
xamarin.googleplayservices.fido is not supporting play-services-fido version 17.0.0

### ISSUE THREAD

**Issue by consoleit** [xamarin/GooglePlayServicesComponents#226]
### Describe your Issue:
xamarin.googleplayservices.fido is missing some classes required in Fido2 as current xamarin.googleplayservices.fido is targeting play-services-fido version 16.0.0 and the new classes are in version 17.0.0

**Comment by moljac** [comment]
@consoleit I managed bump it to 17.0.0. For 18.0.0 I'll need more time due to dependencies.

`preview9` will be out soon.

**Comment by consoleit** [comment]
@moljac that's great. I can test the preview when it's out and please let me know if I can do any help.

**Comment by consoleit** [comment]
@moljac preview 71.1700-9 with version play services 17.0.0 is working well in both register and authentication scenarios. thanks for the fast update.
