### ISSUE TITLE
Upgrade Google Play Games

### ISSUE THREAD

**Issue by gabry90** [xamarin/GooglePlayServicesComponents#227]
### Xamarin.Android Version (eg: 6.0):
Latest

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 64-bit

### Google Play Services Version (eg: 8.4.0):
Latest

### Describe your Issue:
When upgrade Google Play Games to latest version? Leaderboard and Achievement not work!

### Steps to Reproduce (with link to sample solution if possible):
Nothing

**Comment by moljac** [comment]
@gabry90 
I managed to bump to 17.0.0 without too much hassle, but for 18.0.0 I'll need more time due to dependencies and some conflicts with other artifacts.

**Comment by gabry90** [comment]
no problem, as long as the update is taken into consideration because I need the latest features of Google Play Games :)

**Comment by moljac** [comment]
@gabry90 Did you try preview9?

If that is OK. Please close this issue.
