### ISSUE TITLE
Please update the bindings to the June 17, 2019 major update of the Google Play Services libraries

### ISSUE THREAD

**Issue by horaciojcfilho** [xamarin/GooglePlayServicesComponents#231]
From https://firebase.google.com/support/release-notes/android#update_-_june_17_2019:
> This release is a MAJOR version update and includes breaking changes.
> With this release, libraries are migrated from the Android Support Libraries to the Jetpack (AndroidX) Libraries.
> The updated libraries will not work unless you make the following changes in your app:
> - Upgrade com.android.tools.build:gradle to v3.2.1 or later.
> - Upgrade compileSdkVersion to 28 or later.
> - Update your app to use Jetpack (AndroidX); follow the instructions in Migrating to AndroidX.

**Comment by moljac** [comment]
Those GPS artifacts are AndroidX dependent.

Xamarin AndroidX is not released (yet).

**Comment by moljac** [comment]
Starting working on updated bits that depend on AndroidX (next week)

it will be on separate branch.

Please try release 71 and open new issue.

If necessary link to this issue please.

Closing.
