### ISSUE TITLE
Method getGoogleTransactionId() haven't been added into Xamarin.GooglePlayServices.Wallet 60.1142.1

### ISSUE THREAD

**Issue by Hasdik** [xamarin/GooglePlayServicesComponents#232]
### Xamarin.Android Version (eg: 6.0):
Xamarin.GooglePlayServices.Wallet v60.1142.1

### Describe your Issue:
We get an error:
Java.Lang.NoSuchMethodError: No virtual method getGoogleTransactionId()Ljava/lang/String; in class Lcom/google/android/gms/wallet/PaymentData; or its super classes (declaration of 'com.google.android.gms.wallet.PaymentData' appears in /data/app/lealta.lealta_mobile_cabinet-1/base.apk:classes2.dex)

Can you add a getGoogleTransactionId () method?

**Comment by moljac** [comment]
@Hasdik 

It has been surfaced in newer versions. (Checked few secs ago)

please try `preview9` until release is out (and this is matter of minutes, hours, maybe days, but I hope not)

**Comment by Hasdik** [comment]
We have about a week in time, during which time can you add this method?

**Comment by Hasdik** [comment]
@moljac 
We have about a week in time, during which time can you add this method?

**Comment by moljac** [comment]
@Hasdik The method will NOT be added to 60.1142.1.

Please try: 71.1600.0-preview9

from https://www.nuget.org/packages/Xamarin.GooglePlayServices.Wallet/

so 
https://www.nuget.org/packages/Xamarin.GooglePlayServices.Wallet/71.1600.0-preview9

It should be in there

**Comment by moljac** [comment]
Please try release 71 and open new issue.

If necessary link to this issue please.

Closing.
