### ISSUE TITLE
Firebase.Perf not sending logs. (InstanceID is null)

### ISSUE THREAD

**Issue by MatFillion** [xamarin/GooglePlayServicesComponents#234]
### Xamarin.Android Version (eg: 6.0):
Android 9.0
Xamarin.Android SDK 9.1.7.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows

### Google Play Services Version (eg: 8.4.0):
The one implicitly referenced by Xamarin.Firebase.Perf 71.1620.0 

### Describe your Issue:
Logs for Firebase.Performance are not sent to the firebase console. We think this log points to the problem. (full log below)
The adb log says 
```
Google Pixel 3 XL    Warning    13718    FirebasePerformance    App Instance ID is null or empty, dropping the log
```

### Steps to Reproduce (with link to sample solution if possible):
I published a sample app demonstrating the problem:
https://github.com/MatFillion/firebase-performance-sample
 You can observe 3 things.
1- Startup performance logs are not received by the firebase console.
2- Tapping on the Http call button making a dummy call should be logged automatically but nothing happens.
3- Tapping on TRACED HTTP CALL button does tracing with NewHttpMetric but we get this log instead
```
07-22 17:31:25.208 W/FirebasePerformance(10508): App Instance ID is null or empty, dropping the log
07-22 17:31:25.209 W/FirebaseRemoteConfig(10508): IPC failure: 10:NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference
```

### Include any relevant Exception Stack traces, build logs, adb logs:
Related to #228 which we think wasn't really fixed but we were asked to create a new issue.

**Comment by MatFillion** [comment]
We realized that not only Firebase.Performance doesn't work but if we add firebase.performance on top of Firebase.Analytics it prevents analytics from working properly.

Summary : 
* Xamarin.Firebase.Analytics only -> analytic events are sent and shown in the dashboard
* Xamarin.Firebase.Analytics+ Performance ->  analytics and performance both don't work.

Here is a github project with 2 branches, one with only analytics and one with analytics + perf
https://github.com/MatFillion/Firebase-analytics-sample/

**Comment by moljac** [comment]
@MatFillion 
Seems like google uses some kind of gradle plugin for perf. And this will be a problem.

I will take a look into sample[s] - thanks.

**Comment by MatFillion** [comment]
@moljac yeah, discussed a little bit on Gitter with @Redth  and he mentioned the same thing.

One thing that came to my mind is that the gradle plugin must not be something new to firebase.performance monitoring and when I started to try out the packages I had a partially working solution with 60.1142.1, so I went back and validated things.

I added a sample using the previous version of Xamarin.Firebase.Performance 60.1142.1 and it properly finds the InstanceID according to ADB Logs. (for the startup logs)
 Here are the logs I see using the "old" packages:
```
07-23 17:23:37.405 I/FirebasePerformance(17530): Firebase Performance is Enabled
07-23 17:23:37.412 D/FirebasePerformance(17530): onResume md5563b6af7023eaa6da10c5306c2845b23.MainActivity:1334536
07-23 17:23:37.421 I/FA      (17530): Tag Manager is not found and thus will not be used
07-23 17:23:37.726 I/FirebasePerformance(17530): Logging TraceMetric - _as 1334ms
```
It is the branch [version-60-1142-1](https://github.com/MatFillion/firebase-performance-sample/blob/version-60-1142-1/README.md).

In that version the HttpMetrics were not present (and it's also limited to MonoAndroid81 which won't be accepted in a few months) so that's why we looked into the 71 version.

**Comment by MatFillion** [comment]
As for Firebase.Performance interfering with Firebase.Analytics here are the tests/investigations we've done.

### Are dependencies matching well together?
#### Dependencies of Perf are:
* Xamarin.Build.Download (>= 0.4.11)
* Xamarin.Firebase.Analytics (>= 71.1606.0)
* Xamarin.Firebase.Common (>= 71.1610.0)
* Xamarin.Firebase.Config (>= 71.1610.0)
* Xamarin.Firebase.Iid (>= 71.1710.0)
* Xamarin.GooglePlayServices.Base (>= 71.1610.0)
* Xamarin.GooglePlayServices.Basement (>= 71.1620.0)
* Xamarin.GooglePlayServices.Clearcut (>= 71.1600.0)
* Xamarin.GooglePlayServices.Phenotype (>= 71.1600.0)
* Xamarin.GooglePlayServices.Tasks (>= 71.1601.0)

#### Dependencies of Xamarin.Firebase.Analytics are
* Xamarin.Build.Download (>= 0.4.11)
* Xamarin.Firebase.Analytics.Impl (>= 71.1624.0)
* Xamarin.Firebase.Common (>= 71.1610.0)
* Xamarin.GooglePlayServices.Basement (>= 71.1620.0)
* Xamarin.GooglePlayServices.Measurement.Api (>= 71.1604.0)
* Xamarin.GooglePlayServices.Measurement.Base (>= 71.1605.0)
* Xamarin.GooglePlayServices.Stats (>= 71.1601.0)

Good thing is the common dependencies all are the same version!

We tried Xamarin.Firebase.Analytics + it's dependencies + all the Perf dependencies (without perf itself)
Result: InstanceID was OK.

### Can we reproduce the InstanceID problem with C# Code instead of relying on hidden code within Xamarin.Firebase.Perf?
Result: Yes
Calling `Xamarin.firebase.Analytics.Instance.Id` throws a null ref exception (Instance is null). 

The same code does not throw an exception when we use. Xamarin.Firebase.Analytics alone (without Performance).`

### How does this InstanceID thing work?
Under the hood it uses `Xamarin.Common.FirebaseApp.Get(class)`, which uses ComponentRuntime, the IoC of GooglePlayServices.

**Comment by MatFillion** [comment]
> When I started to try out the packages a few weeks ago I had a partially working solution with 60.1142.1, so I went back and validated things.
> 
> I added a sample using the previous version of Xamarin.Firebase.Performance 60.1142.1 and it properly finds the InstanceID according to ADB Logs. (for the startup logs)
> Here are the logs I see using the "old" packages:
> 
> ```
> 07-23 17:23:37.405 I/FirebasePerformance(17530): Firebase Performance is Enabled
> 07-23 17:23:37.412 D/FirebasePerformance(17530): onResume md5563b6af7023eaa6da10c5306c2845b23.MainActivity:1334536
> 07-23 17:23:37.421 I/FA      (17530): Tag Manager is not found and thus will not be used
> 07-23 17:23:37.726 I/FirebasePerformance(17530): Logging TraceMetric - _as 1334ms
> ```

At the time I wrote the above comment I couldn't validate in the console as it takes 12hrs to display data. This morning I confirmed that I did receive the logs of startup using the 60.1142.1 packages
![image](https://user-images.githubusercontent.com/7029537/61811969-9ab87380-ae10-11e9-8b76-4d566e33136f.png)

**Comment by moljac** [comment]
@MatFillion 
Thanks a lot for your comments and investigation and feedback of course.

> it must be a small thing that's screwing up the instanceID, while troublesome, the gradle plugin might not be our problem here?

I (me/myself) can only hope that we do not need that gradle plugin

**Comment by moljac** [comment]
@MatFillion 

Could you try Xamarin.Android.ManifestMerger and provide us feedback, please?

There are known issues with AndroidManifest.xml and we are testing new approach.

https://www.nuget.org/packages/Xamarin.Android.ManifestMerger/1.0.0-preview03

**Comment by alihaluk** [comment]
@moljac 

Hi, is there any documentation for ManifestMerger ? I want to try it but doesn't know how to use.

**Comment by moljac** [comment]
@MatFillion Please can you provide feedback if ManifestMerger works?

Can you try Xamarin.Android.ManifestMerger, because it smells like manifest is not properly merged.

ManifestMerger is a nuget package that adds MSBuild tasks that properly merge AndroidManifes.xml from various nuget packages for bound artifacts.

https://www.nuget.org/packages/Xamarin.Android.ManifestMerger/1.0.0-preview03

**Comment by moljac** [comment]
closing this issue
