### ISSUE TITLE
Xamarin.Firebase.Ads 71.1620.0 leads to compile error

### ISSUE THREAD

**Issue by mfeingol** [xamarin/GooglePlayServicesComponents#236]
### Steps to Reproduce

1. Update Firebase and Google Play Services from 60.1142.1 to 71.1620.0
2. Build an Android project
3. Observe the error

### Expected Behavior

The project should build.

### Actual Behavior

Build error:

```
4>  obj\Debug\90\android\src\mono\com\google\android\gms\ads\reward\mediation\MediationRewardedVideoAdListenerImplementor.java:4: error: MediationRewardedVideoAdListenerImplementor is not abstract and does not override abstract method zzc(Bundle) in MediationRewardedVideoAdListener
4>  public class MediationRewardedVideoAdListenerImplementor
4>         ^
4>  Note: Some input files use or override a deprecated API.
4>  Note: Recompile with -Xlint:deprecation for details.
4>  Note: Some input files use unchecked or unsafe operations.
4>  Note: Recompile with -Xlint:unchecked for details.
4>  1 error
4>C:\Operations\Build\Home\Sideroads\Source\Sideroads.Xamarin\Sideroads.Android\obj\Debug\90\android\src\mono\com\google\android\gms\ads\reward\mediation\MediationRewardedVideoAdListenerImplementor.java(4,8): error :  error: MediationRewardedVideoAdListenerImplementor is not abstract and does not override abstract method zzc(Bundle) in MediationRewardedVideoAdListener
4>C:\Operations\Build\Home\Sideroads\Source\Sideroads.Xamarin\Sideroads.Android\obj\Debug\90\android\src\mono\com\google\android\gms\ads\reward\mediation\MediationRewardedVideoAdListenerImplementor.java(4,8): error : public class MediationRewardedVideoAdListenerImplementor
4>C:\Operations\Build\Home\Sideroads\Source\Sideroads.Xamarin\Sideroads.Android\obj\Debug\90\android\src\mono\com\google\android\gms\ads\reward\mediation\MediationRewardedVideoAdListenerImplementor.java(4,8): error : 
```

### Version Information

VS 2019 16.1.6

```
     <PackageReference Include="Xamarin.GooglePlayServices.Ads">
-      <Version>60.1142.1</Version>
+      <Version>71.1712.0</Version>
```

**Comment by moljac** [comment]
@mfeingol 

> Update Firebase and Google Play Services from 60.1142.1 to 71.1620.0

What is the starting point? Any Android app?

There is obfuscated method that changed the name, but your report does not help very much.

**Comment by mfeingol** [comment]
@moljac: apologies for the lack of details. I was hoping the issue would be obvious.

My own Xamarin Forms app has this problem. I haven't tried with a completely fresh app. I will do so.

**Comment by moljac** [comment]
@mfeingol 
No need to apologize, just to be fast I (we) need more info.

I have almost zilch samples with 60.1142 version and searching will take me a lot of time.

Fix is building right now see current build:
https://dev.azure.com/xamarin/public/_build/results?buildId=4583

**Comment by mfeingol** [comment]
@moljac: it repros in a new project as soon as you add Xamarin.Firebase.Ads 71.1601.0. Here's a solution:

[236.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/3423918/236.zip)

**Comment by moljac** [comment]
@mfeingol Excellent. Thanks.

Testing.

And here are the nugets for testing for you:

https://dev.azure.com/xamarin/_apis/resources/Containers/4298666?itemPath=nuget&$format=zip

Need to test and if OK tag to trigger signed builds

**Comment by mfeingol** [comment]
Unfortunately I don't have access to that link. :-(

**Comment by moljac** [comment]
Hm he builds are public. I must check the rights for artifacts

**Comment by motoko89** [comment]
> @mfeingol Excellent. Thanks.
> 
> Testing.
> 
> And here are the nugets for testing for you:
> 
> https://dev.azure.com/xamarin/_apis/resources/Containers/4298666?itemPath=nuget&$format=zip
> 
> Need to test and if OK tag to trigger signed builds

The build is not accessible. What is the current workaround?

**Comment by moljac** [comment]
@motoko89 @mfeingol 

Please update `Xamarin.GooglePlayServices.Ads.Lite` nuget package to 71.1712.1.

https://www.nuget.org/packages/Xamarin.GooglePlayServices.Ads.Lite/71.1712.1

And close this issue if the problem is solved

**Comment by mfeingol** [comment]
I built debug and release and it seems to work. Thanks for fixing this!

**Comment by mfeingol** [comment]
And as a side note, your app may crash following the upgrade. The solution is in the device log:

```
08-02 20:06:23.099	android_9_0	Error	6579	AndroidRuntime	******************************************************************************
08-02 20:06:23.099	android_9_0	Error	6579	AndroidRuntime	* follow instructions here: https://goo.gl/h17b6x.                           *
08-02 20:06:23.099	android_9_0	Error	6579	AndroidRuntime	* App ID inside the AndroidManifest. Google Ad Manager publishers should     *
08-02 20:06:23.099	android_9_0	Error	6579	AndroidRuntime	* should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
08-02 20:06:23.099	android_9_0	Error	6579	AndroidRuntime	* The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
08-02 20:06:23.099	android_9_0	Error	6579	AndroidRuntime	******************************************************************************
```

Those two links have the solution.
