### ISSUE TITLE
Versioning section in README is out of date

### ISSUE THREAD

**Issue by jkasten2** [xamarin/GooglePlayServicesComponents#238]
Versioning section in README is out of date, it does not include any versions past 60.1142.0.
https://github.com/xamarin/GooglePlayServicesComponents/tree/71#versioning

Please update this mapping table.

**Comment by moljac** [comment]
@jkasten 

This will be resource intensive task to keep the track.

I did quick and dirty trick that points to released config.json.

Check it and close the issue if this is OK, please.

**Comment by jkasten2** [comment]
@moljac Thanks, reading the `config.json` gets Xamarin version to native Google library mapping I was looking for.

**Comment by GitJens** [comment]
Please, don’t mix @jkasten with @jkasten2 ;)
