### ISSUE TITLE
Xamarin.Firebase.Firestore 71.1705.0 since Preview3 doesn't work

### ISSUE THREAD

**Issue by charlitos2** [xamarin/GooglePlayServicesComponents#239]
### Xamarin.Android Version (eg: 6.0):

       9.4.0.51

### Operating System & Version (eg: Mac OSX 10.11):

     Windows 10 Updated July 2019

### Google Play Services Version (eg: 8.4.0):

    71.1610.0

### Describe your Issue:

            I tried work with firebase Firestore, but since version Preview2 on Nuget packages, this 
            library doesn't work; and for that I just work with Preview2 version and works well, But, 
            with this new release I got the same error. 

     Well I think this error it's because it's missing a library with "io.opencensus.tags.Tags" module, and I check all modules, and in Maven Repository, I see this module check like dependency from Grpc Library, And in Xamarin.Grpc, this library doesnt exists. It will be this the cause an error??

### Steps to Reproduce (with link to sample solution if possible):
1. Create a simple project android xamarin.
2. Add all principal firebase modules, principal Google play services and Guava nugets.
3. Initializing firebase with google json file, and all ok.
4. Create a button and on click event load a document firestore.
5. Its here crash all application, resulting the error in log above showed.

### Include any relevant Exception Stack traces, build logs, adb logs:

07-26 17:23:10.541 D/AndroidRuntime(10387): Shutting down VM
**Java.Lang.RuntimeException:** 'Loading...'

07-26 17:23:13.465 E/AndroidRuntime(10387): FATAL EXCEPTION: main
07-26 17:23:13.465 E/AndroidRuntime(10387): java.lang.RuntimeException: Internal error in Firestore (0.6.6-dev).
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at com.google.firebase.firestore.g.zza.zzb(com.google.firebase:firebase-firestore@@17.0.5:324)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at com.google.firebase.firestore.g.zzd.run(com.google.firebase:firebase-firestore@@17.0.5)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at android.os.Handler.handleCallback(Handler.java:751)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at android.os.Looper.loop(Looper.java:154)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at android.app.ActivityThread.main(ActivityThread.java:6165)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at java.lang.reflect.Method.invoke(Native Method)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
07-26 17:23:13.465 E/AndroidRuntime(10387): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lio/opencensus/tags/Tags;
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at io.grpc.internal.CensusStatsModule.<init>(CensusStatsModule.java:84)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at io.grpc.internal.AbstractManagedChannelImplBuilder.getEffectiveInterceptors(AbstractManagedChannelImplBuilder.java:426)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:410)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at com.google.firebase.firestore.f.zzd.<init>(com.google.firebase:firebase-firestore@@17.0.5:102)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at com.google.firebase.firestore.b.zzg.zza(com.google.firebase:firebase-firestore@@17.0.5:1217)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at com.google.firebase.firestore.b.zzi.run(com.google.firebase:firebase-firestore@@17.0.5)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at com.google.firebase.firestore.g.zza$zza.run(com.google.firebase:firebase-firestore@@17.0.5:190)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at java.lang.Thread.run(Thread.java:761)
07-26 17:23:13.465 E/AndroidRuntime(10387): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.opencensus.tags.Tags" on path: DexPathList[[zip file "/data/app/pe.grupodaner.escaly.user-1/base.apk"],nativeLibraryDirectories=[/data/app/pe.grupodaner.escaly.user-1/lib/arm, /data/app/pe.grupodaner.escaly.user-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-26 17:23:13.465 E/AndroidRuntime(10387): 	... 13 more

**Comment by moljac** [comment]
@charlitos2 Minimal repro sample would speed up investigation.

**Comment by charlitos2** [comment]
Alright, here it's a minimal project sample, and config with your own google json, and put the name of app, in the manifest file. that's all.

[FirestoreApp1.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/3437832/FirestoreApp1.zip)

**Comment by moljac** [comment]
@charlitos2 Thanks. I'm on it.

**Comment by dblookup** [comment]
Just chiming in to say I'm also experiencing this. "io.opencensus.tags.Tags" didn't found.
java.lang.RuntimeException: Internal error in Firestore (0.6.6-dev).
....
java.lang.ClassNotFoundException: Didn't find class "io.opencensus.tags.Tags"

**Comment by Redth** [comment]
Please try the latest preview and open a new issue if there are still problems with it.  Thanks.

**Comment by moljac** [comment]
Seems that our dependency detection tool has some issues with transitive dependencies.

`opencensus` libraries are telemetry libraries used by google.

The highest priority is to finish those bindings ASAP.

Duplicates

Xamarin.Firebase.Firestore 71.1705.0 Stills not working #258

https://github.com/xamarin/GooglePlayServicesComponents/issues/258

Firebase Firestore version 71.1705.0 not working #233

https://github.com/xamarin/GooglePlayServicesComponents/issues/233

**Comment by moljac** [comment]
@dblookup @charlitos2 

The issue should be fixed in version 71.20190927

Packages:

*   Xamarin.Firebase.Firestore 71.1705.1
*   Xamarin.GooglePlayServices.Games.71.1700.1

Please update your packages and provide us feedback here (or even close the issue if issue is fixed)
Thanks

**Comment by dblookup** [comment]
@moljac , the issue was solved. Thank you so much for help!

**Comment by charlitos2** [comment]
I agree, this issue was solved. Thank you guys so much. I appreciate your work and time to help us.

**Comment by moljac** [comment]
@dblookup @charlitos2 
Guys thanks for providing feeback and for being patient 8)
