### ISSUE TITLE
Xamarin Forms Analytics and Crashalytics

### ISSUE THREAD

**Issue by jrahma** [xamarin/GooglePlayServicesComponents#246]
Hi,

It will be great if you provide a cross platform Firebase Analytics and Crashalytics to replace the current Android only so user does't need to depend on dependencies

Thanks,
[Jassim](https://www.softnames.com)

**Comment by moljac** [comment]
@jrahma This repo is Android only. "Lifting" abstraction over Android and iOS API (Xamarin.Forms like) consumes quite a lot of effort.

We will discus it, but no promises.

**Comment by iMakeIndia** [comment]
As MS is now focused on Xamarin.Forms cross platform, so we would to have more Xamarin.Forms component like this(Analytics & Crashalytics) along with Firebase Push Notification.

**Comment by moljac** [comment]
New versions of Analytics and Charslytics were published.

Closing this issue
