### ISSUE TITLE
Failed to retrieve Firebase Instance Id

### ISSUE THREAD

**Issue by kyluke** [xamarin/GooglePlayServicesComponents#249]
### Xamarin.Android Version (eg: 6.0):
Version: 9.4.0.51

### Operating System & Version (eg: Mac OSX 10.11):
Mac OS X 10.14.6

### Describe your Issue:
Can't get an FCM token with the sample code provided here https://github.com/xamarin/GooglePlayServicesComponents/blob/master/samples/com.google.firebase/firebase-messaging/FirebaseMessagingQuickstart/MyFirebaseIIdService.cs

### Steps to Reproduce (with link to sample solution if possible):
- Install `Xamarin.Firebase.Messaging` `71.1740.0`.
- Copy and paste code from https://github.com/xamarin/GooglePlayServicesComponents/blob/master/samples/com.google.firebase/firebase-messaging/FirebaseMessagingQuickstart/MyFirebaseIIdService.cs
- Get: [FA] Failed to retrieve Firebase Instance Id

**Comment by corneliu-serediuc** [comment]
Same here!

I was glad to update to the latest Firebase libraries, and then to find out that it is not working properly. Spent 2 days already on trying to fix it with no success.

Please help!

**Comment by GuillaumeSE** [comment]
@corneliu-serediuc 
Can you try the WorkAround we provided there?
https://github.com/xamarin/GooglePlayServicesComponents/issues/216#issuecomment-517740275
The instance ID is most probably null because the manifest is not properly merged.
I know the Xamarin team is working on a Manisfest merger solution but I don't know when it will be release.

**Comment by corneliu-serediuc** [comment]
Thank you @GuillaumeSE, but I have to fix it in another way and now it is working.
What I was missing was the service name inside the Service attribute, like this:

```
    [Service(Name = "packageName.MyFirebaseMessagingService")]
    [IntentFilter(new[] { "com.google.firebase.MESSAGING_EVENT" })]
    public class MyFirebaseMessagingService : FirebaseMessagingService
    {
        public const string TAG = "GB_FCM";

        public override void OnNewToken(string p0)
        {
            base.OnNewToken(p0);

            Log.Debug(TAG, "MyFirebaseMessagingService :: OnNewToken :: Refreshed token: " + p0);

            RegisterDevice(p0);
        }
     }
```

Hope this helps someone!

**Comment by kyluke** [comment]
Hi @corneliu-serediuc, I still am not able to get a token from firebase. Perhaps I am missing something?
Did you simply make that one change to your code base?

**Comment by sumitiu** [comment]
Any Updates on this

**Comment by moljac** [comment]
@sumitiu I have been working on this issue. We hope fix will be implemented soon.

**Comment by mindtheappsrl** [comment]
The main problem is the latest version of Xamarin.Firebase.Core (71.1601.0), if you downgrade it, everything worked!.

Here's my workaround:

1. Downgrade Xamarin.Firebase.Core to 60.1142.1 on Android Project
2. On MainActivity, just after "LoadApplication" (in my case is a Xamarin Forms project) use this code
`           
 LoadApplication(new App());
            
            if (IsPlayServicesAvailable())
            {
                FirebaseApp.InitializeApp(this);
                CreateNotificationChannel();
            }   

-------
        public bool IsPlayServicesAvailable()
        {
            string message = "";
            int resultCode = GoogleApiAvailability.Instance.IsGooglePlayServicesAvailable(this);
            if (resultCode != ConnectionResult.Success)
            {
                if (GoogleApiAvailability.Instance.IsUserResolvableError(resultCode))
                    message = GoogleApiAvailability.Instance.GetErrorString(resultCode);
                else
                {
                    message = "This device is not supported";
                    Finish();
                }
                return false;
            }
            else
            {
                message = "Google Play Services is available.";
                return true;
            }
        }
---------
 private void CreateNotificationChannel()
        {
            if (Build.VERSION.SdkInt < BuildVersionCodes.O)
            {
                // Notification channels are new in API 26 (and not a part of the
                // support library). There is no need to create a notification
                // channel on older versions of Android.
                return;
            }

            var channel = new NotificationChannel(CHANNEL_ID,
                                                  "HYDRA",
                                                  NotificationImportance.High)
            {
                Description = "Firebase Cloud Messages appear in this channel"
            };

            var notificationManager = (NotificationManager)GetSystemService(Android.Content.Context.NotificationService);
            notificationManager.CreateNotificationChannel(channel);
        }
`
3. Create an override of OnNewToken on MyFirebaseMessagingService class like the following example
`[Service]
[IntentFilter(new[] { "com.google.firebase.MESSAGING_EVENT" })]
public class MyFirebaseMessagingService : FirebaseMessagingService
{
    public override void OnNewToken(string p0)
    {
        Log.Debug(TAG, "Refreshed token: " + p0);
        base.OnNewToken(p0);
    }
`
Hope it helps

**Comment by JoacimWall** [comment]
read this now so i pause for while on this update.
https://github.com/xamarin/GooglePlayServicesComponents/issues/249

**Comment by moljac** [comment]
@kyluke @corneliu-serediuc @sumitiu @mindtheappsrl 

Could you try Xamarin.Android.ManifestMerger and provide us feedback, please?

There are known issues with AndroidManifest.xml and we are testing new approach.

https://www.nuget.org/packages/Xamarin.Android.ManifestMerger/1.0.0-preview03

**Comment by moljac** [comment]
@matibak No problems. Thank you for the feedback. I'm glad that worked

**Comment by ramyzbeidy** [comment]
So Xamarin.Firebase.Messaging package should be dependant on Xamarin.Android.ManifestMerger  ?

**Comment by moljac** [comment]
@ramyzbeidy 
No. Seems like ManifestMerger functionality will be moved to core Xamarin.Android tooling.

**Comment by JoacimWall** [comment]
Hi after adding the Xamarin.Android.ManifestMerger
I get this when recive a messages:

Java.Lang.NoSuchFieldError: 'No static field zzaqu of type [Ljava/lang/String; in class Lcom/google/android/gms/measurement/AppMeasurement$UserProperty; or its superclasses (declaration of 'com.google.android.gms.measurement.AppMeasurement$UserProperty' appears in /data/app/com.nixonnixon.libero-ZXAA_cGmXe-jPb_UTw4c9w==/base.apk)'

**Comment by ramyzbeidy** [comment]
When can we expect ETA for that to be added to Xamarin.Android? any beta version of this? Since no one can update to the latest Firebase package with this bug.

**Comment by moljac** [comment]
@ramyzbeidy 

Add ManifestMerger manually. It injects MSBuild Custom Task[s] that merge Manifests properly.

After this will be teseted and added to Xamarin.Android core you will need no nuget package. 

> Since no one can update to the latest Firebase package with this bug.

People do report sucess with ManifestMerger. If you still have issues please open issue with details.

**Comment by moljac** [comment]
@JoacimWall 

OK. This seems like bindings issue, not ManifestMerger. Please open new issue for that with the details

**Comment by rgustavsson** [comment]
Including the Xamarin.Android.ManifestMerger solved my issue as well.
OnNewToken in my FirebaseMessagingService is invoked (again) each time I start my android app.

**Comment by moljac** [comment]
Closing this issue.

**Comment by RumbosN** [comment]
I solved this removing Xamarin.GooglePlayServices.Gcm, Xamarin.Firebase.Core and Xamarin.Firebase.Measurement.Connector.impl packages like:
https://github.com/xamarin/GooglePlayServicesComponents/issues/216#issuecomment-559210025
