### ISSUE TITLE
GoogleServicesJson BuildAction missing

### ISSUE THREAD

**Issue by tallkid10** [xamarin/GooglePlayServicesComponents#25]
### Describe your Issue:
If I use the FirebaseMessaging quickstart sample I see GoogleServicesJson BuildAction is available when I selecet the google-services.json file in the project.

However, according to @Redth 's comment in [this thread](https://forums.xamarin.com/discussion/70248/firebase-configuration/p2) I just need to add the nuget package for Xamarin.GoogleServices.Basement and it should be available.  I have tried this in new projects but I have been unsuccesful.  Is there something else I need to do?

### Steps to Reproduce (with link to sample solution if possible):
-Create a new project
-Add your google-services.json to the project
-Add the nuget package for Xamarin.GoogleServices.Basement
-Click on google-services.json and go to properties.  The buildaction is not available and if you try to enter it manually an error appears saying "Property value is not valid"

**Comment by Redth** [comment]
The build actions can be a bit finicky right after you install a nuget package.  Here are a few things to try:

1. Try cleaning/rebuilding your project
2. Try restarting Visual Studio
3. Make sure that your .csproj has an entry which includes `Xamarin.GooglePlayServices.Basement.targets`

**Comment by tallkid10** [comment]
Rebuilding solved the problem, thanks again @Redth !

**Comment by bmseqat** [comment]
Easy way is to modify .csproj file in TextEdit by adding the following line
<ItemGroup>
    <GoogleServicesJson Include="google-services.json" />
 </ItemGroup>

PS: I tried to clean/rebuild project or restart Xamarin IDE many times, but the results are not consistent.

**Comment by runawayGoblin** [comment]
would there be a .csproj in Xamarin.Forms? or would it be in my specific AppName.Android and Appname.iOS? I'm trying to use the Firebase Auth in both my iOS and Android versions of my app

**Comment by sulimanfarzat** [comment]
download this Packages und restart 👍 
![image](https://user-images.githubusercontent.com/24265145/32135186-255083d4-bbfb-11e7-8187-63c3cdb73cac.png)


![image](https://user-images.githubusercontent.com/24265145/32135198-4dd6be7c-bbfb-11e7-8602-345e3a7ef598.png)

**Comment by juanagu** [comment]
@sulimanfarzat  Thanks! Works for me!

**Comment by VitalinaMoskalenko** [comment]
I have error, but all Packages has been installed

![image](https://user-images.githubusercontent.com/22708390/35243501-685ac7a6-ffbd-11e7-8d72-f542d12c4d3f.png)

**Comment by sulimanfarzat** [comment]
@vitalina
Make sure build Action is GoogleServicesJson

**Comment by geedsen** [comment]
I am unable to Xamarin.Firebase packages. It telss me it is incompatible with MonoAndroid 7.1. I f I try to replave the Mono.Andoid.dll with the 8.0 version, it still just adds the 7.1 version.

**Comment by BanDylan** [comment]
@geedsen Try lowing the version of the Xamarin.Firebase package. That worked for me. Best of luck :)

**Comment by ahoefling** [comment]
Clean/Rebuild + VS Restart fixed it for me

**Comment by vlkam** [comment]
I added the section in csproj 

  <ItemGroup>
    <GoogleServicesJson Include="google-services.json"/>
  </ItemGroup>

**Comment by devology-rob** [comment]
I found another solution here https://forums.xamarin.com/discussion/175159/i-didnt-find-googleservices-json-in-the-build-action? 

My issue was relying on another project NuGet dependency graph (works for compiling, but not for the build-action pop up)
