### ISSUE TITLE
RtbAdapter for Google Play Services ads

### ISSUE THREAD

**Issue by 07101994** [xamarin/GooglePlayServicesComponents#252]
### Describe your Issue:
Hi, I am not able to locate ["RtbAdapter"](https://firebase.google.cn/docs/reference/android/com/google/android/gms/ads/mediation/rtb/RtbAdapter.html) class in the latest Google Play Services Binding.

I am looking to use mediation adapters in my Xamarin Android app but it seems due to this class is not available I am not able to use those mediation adapters.

Could you please look into this?

**Comment by moljac** [comment]
@07101994 

That class is in the Ads.Lite. Can you update to latest version and report here please?

I think it should be in 71.1720.1

**Comment by moljac** [comment]
Due to lack of feedback - closing this one.
