### ISSUE TITLE
Xamarin.GooglePlayServices.Maps metadata required for Android 9 SDK

### ISSUE THREAD

**Issue by GuillaumeSE** [xamarin/GooglePlayServicesComponents#253]
### Xamarin.Android Version (eg: 6.0):
9.0

### Google Play Services Version (eg: 8.4.0):
Xamarin.GooglePlayServices.Maps 71.1600.0

### Describe your Issue:
This is a general note to be aware of.
The current version of Xamarin.GooglePlayServices.Maps 71.1600.0 reference the native aar 
com.google.android.gms:play-services-maps:16.0.0.
With this version it's mandatory to add a metadata in the AndroidManisfest.xml as described in the official doc : https://developers.google.com/android/guides/releases

```
  <uses-library
      android:name="org.apache.http.legacy"
      android:required="false" />
```
To avoid this, it will be necessary to update the aar target to at least 16.1.0. when possible

**Comment by moljac** [comment]
@GuillaumeSE 

Bumped to 16.1.0.
Tagging right now and waiting for CI.

I will inform you when its done and then kindly ask you if you can close the issue yourself.

**Comment by moljac** [comment]
Published 
https://www.nuget.org/packages/Xamarin.GooglePlayServices.Maps/71.1610.0

**Comment by GuillaumeSE** [comment]
@moljac 

Just tested and it's work properly without adding the metadata in the manifest.

Thanks!

**Comment by moljac** [comment]
Duplicate https://github.com/xamarin/GooglePlayServicesComponents/issues/243
