### ISSUE TITLE
The Xamarin.Firebase.Ads package for the latest release is missing from the NuGet repository

### ISSUE THREAD

**Issue by silviubogan** [xamarin/GooglePlayServicesComponents#254]
### Xamarin.Android Version (eg: 6.0):
Android 9.0 (Pie).

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 Pro, latest update at the time of this writing, 1903.

### Google Play Services Version (eg: 8.4.0):
49 in the Android SDK Manager.

### Describe your Issue:
An exception is thrown for an unknown reason with the latest version of the Xamarin.GooglePlayServices.Ads package in NuGet instead of Xamarin.Firebase.Ads.

### Steps to Reproduce (with link to sample solution if possible):
Step 1. Clone the repository: https://github.com/silviubogan/testing-xamarin-ads.
Step 2. Open it in VS2019.
Step 3. Deploy it to an Android phone connected through USB.
Step 4. After the deployment has finished and the background of the Android activity (white) is shown, as in the new Xamarin.Forms project template, but the Label is not, and an exception is thrown.

### Include any relevant Exception Stack traces, build logs, adb logs:
```
Java.Lang.RuntimeException: 'Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 

******************




******************

'
```

### Other information
Screenshot:

![2019-08-21_14-33-12](https://user-images.githubusercontent.com/198924/63428638-b3707500-c420-11e9-9067-51c86243a556.png)

I started to build the packages myself from the 71.20190819 tag and I hope they'll work.
Related issue: #250.
I think I should use Firebase packages, but I see that this bug appears also in this test project.

**Comment by moljac** [comment]
Package is missing?

How come it does run?

In that case - you would not be able to add package and build. 

This must be something else. I will check the sample

**Comment by silviubogan** [comment]
@moljac Thank you. There were actually two issues:

1. The exception thrown in [the sample linked above](https://github.com/silviubogan/testing-xamarin-ads).
2. The missing Firebase.Ads package (I thought it was necessary to use the Firebase package when I first saw that the sample above throws an error). *I saw [here](https://stackoverflow.com/a/37327832/258462) that this is not an issue anymore.*

**Comment by moljac** [comment]
@silvubogan

I'm sorry, butt I'm confused - Xamarin.Firebase.Ads was released month ago.

https://www.nuget.org/packages/Xamarin.Firebase.Ads/71.1601.0

If package would not be published - Add Package would fail and that would cause build to fail and yet you have runtime error.

About the error - I need to see.

**Comment by jvreeker** [comment]
I have the same error
Java.Lang.RuntimeException:** 'Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 

This has nothing to do with firebase.Ads. Because I don't use Firebase.
Only thing I did was updating to the latest version.

**Comment by JoseJohnen** [comment]
So, what exactly is the solution of this nowadays?
Do we need to downgrade our Xamarin.GooglePlayServices.Ads for the time being?

**Comment by imuller** [comment]
Update nuget for 71.2 ??

**Comment by tklempay** [comment]
This morning, I upgraded my Xamarin Forms app to the latest nuget packages, which included upgrading Xamarin.GooglePlayServices.Ads.Lite from v60.1142.1 -> 71.1720.1.  

I got the same runtime error referenced above:
_Java.Lang.RuntimeException: 'Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException:_ 

Updating AndroidManifest.xml with my Google Admob appId information solved the problem for me.  
`<application> . . . 
      <meta-data 
           android:name="com.google.android.gms.ads.APPLICATION_ID" 
           android:value="ca-app-pub-################~##########"/>
</application>`

See here for more:
https://stackoverflow.com/questions/52786963/unable-to-get-provider-com-google-android-gms-ads-mobileadsinitprovider-java-la

**Comment by moljac** [comment]
@tklempay 

Can you post AndroidManifest.xml before and after the change? The diff would be OK.

Did you have to merge some XML nodes into 1?

In the future try adding 

https://www.nuget.org/packages/Xamarin.Android.ManifestMerger/1.0.0-preview03

And please provide us feedback if that worked (here is OK)

**Comment by tklempay** [comment]
What I posted above is the diff from my AndroidManifest.xml.

Also, I did not have to merge any XML nodes

**Comment by geojorg** [comment]
![image](https://user-images.githubusercontent.com/54997758/67970125-7c64cf80-fbd8-11e9-9c8f-9a3dcaa47a1f.png)


New SDK requiere so.

**Comment by moljac** [comment]
@geojorg Thanks a lot for the feedback info.

@tklempay @imuller @JoseJohnen @jvreeker @silvubogan

Did you try fix provided by @geojorg?
Please report here if that works for you.

**Comment by moljac** [comment]
Closing this one
