### ISSUE TITLE
Android.Gms.Games error during compile time

### ISSUE THREAD

**Issue by gabry90** [xamarin/GooglePlayServicesComponents#256]
### Xamarin.Android Version (eg: 6.0):
Latest

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 64bit

### Google Play Services Version (eg: 8.4.0):
latest

### Describe your Issue:
exception during compile time		

### Steps to Reproduce (with link to sample solution if possible):
Compile a project with Games dependencies

### Include any relevant Exception Stack traces, build logs, adb logs:

error XA4212: Type `Android.Gms.Games.Quest.MilestoneBuffer` implements `Android.Runtime.IJavaObject` but does not inherit `Java.Lang.Object` or `Java.Lang.Throwable`. This is not supported.

**Comment by thomcat2** [comment]
The same here after installing VS 2019 and updating all NuGet packages.

**Comment by gabry90** [comment]
How long do you have to wait before the fix is ​​released publicly? I need to use the latest version

**Comment by moljac** [comment]
@gabry 

It was fixed 2 weeks ago, but there were some other runtime errors which needed additional dependency bindings (opencensus tracking libs for grpc).

I hope this might be published next week.

**Comment by moljac** [comment]
@gabry90 @thomcat2 

The issue should be fixed in version 71.20190927

Packages:

*   Xamarin.Firebase.Firestore 71.1705.1
*   Xamarin.GooglePlayServices.Games.71.1700.1

Please update your packages and provide us feedback here (or even close the issue if issue is fixed)
Thanks

**Comment by moljac** [comment]
Closing this one due to lack of responses
