### ISSUE TITLE
DeleteToken() vs DeleteInstanceId()

### ISSUE THREAD

**Issue by tallkid10** [xamarin/GooglePlayServicesComponents#26]
### Describe your Issue:

I'm not sure if this is an issue so much as understanding the different between the two methods in the title (DeleteToken() and DeleteInstanceId()).

In your FirebaseMessagingQuickstart Sample you have the following code to register with FCM:
`Task.Run(() =>
            {
                var instanceID = FirebaseInstanceId.Instance;
                instanceID.DeleteInstanceId();
                var iid1 = instanceID.Token;
                var iid2 = instanceID.GetToken(GetString(Resource.String.gcm_defaultSenderId), FirebaseMessaging.InstanceIdScope);
                Android.Util.Log.Debug(TAG, "Iid1: {0}, iid2: {1}", iid1, iid2);
            });`

However, I would like to keep Instance Id and use that as a unique identifier per app install/device.  I discovered there is a DeleteToken() method which I have replaced with DeleteInstanceId() and used as follows:
`Task.Run(() =>
            {
                var instanceID = FirebaseInstanceId.Instance;
                instanceID.DeleteToken(GetString(Resource.String.gcm_defaultSenderId), FirebaseMessaging.InstanceIdScope);
                //instanceID.DeleteInstanceId();
                var iid1 = instanceID.Token;
                var iid2 = instanceID.GetToken(GetString(Resource.String.gcm_defaultSenderId), FirebaseMessaging.InstanceIdScope);
                Android.Util.Log.Debug(TAG, "Iid1: {0}, iid2: {1}", iid1, iid2);
            });`

I have been able to receive messages from FirebaseConsole using both DeleteToken() and DeleteInstanceId(), however I am only able to send messages to target user segments by app/package name when I use DeleteInstanceId().  If I use DeleteToken(), then I will only receive messages sent to topics I'm subscribed to or single devices by FCM token.
### Steps to Reproduce (with link to sample solution if possible):

Using FirebaseMessagingQuickstart, modify the Task.run code as follows:
`Task.Run(() =>
            {
                var instanceID = FirebaseInstanceId.Instance;
                instanceID.DeleteToken(GetString(Resource.String.gcm_defaultSenderId), FirebaseMessaging.InstanceIdScope);
                //instanceID.DeleteInstanceId();
                var iid1 = instanceID.Token;
                var iid2 = instanceID.GetToken(GetString(Resource.String.gcm_defaultSenderId), FirebaseMessaging.InstanceIdScope);
                Android.Util.Log.Debug(TAG, "Iid1: {0}, iid2: {1}", iid1, iid2);
            });`

Comment out DeleteInstanceId(), run the app, then send messages to the app (you wont receive a message).  However, send a message to the device using what is printed for iid2 in the log and you will receive a message.

**Comment by Redth** [comment]
You've probably figured this out by now, but adding some reference for the archives...

Just looking at google's docs:
https://developers.google.com/instance-id/guides/android-implementation#manage_tokens_and_product_names

It seems like the token is GCM specific, whereas the instance id can be used as sort of a unique identifier for other purposes in the app.  The GCM token is associated with the instance id.
