### ISSUE TITLE
71.1600.0 Xamarin.GooglePlayServices.Location Missing functions

### ISSUE THREAD

**Issue by tony98789** [xamarin/GooglePlayServicesComponents#262]
### Xamarin.Android Version (eg: 6.0):

9.0

### Operating System & Version (eg: Mac OSX 10.11):

Windows 10
Visual Studio 2019

### Google Play Services Version (eg: 8.4.0):

71.1600.0

### Describe your Issue:

When receiving a location update the three functions below all throw breaking exceptions.

1: BearingAccuracyDegrees
2: SpeedAccuracyMetersPerSecond
3: VerticalAccuracyMeters

Edit:

The functions below are also throwing the same NoSuchMethodError.
1: HasBearingAccuracy
2: HasSpeedAccuracy
3: HasVerticalAccuracy

### Steps to Reproduce (with link to sample solution if possible):

Setup an app that gets location updates and attempt to use one of the three properties above on the location result. The binding to the android function does not exist.

Each method will throw the error below but with its relevant android function.

**Java.Lang.NoSuchMethodError:** 'no non-static method "Landroid/location/Location;.getVerticalAccuracyMeters()

**Comment by moljac** [comment]
Can you turn off linking?
What are your linking project settings?

All classes are from `Android.Locations.Location`

https://docs.microsoft.com/en-us/dotnet/api/android.locations.location?view=xamarin-android-sdk-9

I need a minimal repro sampe to see what this issue has to do with Google Play Services.

https://docs.microsoft.com/en-us/dotnet/api/android.locations.location.bearingaccuracydegrees?view=xamarin-android-sdk-9

https://docs.microsoft.com/en-us/dotnet/api/android.locations.location.speedaccuracymeterspersecond?view=xamarin-android-sdk-9

https://docs.microsoft.com/en-us/dotnet/api/android.locations.location.hasbearingaccuracy?view=xamarin-android-sdk-9#Android_Locations_Location_HasBearingAccuracy

https://docs.microsoft.com/en-us/dotnet/api/android.locations.location.hasspeedaccuracy?view=xamarin-android-sdk-9#Android_Locations_Location_HasSpeedAccuracy

https://docs.microsoft.com/en-us/dotnet/api/android.locations.location.hasverticalaccuracy?view=xamarin-android-sdk-9#Android_Locations_Location_HasVerticalAccuracy

https://docs.microsoft.com/en-us/dotnet/api/android.locations.location.verticalaccuracymeters?view=xamarin-android-sdk-9

**Comment by tony98789** [comment]
Hi @moljac, So the projects linking settings are Sdk Assemblies Only. I will put together a repro and attempt to replicate the issue. Will turn of linking and see what the result is.

**Comment by moljac** [comment]
@tony98789 Try turning off linking (no SDK Assemblies only). Please

**Comment by tony98789** [comment]
Hi, sorry its took so long to get back on this. Yer it must of been a linking issue. I used to have my location tracking code in a separate project to my main application, i have since moved that code to the main app and it works correctly.
