### ISSUE TITLE
Failed to retrieve firebase instance ID

### ISSUE THREAD

**Issue by PNDTCS** [xamarin/GooglePlayServicesComponents#277]
### Operating System & Version (eg: Mac OSX 10.11):
MS Windows 10

### Describe your Issue:
I have installed all latest nuget packages for firebase messaging.
Xamarin.Android.Messanging  v71.1740.0
and other packages are also up to date.

But still I am getting "Failed to retrieve firebase instance id".

I have already wasted 3 days to resolve this issue.

**Comment by moljac** [comment]
@PNDTCS 

> and other packages are also up to date.

So there is more than Firebase messaging?

Search issues for: "Failed to retrieve firebase instance id"

You will see that there are other issues (closed). If you have other packages rather than only Firebase Messaging -  add Xamarin.Android.ManifestMerger package to your project (app) and please report here if that helps.

**Comment by a-ta-ta** [comment]
@moljac 
Would you be so kind to give me a hint where Xamarin.Android.ManifestMerger could be found?
I've searched through NuGet Manager and found nothing similiar.

**Comment by moljac** [comment]
@a-ta-ta 
Sure.

https://www.nuget.org/packages/Xamarin.Android.ManifestMerger/

Make sure that you turn on "preview" packages when adding nuget.

**Comment by a-ta-ta** [comment]
@moljac 
Thank you so much! I haven't noticed that small checkbox! Woohoo!

**Comment by moljac** [comment]
@a-ta-ta You re welcome. I'm glad it worked.

Please report if your issue was solved. We need feedback.

**Comment by a-ta-ta** [comment]
The issue was solved, everything is working just fine!

**Comment by PNDTCS** [comment]
The issue is resolved. Thanks

**Comment by RumbosN** [comment]
I solved this removing Xamarin.GooglePlayServices.Gcm, Xamarin.Firebase.Core and Xamarin.Firebase.Measurement.Connector.impl packages like: https://github.com/xamarin/GooglePlayServicesComponents/issues/216#issuecomment-559210025
