### ISSUE TITLE
DynamicLinks: FirebaseDynamicLinks.Instance is null for 71.1615.0

### ISSUE THREAD

**Issue by thisisthekap** [xamarin/GooglePlayServicesComponents#278]
### Xamarin.Android Version (eg: 6.0):

10.0.6.2

### Operating System & Version (eg: Mac OSX 10.11):

mscOS 10.14.6

### Google Play Services Version (eg: 8.4.0):

71.1615.0

### Describe your Issue:

Using Xamarin.Firebase.Dynamic.Links in version 60.1142.1, everything works just fine. After upgrading to 71.1615.0, `FirebaseDynamicLinks.Instance` returns `null`.

This issue seems to be similar to the issue mentioned by another user on Stackoverflow: https://stackoverflow.com/questions/57179021/firebasedynamiclinks-instance-is-null-after-update-from-60-1142-1-to-71-1615-0

### Steps to Reproduce (with link to sample solution if possible):

Use 60.1142.1 --> working --> upgrade to 71.1615.0 --> `FirebaseDynamicLinks.Instance` is `null`

**Comment by moljac** [comment]
@thisisthekap 
1. Do you have other Google.Play.Services and/or Firebase packages?
2. Did you add Xamarin.Adroid.ManifestMerger package?

**Comment by thisisthekap** [comment]
@moljac To answer your questions:

**Do you have other Google.Play.Services and/or Firebase packages?**
* Xamarin.Firebase.Ads.Lite version 71.1601.0
* Xamarin.Firebase.Analytics version 71.1630.0
* Xamarin.Firebase.Dynamic.Links version 71.1615.0
* Microsoft.AppCenter.Push version 2.6.1
  * Depends on Xamarin.Firebase.Messaging version >= 71.1740.0
* Xamarin.GooglePlayServices.Ads.Lite version 71.1720.1
  * Needed because of https://github.com/xamarin/GooglePlayServicesComponents/issues/203

**Did you add Xamarin.Adroid.ManifestMerger package?**
No.

**Comment by moljac** [comment]
@thisisthekap 

> Did you add Xamarin.Adroid.ManifestMerger package?
> No.

Can you make that YES please? 

Seems like known manifest merging issue.

**Comment by AmonDoni** [comment]
Xamarin.Android.ManifestMerger package helped me. But it is on preview state...

**Comment by moljac** [comment]
@AmonDoni 
Thanks for the feedback.

@thisisthekap 
Did you have chance to try it with `Xamarin.Android.ManifestMerger`?

**Comment by aiuex79** [comment]
Having this exact issue.   Any update on this?

**Comment by pablogupi** [comment]
I have same issue. In my case use latest version of https://github.com/CrossGeeks/FirebasePushNotificationPlugin 3.1.6 and latest version DynamicLinks. Before install DynamicLinks app works perfectly and receive notifications. After install Xamarin.Firebase.Dynamic.Links 71.1615 plugin, when start app crashes with this error:

`Attempt to invoke virtual method 'void com.google.firebase.iid.FirebaseInstanceId.zzb(boolean)' on a null object reference`

Only use these plugins with Firebase dependencies. I think GooglePlayServices versions  are compatible.

Any ideas to fix the error?

**Comment by gisongeorge** [comment]
Any update on this? I am also facing the same issue.

**Comment by arthigo** [comment]
Maybe you facing com.google.firebase.components.ComponentDiscoveryService being defined multiple times in the AndroidManifest.xml as describe in https://github.com/xamarin/GooglePlayServicesComponents/issues/216. I had the same problem when using Xamarin.Firebase.Functions and Xamarin.Firebase.Auth together. I used MatFillion`s answer (https://github.com/xamarin/GooglePlayServicesComponents/issues/216#issuecomment-517740275) to fix it.

**Comment by stanleywailers** [comment]
Hello I Had the same problem
I had DynamicLinks implementation working and when i implemented firebase.Messagin stop working, then i installed Did you add Xamarin.Adroid.ManifestMerger package? like @moljac  said and now its woking, very thanks

**Comment by yasarutkuu** [comment]
I have same issue. Could you give reference for Xamarin.Adroid.ManifestMerger package?

**Comment by moljac** [comment]
@thisisthekap @AmonDoni @aiuex79 @pablogupi @gisongeorge @arthigo @stanleywailers @yasarutkuu 

No nuget package needed. We have moved this feature into the core of the Android build system.

https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.2#improved-android-manifest-merging

All you need is to add:

```
<PropertyGroup>
  <AndroidManifestMerger>manifestmerger.jar</AndroidManifestMerger>
</PropertyGroup>
```

to your project[s] that reference GPS-FB packages.

Please prvoide feedback on this, or even better @thisisthekap please close the issue yourself.

Thanks
