### ISSUE TITLE
Please release new version of maps

### ISSUE THREAD

**Issue by kjeremy** [xamarin/GooglePlayServicesComponents#28]
Maps now contains some important fixes including the ability to associate a tag with a marker.  This has been out for a long time.  Please release a new version.

**Comment by kjeremy** [comment]
See: https://developers.google.com/maps/documentation/android-api/releases#august_1_2016

**Comment by kjeremy** [comment]
Any ETA on this?

**Comment by Redth** [comment]
32.961.0 was released in November, and there are prerelease versions of 42.1001.0 available. :)
