### ISSUE TITLE
[Xamarin.Firebase.Auth] Support for Sign in with Apple

### ISSUE THREAD

**Issue by stepheaw** [xamarin/GooglePlayServicesComponents#291]
Support for Sign in with Apple was added to the Firebase.iOS sdk on November 19th of this year. Is it possible we can get an update for this pushed to Nuget?

**Comment by moljac** [comment]
@stepheaw 

New Firebase.Auth has AndroidX dependencies. I have already bound version 18.1.0 (I think)

Here:

https://github.com/xamarin/GooglePlayServicesComponents/blob/master_based_androidx/config.json#L440-L444

Yes it was 18.1.0

I will bump version to 19.2.0 right away, but in  order to publish nugets we need to publish AndroidX stable libraries, which are being extensively tested these days and close to release.

You can track progress here:

https://github.com/xamarin/GooglePlayServicesComponents/blob/master_based_androidx

**Comment by stepheaw** [comment]
It seems like in 6.2.1.1 that this is supported
