### ISSUE TITLE
Xamarin.GooglePlayServices.Auth.Api.Phone and Xamarin.GooglePlayServices.Auth bindings are outdated

### ISSUE THREAD

**Issue by gianlucaparadise** [xamarin/GooglePlayServicesComponents#294]
In order to use the latest features of the SMS Verification APIs explained [here](https://developers.google.com/identity/sms-retriever/user-consent/request), it is needed to update the bindings of the following packages:

* `play-services-auth-api-phone`
    * [Binding version](https://github.com/xamarin/GooglePlayServicesComponents/blob/d54da4793a6b3e2319a43fc11594f36ce9390270/config.json#L89): 16.0.0
    * [Latest version](https://mvnrepository.com/artifact/com.google.android.gms/play-services-auth-api-phone): 17.3.0

* `play-services-auth`
    * [Binding version](https://github.com/xamarin/GooglePlayServicesComponents/blob/d54da4793a6b3e2319a43fc11594f36ce9390270/config.json#L82): 16.0.0
    * [Latest version](https://mvnrepository.com/artifact/com.google.android.gms/play-services-auth): 17.0.0

Is it possible to update the bindings and publish them?

**Comment by moljac** [comment]
@gianlucaparadise 

Dependencies of both packages are AndroidX packages.

GPS-FB with AndroidX can be found here (separate branch):

https://github.com/xamarin/GooglePlayServicesComponents/tree/master_based_androidx

And 1st we need to publish stable AndroidX packages. 

Hope this provides enough info,

Closing this one.

**Comment by gianlucaparadise** [comment]
Since AndroidX is now stable, when is the update of the bindings planned?
