### ISSUE TITLE
[Action Required] Switch to the Play Referrer API by March 1, 2020

### ISSUE THREAD

**Issue by ryl** [xamarin/GooglePlayServicesComponents#295]
I'm using Firebase in one of my Xamarin projects and recently got the email that follows:

> [Action Required] Switch to the Play Referrer API by March 1, 2020
> 
> Hello Google Play Developer,
> 
> We recently announced that we’ll be deprecating the install_referrer intent broadcast mechanism. Because one or more of your apps uses this intent to track referrals, we wanted to ensure you make the switch before March 1, 2020. After this date, new versions of the Play Store app will no longer broadcast the install_referrer intent after app installs.
> 
> Action required
> 
> Migrate to the Play Install Referrer API to track your app installs for the following apps and/or games.

The email includes a link to this article: https://developer.android.com/google/play/installreferrer/library.html

I do not directly use the referrer API in my own code, but it seems that the Firebase libraries most likely do. Do Xamarin's bindings include this new API (com.android.installreferrer:installreferrer:1.1) yet? I'm having a hard time determining for certain whether or not updating to the latest Xamarin Firebase nuget packages will help or not.

**Comment by moljac** [comment]
@ryl 

I haven't hit requirement (dependency) for InstallReferrer yet, though I did not bind the latest versions of GPS-FB.

According to this (not saying it is correct):

https://mvnrepository.com/artifact/com.android.installreferrer/installreferrer/usages?p=1

Nothing in GPS-FB or AndroidX isu using InstallReferer. 

Can you investigate what might be using it, please?

**Comment by ryl** [comment]
@moljac 

It looks like I probably filed this Issue to the wrong project. It looks like Facebook might have been where it needed to go.

https://github.com/facebook/facebook-android-sdk/commit/4c0f57d60b226563b8607b3b39a9450359f327bc

In that commit it looks like Facebook updated their SDK to use the new referrer API, and that the Xamarin wrapper hasn't caught up to the native Facebook SDK yet.

I filed a new issue there https://github.com/xamarin/FacebookComponents/issues/167

**Comment by moljac** [comment]
Closing this one.
