### ISSUE TITLE
No properties to serialize found on class

### ISSUE THREAD

**Issue by joaootavio93** [xamarin/GooglePlayServicesComponents#296]
### Xamarin.Android Version (eg: 6.0):
10.1.1.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version (eg: 8.4.0):
Xamarin.GooglePlayServices.Auth 71.1600.0
Xamarin.GooglePlayServices.Base 71.1610.0
Xamarin.GooglePlayServices.Basement 71.1620.0
Xamarin.GooglePlayServices.Lid 71.1600.0

### Describe your Issue:
When I try to send an Java.Lang.Object in SetValueAsync(obj) method the exception below is thrown. (with strings, for example, it works).

### Include any relevant Exception Stack traces, build logs, adb logs:
Stack trace:
{Firebase.Database.DatabaseException: No properties to serialize found on class crc6486d3b9925a82bdaf.teste
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <e7e2d009b69d4e5f9a00e6ee600b8a8e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <e7e2d009b69d4e5f9a00e6ee600b8a8e>:0 
  at Firebase.Database.DatabaseReference.SetValue (Java.Lang.Object p0) [0x00031] in <31ad3edbc3354343ae96c8ee2a44f93a>:0 
  at Firebase.Database.DatabaseReference.SetValueAsync (Java.Lang.Object obj) [0x00000] in <31ad3edbc3354343ae96c8ee2a44f93a>:0 
  at Azul.AppIntranet.Droid.DependencyServices.FirebaseDatabaseService.SetMessage (System.Int32 attendanceId, Azul.AppIntranet.Nucleo.Entidade.Mensagem message) [0x00047] in C:\Projects\MigracaoBruno\Comunicacao.AppComunicacao\src\Mobile\MinhaAzulApp.Android\DependencyServices\FirebaseDatabaseService.cs:121 
  --- End of managed Firebase.Database.DatabaseException stack trace ---
com.google.firebase.database.DatabaseException: No properties to serialize found on class crc6486d3b9925a82bdaf.teste
	at com.google.android.gms.internal.firebase_database.zzku.<init>(Unknown Source:784)
	at com.google.android.gms.internal.firebase_database.zzkt.zza(Unknown Source:12)
	at com.google.android.gms.internal.firebase_database.zzkt.zzi(Unknown Source:253)
	at com.google.android.gms.internal.firebase_database.zzkt.zzh(Unknown Source:0)
	at com.google.firebase.database.DatabaseReference.zza(Unknown Source:10)
	at com.google.firebase.database.DatabaseReference.setValue(Unknown Source:7)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:215)
	at android.app.ActivityThread.main(ActivityThread.java:6939)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
}

### Steps to Reproduce (with link to sample solution if possible):

Dependency service method:
public async Task<string> SetMessage(int attendanceId, Mensagem message)
 {
            try
            {
                var key = _databaseReference.Push().Key;
                SetDatabaseReference("atendimentos");
                await _databaseReference
                    .Child(attendanceId.ToString())
                    .Child(key)
                    .SetValueAsync(new TestObject());
                return key;
            }
            catch (Exception ex)
            {
                AppIntranet.Utils.LogErro(ex);
            }
            return "";
 }

Java object:

 public class TestObject : Java.Lang.Object
    {
        public String Name { get; set; }

        public TestObject()
        {
            Name = "Test";
        }
    }

I applied the solutions below, but nothing happens (in C#):
 - https://stackoverflow.com/questions/37743661/firebase-no-properties-to-serialize-found-on-class
- https://stackoverflow.com/questions/46254266/firebase-no-properties-to-serialize-found-on-class/46263371 (no ProGuard is used)

**Comment by maikoly1** [comment]
Any update on this?

**Comment by maikoly1** [comment]
> ### Xamarin.Android Version (eg: 6.0):
> 10.1.1.0
> 
> ### Operating System & Version (eg: Mac OSX 10.11):
> Windows 10
> 
> ### Google Play Services Version (eg: 8.4.0):
> Xamarin.GooglePlayServices.Auth 71.1600.0
> Xamarin.GooglePlayServices.Base 71.1610.0
> Xamarin.GooglePlayServices.Basement 71.1620.0
> Xamarin.GooglePlayServices.Lid 71.1600.0
> 
> ### Describe your Issue:
> When I try to send an Java.Lang.Object in SetValueAsync(obj) method the exception below is thrown. (with strings, for example, it works).
> 
> ### Include any relevant Exception Stack traces, build logs, adb logs:
> Stack trace:
> {Firebase.Database.DatabaseException: No properties to serialize found on class crc6486d3b9925a82bdaf.teste
> at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in :0
> at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in :0
> at Firebase.Database.DatabaseReference.SetValue (Java.Lang.Object p0) [0x00031] in <31ad3edbc3354343ae96c8ee2a44f93a>:0
> at Firebase.Database.DatabaseReference.SetValueAsync (Java.Lang.Object obj) [0x00000] in <31ad3edbc3354343ae96c8ee2a44f93a>:0
> at Azul.AppIntranet.Droid.DependencyServices.FirebaseDatabaseService.SetMessage (System.Int32 attendanceId, Azul.AppIntranet.Nucleo.Entidade.Mensagem message) [0x00047] in C:\Projects\MigracaoBruno\Comunicacao.AppComunicacao\src\Mobile\MinhaAzulApp.Android\DependencyServices\FirebaseDatabaseService.cs:121
> --- End of managed Firebase.Database.DatabaseException stack trace ---
> com.google.firebase.database.DatabaseException: No properties to serialize found on class crc6486d3b9925a82bdaf.teste
> at com.google.android.gms.internal.firebase_database.zzku.(Unknown Source:784)
> at com.google.android.gms.internal.firebase_database.zzkt.zza(Unknown Source:12)
> at com.google.android.gms.internal.firebase_database.zzkt.zzi(Unknown Source:253)
> at com.google.android.gms.internal.firebase_database.zzkt.zzh(Unknown Source:0)
> at com.google.firebase.database.DatabaseReference.zza(Unknown Source:10)
> at com.google.firebase.database.DatabaseReference.setValue(Unknown Source:7)
> at mono.java.lang.RunnableImplementor.n_run(Native Method)
> at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
> at android.os.Handler.handleCallback(Handler.java:873)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:215)
> at android.app.ActivityThread.main(ActivityThread.java:6939)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
> }
> 
> ### Steps to Reproduce (with link to sample solution if possible):
> Dependency service method:
> public async Task SetMessage(int attendanceId, Mensagem message)
> {
> try
> {
> var key = _databaseReference.Push().Key;
> SetDatabaseReference("atendimentos");
> await _databaseReference
> .Child(attendanceId.ToString())
> .Child(key)
> .SetValueAsync(new TestObject());
> return key;
> }
> catch (Exception ex)
> {
> AppIntranet.Utils.LogErro(ex);
> }
> return "";
> }
> 
> Java object:
> 
> public class TestObject : Java.Lang.Object
> {
> public String Name { get; set; }
> 
> ```
>     public TestObject()
>     {
>         Name = "Test";
>     }
> }
> ```
> 
> I applied the solutions below, but nothing happens (in C#):
> 
> * https://stackoverflow.com/questions/37743661/firebase-no-properties-to-serialize-found-on-class
> * https://stackoverflow.com/questions/46254266/firebase-no-properties-to-serialize-found-on-class/46263371 (no ProGuard is used)


Any Luck Maybe??

**Comment by maikoly1** [comment]
RESOLVED!! I managed to face out the issue like this
Create a Helper Method with a generic Class(accepting .NET object/classes)
Returning a HashSet object(Java.Lang.Object) Pass this to the Setvalue( [hashsertobject]as a parameter)
 public static HashMap HashModel<T>(T t)
        {
            var properties = t.GetType().GetProperties();
            HashMap hashset = new HashMap();
            System.Collections.IDictionary hDict = new Dictionary<string, object>();
            foreach (var item in properties)
            {
                hDict.Add(item.Name, item.GetValue(t, null));
            }
            hashset.PutAll(hDict);
            return hashset;
        }

**Comment by moljac** [comment]
@maikoly1 

Is it possible to get minimal repro sample to test? It would be greatly appreciated and it would speed up the process of triaging and fixing the issue.

Thanks
