### ISSUE TITLE
Uses-Library org.apache.http.legacy

### ISSUE THREAD

**Issue by Redth** [xamarin/GooglePlayServicesComponents#299]
More recently, the Android team added support for checking for `uses-library` in android manifests and adding them to the `AndroidExternalJavaLibrary` to be included into r8/proguard invocations: https://github.com/xamarin/xamarin-android/commit/b08240ee50e941cb326688cc0dcf5969ebfe5473

This probably means the old method of dealing specifically with the `org.apache.http.legacy` library in google play services compilation should be removed in favor of letting the android build tasks deal with it.

I think these lines can basically just be removed: https://github.com/xamarin/GooglePlayServicesComponents/blob/master/source/com.google.android.gms/play-services-basement/merge.targets#L87-L104

And you could add:
```csharp
[assembly: UsesLibrary("org.apache.http.legacy", Required=false)]
```

To the additions.cs for basement.  This will cause the appropriate uses-library to be included in the app android manifest and should enable r8/proguard to find it when invoked.

**Comment by moljac** [comment]
Done 

https://github.com/xamarin/GooglePlayServicesComponents/commit/cb46cf32b899c3907c31e0296ae95f7518970773

https://github.com/xamarin/GooglePlayServicesComponents/commit/a417cc9ef6375fc401da77ca774ba74eba32ce8f

Closing this one.
