### ISSUE TITLE
Provide bindings for Android Map Utils

### ISSUE THREAD

**Issue by kjeremy** [xamarin/GooglePlayServicesComponents#30]
https://github.com/googlemaps/android-maps-utils

**Comment by Redth** [comment]
This will likely go in the https://github.com/xamarin/XamarinComponents repository if and when it happens.  If anyone's interested, feel free to make a PR there :)

**Comment by alexsorokoletov** [comment]
I'm interested since 2016 :) Here's a repo   https://github.com/alexsorokoletov/Xamarin.Android.Maps.Utils

**Comment by Redth** [comment]
@alexsorokoletov this looks great!  I'm going to close this issue as I don't think there's any need for us to duplicate your already terrific efforts.  Thanks for this!
