### ISSUE TITLE
Update firebase-ml-vision version

### ISSUE THREAD

**Issue by mjbedford2017** [xamarin/GooglePlayServicesComponents#300]
### Xamarin.Android Version (eg: 6.0):
8.0

### Operating System & Version (eg: Mac OSX 10.11):
N/A

### Google Play Services Version (eg: 8.4.0):
17

### Describe your Issue:
I would like to see if the firebase-ml-vision version can be updated. It seems the version currently being used is 17. However, on the Google Firebase page, there is a highlighted note that states version 24.0.0 has significant improvements to accuracy and latency. See the note here: [Vision version](https://firebase.google.com/docs/ml-kit/android/read-barcodes) 

While I am not having a major issue per se, I would like to take advantage of this significant bump in speed and performance.

**Comment by moljac** [comment]
@mjbedford2017 

According to  https://maven.google.com/web/index.html
it is 24.0.1 and I already bumped it yesterday, but did not push it yet. I must finish bindings for some new artifacts and new dependencies which do not belong to GPS or FB (Android DataTransport).

**Comment by mjbedford2017** [comment]
@moljac Excellent! Thank you for the update and prompt changes! I look forward to testing this in my app to see if it actually does bring some improvement to speed and performance. I will just keep checking back to see when it is pushed unless you have an ETA. Thanks!!!

**Comment by mjbedford2017** [comment]
@moljac Has this been done yet? Just wondering if it has been bumped to the latest version. Thanks!

**Comment by moljac** [comment]
24.0.0 is bound, but I think there was 24.0.1 which I did not bind yet.

https://github.com/xamarin/GooglePlayServicesComponents/blob/master_based_androidx/config.json#L621

Closing this one.

**Comment by mjbedford2017** [comment]
@moljac Thank you for the update, I am good with the close of this since it is done. I don't mind that it is not 24.0.1 because it seems that Google noted the main performance increase in 24.0.0. 

Quick question, I got this package via NuGet. Is it safe to say that if I just update my NuGet reference, it will pull this in and have the 24.0.0 version now?

**Comment by moljac** [comment]
No nugets are not published yet.

I'm (and the rest of the team is) fighting few issues on AndroidX front and some build issues on DevOps with GooglePlayServices, so you'll need to build it yourself and use local nugets

```
git clone --branch=master_based_androidx \
      https://github.com/xamarin/GooglePlayServicesComponents.git
cd AndroidX/
dotnet cake --target=ci
```
That's "all" on all platforms. 8-P

I hope I will manage to puiblish previews soon (together with 24.0.1)

**Comment by sukanzubair** [comment]
I executed the instructions above  i.e cloned repo and executed dotnet cake --target=ci

After installing the nuget package Xamarin.GooglePlayServices.Vision.119.0.0-preview01.nupkg
I get the following errors when buildinga new Xam forms app (see attached file for output log)
Example
 javac.exe error JAVAC0000:  error: package com.google.android.gms.security.ProviderInstaller does not exist
javac.exe error JAVAC0000: 		com.google.android.gms.security.ProviderInstaller.ProviderInstallListener

javac.exe error JAVAC0000:  error: package com.google.android.gms.tasks does not exist
javac.exe error JAVAC0000: 		com.google.android.gms.tasks.OnFailureListener

[buildOutputLog.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/4509763/buildOutputLog.txt)

I have deleted bin/obj folders and clean and rebuilt solution with no success.

Please assist.
