### ISSUE TITLE
Xamarin Forms' Analytics and Crashalytics

### ISSUE THREAD

**Issue by jrahma** [xamarin/GooglePlayServicesComponents#301]
Hi,

I hope you will soon have a Xamarin Forms' package for Analytics and Crashalytics instead of platform specifics.

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by moljac** [comment]
@jrahma 

You could try this one:
https://github.com/f-miyu/Plugin.FirebaseCrashlytics

closing this.
