### ISSUE TITLE
FirebaseInstanceId.Instance is returning null

### ISSUE THREAD

**Issue by PNDTCS** [xamarin/GooglePlayServicesComponents#302]
### Describe your Issue: FirebaseInstanceId.Instance is always coming null in my project. I almost wasted 2 days in searching solution for it but no luck.

I have installed below Nuget packages,

package id="Xamarin.Firebase.Common" version="71.1610.0" targetFramework="monoandroid90" ,

 package id="Xamarin.Firebase.Core" version="71.1601.0" targetFramework="monoandroid90" 

  package id="Xamarin.Firebase.Iid" version="71.1710.0" targetFramework="monoandroid90" 

 package id="Xamarin.Firebase.Iid.Interop" version="71.1601.0" targetFramework="monoandroid90" 

Below code I am using to retrieve FCM token,

FirebaseInstanceId instance = FirebaseInstanceId.Instance;
Android.Gms.Tasks.Task instanceId = instance.GetInstanceId();
instanceId.AddOnSuccessListener(this, this);

**Comment by moljac** [comment]
@PNDTCS 
Please add Xamarin.Android.ManifestMerger nuget and report results here.

Thanks

**Comment by PNDTCS** [comment]
@moljac  sure will try this and update you. Thank you.

**Comment by moljac** [comment]
@PNDTCS No! THank you!

**Comment by PNDTCS** [comment]
@moljac Working fine now after adding manifest merger. Thanks
