### ISSUE TITLE
Can't compile my application using Ads.Lite 71.1720.1

### ISSUE THREAD

**Issue by mariohik** [xamarin/GooglePlayServicesComponents#306]
### Describe your Issue:
Can't compile my application using Ads.Lite 71.1720.1

### Include any relevant Exception Stack traces, build logs, adb logs:
`java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAdsInitProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/x2apps.checkplaca.android-sENTqvUCS5WkCqdGTEaL8Q==/base.apk", zip file "/data/app/x2apps.checkplaca.android-sENTqvUCS5WkCqdGTEaL8Q==/split_config.arm64_v8a.apk", zip file "/data/app/x2apps.checkplaca.android-sENTqvUCS5WkCqdGTEaL8Q==/split_config.pt.apk", zip file "/data/app/x2apps.checkplaca.android-sENTqvUCS5WkCqdGTEaL8Q==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/x2apps.checkplaca.android-sENTqvUCS5WkCqdGTEaL8Q==/lib/arm64, /data/app/x2apps.checkplaca.android-sENTqvUCS5WkCqdGTEaL8Q==/base.apk!/lib/arm64-v8a, /data/app/x2apps.checkplaca.android-sENTqvUCS5WkCqdGTEaL8Q==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/x2apps.checkplaca.android-sENTqvUCS5WkCqdG`

**Comment by moljac** [comment]
@mariohik 

Pleas try adding this to your `AndroidManifest.xml`:

```
<uses-library
      android:name="org.apache.http.legacy"
      android:required="false" />
```
or 

```
[assembly: UsesLibrary("org.apache.http.legacy", Required=false)]
```

Please provide short feedback if that helped.

Newer versions should have this fixed.

Related:

https://github.com/xamarin/GooglePlayServicesComponents/issues/299

https://github.com/xamarin/xamarin-android/issues/2705
