### ISSUE TITLE
Firebase performance crash at startup

### ISSUE THREAD

**Issue by EmmanueleVilla** [xamarin/GooglePlayServicesComponents#310]
### Xamarin.Android Version (eg: 6.0):
Versione: 10.1.3.7 (Visual Studio Community)

### Operating System & Version (eg: Mac OSX 10.11):
macOS Mojave 10.14.6

### Google Play Services Version (eg: 8.4.0):
71.16.10 / .20 / .30 depending on the library, everyone is at their latest version

### Describe your Issue:
I have a following crash right at the startup

### Steps to Reproduce (with link to sample solution if possible):
I tried to create a new project but I had a lot of packages conflicts between Firebase and Xamarin Essentials, even tho in my "real" project I have both installed. I would have to add each library manually but I think then the test will be flawed

### Include any relevant Exception Stack traces, build logs, adb logs:
`[FA] Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfb.zzgj(Unknown Source:29)`

### Notes
Everything was working fine using the 60.1142.1 version.
I had to add also Firebase Crashlitics that requires Xamarin.Build > 0.8, so I had to update everything.
In both cases (60.x working and 70.x not working) the android support libraries are 28.0.3.
I also tried to migrate to AndroidX with no luck and the same error

**Comment by gabrieldwight** [comment]
@EmmanueleVilla Have you tried to install the Xamarin.Android.ManifestMerger nuget package which may fix the firebase performance startup issue. Or if you have the latest version of visual studio which will contain Xamarin Android 10.2 you can add the following line in your csproj file:
`<PropertyGroup>
  <AndroidManifestMerger>manifestmerger.jar</AndroidManifestMerger>
</PropertyGroup>`

After adding the above line in your project file then you can safely remove Xamarin.Android.ManifestMerger nuget package

**Comment by EmmanueleVilla** [comment]
@gabrieldwight thanks for the tip, I'll try but meanwhile I gave up with this component and simply used the native GooglePlayServices in a native library, and then I bound it. Worked like a charm

**Comment by moljac** [comment]
@EmmanueleVilla Do you have repro sample? I'd like to test with ManfiestMerger package

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.

**Comment by EmmanueleVilla** [comment]
Hey, sorry for the late reply. I just tried yesterday adding the ManifestMerger component and the error went away! Maybe you should consider to add that component to the dependencies?
Also, I've added again Firebase Crash and Firebase Perf and the Xamarin.Build version stayed at 0.4, did you change the dependency version?
