### ISSUE TITLE
Typo in readme file for Google Play Services Version?

### ISSUE THREAD

**Issue by TomSoderling** [xamarin/GooglePlayServicesComponents#311]
I noticed on the readme page that the Google Play Services Version listed for version 71 of the NuGet package is 71. That should be 17, right?

<img width="752" alt="Screen Shot 2020-03-03 at 2 03 11 PM" src="https://user-images.githubusercontent.com/18268845/75814807-01631f80-5d58-11ea-891d-16bfbc9e8d1a.png">

**Comment by moljac** [comment]
No. If you check google's versions for artifacts you will see that some are version 15.x.y, some 16.x.y and some 17.x.y. For example packages with AndroidX dependencies are 100.x.y.z.

Clsoing this one.
