### ISSUE TITLE
Missing Method in Vision API -Barcode Class

### ISSUE THREAD

**Issue by sukanzubair** [xamarin/GooglePlayServicesComponents#327]
### Describe your Issue:
The problem I am facing:
I need to scan barcodes which are in ISO 8859-1 (latin1) format. However, the rawValue property of the Barcode class has already been encoded using UTF-8 and contains some replacement characters (�). Consequently, I am unable to determine what the actual value of the data was.

Proposed Solution:
Add a rawBytes property to the Barcode class - populate this property using getRawBytes . Then, in cases that the barcode follows formats other than UTF-8, rawBytes can be used with the applicable format.

If there is a better solution to this problem I really would like some help.

**Comment by sukanzubair** [comment]
I noticed that this is only available in the maven package Play Services Vision » 18.0.0 and upwards and Xamarin.GooglePlayServices.Vision is still on version 17.2.0.

Any idea when there will be an update on this?

**Comment by moljac** [comment]
Thanks for the feedback. 

Those versions are most likely with AndroidX dependencies and I'm working on the new sets of previews and bindings.

Tagged version:

https://github.com/xamarin/GooglePlayServicesComponents/tree/100.20200429-androidx-previews01

Waiting for CI build (cross fingers) and publishing will happen. 

Check `config.json` if your version is in there. If not ping me here, so I can prepare next waves of nuget packages. 

There is another one already waiting.

**Comment by moljac** [comment]
@sukanzubair 

Version 19.0.0 is out (preview)

https://www.nuget.org/packages/Xamarin.GooglePlayServices.Vision/119.0.0-preview01


preview02 is prepared and should be out soon.

Please, close this issue yourself.
