### ISSUE TITLE
Where is the code for FCM device registration?

### ISSUE THREAD

**Issue by wutever0** [xamarin/GooglePlayServicesComponents#328]
Hi.. 
Sorry if I'm misunderstanding something here but I'm using the Xamarin.Firebase.Messaging and Xamarin.GooglePlayServices.Base NuGet packages for Push Notifications and I can't find the source code in those packages where the SDK registers the mobile device with the Firebase Cloud Messaging service to get the device token.

Any pointers as to where I can find that piece of could would be very helpful 🙏🏼.

**Comment by tmijieux** [comment]
I may be wrong, but I think this is a xamarin android binding project:
Basically there is a build tool that extracts api from the jars files directly and convert it to csharp code with csharp style API automatically.

Basically you should refer to the java api and transform calls by adding capital letter at begin of function, getter/setter become properties, package become namespace, etc ...

If you want to see the source, either the corresponding java code is open source and you should look for that, or it isn't and you should just refer to the api documentation. (I'm not familiar with what google components are opensource or not... )

**Comment by moljac** [comment]
@wutever0 

@tmijieux is completely right! There is not much C# code in here. Android Java (and Kotlin) bindings are XPath transformations of the google's AOSP API xml format which is extracted from `*.jar`s (and `*.aar`s) and then C# code is generated (and much more)

What is your question? Why do you need the code?

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
