### ISSUE TITLE
Custom Ml Vision not found

### ISSUE THREAD

**Issue by thanoue** [xamarin/GooglePlayServicesComponents#335]
I installed Xamarin.Firebase.ML.Model.Interpreter to use Firebase Custom Ml label.
But I can't found FirebaseCustomRemoteModel class on it

**Comment by moljac** [comment]
@thanoue 

Thanks for the feedback, but a little bit information would be helpfull...
What version?

There are nugets with Android.Support dependencies (versions 71.xxx) and new previews with AndroidX dependecies (versions 1xx.yyy).

**Comment by thanoue** [comment]
I meant version 71

**Comment by moljac** [comment]
@thanoue 

OK. Thanks. I will take a look into it.

**Comment by moljac** [comment]
@thanoue 

This class is available in version 22.0.0+

https://firebase.google.com/support/release-notes/android#mlkit-model-interpreter_v22-0-0

closing issue, soon

**Comment by moljac** [comment]
The library is already bound and waiting for publishing.

https://github.com/xamarin/GooglePlayServicesComponents/blob/master_based_androidx_based_updates_202002/config.json#L717-L724

Closing this one.
