### ISSUE TITLE
firebase-ml-vision-barcode-model dependency

### ISSUE THREAD

**Issue by claudeHasler** [xamarin/GooglePlayServicesComponents#336]
Hi, ive successfully implemented a barcode scanner for android using these firebase bindings. Performance is not optimal though, and I'm guessing this has to to with the missing dependency:

firebase-ml-vision-barcode-model
https://firebase.google.com/docs/ml-kit/android/read-barcodes

>  Version 24.0.0 of firebase-ml-vision introduces a new barcode scanning model, which comes with significant improvements in both latency and accuracy over the older model. In addition, with the latest API, you now can access the raw bytes for non UTF-8 encoded barcode data.

> Be sure to add the new firebase-ml-vision-barcode-model module to your project dependencies to use the new model.

this dependency would provide an up to date model for barcode detection

is it possible to add this?

**Comment by moljac** [comment]
@claudeHasler 

Thanks for the feedback, but I'll need more info on the issue.

> Hi, ive successfully implemented a barcode scanner for android using these firebase bindings.

Which version?

> is it possible to add this?

For sure. 1st I need to know which version you ve been using. 24.0.0 is quite new and I must bind older versions 1st. It is simply easier to go step by step. Recently I published previews (after a long fight) and plan to bump versions step wise in much faster cadence.

Thanks

**Comment by claudeHasler** [comment]
awesome! thanks for the good work

My version atm:
Xamarin.Firebase.ML.Vision v71.1700.0

Is there a roadmap/timeframe for when this feature will be available?

**Comment by moljac** [comment]
Morn @claudeHasler 

I have prepared everything (almost) to be as soon as possible.

https://github.com/xamarin/GooglePlayServicesComponents/blob/master_based_androidx_based_updates_202002/config.json#L774-L829

But 1st I want to have master green and have issues with some of our packages/tools, but am working on fixing that.

**Comment by claudeHasler** [comment]
awesome thanks!

**Comment by moljac** [comment]
@claudeHasler 

Preview published yesterday:

https://www.nuget.org/packages/Xamarin.Firebase.ML.Vision.BarCode.Model/116.1.1-preview01

Closing this one soon
