### ISSUE TITLE
Google Play Services - Maps assembly not compiling

### ISSUE THREAD

**Issue by wsloth** [xamarin/GooglePlayServicesComponents#34]
### Xamarin.Android Version (eg: 6.0):
6.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 Home

### Google Play Services Version (eg: 8.4.0):
Xamarin.GooglePlayServices.Maps 29.0.0.2
Google Play Services Rev 37 (From Android SDK Manager)

### Describe your Issue:
After installing the `Google Play Services - Maps` component into my android application and using the MapFragment class:
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

  <fragment xmlns:android="http://schemas.android.com/apk/res/android"
            android:id="@+id/map"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            class="com.google.android.gms.maps.MapFragment" />

</LinearLayout>
```
When building, I simply receive all kinds of errors that makes me suspicious that something in the Maps package was not configured correctly.

![err](https://cloud.githubusercontent.com/assets/4933907/19899559/e37995f6-a060-11e6-8fa2-ff63f31e0398.PNG)

Also: the [Xamarin documentation on Maps](https://developer.xamarin.com/guides/android/platform_features/maps_and_location/maps/part_2_-_maps_api/) is way out of date and does not show any accurate info on using maps anymore.

### Steps to Reproduce (with link to sample solution if possible):

* Create a new solution
* Install the Google Play Services Maps component
* Use the layout XAML shown above
* Build and Run

### Include any relevant Exception Stack traces, build logs, adb logs:

N/A

**Comment by Redth** [comment]
This looks like a problem with the dependencies installed.  I know this is an old issue, but if it's still an issue please try updating to the latest stable nuget packages for play services, make sure you're also using Xamarin.Build.Download 0.4.3 or higher, and try deleting your bin/ and obj/ folders, and building again.
