### ISSUE TITLE
Firebase InAppMessaging not available for android

### ISSUE THREAD

**Issue by amit04jain** [xamarin/GooglePlayServicesComponents#340]
### Xamarin.Android Version (eg: 6.0):
10.0

### Operating System & Version (eg: Mac OSX 10.11):
windows

### Describe your Issue:
Firebase Inappmessaging is till not available for xamarin . android

**Comment by moljac** [comment]
Not an issue. It is being worked on those bindings, but 1st I need to get master building with new Xamarin toolset, then release preivous versions of the GPS-FB packages with AndroidX dependencies.

**Comment by amitlodha** [comment]
same has been released for IOS.

**Comment by moljac** [comment]
@amitlodha If it is released on iOS - it does not imply it is released on Android. Two teams with different timeplans.

**Comment by moljac** [comment]
Preview published

https://www.nuget.org/packages/Xamarin.Firebase.InAppMessaging/119.0.6-preview01

Closing this one.
