### ISSUE TITLE
Firebase crashlytics not available for xamarin.android

### ISSUE THREAD

**Issue by amit04jain** [xamarin/GooglePlayServicesComponents#341]
### Xamarin.Android Version (eg: 6.0):
10

### Operating System & Version (eg: Mac OSX 10.11):
windows

### Describe your Issue:
Firebase crashlytics is not available for xamarin.android

**Comment by moljac** [comment]
Not an issue. It is being worked on those bindings, but 1st I need to get master building with new Xamarin toolset, then release preivous versions of the GPS-FB packages with AndroidX dependencies.

Stabe artifacts were published on 2020-04-27

https://firebase.google.com/support/release-notes/android#crashlytics_v17-0-0

**Comment by moljac** [comment]
Previews published"

https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics/117.0.0-preview01

https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics.NDK/117.0.0-preview01

closing this one
