### ISSUE TITLE
117.0.0-preview02 does not work target API 21

### ISSUE THREAD

**Issue by jorgenstorlie** [xamarin/GooglePlayServicesComponents#345]
### Google Play Services Version
117.0.0-preview02

### Describe your Issue
I use latest version of Xamarin.Android

### Steps to Reproduce (with link to sample solution if possible):
use 
117.0.0-preview02
with 
target API 21

this works:
target API 24
or 
117.0.0-preview01 

### Include any relevant Exception Stack traces, build logs, adb logs:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error AMM0000: /Users/jorgenstorlie/Apper/113Xamarin/Hjelp113-GPS.Android/obj/Debug/AndroidManifest.xml:5:3-72 Error: (AMM0000) (Hjelp113-GPS.Android)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error AMM0000: 	uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library /Users/jorgenstorlie/Apper/113Xamarin/Hjelp113-GPS.Android/obj/Debug/lp/68/jl/AndroidManifest.xml as the library might be using APIs not available in 21 (AMM0000) (Hjelp113-GPS.Android)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error AMM0000: 	Suggestion: use a compatible library with a minSdk of at most 21, (AMM0000) (Hjelp113-GPS.Android)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error AMM0000: 		or increase this project's minSdk version to at least 24, (AMM0000) (Hjelp113-GPS.Android)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error AMM0000: 		or use tools:overrideLibrary="io.crossbar.autobahn" to force usage (may lead to runtime failures) (AMM0000) (Hjelp113-GPS.Android)

**Comment by moljac** [comment]
Which GPS-FB is that?

I see only version `117.0.0-<suffix>`

Please provide `PackageReference` from csproj

**Comment by jorgenstorlie** [comment]
Here is the package that works.
If I update to Preview2 it fails.

  <ItemGroup>
    <PackageReference Include="AndHUD">
      <Version>1.4.2</Version>
    </PackageReference>
    <PackageReference Include="Com.Airbnb.Android.Lottie">
      <Version>3.4.2</Version>
    </PackageReference>
    <PackageReference Include="JWT">
      <Version>7.2.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Analytics">
      <Version>3.2.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Crashes">
      <Version>3.2.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Build.Framework">
      <Version>16.5.0</Version>
    </PackageReference>
    <PackageReference Include="Nager.Date">
      <Version>1.25.11</Version>
    </PackageReference>
    <PackageReference Include="RBush">
      <Version>2.0.41</Version>
    </PackageReference>
    <PackageReference Include="RestSharp.Serializers.NewtonsoftJson">
      <Version>106.11.5-alpha.0.2</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.7.335</Version>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.bundle_green">
      <Version>2.0.3</Version>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3">
      <Version>2.0.3</Version>
    </PackageReference>
    <PackageReference Include="Square.OkHttp3">
      <Version>4.2.2</Version>
    </PackageReference>
    <PackageReference Include="Square.OkIO">
      <Version>2.4.1</Version>
    </PackageReference>
    <PackageReference Include="System.Collections.Immutable">
      <Version>5.0.0-preview.4.20251.6</Version>
    </PackageReference>
    <PackageReference Include="System.Memory">
      <Version>4.5.4</Version>
    </PackageReference>
    <PackageReference Include="System.Numerics.Vectors">
      <Version>4.6.0-preview5.19224.8</Version>
    </PackageReference>
    <PackageReference Include="System.Reflection.TypeExtensions">
      <Version>4.7.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe">
      <Version>5.0.0-preview.4.20251.6</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.Serialization.Primitives">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.Serialization.Xml">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Threading.Thread">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Xml.XmlSerializer">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Connectivity">
      <Version>4.0.0.190-beta</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Maps.Utils">
      <Version>0.5.1-beta2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Browser">
      <Version>1.2.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData">
      <Version>2.2.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Migration">
      <Version>1.0.6</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.ViewPager2">
      <Version>1.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Build.Download">
      <Version>0.10.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Essentials">
      <Version>1.5.3.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Google.Android.Material">
      <Version>1.1.0-rc3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Location">
      <Version>117.0.0-preview01</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Maps">
      <Version>117.0.0-preview01</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.AppCompat.Resources">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Fragment">
      <Version>1.2.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.v4">
      <Version>28.0.0.3</Version>
    </PackageReference>
  </ItemGroup>

**Comment by jorgenstorlie** [comment]
Here is the package that works.
If I update to Preview2 it fails.

`  <ItemGroup>
    <PackageReference Include="AndHUD">
      <Version>1.4.2</Version>
    </PackageReference>
    <PackageReference Include="Com.Airbnb.Android.Lottie">
      <Version>3.4.2</Version>
    </PackageReference>
    <PackageReference Include="JWT">
      <Version>7.2.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Analytics">
      <Version>3.2.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Crashes">
      <Version>3.2.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Build.Framework">
      <Version>16.5.0</Version>
    </PackageReference>
    <PackageReference Include="Nager.Date">
      <Version>1.25.11</Version>
    </PackageReference>
    <PackageReference Include="RBush">
      <Version>2.0.41</Version>
    </PackageReference>
    <PackageReference Include="RestSharp.Serializers.NewtonsoftJson">
      <Version>106.11.5-alpha.0.2</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.7.335</Version>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.bundle_green">
      <Version>2.0.3</Version>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3">
      <Version>2.0.3</Version>
    </PackageReference>
    <PackageReference Include="Square.OkHttp3">
      <Version>4.2.2</Version>
    </PackageReference>
    <PackageReference Include="Square.OkIO">
      <Version>2.4.1</Version>
    </PackageReference>
    <PackageReference Include="System.Collections.Immutable">
      <Version>5.0.0-preview.4.20251.6</Version>
    </PackageReference>
    <PackageReference Include="System.Memory">
      <Version>4.5.4</Version>
    </PackageReference>
    <PackageReference Include="System.Numerics.Vectors">
      <Version>4.6.0-preview5.19224.8</Version>
    </PackageReference>
    <PackageReference Include="System.Reflection.TypeExtensions">
      <Version>4.7.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe">
      <Version>5.0.0-preview.4.20251.6</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.Serialization.Primitives">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.Serialization.Xml">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Threading.Thread">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Xml.XmlSerializer">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Connectivity">
      <Version>4.0.0.190-beta</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Maps.Utils">
      <Version>0.5.1-beta2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Browser">
      <Version>1.2.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData">
      <Version>2.2.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Migration">
      <Version>1.0.6</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.ViewPager2">
      <Version>1.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Build.Download">
      <Version>0.10.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Essentials">
      <Version>1.5.3.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Google.Android.Material">
      <Version>1.1.0-rc3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Location">
      <Version>117.0.0-preview01</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Maps">
      <Version>117.0.0-preview01</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.AppCompat.Resources">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Fragment">
      <Version>1.2.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.v4">
      <Version>28.0.0.3</Version>
    </PackageReference>
  </ItemGroup>
`

**Comment by jorgenstorlie** [comment]
The problem was 
io.crossbar.autobahn

I have now removed it and it works
