### ISSUE TITLE
Play Core Library to use In-app Updates

### ISSUE THREAD

**Issue by viveksamele08** [xamarin/GooglePlayServicesComponents#348]
I wants to use ”In-app Updates” feature in Xamarin.Android.

Do you plan to support "Play Core Library" in Xamarin?
https://developer.android.com/guide/app-bundle/in-app-updates

**Comment by moljac** [comment]
@viveksamele08 
Not at this point. There was issue for bindings in xamarin-android, but we did not work on those bindings.

I have it on my nice-to-have list, but I need to see other tasks and priorities.

**Comment by amitlodha** [comment]
Inapp update is good feature to update app it will be good if you guys work on this

**Comment by alvynfash** [comment]
@amitlodha In the meantime,  you can use this: [https://github.com/PatGet/XamarinPlayCoreUpdater](url)

**Comment by eman1986** [comment]
do you guys have an ETA on when you'll be getting to this? I'll use the above solution for now, but will prefer a more official solution eventually.

**Comment by moljac** [comment]
closing this one.
