### ISSUE TITLE
VS 16.7.0 Preview 2.0 - java.lang.NoSuchFieldError: no "Lcom/google/android/gms/auth/api/signin/GoogleSignInOptions;" field "DEFAULT_SIGN_IN" in class 

### ISSUE THREAD

**Issue by gmck** [xamarin/GooglePlayServicesComponents#350]
I’m using Google Sign In successfully in my Debug build, but get the above error in the Release build. 

Earlier I was getting a similar error from firebase e.g. java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider". I got rid of that one by adding -keep class com.google.firebase.provider.FirebaseInitProvider to my proguard.cfg. 

I tried adding -keep class com.google.android.gms.auth.api.signin.GoogleSignInOptions but that didn’t help with the above error and then I found that it had already been added anyway as part of the package as in

```
-keep class com.google.android.gms.auth.api.signin.GoogleSignInOptions
-keepclassmembers class com.google.android.gms.auth.api.signin.GoogleSignInOptions {
   *** describeContents(...);
   *** getAccount(...);
   *** getExtensions(...);
   *** isForceCodeForRefreshToken(...);
   *** isIdTokenRequested(...);
   *** isServerAuthCodeRequested(...);
   *** getLogSessionId(...);
   *** getScopes(...);
   *** getServerClientId(...);
   *** getScopeArray(...);
   *** writeToParcel(...);
   *** zab(...);
   *** zae(...);
}
```

Can anyone please advise what is the correct syntax to add the missing field?
```
[Register("DEFAULT_SIGN_IN")]
public static GoogleSignInOptions DefaultSignIn { get; }
```

Using 
Xamarin.Firebase.Auth 119.3.1-preview01
Xamarin.GooglePlayServices.Auth 118.0.0-preview01

P.S. One more question has anyone got any advice as to a quicker way of discovering what is missing from a proguard.cfg? Doing it one build at a time with -keep class for every class not found exception is painful.

**Comment by moljac** [comment]
@gmck 

This is GPS-FB issue, so I transferred it here.

Few comments:

> One more question has anyone got any advice as to a quicker way of discovering what is missing from a proguard.cfg? 

Sorry, but no. R8 is much aggressive with optimizations and linking, so I have issues with it too. All the time. Simply I need to dig deeper into R8/proguard advanced features and syntax.

> Doing it one build at a time with -keep class for every class not found exception is painful.

Yeah. Tell me about it. I feel your pain.

**Comment by gmck** [comment]
@moljac  **R8/proguard advanced features and syntax**. Me too, but not looking forward to it.

I got a little further along with it. I went back to my original GoogleSignIn test app and played around with it there.

Added
`-keep class com.google.android.gms.auth.api.signin.GoogleSignInOptions{ *;}`

That got me a little further at least my login window comes up. But then I got a 
`java.lang.InstantiationException: java.lang.Class<com.google.android.gms.auth.api.signin.internal.SignInHubActivity> cannot be instantiated.` 
as soon as I hit the Sign In button.

So I added
`-keep class com.google.android.gms.auth.api.signin.internal.SignInHubActivity {*; }`

Now the Sign In button displays the Choose an Account dialog, but when you select an account it obviously gets the GoogleSignInAccount data because you can see the GoogleSignInAccount.Email and GoogleSignInAccount.Id, however, it now fails the await FirebaseAuthWithGoogle(account) because the try/catch returns the Toast “authentication failed”. The same code doesn’t fail in debug release.

I started out on this GoogleSignIn test app when you first released the AndroidX version of GooglePlayServices last year but quickly found out it wasn’t AndroidX compatible because it still had v4 Dialog fragments, so I gave up on it then. Then when these new releases became available I started on it again. I think this new problem is that I based my code on the original sample code. 

I’ve just found new firebase docs https://firebase.google.com/docs/auth/android/google-signin#java_4 that suggest that we should be doing the FirebaseAuthWithGoogle using an OnCompleteListener. So I’m going to play around with that and see if gets around this problem.

When I'm done I upload a new sample.

**Comment by gmck** [comment]
@moljac . I got it working based on those docs. I'm still plenty confused about Proguard syntax, so I think the proguard.cfg can be improved. I left some notes in there that may help.

Attaching the sample, which is now only loosely based on the original sample.
[GoogleSignInTestX.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/4741191/GoogleSignInTestX.zip)

Just noticed a typo in the cfg. "would" should be "wouldn't"

**Comment by moljac** [comment]
@gmck Thanks for the feedback. I will check the sample and rest of this issue ASAP.

**Comment by moljac** [comment]
@gmck 
Trying to get in touch privately, but could not find you on gitter and there is no email associated with your account.
Ping me privately on gitter please.

**Comment by gmck** [comment]
@moljac Didn't realise there was no email. Have made it public now. Sorry not on glitter

**Comment by moljac** [comment]
@gmck You can make it private now. To reduce spam.
Did you get my mail?

**Comment by moljac** [comment]
closing this issue
