### ISSUE TITLE
Deprecated warnings regarding Google Drive classes in DriveSample and ClassNotFoundException 

### ISSUE THREAD

**Issue by irine-k** [xamarin/GooglePlayServicesComponents#355]
### Xamarin.Android Version (eg: 6.0):
Xamarin 16.5 Xamarin.Android SDK 10.2.0.100

### Operating System & Version (eg: Mac OSX 10.11):

Windows 10

### Describe your Issue
I built DriveSample.sln with VS 2019, got  'is obsolete' warnings:

```
__1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(539,3): warning XA0119: Using Fast Deployment and a Code Shrinker at the same time is not recommended. Use Fast Deployment for Debug configurations and a Code Shrinker for Release configurations.
1>C:\Users\Administrator\.nuget\packages\xamarin.build.download\0.10.0\buildTransitive\Xamarin.Build.Download.targets(88,3): warning XBD100: ItemGroup `XamarinBuildDownloadRestoreAssemblyAar` is no longer supported.  If your build is failing, revert to an older Xamarin.Build.Download version, or migrate your packages to use the new `XamarinBuildDownloadAndroidAarLibrary` ItemGroup.  If your build is succeeding it is safe to ignore this warning.
1>C:\Proj\GooglePlayServicesComponents\samples\com.google.android.gms\play-services-drive\DriveSample\MainActivity.cs(48,34,48,85): warning CS0618: 'IDriveApi.GetRootFolder(GoogleApiClient)' is obsolete: 'deprecated'
1>C:\Proj\GooglePlayServicesComponents\samples\com.google.android.gms\play-services-drive\DriveSample\MainActivity.cs(51,23,51,87): warning CS0618: 'IDriveFolder.CreateFile(GoogleApiClient, MetadataChangeSet, IDriveContents)' is obsolete: 'deprecated'
1>C:\Proj\GooglePlayServicesComponents\samples\com.google.android.gms\play-services-drive\DriveSample\MainActivity.cs(51,96,51,123): warning CS0618: 'IDriveFolderDriveFileResult' is obsolete: 'This class is obsoleted in this android platform'
1>C:\Proj\GooglePlayServicesComponents\samples\com.google.android.gms\play-services-drive\DriveSample\MainActivity.cs(66,37,66,87): warning CS0618: 'IDriveApi.Query(GoogleApiClient, QueryClass)' is obsolete: 'deprecated'
1>C:\Proj\GooglePlayServicesComponents\samples\com.google.android.gms\play-services-drive\DriveSample\MainActivity.cs(66,96,66,125): warning CS0618: 'IDriveApiMetadataBufferResult' is obsolete: 'This class is obsoleted in this android platform'
1>C:\Proj\GooglePlayServicesComponents\samples\com.google.android.gms\play-services-drive\DriveSample\MainActivity.cs(109,27,109,38): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Proj\GooglePlayServicesComponents\samples\com.google.android.gms\play-services-drive\DriveSample\MainActivity.cs(129,17,129,82): warning CS0618: 'GooglePlayServicesUtil.GetErrorDialog(int, Activity, int)' is obsolete: 'deprecated'_
```

When I thy to run the sample, I got the exception:

```
J_ava.Lang.ClassNotFoundException
  Message=Didn't find class "com.google.android.gms.common.api.GoogleApiClient$Builder" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xamarin.googleplayservices.drivesample-LbQ_Dt2YbS65Zpj1JgWdUQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.xamarin.googleplayservices.drivesample-LbQ_Dt2YbS65Zpj1JgWdUQ==/lib/x86, /data/app/com.xamarin.googleplayservices.drivesample-LbQ_Dt2YbS65Zpj1JgWdUQ==/base.apk!/lib/x86, /system/lib]]_
```

- Are the warnings and the exception related to the deprecation of Goggle Drive API from Dec 2019 announced by Google ?
- If so, do you have a roadmap for implementation of current v3 API for Android?  
Thank you

**Comment by moljac** [comment]
Google has obsoleted some APIs and because they have it in the artifacts we do bindings for those too.

To help you with `java.Lang.ClassNotFoundException` I need more info. Read issue template please. You have deleted parts that explain what is needed to triage issues.

**Comment by moljac** [comment]
@irine-k 
Well, I will need `PackageReference`s to see which version does.

Can you add proguard rules and following one to your project, please?

Something like:

```
-keep class com.google.android.gms.common.api.GoogleApiClient$Builder { *; }
```

Namely this class is generated in 3 branches, so I think linker or R8 might be the cause of removing that class.

```
find ./generated/ -type f -name "*GoogleApiClient.cs" -exec grep -Hni " Builder" {} \;
```

201908:

```
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:28:		public sealed partial class Builder : global::Java.Lang.Object {
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:49:			internal Builder (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer) {}
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:53:			public unsafe Builder (global::Android.Content.Context p0)
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:73:			public unsafe Builder (global::Android.Content.Context p0, global::Android.Gms.Common.Apis.GoogleApiClient.IConnectionCallbacks p1, global::Android.Gms.Common.Apis.GoogleApiClient.IOnConnectionFailedListener p2)
```

202002:

```
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:28:		public sealed partial class Builder : global::Java.Lang.Object {
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:49:			internal Builder (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer) {}
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:53:			public unsafe Builder (global::Android.Content.Context p0)
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:73:			public unsafe Builder (global::Android.Content.Context p0, global::Android.Gms.Common.Apis.GoogleApiClient.IConnectionCallbacks p1, global::Android.Gms.Common.Apis.GoogleApiClient.IOnConnectionFailedListener p2)```
```

202005:

```
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:28:		public sealed partial class Builder : global::Java.Lang.Object {
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:49:			internal Builder (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer) {}
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:53:			public unsafe Builder (global::Android.Content.Context p0)
./generated//com.google.android.gms.play-services-base/obj/Release/monoandroid90/generated/src/Android.Gms.Common.Apis.GoogleApiClient.cs:73:			public unsafe Builder (global::Android.Content.Context p0, global::Android.Gms.Common.Apis.GoogleApiClient.IConnectionCallbacks p1, global::Android.Gms.Common.Apis.GoogleApiClient.IOnConnectionFailedListener p2)
```

**Comment by irine-k** [comment]
Do you mean, PackageReference from csproj?
`   <PackageReference Include="Xamarin.Android.Arch.Core.Common">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Core.Runtime">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Lifecycle.Common">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Lifecycle.LiveData">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Lifecycle.LiveData.Core">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Lifecycle.Runtime">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Arch.Lifecycle.ViewModel">
      <Version>1.1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Annotations">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.AsyncLayoutInflater">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Collections">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Compat">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.CoordinaterLayout">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Core.UI">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Core.Utils">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.CursorAdapter">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.CustomView">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.DocumentFile">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.DrawerLayout">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Fragment">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Interpolator">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Loader">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.LocalBroadcastManager">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Media.Compat">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Print">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.SlidingPaneLayout">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.SwipeRefreshLayout">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.v4">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.VersionedParcelable">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.ViewPager">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Build.Download">
      <Version>0.10.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Base">
      <Version>71.1610.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Basement">
      <Version>71.1620.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Drive">
      <Version>71.1600.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Tasks">
      <Version>71.1601.0</Version>
    </PackageReference>`

 

> Can you add proguard rules and following one to your project, please?

Sorry, I need more detailed instructions here. 

> find ./generated/ -type f -name "*GoogleApiClient.cs" -exec grep -Hni " Builder" {} \;

That what I found:
 _.\generated\com.google.android.gms.play-services-base\obj\Debug\monoandroid90\generated\src\Android.Gms.Common.Apis.GoogleApiClient.cs (4 hits)
	Line 26: 		public sealed partial class Builder : global::Java.Lang.Object {
	Line 47: 			internal Builder (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer) {}
	Line 51: 			public unsafe Builder (global::Android.Content.Context context)
	Line 71: 			public unsafe Builder (global::Android.Content.Context context, global::Android.Gms.Common.Apis.GoogleApiClient.IConnectionCallbacks connectedListener, global::Android.Gms.Common.Apis.GoogleApiClient.IOnConnectionFailedListener connectionFailedListener)_

**Comment by moljac** [comment]
@irine-k 

Did you try adding proguard rules? Without more info I will be forced to close the issue soon. Thanks

**Comment by irine-k** [comment]
I had to leave this project aside.
