### ISSUE TITLE
Cloud Map Styling 

### ISSUE THREAD

**Issue by brunodubcosta** [xamarin/GooglePlayServicesComponents#364]
### Xamarin.Android Version (eg: 6.0):
6.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version
60.1142.1

### Describe your Issue
Cloud Map Styling 
### Relevant information
I cannot find a way to add a mapId to add it's style.

https://github.com/googlemaps/android-samples/blob/master/ApiDemos/java/app/src/v3/res/layout/cloud_styling_basic_demo.xml

### Minimal Repro Code Sample
<fragment
    android:id="@+id/map"
    class="com.google.android.libraries.maps.SupportMapFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    map:cameraTargetLat="47.6089945"
    map:cameraTargetLng="-122.3410462"
    map:cameraZoom="14"
    map:mapId="@string/cloud_styling_basic_map_id" />

**Comment by moljac** [comment]
I am not sure if you can do that with version `60.1142.1` (that is bindings for version 11.4.2). And your sample uses version 17.0.0:

https://github.com/googlemaps/android-samples/blob/master/ApiDemos/java/app/build.gradle#L61

So, you need 117.0.0-preview04 to achieve that. (Not sure 100%)

**Comment by brunodubcosta** [comment]
Thank you for the info! 
I got around this by importing the map style to the project and then set my map style to the xml file. But I will be checking that preview Thanks.

` var success = googleMap.SetMapStyle(MapStyleOptions.LoadRawResourceStyle(Context.ApplicationContext,Resource.Raw.silverMapStyle));`
