### ISSUE TITLE
[Deprecated] Fabric SDK and old versions of the Firebase Crashlytics SDK on November 15, 2020

### ISSUE THREAD

**Issue by Dona278** [xamarin/GooglePlayServicesComponents#365]
As mentioned in the [offical firebase documentation](https://firebase.google.com/docs/crashlytics/get-started?platform=android)

> The Fabric SDK is now deprecated and will continue reporting your app's crashes until November 15, 2020. On this date, the Fabric SDK and old versions of the Firebase Crashlytics SDK will stop sending crashes for your app. To continue getting crash reports in the Firebase console, make sure you upgrade to the Firebase Crashlytics SDK versions 17.0.0+ for Android, 4.0.0+ for iOS, and 6.15.0+ for Unity.

And at this moment there is only the [firebase-crash library bound to the version 16.2.1](https://github.com/xamarin/GooglePlayServicesComponents/blob/master_based_androidx/config.json#L541)

There is any update in the roadmap now that AndroidX xamarin library have been released?

**Comment by Dona278** [comment]
I'm sorry, I noticed that already exists the package Xamarin.Firebase.Crashlytics

**Comment by aandino-dev** [comment]
Hi,

Is there an update on the roadmap? When would it be available for the new version of the library?
