### ISSUE TITLE
Binding Missing com.google.firebase:firebase-crashlytics

### ISSUE THREAD

**Issue by epsmae** [xamarin/GooglePlayServicesComponents#371]
### Xamarin.Android Version:
Xamarin Android 10

### Crashlytics info
`We are writing to let you know that the Fabric Crashlytics SDK is now deprecated and will continue reporting your app's crashes until November 15, 2020. After this date, the Fabric Crashlytics SDK and beta versions of the Firebase Crashlytics SDK will stop sending crash reports for your app. `

### Upgrade Instructions
https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android

### Issue
The binding for com.google.firebase:firebase-crashlytics is missing.
Is there a reason why this binding is missing?
Can we expect this binding to be created soon?

**Comment by moljac** [comment]
The bindings are published as previews:

*.  https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics/117.0.0-preview02

*.  https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics.NDK/117.0.0-preview02

Branch and config file:

https://github.com/xamarin/GooglePlayServicesComponents/blob/master_based_androidx_based_updates_202005/config.json#L588-L602

**Comment by moljac** [comment]
Closing the issue

**Comment by rameshbabudevalingam** [comment]
> The bindings are published as previews:
> 
> *. https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics/117.0.0-preview02
> 
> *. https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics.NDK/117.0.0-preview02
> 
> Branch and config file:
> 
> https://github.com/xamarin/GooglePlayServicesComponents/blob/master_based_androidx_based_updates_202005/config.json#L588-L602

@moljac , when can we expect a stable version of this bindings?
