### ISSUE TITLE
When do you support   MLKit barcode scanning?

### ISSUE THREAD

**Issue by pulmuone** [xamarin/GooglePlayServicesComponents#377]
### Google Play Services Version

https://mvnrepository.com/artifact/com.google.mlkit/barcode-scanning

<dependency>
    <groupId>com.google.mlkit</groupId>
    <artifactId>barcode-scanning</artifactId>
    <version>16.0.2</version>
</dependency>

**Comment by moljac** [comment]
How about this

https://github.com/xamarin/XamarinComponents/pull/933/files#diff-7f9d393796eb181f8b4a9e9863953151R12-R15
?

**Comment by moljac** [comment]
closing this one
