### ISSUE TITLE
RuntimeException: Class not Found when linking sdk assemblies or using d8 Dex compiler with bundle format. 

### ISSUE THREAD

**Issue by sirwes** [xamarin/GooglePlayServicesComponents#378]
### Xamarin.Android Version (eg: 6.0):

4.8
### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version
71.1720.4

### Describe your Issue
When I try to use the d8 compiler with the bundle format and the r8 code shrinker, I get this error. I also get this error using the dx compiler with the apk format and the ProGuard code shrinker when I link sdk assemblies. The code shrinking/linking seems to be remove an essential class for the mobile ads package.

### Stack Trace
Java.Lang.RuntimeException
  Message=Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAdsInitProvider" on path: DexPathList[[zip file "/data/app/com.com.package-Q6u0iTiEb3lcLfW_M9t01Q==/base.apk", zip file "/data/app/com.com.package-Q6u0iTiEb3lcLfW_M9t01Q==/split_config.arm64_v8a.apk", zip file "/data/app/com.com.package-Q6u0iTiEb3lcLfW_M9t01Q==/split_config.en.apk", zip file "/data/app/com.com.package-Q6u0iTiEb3lcLfW_M9t01Q==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.com.package-Q6u0iTiEb3lcLfW_M9t01Q==/lib/arm64, /data/app/com.com.package-Q6u0iTiEb3lcLfW_M9t01Q==/base.apk!/lib/arm64-v8a, /data/app/com.com.package-Q6u0iTiEb3lcLfW_M9t01Q==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.com.package-Q6u0iTiEb3lcLfW_M9t01Q==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.com.package-Q6u0iTiEb3lcLfW_M9t01Q==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]

Packages used:
Xamarin.GooglePlayServices.Ads.Lite

Build settings (tools)

```
    <AndroidDexTool>d8</AndroidDexTool>
    <AndroidLinkTool>r8</AndroidLinkTool>
```

**Comment by Mataboge** [comment]
Did you try using the preview02 package version?

or try adding this line in your Proguard.cfg file:
-keep class com.google.android.gms.** { *; }

**Comment by sirwes** [comment]
@Mataboge I'm not sure what the preview02 package version is...
But adding that line in the cfg file worked!
