### ISSUE TITLE
Which version of Google Mobile Ads SDK are your providing ?

### ISSUE THREAD

**Issue by jonathanantoine** [xamarin/GooglePlayServicesComponents#386]
Hello,

I am using the Xamarin.GooglePlayServices.Ads package version 71.1720.4 and if I use [the table on this repository home page](https://github.com/xamarin/GooglePlayServicesComponents/blob/46fb07d8724f6c2342ff2b36bd332cc70106bab3/config.json) it feels like it's the Google 17.1.2 version. Please tell me I am wrong and it's not the version from "2018‑12‑03".

Thanks for your help !

**Comment by moljac** [comment]
It is.

There are previews for newer versions:

https://www.nuget.org/packages/Xamarin.GooglePlayServices.Ads/

**Comment by jonathanantoine** [comment]
Thank you. Can you please tell me which "Google version" it is in the prerelease ?

Thanks !

**Comment by moljac** [comment]
```
18.1.1
18.3.0
19.1.0
```

**Comment by jonathanantoine** [comment]
Thanks a lot. I struggled a lot to make it works (mainly because I was using old package config file) but it's working fine now. !

**Comment by moljac** [comment]
!st rule - migrate to modern tooling:

1. PackageReference instead of packages.config
2. modern Androd tools (D8, R8, aapt2)
