### ISSUE TITLE
Google Fitness API (and authentication) have been obsoleted without alternatives

### ISSUE THREAD

**Issue by Mechameesh** [xamarin/GooglePlayServicesComponents#394]
### Xamarin version

Xamarin.Forms 4.8.0.1451

### Operating System & Version (eg: Mac OSX 10.11):

Windows 10 - 1909

### Google Play Services Version

Xamarin.GooglePlayServices.Fitness 118.0.0

### Other noteworthy packages

Xamarin.Firebase.Messaging 120.1.7

### Describe your Issue

After updating to version 118, pretty much all the classes from the Fitness package I have in use are marked as obsolete and deprecated without any documentation on what the alternatives are.

The following are obsoleted:

* GoogleApiClient
* FitnessClass.RECORDING_API
* FitnessClass.HISTORY_API
* FitnessClass.RecordingApi
* FitnessClass.HistoryApi

With the last two being the wrapper for javastyle listener -> async/await code as far as i can tell

Do you have any pointers as for how to replace the obsoleted code?

### Build log

**Java.Lang.NoSuchMethodError:** 'No static method checkBuilderRequirement(Ljava/lang/Object;Ljava/lang/Class;)V in class Ldagger/internal/Preconditions; or its super classes (declaration of 'dagger.internal.Preconditions' appears in /data/app/countrycode.company.appnamespace-VehJfiuOAJ41Delbo9r4ig==/base.apk)'

with the actual namespace replaced with placeholder for issue

**Comment by Mechameesh** [comment]
This also means that the sample code at https://github.com/xamarin/GooglePlayServicesComponents/tree/master/samples/com.google.android.gms/play-services-fitness is also obsolete.

**Comment by Mechameesh** [comment]
The dagger error went away after installing dagger as mentioned in [this stackoverflow question](https://stackoverflow.com/questions/64428377/java-lang-nosuchmethoderror-no-static-method-checkbuilderrequirement) although I'm not sure why this wouldn't just be a nuget dependency if it is needed

**Comment by moljac** [comment]
@Mechameesh 
Thanks for the feedback

> I'm not sure why this wouldn't just be a nuget dependency if it is needed

It is, but probably in nuget is older dagger version which does not have that method.

**Comment by chrisfoulds** [comment]
Regarding examples, I just took the ones from the website and converted them in C# as always, it's the same API's just slightly different names

**Comment by Mechameesh** [comment]
@chrisfoulds Which website? https://developers.google.com/fit/android I assume? 

I've been using `GoogleApiClient.Builder` to do authentication, but this has been deprecated, so any pointers to what is the "correct" auth API would be appreciated.

**Comment by Mechameesh** [comment]
Got it working! Listing a couple of gotchas for future readers:

`GoogleApiClient` will have to be replaced with the following auth flow

1. Create `GoogleSignInOptions` via builder setting appropriate Scopes from `FitnessClass.Scope*`
2. Use `GoogleSignIn.GetClient()` to get a client
3. Use the `SignInIntent` from the client to StartActivityForResult()
4. Once you have a login get a `GoogleSignClient` with the appropriate read/write accesses like so:
```
IGoogleSignInOptionsExtension fitnessOptions = FitnessOptions.InvokeBuilder()
.AddDataType(DataType.TypeActivitySegment, FitnessOptions.AccessRead)
.AddDataType(DataType.AggregateActivitySummary, FitnessOptions.AccessRead)
.AddDataType(DataType.TypeSpeed, FitnessOptions.AccessRead)
.AddDataType(DataType.AggregateSpeedSummary, FitnessOptions.AccessRead)
.Build();

signInAccount = GoogleSignIn.GetAccountForExtension(Application.Context, fitnessOptions);
```


When accessing the various FitnessClass APIs `FitnessClass.HistoryApi` has been replaced with calls to `FitnessClass.getHistoryClient()` where you have to pass in the signInAccount from above.
