### ISSUE TITLE
Remote Display (RemoteDisplayLocalService) not working.

### ISSUE THREAD

**Issue by ryansites310** [xamarin/GooglePlayServicesComponents#40]
Xamarin.Android Version (7.0.2.37)
(Windows 10 Visual Studio 2015 Enterprise)

No matter what I have tried, I cannot get a working example of RemoteDisplayLocalService to work completely. After calling 
` CastRemoteDisplayLocalService.StartService(this, Class.FromType(typeof(MyPresentationService)),
                    "APP_ID", castDevice, settings, new CastDisplayCallbacks(castDevice, this));`
my instance of CastRemoteDisplayLocalService OnCreate method is called...and the default display is displayed on TV with name of application registered... however the `OnCreatePresentation(Display display)` method never gets called?!?! This is needed to create the CastPresentation.
I'm looking for a Christmas Miracle here. I have posted on every forum available, and I've been kicked in the face for not posting it the "appropriate forums. The sample only utilizes media playback, so I am hoping you guys have a secret arsenal of sample code for remote display that you can share with me!

**Comment by ryansites310** [comment]
@Redth can you at least tell me if this project is still actively worked?

**Comment by Redth** [comment]
We are definitely actively working on this repo. Can you try the latest prerelease on nuget? 42.1001.0-beta1? If that doesn't work the next step would be to verify this is an issue with the binding and not the library itself by replicating the relevant bits of code in a Java app. It would be helpful if you can post a sample solution isolating the issue.

**Comment by ryansites310** [comment]
@Redth I tried updating to the latest Xamarin.GooglePlayServices libraries as you suggested (42.1001.0-beta1) and couldn't get it to compile. So I created a brand new project with only these assembly references from nugget, and still cant get it to compile with the beta. Created a quick project it GitHub here to show : https://github.com/ryansites310/GoogleCastAndroidSample

Not sure why it won't compile. In the meantime, I am going to create a project with android studio and verify that google cast library is in fact working.

**Comment by ryansites310** [comment]
@Redth Wanted to give update. Did figure out why OnCreatePresentation(Display display) callback method was not firing. When I registered my application in Cast Developer Console, I registered it as 'Styled Media Receiver' instead of 'Remote Display' application. After recreating application in console correctly, all bindings worked. Thanks for the tip to write it in native Java app, b/c it didn't work there either, which made me realize I probably had something wrong on my end.

As a final note, I still can not get latest beta version to compile locally.

**Comment by Redth** [comment]
Thanks for following up!  Creating a Java version is definitely a pain (after all we are trying to avoid Java!) but really can help quickly eliminate the binding as a variable so thank you for being patient and trying that route. 

I will have a look this week at your sample when I'm back at my desk and see why it's not compiling.

**Comment by Redth** [comment]
I hope you've tried 42.1001.0-beta2 by now, with a newer version of the Xamarin.Build.Download dependency which should fix this issue.
