### ISSUE TITLE
Unable install Xamarin Firebase - Common 32.961.0 to xamarin.forms solution

### ISSUE THREAD

**Issue by Femilshajin** [xamarin/GooglePlayServicesComponents#41]
### Xamarin.Android Version (eg: 6.0):
Xamarin 6.1.3, MonoAndroid,Version=v6.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Describe your Issue:
Unable to add Xamarin Firebase - Common NuGet to my xamarin.forms solution

### Steps to Reproduce (with link to sample solution if possible):
Create a new  xamarin.forms solution and try to add firebase package

### Include any relevant Exception Stack traces, build logs, adb logs:
Attempting to gather dependency information for package 'Xamarin.Firebase.Common.32.961.0' with respect to project 'Fire.Droid', targeting 'MonoAndroid,Version=v6.0'
Attempting to resolve dependencies for package 'Xamarin.Firebase.Common.32.961.0' with DependencyBehavior 'Lowest'
Unable to find a version of 'Xamarin.Android.Support.v4' that is compatible with 'Xamarin.Android.Support.Animated.Vector.Drawable 23.3.0 constraint: Xamarin.Android.Support.v4 (= 23.3.0)', 'Xamarin.Android.Support.Design 23.3.0 constraint: Xamarin.Android.Support.v4 (= 23.3.0)', 'Xamarin.Android.Support.v7.AppCompat 23.3.0 constraint: Xamarin.Android.Support.v4 (= 23.3.0)', 'Xamarin.Android.Support.v7.MediaRouter 23.3.0 constraint: Xamarin.Android.Support.v4 (= 23.3.0)', 'Xamarin.Android.Support.v7.RecyclerView 23.3.0 constraint: Xamarin.Android.Support.v4 (= 23.3.0)', 'Xamarin.Android.Support.Vector.Drawable 23.3.0 constraint: Xamarin.Android.Support.v4 (= 23.3.0)', 'Xamarin.Forms 2.3.3.180 constraint: Xamarin.Android.Support.v4 (= 23.3.0)', 'Xamarin.GooglePlayServices.Basement 32.961.0 constraint: Xamarin.Android.Support.v4 (>= 24.2.1)'.

**Comment by zmarwa** [comment]
Xamarin.Firebase.Common -Version 32.961.0 depends on Xamarin.GooglePlayServices.Basement Version = 32.961.0
And Xamarin.GooglePlayServices.Basement Version = 32.961.0 depends on Xamarin.Android.Support.v4 (Version >= 24.2.1)
But the latest xamarin.forms depends on Xamarin.Android.Support.v4 (Version = 23.3.0)

I think, you have to find a version of Xamarin.Firebase.Common which work with  Xamarin.Android.Support.v4 (Version = 23.3.0)

**Comment by ksachdeva** [comment]
Facing the same issue. Xamarin Forms not keeping up with the latest Xamarin.Adnroid.Support packages results not being able to use native libraries like this and others. 

From what I have understood there are 2 potential resolutions -

a) GooglePlayServicesComponents and its dependencies use the same version as of Xamarin.Forms

or

b) Xamarin.Forms keep up with the Xamarin.Android support packages

Quite frustrating indeed :(

**Comment by Redth** [comment]
This is really an issue of Xamarin.Forms, not Google Play Services.  I can tell you it's on that team's roadmap to support a newer version of play services very soon.

**Comment by Enoges** [comment]
So, no solutions here?

**Comment by zmarwa** [comment]
@Enoges try to have a configuration of file package.config like : 

<packages>
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="23.3.0" targetFramework="MonoAndroid60" />
  <package id="Xamarin.Android.Support.Design" version="23.3.0" targetFramework="MonoAndroid60" />
  <package id="Xamarin.Android.Support.v4" version="23.3.0" targetFramework="MonoAndroid60" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="23.3.0" targetFramework="MonoAndroid60" />
  <package id="Xamarin.Android.Support.v7.CardView" version="23.3.0" targetFramework="MonoAndroid60" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="23.3.0" targetFramework="MonoAndroid60" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="23.3.0" targetFramework="MonoAndroid60" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="23.3.0" targetFramework="MonoAndroid60" />
  <package id="Xamarin.Firebase.Common" version="32.940.0-beta3" targetFramework="monoandroid70" />
  <package id="Xamarin.Firebase.Iid" version="32.940.0-beta3" targetFramework="monoandroid70" />
  <package id="Xamarin.Firebase.Messaging" version="32.940.0-beta3" targetFramework="monoandroid70" />
  <package id="Xamarin.Forms" version="2.3.2.127" targetFramework="monoandroid70" />
  <package id="Xamarin.GooglePlayServices.Basement" version="32.940.0-beta3" targetFramework="monoandroid70" />
  <package id="Xamarin.GooglePlayServices.Tasks" version="32.940.0-beta3" targetFramework="monoandroid70" />
 </packages>

source: https://github.com/xamarin/GooglePlayServicesComponents/issues/20#issuecomment-269387028

**Comment by Redth** [comment]
The solution is to use the latest stable Xamarin.Forms and have your project's compileSdkVersion (so Target Framework) set to 7.0 or higher.  You will then be able to install newer versions of Android Support and therefore Google Play Services packages.
