### ISSUE TITLE
Xamarin.Firebase.Messaging Crash java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/datatransport/runtime/dagger/internal/Factory;

### ISSUE THREAD

**Issue by giuseppenovielli** [xamarin/GooglePlayServicesComponents#410]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android
Versione: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/hrcoffee2/Library/Android/sdk
	Versione di Android supportate:
		7.1 (livello API 25)
		8.0 (livello API 26)
		8.1 (livello API 27)

### Operating System & Version (eg: Mac OSX 10.11):
MacOs Catalina 10.15.4

### Describe your Issue
After install Xamarin.Firebase.Messaging latest version, into Xamarin.Forms (4.8.0.1560) application, include google-services.json, launch Debug Android application, it crash!

**A Workaround is installing Xamarin.Google.Dagger, as reported into stackoverflow link!**

Build settings (tools)
Debug

### Minimal Repro Code Sample
https://stackoverflow.com/questions/65381403/java-lang-noclassdeffounderror-when-implementing-firebase-cloud-messaging

### Steps to Reproduce (with link to sample solution if possible):
Install Xamarin.Firebase.Messaging latest version, into Xamarin.Forms (4.8.0.1560) application.
Only Xamarin.Firebase.Messaging is installed as Google plugin, nobody else.

### Include any relevant Exception Stack traces, build logs, adb logs:
[AndroidRuntime] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/datatransport/runtime/dagger/internal/Factory;
[AndroidRuntime] 	at com.google.android.datatransport.runtime.DaggerTransportRuntimeComponent.builder(DaggerTransportRuntimeComponent.java:70)
[AndroidRuntime] 	at com.google.firebase.datatransport.TransportRegistrar.lambda$getComponents$0(TransportRegistrar.java:37)
[AndroidRuntime] 	at com.google.firebase.datatransport.TransportRegistrar$$Lambda$1.create(Unknown Source:0)
[AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
[AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
[AndroidRuntime] 	at com.google.firebase.components.Lazy.get(Lazy.java:53)
[AndroidRuntime] 	at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
[AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
[AndroidRuntime] 	at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
[AndroidRuntime] 	at com.google.firebase.messaging.FirebaseMessagingRegistrar.lambda$getComponents$0$FirebaseMessagingRegistrar(Unknown Source:43)
[AndroidRuntime] 	at com.google.firebase.messaging.FirebaseMessagingRegistrar$$Lambda$0.create(Unknown Source:0)
[AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
[AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
[AndroidRuntime] 	at com.google.firebase.components.Lazy.get(Lazy.java:53)
[AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
[AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
[AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
[AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
[AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
[AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
[AndroidRuntime] 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
[AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
[AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
[AndroidRuntime] 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
[AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
[AndroidRuntime] 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
[AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
[AndroidRuntime] 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:107)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:214)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7356)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[AndroidRuntime] Caused by: java.lang.ClassNotFoundException: com.google.android.datatransport.runtime.dagger.internal.Factory
[AndroidRuntime] 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
[AndroidRuntime] 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[AndroidRuntime] 	... 36 more
[AndroidRuntime] Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/inject/Provider;
[AndroidRuntime] 	... 36 more
[AndroidRuntime] Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.inject.Provider" on path: DexPathList[[zip file "/data/app/com.aqpsmart.android-5C6XOMANNiIBbalDaCoXfg==/base.apk"],nativeLibraryDirectories=[/data/app/com.aqpsmart.android-5C6XOMANNiIBbalDaCoXfg==/lib/x86, /data/app/com.aqpsmart.android-5C6XOMANNiIBbalDaCoXfg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
[AndroidRuntime] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[AndroidRuntime] 	... 36 more

**Comment by arthurgsf** [comment]
> A Workaround is installing Xamarin.Google.Dagger, as reported into stackoverflow link!
This solved the problem

**Comment by giuseppenovielli** [comment]
@arthurgsf Yes but it is a workaround, but this is an issue, that must be fixed or explain why i must install also GoogleDatter if i want only FirebaseMessaging.

**Comment by moljac** [comment]
@giuseppenovielli 

Because FirebaseMessaging depends on Dagger and when it was bound it was older version of the library which does not have that API, so transitive dependencies do not pull latest nuget package, but the one that was specified when library was bound.

**Comment by moljac** [comment]
@giuseppenovielli 

The comment written by @arthurgsf was NOT off topic. Please do not mark comments as off topic if you are not 200% sure.

**Comment by moljac** [comment]
Closing this one.

**Comment by giuseppenovielli** [comment]
@moljac Thanks! My Comment deleted!

**Comment by moljac** [comment]
@giuseppenovielli 
No need to delete, but just do not mark it as off topic, because it help other users including us...

Thanks
