### ISSUE TITLE
Outdated bindings to Google ML Kit Vision Text Regognition api

### ISSUE THREAD

**Issue by deelw** [xamarin/GooglePlayServicesComponents#420]
Because we’re using ML Kit for Firebase (https://firebase.google.com/docs/ml-kit) for on-device text recognition and this is an old version, we need to migrate to the actual version of ML Kit (https://developers.google.com/ml-kit/vision/text-recognition ).

As Dutch government, we develop our apps using Xamarin and we need to migrate as well our Xamarin.iOS as our Xamarin.Android implementation.

For Xamarin.iOS we’re using nuget package Xamarin.Firebase.iOS.MLKit.Vision version 0.21.0 from Microsoft while for Xamarin.Android we’re using nuget package Xamarin.GooglePlayServices.Vision version 120.1.3, also from Microsoft. These packages contains C# bindings to ML Kit for Firebase.

Surprisingly there seems to be no Xamarin nuget packages available for the current GoogleMLKit/TextRecognition (https://developers.google.com/ml-kit/vision/text-recognition). Neither for Xamarin.iOS nor for Xamarin.Android.

We did try to make iOS bindings ourselves. While we did succeed in making and invoking these bindings, text is never recognized.

We ask you to make nuget packages available for the current versions of Google MLKit, specifically for maven repository com.google.android.gms:play-services-mlkit-text-recognition and cocoapod GoogleMLKit/TextRecognition.

Related issue: https://github.com/xamarin/GoogleApisForiOSComponents/issues/472

**Comment by deelw** [comment]
In addition to the above we're also using google's barcode scanning functionality (only) in our Android apps. Therefore we also need to migrate to maven repo com.google.mlkit:barcode-scanning. Could you also make this available? Thanks a lot!

**Comment by moljac** [comment]
@deelw 
See/check https://github.com/xamarin/GooglePlayServicesComponents/pull/421

Work in progress. Soon to be published (most likely next week). Bindings were done last summer, but there were some issues publishing them from XamarinComponents repo. So, MLKit was moved to GPS-FB repo

Closing this issue soon

**Comment by deelw** [comment]
@moljac
Good to hear! Thank your

How about the iOS counterpart?
[GoogleApisForiOSComponents/issues/472](https://github.com/xamarin/GoogleApisForiOSComponents/issues/472)

**Comment by moljac** [comment]
@deelw 
There used to be Components team which was working on bindings. Most of the team members were cross platform, but as usual one platform was more dominant for each team member.

Components team was dissolved and team members are on other teams in Xamarin org or else... 

Now. It is up to you to make conclusion (about iOS counterpart).

**Comment by deelw** [comment]
@moljac 
My conclusion is that I have to beg you as a contributor of the GoogleApisForiOSComponents repo to also make the iOS bindings for the Google MLKit TextRegognition api ;-)

Of course I can tell you the steps I did if you want, if that helps.

**Comment by moljac** [comment]
@deelw 

It is not about begging or maybe it is, but somebody/somewhere else... I work on Android team right now and was "almost gone" few months ago. Team member that was supposed to take over my tasks stated that he will continue to help me, because maintaining AndroidX, GPS-FB and Android stuff in XamarinComponents is effort for more than one person. So, chances that I will be able/capable to bind iOS are close to zero.

Now you will have to make conclusion whom/where to beg further. I will escalate, but my voice is not that strong...

BTW I am not sure I was contributor to GoogleApisForiOSComponents.

**Comment by deelw** [comment]
@moljac 
Oke, I understand. Thank you for escalating. I will escalate the iOS part too.

**Comment by moljac** [comment]
closing this one
