### ISSUE TITLE
Firebase analytics not appearing in firebase console

### ISSUE THREAD

**Issue by sureshValle** [xamarin/GooglePlayServicesComponents#44]
### Xamarin.Android Version (eg: 6.0):
Version: 7.0.2.42 

### Operating System & Version (eg: Mac OSX 10.11):
Mac OSX 10.12.2(16C67)

### Google Play Services Version (eg: 8.4.0):
Version: 32.961.0

### Describe your Issue:
Firebase analytics not appearing in firebase console

### Steps to Reproduce (with link to sample solution if possible):
Sample Solution:-
https://www.dropbox.com/s/trqk60vr7os8n1l/FirebaseAnalyticsDemo.zip?dl=0### 

Include any relevant Exception Stack traces, build logs, adb logs:

**Comment by Redth** [comment]
Was never able to reproduce, except that it takes a noticeably long time for analytics to show up in the console after they are logged in the app (the same is true for a java app).  Please open a new issue if it's still a problem with newer versions of play services.
