### ISSUE TITLE
How are the two different?

### ISSUE THREAD

**Issue by pulmuone** [xamarin/GooglePlayServicesComponents#441]
How are the two different?
Xamarin.Google.MLKit.BarcodeScanning vs Xamarin.GooglePlayServices.MLKit.BarcodeScanning

**Comment by moljac** [comment]
I am not expert, though I plan to start writing (porting) samples for those, but here is my laic understanding:

1.  `Xamarin.GooglePlayServices.MLKit.BarcodeScanning`
     this is part of Goggle Play Services, so it is cloud based, meaning barcode is sent to cloud where is processed and
     result is returned to user's device
     Note: Firebase is also cloud based
2.  `Xamarin.Google.MLKit.BarcodeScanning`
     MLKit is device based, where you deploy trained model on the device. Barcode is processed by trained model on the
     device, so no network traffic. MNodel can be trained either on device (usually desktop or even phone) or in the cloud.
     
But do not trust me 100% with this. I think I am close enough.

If answer satisfies you, please close the issue.

**Comment by moljac** [comment]
closing this one
