### ISSUE TITLE
Looking for an example of Xamarin.Google.MLKit.PoseDetection 117.0.0

### ISSUE THREAD

**Issue by vpenades** [xamarin/GooglePlayServicesComponents#446]
I'm looking to write an app that implements Xamarin.Google.MLKit.PoseDetection, but I have not been able to find any example or use case, or even how to start using it with Xamarin.... help?

Also, when trying to use `Xamarin.Google.MLKit.PoseDetection 117.0.0` , I've noticed it's impossible to create a `AccuratePoseDetectorOptions` object; because the nested Builder class doesn't have a `.Build()` method.

I'm not an expert, but looking at the APIs, It gives me the impression that classes `PoseDetectorOptions.Builder` `AccuratePoseDetectorOptions.Builder` should inherit from `PoseDetectorOptionsBase.Builder` , is that right?

I guess the nuget packages 117.0.0 have been automatically generated with the xamarin bindings system, but there's no actual examples for them?

**Comment by vpenades** [comment]
@moljac 

> And this is a problem - we do not bind prereleases except in special cases.

Ah, I didn't know that policy, so I understand you have to wait for 17.0.0.1 to update the bindings.

I was asking about the "outdated" API because some of our logic depends on those new "Z" values available in the new betas.... but we can wait for when google moves it from beta to release, so no worries.

> Full repro samples are more preferred. And it would be great if you would share it.

I'll try to strip it down from our stuff and upload the repo

**Comment by vpenades** [comment]
@moljac sent you an invitation to the repo with the code. Feel free to take a look and comment.

**Comment by moljac** [comment]
@vpenades 
Thanks a lot! Appreciated.

**Comment by vpenades** [comment]
Hi, sorry to ask for your attention again. I am aware you're busy, and most probably this is beyond what you can do on your own.

That's why I would like you to ask the people responsible above you to consider increasing the work force involved in this project, under these considerations:

- Artifical Intelligence based projects are going to be subject to long development periods where they evolve based on feedback, this is apparent with PoseNet, for which google has released Beta 5, and the possibility that they will keep going with Beta 6, Beta 7 and so on. So I don't know if "waiting for a release version" applies here.
- The current 117.0.0 has binding bugs, so it is not really usable as it's meant to be. So we don't even have the chance to use an old version and wait for the new one. The practical effect is that it is as if it's never been released.

Business based on other platforms/technologies are already delivering products based on these PoseNet betas, meanwhile those of us who invested in Xamarin are waiting idle for a non Beta version that might take months, or even years, based on Google's current trend.

In fact, PoseNet, Beta or not, is the key technology we require for what we want to do. So we're ready to move away from Xamarin just because the lack of MLKit support.

@moljac This is not a rant against you, but against the whole xamarin organization and specially against the people in charge.

**Comment by vpenades** [comment]
Closing this since it's going nowhere.
