### ISSUE TITLE
Awareness Api not compatible with Xamarin Forms.

### ISSUE THREAD

**Issue by Anil86** [xamarin/GooglePlayServicesComponents#45]
### Describe your Issue:
Xamarin.GooglePlayServices.Awareness doesn't work with Xamarin Forms.

### Steps to Reproduce (with link to sample solution if possible):
Create a blank project & use Xamarin.GooglePlayServices.Awareness as described in [Xamarin's blog post](https://blog.xamarin.com/google-awareness-api-for-android-query-and-react-to-signals/).

**Comment by Redth** [comment]
Since there's not a lot of information to go on here, I'm going to assume you're using the latest stable nuget version of Xamarin.Forms (2.3.3.180).  If that is correct then, no, you will not be able to use the newest Play Services with that version of Xamarin.Forms since it's locked to using Android Support 23.3.0, and Play Services 42.1001.0 requires Android Support 25.1.0 or newer.

However, if you opt to use the preview release of Xamarin.Forms (2.3.4.192-pre2) and you make your Android Application Project use Target Framework v7.0 or higher, you will be able to install a newer version of Android Support Libraries, and therefore also Play Services 42.1001.0.

Hope that helps!

**Comment by Anil86** [comment]
@Redth I've tried with following versions of Xamarin Forms (before posting here): 2.3.3.193, 2.3.4.192-pre2 & 2.3.3.180.
None of them are working for me.

**Comment by Redth** [comment]
You need to use 2.3.4.192-pre2 and also set you app projects target framework to android 7.0 or higher before the nuget will install.

**Comment by Anil86** [comment]
It's not working. Thanks for replying.

**Comment by Redth** [comment]
What does "It's not working." mean exactly? Please give more information.

**Comment by Anil86** [comment]
I'm getting the same above error.

Steps I followed:

1. Create a blank Forms project
2. Update Forms to 2.3.4.192-pre2
3. Install Awareness ver. 42.1001.0
4. Add keys in Manifest
5. Initialize Awareness in MainActivity w/ code:

 ```
        private GoogleApiClient client;

        protected override async void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);

            client = await new GoogleApiClient.Builder(this)
                .AddApi(Awareness.Api)
                .AddConnectionCallbacks(() =>
                {
                    Debug.WriteLine($"Connected to Awareness from Forms - Anil Kumar");
                })
                .BuildAndConnectAsync((i) =>
                {
                });

            LoadApplication(new Portable.App());
        }
```


### Build log:
[Build log.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/768210/Build.log.txt)

**Comment by Anil86** [comment]
@Redth As `Xamarin Forms` compatibility with `Xamarin.GooglePlayServices.Awareness` is **still an issue**, please reopen the issue so that it's more visible to community.

**Comment by Redth** [comment]
I don't believe this is related to Google Play Services directly anyway.  I followed your steps and it compiles fine for me.

A couple things to look at/try:
1. What version of Java is installed and being used for your build? (Make sure you're using JDK8)
2. Try increasing the Java heap size in your project settings under Android Build (try 1G)
3. Make sure diagnostic log outputs are enabled in your IDE, this may provide more useful information in the build output.
