### ISSUE TITLE
Xamarin.Firebase.Database.Connection nuget not adding to project 

### ISSUE THREAD

**Issue by vipinmallaya** [xamarin/GooglePlayServicesComponents#46]
### Include any relevant Exception Stack traces, build logs, adb logs:
Could not install package 'Xamarin.Firebase.Database.Connection 42.1001.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by zenasprime** [comment]
Have the same problem with GooglePlayServices.Drive

**Comment by vipinmallaya** [comment]
The work around is by updating the Google play services and Android Repositories. Then Update the Target Platform to Use Android SDK 7.

**Comment by Redth** [comment]
You will need to update your app to compile against Android 7.0 or higher, as the version of support libraries these packages depend on require that. 

You can still target a lower version that your app will run on, it just means you will have to make sure you don't use any API's that don't exist on those lower versions.
