### ISSUE TITLE
[.NET 6] remove usage of System.Json

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/GooglePlayServicesComponents#478]
The System.Json package [will not work in .NET 6](https://github.com/dotnet/designs/pull/222#issuecomment-861617052). (Note this isn't the new System.Text.Json.) System.Json is a deprecated package that they don't have a way to ship an update.

It appears we use this as a dependency of `Xamarin.GooglePlayServices.SafetyNet`:

https://github.com/xamarin/GooglePlayServicesComponents/blob/6c65b4e352410a3f61ecc37be2e810d067398456/source/GooglePlayServicesProject.cshtml#L254-L257

Can we remove System.Json in favor of something else? Thanks!

**Comment by akoeplinger** [comment]
It'd be enough to remove the package for `net6.0` and up if you don't want to change how it works on existing Xamarin.

**Comment by jpobst** [comment]
It looks like our usage of if it is pretty minimal:

https://github.com/xamarin/GooglePlayServicesComponents/blob/main/source/com.google.android.gms/play-services-safetynet/Additions/Additions.cs#L32-L34

**Comment by moljac** [comment]
Tried to remove it, but decided to finish updates first and make it in another PR.

`System.Json.JsonObject.Parse()` must be replaced with `System.Text.Json.JsonDocument.Parse()`

**Comment by akoeplinger** [comment]
This was done with https://github.com/xamarin/GooglePlayServicesComponents/pull/480 right?

**Comment by moljac** [comment]
yes. It was done with #480, but issue and PR were not linked, so this issue was not closed.

Closing it right now.
