### ISSUE TITLE
Xamarin.Google.Android.Play.Core 1.10.0 missing method

### ISSUE THREAD

**Issue by DarkSpikeX** [xamarin/GooglePlayServicesComponents#483]
As per the Android documentation
https://developer.android.com/guide/playcore/in-app-review/kotlin-java#request-review-info

There should be a method called "addOnCompleteListener" but the only one available is AddOnFailureListener

**Comment by wcoder** [comment]
Looks like issue is here:
https://github.com/xamarin/GooglePlayServicesComponents/blob/f7e62317ef8cff396e6d68d4303f19378fdd9689/source/com.google.android.play/core/Transforms/Metadata.xml#L4-L6

Can be replaced to:
```xml
<remove-node path="/api/package[@name='com.google.android.play.core.tasks']/class[@name='NativeOnCompleteListener']" />
<attr path="/api/package[@name='com.google.android.play.core.tasks']/class[@name='Tasks']" name="managedName">Tasks</attr>
```

After that `AddOnCompleteListener` will be available.

@moljac what do you think?

**Comment by wcoder** [comment]
## Workaround
Use another NuGet package: https://www.nuget.org/packages/PlayCore/
