### ISSUE TITLE
javac.exe error clash: onAdLoaded(Object) in AdLoadCallback

### ISSUE THREAD

**Issue by mhdwaelanjo** [xamarin/GooglePlayServicesComponents#487]
### Google Play Services Version 120.2.0
 
I can't build an app when I use the latest version of Xamarin.GooglePlayServices.Ads because I have this error : 
javac.exe error JAVAC0000:  
error: name clash: onAdLoaded(Object) in AdsGoogle_AdMobInterstitial and onAdLoaded(AdT) in AdLoadCallback have the same erasure, yet neither overrides the other
public void onAdLoaded (java.lang.Object p0)
where AdT is a type-variable:
AdT extends Object declared in class AdLoadCallback

OutPut : https://prnt.sc/17f5h38

**Comment by Sebastian1989101** [comment]
I have the same issue. Seems like it is a once more a untested mess from Xamarin. There is a ugly workaround here: https://github.com/xamarin/GooglePlayServicesComponents/issues/425#issuecomment-782789052

**Comment by mhdwaelanjo** [comment]
I fixed the problem.. we can use my libraries :
 
```
 <PackageReference Include="Anjo.Android.GoogleServices.Ads" Version="22.0.0" />
 <PackageReference Include="Anjo.Android.GoogleServices.AdsBase" Version="22.0.0" />
 <PackageReference Include="Anjo.Android.GoogleServices.AdsLite" Version="22.0.0" />
```

Supports fixing the problem of Loading ads using : 
---------------------------------

- Let's rename for Interstitial ads **InterstitialAdLoadCallback** to **AnjoInterstitialLoadCallback**.
- Let's rename for Rewarded ads **RewardedAdLoadCallback** to **AnjoRewardedLoadCallback**.
- Let's rename for App Open Ads **AppOpenAd.AppOpenAdLoadCallback** to **AnjoAppOpenLoadCallback**.
- Let's rename for Rewarded interstitial ads **RewardedInterstitialAdLoadCallback** to **AnjoRewardedInterstitialLoadCallback**.
