### ISSUE TITLE
A lot of compilation and references warnings

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/GooglePlayServicesComponents#49]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android 7.1
I have Xamarin updated to latest released stable.

**Android SDK Tools**                25.2.5 
**Android SDK Platform-tools** 25.0.3
**Android SDK Build-tools**       25.0.2

**Java SDK** in Xamarin settings points to C:\Program Files\Java\jdk.1.8.0_121

**Visual Studio 2015** (Update 3)
**NuGet** 3.5.0

### Operating System & Version (eg: Mac OSX 10.11):
**Windows 10** x64

### Google Play Services Version (eg: 8.4.0):
25.1.0
Same issue with 25.1.1, see last step in "Steps to Reproduce" below.

### Describe your Issue:
I get a lot of compilation and references warnings when adding Xamarin Google Play Services to an Android app just created from template.

### Steps to Reproduce (with link to sample solution if possible):
1. In Visual Studio 2015, create a new Android app. I chose Single-View App template.
2. Just checking, Android project shows
![image](https://cloud.githubusercontent.com/assets/743918/23545986/504c9bf6-0006-11e7-9d30-add42b64947a.png)

3. In NuGet, I select to add Xamarin.GooglePlayServices.Location latest stable (42.1001.0)
![image](https://cloud.githubusercontent.com/assets/743918/23545734/3976056c-0005-11e7-9241-4a57bb50853f.png)

4. Rebuild solution, 13 warnings are shown:
![image](https://cloud.githubusercontent.com/assets/743918/23545824/9495829c-0005-11e7-90d9-543d107ea563.png)

5. I close solution, reopen it and rebuild it. Now I see warnings on references and compilation warnings
![image](https://cloud.githubusercontent.com/assets/743918/23545875/ccb3d57a-0005-11e7-88b1-7e332a2c3dc3.png)
![image](https://cloud.githubusercontent.com/assets/743918/23545909/f330a714-0005-11e7-87e2-88fcf5898240.png)

6. I tried to remove `obj` and `bin` directories and rebuild solution, same result.

7. I updated to 25.1.1 
![image](https://cloud.githubusercontent.com/assets/743918/23548740/a6140410-0011-11e7-8ebf-b8bc132cfebc.png)

  Some warnings are gone (regarding constant) but there's still same compilation and references warnings: 
![image](https://cloud.githubusercontent.com/assets/743918/23548801/e460fd36-0011-11e7-8205-d62452ed8b18.png)
![image](https://cloud.githubusercontent.com/assets/743918/23548823/f8fa48ba-0011-11e7-8c01-4b0f912e6c20.png)

The same issue is reproducible in Xamarin Studio. I also tried it on another PC, same configuration, same issues.

**Comment by Redth** [comment]
Can you try unzipping this file and referencing the .dll

[Xamarin.Android.Support.Annotations.dll.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/869246/Xamarin.Android.Support.Annotations.dll.zip)
 in your project?  It should clear up the warnings.

**Comment by Redth** [comment]
Also try Xamarin.Build.Download 0.4.3 or higher.

**Comment by andreinitescu** [comment]
The yellow warnings in references disappeared, but there are still a lot of compilation warnings.

`JAVAC : warning : unknown enum constant Scope.LIBRARY_GROUP`

Many people have been reporting it.
https://bugzilla.xamarin.com/show_bug.cgi?id=52944
https://forums.xamarin.com/discussion/86702/upgrading-from-java-1-7-to-1-8-causes-javac-warning-unknown-enum-constant-scope-library-group

**Comment by Redth** [comment]
Please try adding this package to your project, the JAVAC warnings should go away: https://www.nuget.org/packages/Xamarin.Android.Support.Annotations/25.3.1-beta1

**Comment by Redth** [comment]
The Xamarin.Android.Support.Annotations library will be part of the dependency chain for Android Support library packages as of 25.3.1.  I'm closing this issue here, as it's not really a Google Play Services issue, and it will be resolved in newer support library versions going forward.
