### ISSUE TITLE
Not able to connect to Play services when using Awareness API.

### ISSUE THREAD

**Issue by Anil86** [xamarin/GooglePlayServicesComponents#51]
### IDE:
Visual Studio 2017

### Xamarin.Android Version:
7.1.041

### Operating System & Version:
Lineage OS 14.1 _(custom Android ROM equivalent to Android 7.1.1)_
Win 10 Pro 14393

### Google Play Services Version:
Google Play services 10.2.99
Xamarin.GooglePlayServices.Awareness 42.1001.0

### Xamarin Forms version:
2.3.4.212-pre4

### Describe your Issue:
Code written after initializing GoogleApiClient.Builder() inside OnCreate() doesn't run.

```
public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
{
        private GoogleApiClient _client;

        protected override async void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            LoadApplication(new App());

            _client = await new GoogleApiClient.Builder(this)
                            .AddApi(Awareness.Api)
                            .AddConnectionCallbacks(() =>
                            {
                                Debug.WriteLine($"******########Connected to Awareness from Forms. Even this is not printed******########");

                            })
                            .BuildAndConnectAsync((i) =>
                            {
                                Debug.WriteLine($"******########Connected to Awareness from Forms. Even this is not printed******########");

                            });


                  Debug.WriteLine("Testing\nTesting\nTesting\nThis line never executes");   // Set breakpoint
       }
}
```

Stackoverflow answer suggests that [Awareness api doesn't work on custom Android ROMs.](http://stackoverflow.com/a/38587573/4038979)

### Steps to Reproduce (with link to sample solution if possible):
1. Copy above code in MainActivity
2. Set breakpoint on line: `Debug.WriteLine("Testing\nTesting\nTesting\nThis line never executes");`
3. Breakpoint never reaches.

**Comment by Anil86** [comment]
There is a **bug** in **`GoogleApiClient.Builder.BuildAndConnectAsync();`**

After referring to [Activity Recognition sample](https://developer.xamarin.com/samples/monodroid/google-services/Location/ActivityRecognition/), I changed `BuildAndConnectAsync()`  to   `Build()` & it's working.

```
  var _client = GoogleApiClient.Builder.Build();
  _client.Connect();
```

**Comment by halukmy** [comment]
@Anil86  anyupdate?

**Comment by halukmy** [comment]
@Redth  can you share working awareness api?

**Comment by Redth** [comment]
For now, use .Build() instead...

I'm going to open a new issue about problems with BuildAndConnectAsync...

**Comment by halukmy** [comment]
@Redth i got serious problem with awarness api,

i try everyway but not possbile connect awarness api ..

**Comment by halukmy** [comment]
@Redth

**Comment by halukmy** [comment]
@Redth  i just create issue @jamesmontemagno  on his awareness api page but not update guess

**Comment by Redth** [comment]
@halukmy please provide more info.... do you get any exceptions? If so, what is the stack trace?  Can you provide an ADB debug log?

**Comment by Redth** [comment]
This code is working fine for me:

```csharp
using Android.App;
using Android.Widget;
using Android.OS;
using Android.Support.V7.App;
using Android.Gms.Common.Apis;
using Android.Gms.Extensions;
using Android.Gms.Awareness;

namespace GpsAsyncTest
{
	[Activity(Label = "GpsAsyncTest", MainLauncher = true, Icon = "@mipmap/icon", Theme="@style/Theme.AppCompat")]
	public class MainActivity : AppCompatActivity
	{
		GoogleApiClient googleApi;
		
		protected async override void OnCreate(Bundle savedInstanceState)
		{
			base.OnCreate(savedInstanceState);

			// Set our view from the "main" layout resource
			SetContentView(Resource.Layout.Main);

			googleApi = await new GoogleApiClient.Builder(this)
				   .EnableAutoManage(this, (unresolvedConnectionResult) =>
				   {
						// Couldn't connect
				   })
				   .AddApi(Android.Gms.Location.LocationServices.API)
				   .BuildAndConnectAsync((obj) =>
				   {
						// paused
				   });

			var button = FindViewById<Button>(Resource.Id.myButton);
			button.Click += async (sender, e) =>
			{
				var da = await Awareness.SnapshotApi.GetDetectedActivityAsync(googleApi);

				var probableActivity = da?.ActivityRecognitionResult?.MostProbableActivity;

				if (probableActivity != null)
					Android.Util.Log.Debug("AWARENESS", "Type: {0}, Confidence: {1}", probableActivity.Confidence, probableActivity.Type);
			};
		}
	}
}
```

**Comment by Redth** [comment]
Closing this issue, I do not think there is a problem with the binding.  Please comment back if you have new findings.

**Comment by Anil86** [comment]
I've almost the same setup. One of the difference is that I'm using **Xamarin Forms**.
