### ISSUE TITLE
GoogleAuthUtil removed from Xamarin.GooglePlayServices.Auth.Base 117.1

### ISSUE THREAD

**Issue by jpobst** [xamarin/GooglePlayServicesComponents#532]
Context: https://developercommunity.visualstudio.com/t/Visual-Studio-Android-GooglePlayServices/1559747

Xamarin.GooglePlayServices.Auth.Base `117.0.0` contains the type `Android.Gms.Auth.GoogleAuthUtil`:
https://www.fuget.org/packages/Xamarin.GooglePlayServices.Auth.Base/117.0.0/lib/monoandroid90/Xamarin.GooglePlayServices.Auth.Base.dll/Android.Gms.Auth/GoogleAuthUtil

However this type is missing from `117.1+`:
https://www.fuget.org/packages/Xamarin.GooglePlayServices.Auth.Base/117.1.0

This type does not look like it should have been removed:
![image](https://user-images.githubusercontent.com/179295/138726051-21342c3c-01fc-4e13-a7d4-3c87084225f2.png)

**Comment by VanjaPopovic** [comment]
Any updates on this?

**Comment by danwinp** [comment]
I have tried using the Xamarin.GooglePlayServices.Auth.Base 117.1.4.3 nuget package but the GoogleAuthUtil still does not exists in this version.
