### ISSUE TITLE
Unable to recognize single digit characters from receipts

### ISSUE THREAD

**Issue by manan-itsol** [xamarin/GooglePlayServicesComponents#566]
Xamarin.Forms Version: 5.0.0.2125

Xamarin.Firebase.ML.Vision Version: 124.1.0

I'm using `TextRecognizer` to extract text from receipts in Xamarin.Android, the issue I noticed here is, it's not recognizing single-digit characters from receipts, reset of the data (numbers with at least 2 digits) are captured perfectly fine. Can you please help me out with that?

**Comment by moljac** [comment]
@manan-itsol 

Thanks for the feedback.

Could you provide repro sample from receipt, please?

**Comment by manan-itsol** [comment]
@moljac 

Thanks for your reply. First of all really sorry to respond you back very late. Actually caught up in an urgent stuff and couldn't manage time to prepare sample repro on time.

Here's the sample repository to show you the issue that I'm facing. Please navigate to 'Results' folder to see the results. I underlined the numbers those were not captured by Text Recognizer.
https://github.com/manan-itsol/MlKitTextRecognitionSample

Thanks again for your support.

**Comment by manan-itsol** [comment]
Hi @moljac , have you got a chance to look at the sample repro? Can you please help me out with the issue?

**Comment by moljac** [comment]
@manan-itsol 

>have you got a chance to look at the sample repro? 

I'm sorry, but not yet.

> Can you please help me out with the issue?

I will do my best, but I'm not ML expert.

**Comment by moljac** [comment]
@manan-itsol 

please correct: it is not MLKit, but you are using firebase ml 

https://firebase.google.com/products/ml

which is different from MLKit

**Comment by moljac** [comment]
from what I see your model DOES recognize text, but has issues with single digits. So, no crashes or runtime issues which would lead to Xamarin problems.

I think you need to use different model (retrain existing with new data and corrections)
