### ISSUE TITLE
Status of MLKit.Pose-Detection

### ISSUE THREAD

**Issue by vpenades** [xamarin/GooglePlayServicesComponents#570]
First of all, I am fully aware that there's a policy of not binding to beta APIs,

But then, it seems apparent that Google is not planning to publish a non-beta version of pose-detection any time soon:

https://maven.google.com/web/index.html?q=pose-de#com.google.mlkit:pose-detection

As we can see, Google has jumped from 17.0.1-beta7 to 18.0.0-beta3, without releasing any 17.0.1 final.

And nothing prevents Google from keep doing this for the next releases of 18, as it seems it's already happening.

In the meantime the published Xamarin.Google.MLKit.PoseDetection 117.0.0.3 remains unusable due to incorrect bindings that were never fixed.

So, what's the plan for Pose-Detection?  could it be possible to drop the restriction for betas in this case?

**Comment by moljac** [comment]
published

https://www.nuget.org/packages?q=Xamarin.GooglePlayServices.MLKit.PoseDetection

**Comment by moljac** [comment]
closing this issue
