### ISSUE TITLE
Missing ExpandedControllerActivity Under Android.Gms.Cast.Framework.Media.Widget

### ISSUE THREAD

**Issue by sathukorale** [xamarin/GooglePlayServicesComponents#58]
**Xamarin.Android Version :** 7.0.2.42
**Operating System & Version :** Windows 7 x64, Windows 10 x64
**Google Play Services Version :** 42.1001.0/10.0.1

**Issue :** 
I am trying to add google cast support for my app, and I am following the guide on [Google Cast Documentation](https://developers.google.com/cast/docs/android_sender_integrate) to do this. So one of the steps is to create an Activity that extends **ExtendedControllerActivity**. So, from what I can guess, this class should fall under **Android.Gms.Cast.Framework.Media.Widget** namespace. But the only classes I can see are the **ControlButtonsContainer** and **MiniControllerFragment**. 

I am very much a noob when it comes to Xamarin Java Bindings (may a couple of minutes old). So decided to checkout this code (master @ f1da9ae508bd032f9d816e9aa82e1038148ad7ad) and try building my self, and discovered that the generated code is still missing, the **ExpandedControllerActivity** class. So I added the following line : 
<pre><code>&lt;attr path="/api/package[@name='com.google.android.gms.cast.framework.media.widget']/class[@name=ExpandedControllerActivity]" name="managedName">ExpandedControllerActivity&lt;/attr></code></pre> 
to the **cast-framework\source\Transforms\Metadata.xml**. But the generated code is still missing the said file, but I am getting the following warning (there are like 1000 warnings, but filtered this one out) :
<pre><code>D:\GooglePlayServicesComponents-master\cast-framework\source\BINDINGSGENERATOR: Warning BG8604: top ancestor ExpandedControllerActivity not found for nested type Android.Gms.Cast.Framework.Media.Widget.ExpandedControllerActivity.1. (BG8604) (Cast.Framework)
</code></pre>
I am not sure, why this happens or whether further more experimenting can fix this issue, but I would love it, if you guys can look into this issue as soon as possible. Not trying to pressure you guys or anything, its just that I need to implement cast into the app, so that I can test it through out the next week.

**Comment by sathukorale** [comment]
Referencing **Xamarin.Android.Support.v7.AppCompat** and updating the **cast-framework\source\Transforms\Metadata.xml** seems to generate the **ExtendedControllerActivity** class. Not sure whether this is the right fix though.

**Comment by sathukorale** [comment]
@Redth It would be great if you could include this fix in any upcoming release (the earliest would be the best)

**Comment by Redth** [comment]
This is fixed in the 42.1021.1 release now available on NuGet.  Thanks!
