### ISSUE TITLE
update Google Mobile Ads-SDK to 20.4.0 needed

### ISSUE THREAD

**Issue by uwe-neuronation** [xamarin/GooglePlayServicesComponents#584]
From what I see on Google Mobile Ads-SDK documentation an update to at least version 20.4.0 would be needed.

> **Update your app for advertising ID permissions**
Apps updating their target API level to 31 (Android 12) will need to declare a [Google Play services normal permission](https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient.Info) in the Android manifest file in order to use the advertising ID. For apps that do not declare this permission and target Android 12, the advertising ID will automatically be removed and replaced with a string of zeros. 
> You can update your app to [GMA SDK 20.4.0+](https://developers.google.com/admob/android/sdk) , which will automatically have the permission declared. If you’re using [GMA SDK 20.4.0+](https://developers.google.com/admob/android/sdk) , no further action is required to continue using the advertising ID. 
> To learn more about the new permission, including how to disable it, refer to the [Play Console Help Center](https://support.google.com/googleplay/android-developer/answer/6048248).

See: https://support.google.com/admob/answer/11402075

current nuget is 120.3.0.3 (20.3.0) https://www.nuget.org/packages/Xamarin.GooglePlayServices.Ads/

Deadline is close 1st of April:
`Starting in late 2021, when a user opts out of interest-based advertising or ads personalization, the advertising identifier will not be available. You will receive a string of zeros in place of the identifier.
This update will expand to all apps running on Android phones, Tablets, and Android TV that support Google Play on April 1, 2022.`
See: https://support.google.com/googleplay/android-developer/answer/6048248?hl=en

What's the plan? Will there be a release soon. It's only two weeks left. Possible workarounds?
Please help!

**Comment by moljac** [comment]
google introduced mandatory Monodroid12.0 tfm

https://github.com/xamarin/AndroidX/issues/444

I tried to catch up GPS-FB-MLKit without bumping to Monodroid12.0, but I was not able to.

if you check following PR

https://github.com/xamarin/GooglePlayServicesComponents/pull/575

you will see that 20.5.0 is prepared

https://github.com/xamarin/GooglePlayServicesComponents/blob/mu-20220215/config.json#L101-L106

I hope I will be able to publish those soon enough

**Comment by mhdwaelanjo** [comment]
we can use my libraries :
 
```
 <PackageReference Include="Anjo.Android.GoogleServices.Ads" Version="22.0.0" />
 <PackageReference Include="Anjo.Android.GoogleServices.AdsBase" Version="22.0.0" />
 <PackageReference Include="Anjo.Android.GoogleServices.AdsLite" Version="22.0.0" />
```

Supports fixing the problem of Loading ads using : 
---------------------------------

- Let's rename for Interstitial ads **InterstitialAdLoadCallback** to **AnjoInterstitialLoadCallback**.
- Let's rename for Rewarded ads **RewardedAdLoadCallback** to **AnjoRewardedLoadCallback**.
- Let's rename for App Open Ads **AppOpenAd.AppOpenAdLoadCallback** to **AnjoAppOpenLoadCallback**.
- Let's rename for Rewarded interstitial ads **RewardedInterstitialAdLoadCallback** to **AnjoRewardedInterstitialLoadCallback**.
