### ISSUE TITLE
V"2019/2022 - Xamarin.GooglePlayServices - Update destroy project

### ISSUE THREAD

**Issue by harrypotter06** [xamarin/GooglePlayServicesComponents#586]
I need update some Xamarin.GooglePlayServices - Nugets (see screenshot) on last Version.
The Project has the API level 30/31 (same issue) 
After Update, all Objects(.dll-files) with "Xamarin....." are lost on "Objectexplorer"

I reproduce on VS2019 and VS 2022 

![GooglePlayServices-Nugets](https://user-images.githubusercontent.com/11202949/158448888-f08bf06b-d800-481b-abf7-822a652373e9.JPG)

**Comment by moljac** [comment]
This is most likely Visual Studio installation issue.

Open a new issue if problem persists, please.
