### ISSUE TITLE
Add Google Play Services Appset binding

### ISSUE THREAD

**Issue by entdark** [xamarin/GooglePlayServicesComponents#587]
Some new libraries depend on that component.
Link: https://maven.google.com/web/index.html#com.google.android.gms:play-services-appset:16.0.2

**Comment by moljac** [comment]
@entdark Thanks for feedback. Appreciated.

> Some new libraries depend on that component.

Please elaborate. I need to elaborate efforts. Thanks

**Comment by moljac** [comment]
Prepared

https://github.com/xamarin/GooglePlayServicesComponents/blob/mu-20220215/config.json#L164-L171

in 

https://github.com/xamarin/GooglePlayServicesComponents/pull/575

**Comment by entdark** [comment]
> Please elaborate. I need to elaborate efforts. Thanks

For example, this:
https://appmetrica.yandex.ru/docs/mobile-sdk-dg/concepts/android-dependencies.html

**Comment by moljac** [comment]
published

https://www.nuget.org/packages/Xamarin.GooglePlayServices.AppSet/

closing this issue
