### ISSUE TITLE
Xamarin.GooglePlayServices.Ads.Lite needs newer Xamarin.AndroidX.Work.Runtime dependency

### ISSUE THREAD

**Issue by wouterst79** [xamarin/GooglePlayServicesComponents#592]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Xamarin.Android 12.0.0.3 (built through macos-latest in Azure)

### Description

As I'm upgrading my Xamarin.Android app from Android 10 to Android 12 (and with significant packages, build pipeline and other updates), somewhere between 5% and 10% of the runs in the pre-launch report crash with the below stack trace. 

Changing the GC to use the tarjan bridge appeared to have fixed the problem however a few days after rolling out to the open beta, I'm getting reports of the same crash. 

I'm not able to reproduce the issue locally.

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0

backtrace:
  #00  pc 0000000000051010  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #00  pc 00000000000200f8  /data/app/~~#==/split_config.arm64_v8a.apk!libmono-android.release.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144)
  #00  pc 000000000028b6f8  /data/app/~~#==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (monoeg_g_logv_nofree+192)

```

Open beta track:
![image](https://user-images.githubusercontent.com/6962440/160651673-f5116c16-bcfa-4163-93e9-f42ed0d92f3a.png)

Before changing the GC bridge (different roll-out audience):
![image](https://user-images.githubusercontent.com/6962440/160651981-f5e00ce5-da8a-4d7b-b17f-a306d7730891.png)

### Steps to Reproduce

Build app in release mode through macos-latest on Azure devops.
Wait for the pre-launch report - sometimes it has these crashes.

### Did you find any workaround?

No

### Relevant log output

```shell
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.dailybits.fooddiary8preview <<<

backtrace:
  #00  pc 000000000008be20  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168)
  #00  pc 00000000000200f8  /data/app/~~w2OKOymcEnwjVvDFPL5iIw==/com.dailybits.fooddiary8preview-DyoFrHc4yjtMnNEmN5825A==/split_config.arm64_v8a.apk!libmono-android.release.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144)
  #00  pc 000000000028b6f8  /data/app/~~w2OKOymcEnwjVvDFPL5iIw==/com.dailybits.fooddiary8preview-DyoFrHc4yjtMnNEmN5825A==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (monoeg_g_logv_nofree+192)




*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.dailybits.foodjournal <<<

backtrace:
  #00  pc 000000000008be20  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168)
  #00  pc 00000000000200f8  /data/app/~~9fJdkrZD2aYtpWLh6d9qoQ==/com.dailybits.foodjournal-I8tcbI3wfWMx_k8bOT4HjA==/split_config.arm64_v8a.apk!libmono-android.release.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144)
  #00  pc 000000000028b6f8  /data/app/~~9fJdkrZD2aYtpWLh6d9qoQ==/com.dailybits.foodjournal-I8tcbI3wfWMx_k8bOT4HjA==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (monoeg_g_logv_nofree+192)
```

**Comment by moljac** [comment]
https://github.com/xamarin/GooglePlayServicesComponents/blob/mu-20220215/config.json#L2053-L2060

try adding

```xml
    <ItemGroup>
        <AndroidLibrary Include="androidx.work.work-runtime-2.7.1.aar" Bind="false" />
    </ItemGroup>
```

this might help until the packages are released.
