### ISSUE TITLE
After updating i can no longer use GoogleAuthUtil

### ISSUE THREAD

**Issue by Eversor** [xamarin/GooglePlayServicesComponents#60]
### Xamarin.Android Version (eg: 6.0):
 7.2.0.7 (Xamarin Studio Community)

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 Version	10.0.14393 Build 14393

### Google Play Services Version (eg: 8.4.0):
Nuget 42.1021

### Describe your Issue:
Error CS0234: The type or namespace name 'GoogleAuthUtil' does not exist in the namespace 'Android.Gms.Auth' (are you missing an assembly reference?) (CS0234)

**Comment by Eversor** [comment]
Seems like i had to remove all google services references and add them through the Xamarin Studio Wizard. Noticed the referenced packages were different : they now look like this 

![immagine](https://cloud.githubusercontent.com/assets/733699/25845611/d715d3aa-34ae-11e7-8cf2-d1f5425ddb81.png)

**Comment by Redth** [comment]
Thanks, we will be releasing a 42.1021.1 version to address this very shortly.

**Comment by Redth** [comment]
This is fixed in the 42.1021.1 release now available on NuGet.  Thanks!
