### ISSUE TITLE
Build fails when install Xamarin.GooglePlayServices.Ads.Lite in .NET MAUI RC1

### ISSUE THREAD

**Issue by nacompllo** [xamarin/GooglePlayServicesComponents#603]
### Android application type:
Android for .NET (net6.0-android)

### Google Play Services Version

*   Xamarin.GooglePlayServices.Ads.Lite 120.3.0.5

### Describe your Issue

After installing Xamarin.GooglePlayServices.Ads.Lite 120.3.0.5 in a .NET MAUI (RC1) project and building the project I get the following errors:

`1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(8,37): javac.exe error JAVAC0000:  error: package com.google.android.ump.ConsentForm does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(8,37): javac.exe error JAVAC0000: 		com.google.android.ump.ConsentForm.OnConsentFormDismissedListener
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(8,37): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(28,60): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(28,60): javac.exe error JAVAC0000: 	public void onConsentFormDismissed (com.google.android.ump.FormError p0)
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(28,60): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(33,70): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(33,70): javac.exe error JAVAC0000: 	private native void n_onConsentFormDismissed (com.google.android.ump.FormError p0);
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(33,70): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(8,44): javac.exe error JAVAC0000:  error: package com.google.android.ump.ConsentInformation does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(8,44): javac.exe error JAVAC0000: 		com.google.android.ump.ConsentInformation.OnConsentInfoUpdateFailureListener
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(8,44): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(28,64): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(28,64): javac.exe error JAVAC0000: 	public void onConsentInfoUpdateFailure (com.google.android.ump.FormError p0)
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(28,64): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(33,74): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(33,74): javac.exe error JAVAC0000: 	private native void n_onConsentInfoUpdateFailure (com.google.android.ump.FormError p0);
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(33,74): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateSuccessListenerImplementor.java(8,44): javac.exe error JAVAC0000:  error: package com.google.android.ump.ConsentInformation does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateSuccessListenerImplementor.java(8,44): javac.exe error JAVAC0000: 		com.google.android.ump.ConsentInformation.OnConsentInfoUpdateSuccessListener
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateSuccessListenerImplementor.java(8,44): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(8,47): javac.exe error JAVAC0000:  error: package com.google.android.ump.UserMessagingPlatform does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(8,47): javac.exe error JAVAC0000: 		com.google.android.ump.UserMessagingPlatform.OnConsentFormLoadFailureListener
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(8,47): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(28,62): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(28,62): javac.exe error JAVAC0000: 	public void onConsentFormLoadFailure (com.google.android.ump.FormError p0)
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(28,62): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(33,72): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(33,72): javac.exe error JAVAC0000: 	private native void n_onConsentFormLoadFailure (com.google.android.ump.FormError p0);
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(33,72): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(8,47): javac.exe error JAVAC0000:  error: package com.google.android.ump.UserMessagingPlatform does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(8,47): javac.exe error JAVAC0000: 		com.google.android.ump.UserMessagingPlatform.OnConsentFormLoadSuccessListener
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(8,47): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(28,62): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(28,62): javac.exe error JAVAC0000: 	public void onConsentFormLoadSuccess (com.google.android.ump.ConsentForm p0)
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(28,62): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(33,72): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(33,72): javac.exe error JAVAC0000: 	private native void n_onConsentFormLoadSuccess (com.google.android.ump.ConsentForm p0);
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(33,72): javac.exe error JAVAC0000`

### Minimal Repro Code Sample

I have created a repository on GitHub to be able to reproduce the errors:
https://github.com/nacompllo/AdsLiteIssue

### Steps to Reproduce:
Download the attached repository and compile the project. Or create a new .NET Maui project and install the Xamarin.GooglePlayServices.Ads.Lite 120.3.0.5 nuget.

**Comment by dtaylorus** [comment]
I get the same errors but with a plain net6.0-android project (no MAUI) and Xamarin.GooglePlayServices.Ads package.

I tried adding the Xamarin.Google.UserMessagingPlatform package but still get the same compile errors.

**Comment by dtaylorus** [comment]
I was able to work around this issue by adding the following to my csproj file:

```
    <ItemGroup>
        <AndroidLibrary Include="Dependencies\user-messaging-platform-2.0.0.aar" Bind="false" />
    </ItemGroup>
```

I got the file `user-messaging-platform-2.0.0.aar` from the Maven repository using gradle, but you could probably download it manually.

Unfortunately, the app crashes at runtime now with `Failed resolution of: Lcom/google/android/datatransport/Transformer` but that's a separate problem.

**Comment by moljac** [comment]
`Xamarin.Google.UserMessagingPlatform` 2.0.0 is bound in

https://github.com/xamarin/GooglePlayServicesComponents/pull/575

https://github.com/xamarin/GooglePlayServicesComponents/blob/mu-20220215/config.json#L549-L555

**Comment by nacompllo** [comment]
I get the same errors when installing Xamarin.Google.UserMessagingPlatform and building the project:

```
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(8,37): javac.exe error JAVAC0000:  error: package com.google.android.ump.ConsentForm does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(8,37): javac.exe error JAVAC0000: 		com.google.android.ump.ConsentForm.OnConsentFormDismissedListener
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(8,37): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(28,60): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(28,60): javac.exe error JAVAC0000: 	public void onConsentFormDismissed (com.google.android.ump.FormError p0)
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(28,60): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(33,70): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(33,70): javac.exe error JAVAC0000: 	private native void n_onConsentFormDismissed (com.google.android.ump.FormError p0);
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentForm_OnConsentFormDismissedListenerImplementor.java(33,70): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(8,44): javac.exe error JAVAC0000:  error: package com.google.android.ump.ConsentInformation does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(8,44): javac.exe error JAVAC0000: 		com.google.android.ump.ConsentInformation.OnConsentInfoUpdateFailureListener
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(8,44): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(28,64): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(28,64): javac.exe error JAVAC0000: 	public void onConsentInfoUpdateFailure (com.google.android.ump.FormError p0)
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(28,64): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(33,74): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(33,74): javac.exe error JAVAC0000: 	private native void n_onConsentInfoUpdateFailure (com.google.android.ump.FormError p0);
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateFailureListenerImplementor.java(33,74): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateSuccessListenerImplementor.java(8,44): javac.exe error JAVAC0000:  error: package com.google.android.ump.ConsentInformation does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateSuccessListenerImplementor.java(8,44): javac.exe error JAVAC0000: 		com.google.android.ump.ConsentInformation.OnConsentInfoUpdateSuccessListener
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\ConsentInformation_OnConsentInfoUpdateSuccessListenerImplementor.java(8,44): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(8,47): javac.exe error JAVAC0000:  error: package com.google.android.ump.UserMessagingPlatform does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(8,47): javac.exe error JAVAC0000: 		com.google.android.ump.UserMessagingPlatform.OnConsentFormLoadFailureListener
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(8,47): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(28,62): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(28,62): javac.exe error JAVAC0000: 	public void onConsentFormLoadFailure (com.google.android.ump.FormError p0)
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(28,62): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(33,72): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(33,72): javac.exe error JAVAC0000: 	private native void n_onConsentFormLoadFailure (com.google.android.ump.FormError p0);
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadFailureListenerImplementor.java(33,72): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(8,47): javac.exe error JAVAC0000:  error: package com.google.android.ump.UserMessagingPlatform does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(8,47): javac.exe error JAVAC0000: 		com.google.android.ump.UserMessagingPlatform.OnConsentFormLoadSuccessListener
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(8,47): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(28,62): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(28,62): javac.exe error JAVAC0000: 	public void onConsentFormLoadSuccess (com.google.android.ump.ConsentForm p0)
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(28,62): javac.exe error JAVAC0000:
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(33,72): javac.exe error JAVAC0000:  error: package com.google.android.ump does not exist
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(33,72): javac.exe error JAVAC0000: 	private native void n_onConsentFormLoadSuccess (com.google.android.ump.ConsentForm p0);
1>obj\Debug\net6.0-android\android\src\mono\com\google\android\ump\UserMessagingPlatform_OnConsentFormLoadSuccessListenerImplementor.java(33,72): javac.exe error JAVAC0000
```

**Comment by tipa** [comment]
Hitting the same issue, would appreciate a fix :)

**Comment by tipa** [comment]
> I was able to work around this issue by adding the following to my csproj file:
> 
> ```
>     <ItemGroup>
>         <AndroidLibrary Include="Dependencies\user-messaging-platform-2.0.0.aar" Bind="false" />
>     </ItemGroup>
> ```
> 
> I got the file `user-messaging-platform-2.0.0.aar` from the Maven repository using gradle, but you could probably download it manually.
> 
> Unfortunately, the app crashes at runtime now with `Failed resolution of: Lcom/google/android/datatransport/Transformer` but that's a separate problem.

This is not working for me unfortunately, I still get these build errors:
![image](https://user-images.githubusercontent.com/2863198/175781885-45f767a5-c31c-4bc0-90e1-205c5ae0d5b6.png)

**Comment by moljac** [comment]
Try updating to latest package versions and please report here if the new packages fixed the issue. 

Thanks.

**Comment by tipa** [comment]
It appears to have fixed the issue, thank you!

**Comment by moljac** [comment]
> It appears to have fixed the issue, thank you!

Thanks to other team members. BuildActions caused issues with packaging for `net6`.
