### ISSUE TITLE
[Request] Add an IsRunningInTestLab method to detect if app is running in test lab/Google Play pre-launch test environment 

### ISSUE THREAD

**Issue by mikequ-taggysoft** [xamarin/GooglePlayServicesComponents#610]
The React Native Firebase SDK has an `.isRunningInTestLab` method that can be used to detect if the app is running in a test lab or Google Play Console pre-launch test environment.

I can't seem to find an equivalent helper method in the Xamarin SDK. It can be quite handy to have this check available so that we can filter out some unnecessary/unwanted actions that can be triggered in these test environments.

**Comment by moljac** [comment]
Hi

Thanks for the feedback. 

is this only for Firebase? Maybe setting environment variable in test lab setup and reading it from Xamarin.

I don't think that will be implemented in Xamarin soon.
