### ISSUE TITLE
Bind Play Integrity API: 'com.google.android.play:integrity'

### ISSUE THREAD

**Issue by shuaga** [xamarin/GooglePlayServicesComponents#613]
Link to the Android docs:
[Play Integrity API](https://developer.android.com/google/play/integrity/overview)

**Comment by rkops-bd** [comment]
Or will this be included in for the MAUI releases?

**Comment by moljac** [comment]
> Or will this be included in for the MAUI releases?

Hi. Why would that be important/significant for MAUI?

I am not familiar with the library. 

Just ask yourself if there is equivalent iOS library. That would make it candidate for MAUI and Xamarin.Forms.

**Comment by SaqibS** [comment]
Hi, we're blocked by this missing binding. Any commitment from the team to take this on?

**Comment by lukeid123** [comment]
Attempted to create a binding too, but found that AppCheck relies on a newer version of firebase-common (20.1.1 latest as I write this), where Xamain.Firebase.Common only goes up to 20.0.0 as a NuGet package. I found that the difference is a new HeartBeatController.java class in Common in used by AppCheck

**Comment by moljac** [comment]
https://www.nuget.org/packages/Xamarin.Google.Android.Play.Integrity/

**Comment by moljac** [comment]
I know version 1.0.0

but check what google does from version 1.0.0 to 1.1.0 the license changed.

Fun? huh?

**Comment by lukeid123** [comment]
> https://www.nuget.org/packages/Xamarin.Google.Android.Play.Integrity/

I spend all day trying to get it to work, then you come along with a NuGet package 🤣 Thanks!

**Comment by moljac** [comment]
even worse google changed version for 1.0.0 from Apache to  Play Integrity API Terms of Service

**Comment by moljac** [comment]
closing this issue
