### ISSUE TITLE
Places compatibility library deprecation

### ISSUE THREAD

**Issue by garie** [xamarin/GooglePlayServicesComponents#615]
`com.google.android.gms:play-services-places` is deprecated as of March 31, 2022. Google recommends that you migrate to the Places SDK for Android. See [docs](https://developers.google.com/maps/documentation/places/android-sdk/client-migration). 

You can only install either the Places SDK for Android (`com.google.android.libraries.places:places`) or the compatibility library (`com.google.android.libraries.places:places-compat`), but not both. Release notes for the Places SDK can be found [here](https://developers.google.cn/maps/documentation/places/android-sdk/releases).

I'm not sure if `Xamarin.GooglePlayServices.Places` nuget package should be deprecated and the Places SDK added as a new package, or if the Places SDK should replace `Xamarin.GooglePlayServices.Places` as a major version change. The versioning for the new package does not match the old one as the new one is on version `2.6.0` and the old is `17.0.0`.

**Comment by moljac** [comment]
if approved there will be new nuget package.

**Comment by moljac** [comment]
* old

  * `com.google.android.gms:play-services-places`

  * https://maven.google.com/web/index.html?q=places#com.google.android.gms:play-services-places

* new 

  * `com.google.android.libraries.places:places-compat`

    * https://maven.google.com/web/index.html?q=places-compat#com.google.android.libraries.places:places-compat

**Comment by moljac** [comment]
published

https://www.nuget.org/packages?q=com.google.android.libraries.places

closing this issue
