### ISSUE TITLE
Xamarin forms firestore support

### ISSUE THREAD

**Issue by ohumidk** [xamarin/GooglePlayServicesComponents#616]
Not sure where to post this but is there support to use firestore with the latest xamarin forms? If so where can I find a sample or documentation?

**Comment by moljac** [comment]
I wish I would have some time to work on samples and docs. At least to inspect and learn new APIs.

So, I guess you are out of luck. At least for a while.

**Comment by moljac** [comment]
Closing this one. Lack of resources (time) to work on samples.
