### ISSUE TITLE
Invalid item ID image-1.0.0-beta1

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/GooglePlayServicesComponents#621]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Invalid-item-ID-image-100-beta1/10040118)._

---
[severity:I'm unable to use this version]
I am unable to build this project because of an error when building.

Invalid item ID image-1.0.0-beta1

This happened after I added the following Nuget package:

Xamarin.Google.Android.ODML.Image 1.0.0.0-beta1

After the error a considerable number of errors then show relating to all packages / dlls.

I am unable to establish what causes the error from the build output, even in verbose mode.

This is the example Xamarin application for CameraX which has been updated to latest versions of Nugets as appropriate. 

A repro is available at:

[https://github.com/NetworkGithub/CSSClientAppsXamarinSampleCode2](https://github.com/NetworkGithub/CSSClientAppsXamarinSampleCode2)

---
#### Feedback Bot on 5/12/2022, 02:04 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by moljac** [comment]
> I am unable to establish what causes the error from the build output, even in verbose mode.

I think it is XBD and preview version parsing/checks, but I am not sure.

> A repro is available at:
> 
> https://github.com/NetworkGithub/CSSClientAppsXamarinSampleCode2

thanks for the repo. Will take a look.

**Comment by moljac** [comment]
try updating (explicitly adding reference) to projects:

```
<PackageReference Include="Xamarin.Build.Download" Version="0.11.3" />
```

And please report if this works.

Thanks

**Comment by moljac** [comment]
Closing this one due to lack of feedback. 
If the issue persists open a new issue, please.
