### ISSUE TITLE
Please update mlkit barcode version - com.google.mlkit:barcode-scanning:17.0.2

### ISSUE THREAD

**Issue by dineshkandan** [xamarin/GooglePlayServicesComponents#624]
new version have  been released  
implementation 'com.google.mlkit:barcode-scanning:17.0.2'

when we can expect this update in Xamarin

Thanks
@radical @bratsche @krukow @hilli @chrisntr

**Comment by moljac** [comment]
thanks for the feedback

2 weeks ago 18.0.0

https://www.nuget.org/packages/Xamarin.GooglePlayServices.MLKit.BarcodeScanning/118.0.0

**Comment by moljac** [comment]
if that is OK please close the issue yourself

**Comment by dineshkandan** [comment]
Hi @moljac Thanks for the response 
Our app doesn't required internet 
Unbundled - implementation 'com.google.android.gms:play-services-mlkit-barcode-scanning:18.0.0'
which is currently updated but we need 
Bundled -  implementation 'com.google.mlkit:barcode-scanning:17.0.2'

when compared to Unbundled
Bundled  model is faster and more accurate.
Bundled  model detects more correct results from bad-quality inputs and have more stable bounding boxes in streaming mode. Recall is improved by 17.1%.

Kindly refer to https://developers.google.com/ml-kit/vision/barcode-scanning/android

please do needful 
Thanks

**Comment by moljac** [comment]
for bundled/on-device/offline barcode scanning there is

17.0.2

https://www.nuget.org/packages/Xamarin.Google.MLKit.BarcodeScanning/117.0.2

and this is what you wanted. Right?

**Comment by dineshkandan** [comment]
Yes thank you so much @moljac

**Comment by dineshkandan** [comment]
Hi @moljac 

after updating this i am getting error 
**error XBD020: Invalid item ID image-1.0.0-beta1**
please help

@radical @bratsche @krukow @hilli

**Comment by moljac** [comment]
> Hi @moljac
> 
> after updating this i am getting error **error XBD020: Invalid item ID image-1.0.0-beta1** please help
> 
> @radical @bratsche @krukow @hilli

this is completely different issue.

XamarinBuildDownload was not designed to work with preview packages - against our/decent policies.

But, number of google's packages depending on previews is growing an this causes tons of problems.

**Comment by dineshkandan** [comment]
Hi @moljac any solution to fix this?

**Comment by Sathishobs** [comment]
Hi @moljac  @dineshkandan  I'm also facing this error **XBD020: Invalid item ID image-1.0.0-beta1**  after updating the recent version released. I can't move forward to build my app. 

Could you help us how do we avoid this error and use the latest Xamarin version released? 

This is kind of blocker to use the latest version for cross developers. 

The solution or a way to ignore this issue would be greatly appreciated. 

@radical  @bratsche  @krukow  @hilli 

Thanks,
Sathish

**Comment by moljac** [comment]
try updating (explicitly adding reference) to projects:

```
<PackageReference Include="Xamarin.Build.Download" Version="0.11.3" />
```

And please report if this works.

Thanks

**Comment by DeliriumCode** [comment]
Just for anyone who has this issue.
Try adding the pre-release version of Xamarin.Google.Android.ODML.Image via nuget.

It looks like any pre-release dependencies need to be manually added rather than auto added as a transitive dependancy
