### ISSUE TITLE
Cannot build .NET6 app with Xamarin.GooglePlayServices.Ads.Lite

### ISSUE THREAD

**Issue by tipa** [xamarin/GooglePlayServicesComponents#638]
Simply create a new Android .NET6 app and add the Xamarin.GooglePlayServices.Ads.Lite package (version 120.6.0.1):
App cannot be built with the errors below:

```
Error	JAVAC0000	 error: package com.google.android.ump.ConsentForm does not exist
		com.google.android.ump.ConsentForm.OnConsentFormDismissedListener
```
![image](https://user-images.githubusercontent.com/2863198/173252545-5f1a59bb-a6c0-4805-af19-4f27fcb1fcdb.png)

Demo app: [testapp.zip](https://github.com/xamarin/XamarinComponents/files/8886769/testapp.zip)

**Comment by mhdwaelanjo** [comment]
I fixed the problem.. we can use my libraries :
 
```
 <PackageReference Include="Anjo.Android.GoogleServices.Ads" Version="22.0.0" />
 <PackageReference Include="Anjo.Android.GoogleServices.AdsBase" Version="22.0.0" />
 <PackageReference Include="Anjo.Android.GoogleServices.AdsLite" Version="22.0.0" />
```

Supports fixing the problem of Loading ads using : 
---------------------------------

- Let's rename for Interstitial ads **InterstitialAdLoadCallback** to **AnjoInterstitialLoadCallback**.
- Let's rename for Rewarded ads **RewardedAdLoadCallback** to **AnjoRewardedLoadCallback**.
- Let's rename for App Open Ads **AppOpenAd.AppOpenAdLoadCallback** to **AnjoAppOpenLoadCallback**.
- Let's rename for Rewarded interstitial ads **RewardedInterstitialAdLoadCallback** to **AnjoRewardedInterstitialLoadCallback**.
