### ISSUE TITLE
Xamarin.Grpc.Core 1.45.1 is not compatible with netstandard

### ISSUE THREAD

**Issue by liuzhenLz** [xamarin/GooglePlayServicesComponents#646]
Package Xamarin.Grpc.Core 1.45.1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Xamarin.Grpc.Core 1.45.1 supports:
  - monoandroid12.0 (MonoAndroid,Version=v12.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)

That's funny！！！！

**Comment by moljac** [comment]
@liuzhenLz 

Thanks for the feedback.

> That's funny！！！！

Well... Depends. Being `netstandard2.0` compatible would mean it can be used on iOS, Mac, Windows, etc... But being maven (jar or aar) Android binding library it does not make sense to signal users it can be used on anything but Android.

If you need xplat GRPC packages I suggest:

https://www.nuget.org/packages/Grpc.Core#dependencies-body-tab

or

https://www.nuget.org/packages/Grpc.Core.Xamarin

**Comment by moljac** [comment]
closing this one.
