### ISSUE TITLE
Error java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete

### ISSUE THREAD

**Issue by adydecki** [xamarin/GooglePlayServicesComponents#648]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

.NET 6.0.301

### Description

When two packages `Square.OkHttp3` and `Xamarin.Kotlin.StdLib` are added to the .net6-android application then compile time error (as shown in the repro steps) occurs during the application build. 

### Steps to Reproduce

1. create new Android application, i.e. `dotnet new android -n AndroidApp`
2. cd to /AndroidApp and add Xamarin.Kotlin.StdLib and Square.OkHttp3 packages, i.e. `dotnet add package Xamarin.Kotlin.StdLib` `dotnet add package Square.OkHttp3`
3. build the application `dotnet build`
4. the following compile time error shows up
`/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.415/tools/Xamarin.Android.D8.targets(79,5): error : java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/adrian/.nuget/packages/xamarin.kotlin.stdlib/1.6.21.1/buildTransitive/net6.0-android31.0/../../jar/org.jetbrains.kotlin.kotlin-stdlib-1.6.21.jar : kotlin/collections/ArraysUtilJVM.class [/Users/adrian/Dev/projects/github/net6-maui-test/AndroidApp/AndroidApp.csproj]`

Above steps can be found in the repository [https://github.com/adydecki/net6-maui-test/tree/main/AndroidApp](https://github.com/adydecki/net6-maui-test/tree/main/AndroidApp)

**Comment by tuyen-vuduc** [comment]
@jonathanpeppers Do we still need to do the workaround by far?

**Comment by jonathanpeppers** [comment]
No, this was fixed in https://github.com/xamarin/GooglePlayServicesComponents/pull/649.

You might update all NuGet packages and see if that is the problem.

**Comment by tuyen-vuduc** [comment]
@jonathanpeppers Can you advise which packages in particular?

**Comment by jonathanpeppers** [comment]
@moljac what versions of GPS packages would contain https://github.com/xamarin/GooglePlayServicesComponents/pull/649?

**Comment by tuyen-vuduc** [comment]
@jonathanpeppers After upgrading Square.OkHttp3 to the latest version, it seems to be ok. I will revert if I face any other issues.

**Comment by moljac** [comment]
> @moljac what versions of GPS packages would contain #649?

There was tons of updates since 2022-07. Several times bumped all packages for various reasons. 

Do you want me to go deeper into details?
