### ISSUE TITLE
Phone Authentication class is not available.

### ISSUE THREAD

**Issue by umairali612** [xamarin/GooglePlayServicesComponents#65]
### Describe your Issue:
Firebase authentication of phone no function or class is not there.

**Comment by jlovatt121** [comment]
This is a feature that needs to be implemented soon. I have an app that currently uses Digits as the sign in method. Digits is being deprecated and moved completely to Firebase at the end of September, meaning I need to move to this new system. Without it most of the users on my app will no longer be able to log in. Is there any estimate on when this will be complete as many people depend on it.

**Comment by Balakrishna12** [comment]
When can we expect  Firebase phone  authentication function?

**Comment by Redth** [comment]
This is available definitely in the latest prerelease versions on nuget which will soon be stable.
