### ISSUE TITLE
Fix templates that use `<LibraryProjectZip>`

### ISSUE THREAD

**Issue by jpobst** [xamarin/GooglePlayServicesComponents#652]
Context: https://github.com/dotnet/maui/issues/8233

We currently use `<LibraryProjectZip>` to specify which Java library we want to bind.  Unfortunately, using this alone does not produce valid NuGet packages for .NET 6.  These packages are missing the `.jar`/`.aar` library that should sit next to the `.dll`.  (This library is no longer embedded in the `.dll` in .NET 6.)

We need to switch to using `<AndroidLibrary>` instead, which will do the correct thing for both .NET 6 and classic XA.

It looks like we use `<LibraryProjectZip>` in 22 templates:
https://github.com/xamarin/GooglePlayServicesComponents/search?q=LibraryProjectZip

Once changed, verify that the `.aar` is in the NuGet. ex:

![image](https://user-images.githubusercontent.com/179295/177416038-26e707d8-3189-4c57-8818-4ea56c99101b.png)

This is likely causing many issues like:
- https://github.com/xamarin/GooglePlayServicesComponents/issues/630
- https://github.com/xamarin/GooglePlayServicesComponents/issues/604
- https://github.com/xamarin/GooglePlayServicesComponents/issues/560

**Comment by manuelelucchi** [comment]
Any news on this? maui is GA since two months... @moljac

**Comment by moljac** [comment]
@manuelelucchi Thanks for the "feedback". 

> Any news on this? 

Working on it.

> maui is GA since two months... @moljac

IIRC Windows  11 too, but thanks for the info.
