### ISSUE TITLE
It seems that only deprecated APIs are bound in Xamarin.Firebase.ML.Vision (and marked as deprecated)

### ISSUE THREAD

**Issue by ivanicin** [xamarin/GooglePlayServicesComponents#660]
### Xamarin.Android Version (eg: 6.0):
12.3.3.3

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10, 19044.1826

### Google Play Services Version

*   [] GPS-FB with AndroidX dependencies (versions `1xx.yyyy.zz`)
Xamarin.AndroidX.AppCompat 1.4.2.1

### Describe your Issue
I have added the package  `Xamarin.Firebase.ML.Vision`

The only API for the text recognition that I was able to access is `Firebase.ML.Vision.FirebaseVision.Instance.OnDeviceTextRecognizer`. This is marked as deprecated (and is deprecated by Google).

I've tried to find the new non-deprecated `TextRecognition` API described here: https://developers.google.com/ml-kit/vision/text-recognition/android, but it doesn't appear anywhere. Intellisense doesn't offer any namespace suggestion and I have manually checked every namespace that seems reasonable to me (Com.Google, Google, Xamarin.Google, Firebase, MlKit).

### Relevant information

Add relevant project settings from `*.csproj` file:

Packages used:
```
    <PackageReference Include="Xamarin.Essentials" Version="1.7.3" />
```

Build settings (tools)

```
    <AndroidDexTool>d8</AndroidDexTool>
    <AndroidLinkTool>r8</AndroidLinkTool>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidEnableDesugar>true</AndroidEnableDesugar>
```

or even better - links to the existing code:

NOTE: Please DO NOT submit screenshot images. Images are not searchable! 

### Minimal Repro Code Sample

If you want to speed up investigation and bug fixing: please provide minimal repro sample for tests.

**Comment by jpobst** [comment]
Google has many different "MLKit" "Vision" packages.

I think the one you are looking for is:
https://www.nuget.org/packages/Xamarin.GooglePlayServices.MLKit.Text.Recognition.Common

**Comment by ivanicin** [comment]
> Google has many many different "MLKit" "Vision" packages.
> 
> I think the one you are looking for is: https://www.nuget.org/packages/Xamarin.GooglePlayServices.MLKit.Text.Recognition.Common

Thanks. After some looking I would say that it should be: https://www.nuget.org/packages/Xamarin.GooglePlayServices.MLKit.Text.Recognition

It matches some descriptions from that document.

But while that should be the right one, it doesn't seem to actually resolve the problem - intellisense still doesn't offer any namespace suggestion and I can't find that anything was added - as far as I understand notation it should be under Xamarin.Google, but that namespace doesn't exist and there is nothing that seems to be added under Google or com.google or MLKit (which is not found by intellisense either)...

I have also tried the packages that you have suggested and even both of them together. I have tried that on a clean project.

**Comment by jpobst** [comment]
Looks like it should be: `Xamarin.Google.MLKit.Vision.Text.TextRecognition`:

https://www.fuget.org/packages/Xamarin.GooglePlayServices.MLKit.Text.Recognition.Common/117.0.0.1/lib/net6.0-android31.0/Xamarin.GooglePlayServices.MLKit.Text.Recognition.Common.dll/Xamarin.Google.MLKit.Vision.Text/TextRecognition

**Comment by ivanicin** [comment]
@jpobst  I appreciate your willingness to help, but as said above I have tried to add that package and there is no Xamarin.Google namespace after adding it... I have used the default clean project and added the package and checked (and the other one that I have mentioned and both of them together).

**Comment by ivanicin** [comment]
Anyway I'll close this issue as that particular question seems to be answered properly. However I'll submit the new issue with the test case for this new problem so everyone can see whether it works or not and hopefully fix it...
