### ISSUE TITLE
TensorFlow.Lite - Interpreter class not found on .NET MAUI

### ISSUE THREAD

**Issue by artimisgroup** [xamarin/GooglePlayServicesComponents#662]
During execution

```
Didn't find class "org.tensorflow.lite.Interpreter" on path: DexPathList[[sip file ""/data/app/~~_L8pALU3K30Ih0QNAXfnUw==/au.com.someapp-xrobOHSGY_trXS_n14eRQ==/base.apk"],nativeLibraryDirectories=[]
```

**Comment by moljac** [comment]
thanks for the feedback:

```
 ls -1 ./generated/org.tensorflow.tensorflow-lite/obj/Release/monoandroid12.0/generated/src/
```

```
Java.Interop.__TypeRegistrations.cs
Xamarin.TensorFlow.Lite.Annotations.IUsedByReflection.cs
Xamarin.TensorFlow.Lite.Annotations.UsedByReflectionAttribute.cs
Xamarin.TensorFlow.Lite.DataType.cs
Xamarin.TensorFlow.Lite.IDelegate.cs
Xamarin.TensorFlow.Lite.IInterpreterApi.cs
Xamarin.TensorFlow.Lite.Interpreter.cs
Xamarin.TensorFlow.Lite.Nnapi.NnApiDelegate.cs
Xamarin.TensorFlow.Lite.Tensor.cs
Xamarin.TensorFlow.Lite.TensorFlowLite.cs
Xamarin.TensorFlow.Lite.projitems
__NamespaceMapping__.cs
enumlist
generator.rsp
```

try adding proguard rules to prevent shrinking/optimization of some or all tensorflow-lite classes.

**Comment by artimisgroup** [comment]
Hi Thank you for your advise.
I have tried adding proguard rules (that I list below), however still getting the same error. 

I also noticed on Device Log the following Warning: open_from_bundles: failed to load assembly Xamarin.TensorFlow.Lite.dll

To add the proguard rules I have done the following:

1. Added a ProguardConfiguration into my csproj file
<ItemGroup Condition="$(TargetFramework.Contains('-android'))">
      <ProguardConfiguration Include="Platforms\Android\proguard.cfg" />
	</ItemGroup> 
 2. proguard.cfg file rules below
 
 -keep class org.tensorflow.lite.Interpreter** {*;}
-keep class org.tensorflow.lite.** {*;}
-keep interface org.tensorflow.lite.** {*;}
-keep class org.tensorflow-lite.** {*;}
-keep interface org.tensorflow-lite.** {*;}
-keep class Xamarin.TensorFlow.Lite.** {*;}
-keep interface Xamarin.TensorFlow.Lite.** {*;}

Do I need to change anything further on the MAUI project configs?

If there is any simple working example that will be of great help.

**Comment by moljac** [comment]
@artimisgroup 

Hi

Is this `net6.0` app? MAUI? 

Or classic? `monoandroidX.0`?

**Comment by artimisgroup** [comment]
Hi Thank you for looking at this. 
It is a MAUI App

`<TargetFrameworks>net6.0-android;net6.0-ios</TargetFrameworks>`

I was testing net6.0-android.

**Comment by moljac** [comment]
@artimisgroup 

Thanks for the feedback

> Do I need to change anything further on the MAUI project configs?

No. This is not MAUI issue. It is bindings. Seems like we have "small" issues with new BuildActions for `net6.0-android` TFM.
 
> If there is any simple working example that will be of great help.

I wish. I have high on my list to do some ML, but keep on postponing it. I would appreciate if you could point me out few, so I can check them later and maybe add them as test samples to the repos.
 
> Hi Thank you for looking at this. It is a MAUI App

No problems. This is what we do. Sorry for kepping you waiting. Priorities.
 
> `<TargetFrameworks>net6.0-android;net6.0-ios</TargetFrameworks>`

yup. That is what I expected.
 
> I was testing net6.0-android.

Thanks. This narrows our search and confirms some ideas.

**Comment by artimisgroup** [comment]
Hi Thanks again.
I was converting the following example into .NET MAUI to start with.
 
https://devblogs.microsoft.com/xamarin/image-classification-xamarin-android/
code https://github.com/dhindrik/MushroomDetector/

**Comment by moljac** [comment]
Closing this one. Open new issue if the problem persists.

**Comment by lawr1292** [comment]
Hello, I am having this exact issue, and I'm not seeing how the original poster solved this issue. I am creating a MAUI app and currently targeting net6.0-android. I have also tried adding the proguard rules file OP added to no avail. 
(These are the steps I followed to add the proguard rules)
-First add proguard.cfg to your android project level.
-Change proguard.cfg file build action to ProguardConfiguration
-Change proguard.cfg file Encoding using Notepad++ to UTF-8

**Comment by AugPav** [comment]
> Hola gracias de nuevo. Para empezar, estaba convirtiendo el siguiente ejemplo a .NET MAUI.
> 
> https://devblogs.microsoft.com/xamarin/image-classification-xamarin-android/ código https://github.com/dhindrik/MushroomDetector/
> 
> Código del clasificador en MAUI
> 
> ```
> public class TensorFlowClassifier
>     {
>         public const int FloatSize = 4;
>         public const int PixelSize = 3;
> 
>         public event EventHandler<ClassificationEventArgs> ClassificationCompleted;
> 
>         public async Task Classify(byte[] bytes)
>         {
>             try
>             {
>                 var mappedByteBuffer = await GetModelAsMappedByteBufferAsync();
> 
>                 var interpreter = new Xamarin.TensorFlow.Lite.Interpreter(mappedByteBuffer);
> 
>                 var tensor = interpreter.GetInputTensor(0);
> 
>                 var shape = tensor.Shape();
> 
>                 var width = shape[1];
>                 var height = shape[2];
> 
>                 var byteBuffer = GetPhotoAsByteBuffer(bytes, width, height);
> 
>                 using var stream = FileSystem.OpenAppPackageFileAsync("labels.txt").Result;
>                 using var reader = new StreamReader(stream);
>                 var labels = reader.ReadToEnd().Split('\n').Select(s => s.Trim()).Where(s => !string.IsNullOrEmpty(s))
>                     .ToList();
> 
>                 var outputLocations = new float[1][] { new float[labels.Count] };
> 
>                 var outputs = Java.Lang.Object.FromArray(outputLocations);
> 
>                 interpreter.Run(byteBuffer, outputs);
> 
>                 var classificationResult = outputs.ToArray<float[]>();
> 
>                 var result = new List<Classification>();
> 
>                 for (var i = 0; i < labels.Count; i++)
>                 {
>                     var label = labels[i];
>                     result.Add(new Classification(label, classificationResult[0][i]));
>                 }
> 
>                 ClassificationCompleted(this, new ClassificationEventArgs(result));
>             }
>             catch (Exception exception)
>             {
>                 throw exception;
>             }
>         }
> 
>         async Task<ByteBuffer> GetModelAsMappedByteBufferAsync()
>         {
>             using var stream = await FileSystem.OpenAppPackageFileAsync("model.tflite");
> 
>             var bytes = stream.ReadAllBytes();
> 
>             var bb = MappedByteBuffer.Wrap(bytes);
>             return bb;
> 
>         }
> 
>         private ByteBuffer GetPhotoAsByteBuffer(byte[] bytes, int width, int height)
>         {
>             var modelInputSize = FloatSize * height * width * PixelSize;
> 
>             var bitmap = BitmapFactory.DecodeByteArray(bytes, 0, bytes.Length);
>             var resizedBitmap = Bitmap.CreateScaledBitmap(bitmap, width, height, true);
> 
>             var byteBuffer = ByteBuffer.AllocateDirect(modelInputSize);
>             byteBuffer.Order(ByteOrder.NativeOrder());
> 
>             var pixels = new int[width * height];
>             resizedBitmap.GetPixels(pixels, 0, resizedBitmap.Width, 0, 0, resizedBitmap.Width, resizedBitmap.Height);
> 
>             var pixel = 0;
> 
>             for (var i = 0; i < width; i++)
>             {
>                 for (var j = 0; j < height; j++)
>                 {
>                     var pixelVal = pixels[pixel++];
> 
>                     byteBuffer.PutFloat(pixelVal >> 16 & 0xFF);
>                     byteBuffer.PutFloat(pixelVal >> 8 & 0xFF);
>                     byteBuffer.PutFloat(pixelVal & 0xFF);
>                 }
>             }
> 
>             bitmap.Recycle();
> 
>             return byteBuffer;
>         }
> 
> 
>     }
> 
>     public static class StreamExtensions
>     {
>         public static byte[] ReadAllBytes(this Stream instream)
>         {
>             if (instream is MemoryStream)
>                 return ((MemoryStream)instream).ToArray();
> 
>             using (var memoryStream = new MemoryStream())
>             {
>                 instream.CopyTo(memoryStream);
>                 return memoryStream.ToArray();
>             }
>         }
>     }
> ```
@artimisgroup Were you finally able to solve it?
