### ISSUE TITLE
Add tensorflow-lite-select-tf-ops

### ISSUE THREAD

**Issue by josago97** [xamarin/GooglePlayServicesComponents#667]
Hello,
I am making a project in Android and when I open the model ([model.zip](https://github.com/xamarin/XamarinComponents/files/9160007/model.zip)) I get the following error: "Java.Lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Select TensorFlow op(s), included in the given model, is (are) not supported by this interpreter.Make sure you apply/link the Flex delegate before inference.For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency".

Could you add org.tensorflow:tensorflow-lite-select-tf-ops?

Thank you.

**Comment by moljac** [comment]
@josago97 

Thanks for the feedback. Appreciated.

> Could you add org.tensorflow:tensorflow-lite-select-tf-ops?

As soon as I find some time. You know priorities.

**Comment by josago97** [comment]
Thank you for your work.

A few days ago I tried to create a package with such dependency (https://github.com/josago97/Xamarin.TensorFlow.Lite.AndroidBinding/tree/main/source/Xamarin.TensorFlow.Lite.Select-TF-Ops.Bindings.XamarinAndroid). However, it did not solve the problem, I kept getting the same error. Surely I have done something wrong, I hope it goes better for you.

**Comment by moljac** [comment]
WIP

https://github.com/xamarin/GooglePlayServicesComponents/pull/700
