### ISSUE TITLE
Add Xamarin.GooglePlayServices.Base dependency to Firebase (Messaging) packages.

### ISSUE THREAD

**Issue by maximhan** [xamarin/GooglePlayServicesComponents#67]
### Xamarin.Android Version (eg: 6.0):
7.3.1.2

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 (Version 1703 - Build 15063.483)

### Google Play Services Version (eg: 8.4.0):
10.2.1

### Describe your Issue:
The Firebase (and Xamarin) documentation states that we should check for Google Play services APK using Android.Gsm.Common.GoogleApiAvailability, but this API is not available under the currently installed depdendencies for Xamarin.Firebase.Messaging.

This, combined with the "do not install directly" description message on the Xamarin.GooglePlayServices.* packages, makes the whole thing a bit confusing, and nonsensical.

Suggest that Xamarin.GooglePlayServices.Base be included as a dependency when consuming Xamarin.Firebase.* packages/API's.

### Steps to Reproduce (with link to sample solution if possible):
Add Xamarin.Firebase.Messaging to your solution / Android project.

Try to follow the guide linked below, more specifically, the part where you're asked/recommended to implement the suggested "IsPlayServicesAvailable ()" method:

https://developer.xamarin.com/guides/android/application_fundamentals/notifications/remote-notifications-with-fcm/

The following line will return "The name "GoogleApiAvailability" does not exist in the current context, even after including "Android.Gms.Common".

`int resultCode = GoogleApiAvailability.Instance.IsGooglePlayServicesAvailable(this);`

**Comment by Redth** [comment]
The next release of Play Services stable nuget will remove this "do not install directly" messaging.  You're right, it was confusing.  It was mostly to prevent users from installing this package and thinking they installed all of google play services, since they were used to one monolithic package and we were deprecating that one.  This seems to cause more confusion than anything now, so it should be removed.

**Comment by jeffmoreta** [comment]
solucion...?

**Comment by jeffmoreta** [comment]
tengo el mismo problema y tengo actualizado y nada que se soluciona.
