### ISSUE TITLE
Binding for com.google.android.play:app-update:2.0.0

### ISSUE THREAD

**Issue by SarthakGz** [xamarin/GooglePlayServicesComponents#670]
Is there bindings available for com.google.android.play:app-update:2.0.0.
I would like to use native update available functionality provided by google.

**Comment by moljac** [comment]
@SarthakGz 

Thanks for the feedback. Appreciated.

**Comment by moljac** [comment]
published

https://www.nuget.org/packages/Xamarin.Google.Android.Play.App.Update

closing this issue

**Comment by SarthakGz** [comment]
Thank you so much
