### ISSUE TITLE
Error while delivering the message: ServiceIntent not found

### ISSUE THREAD

**Issue by roopeshnaik** [xamarin/GooglePlayServicesComponents#70]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android   7.4.0.19

### Operating System & Version (eg: Mac OSX 10.11):
Windows 7

### Google Play Services Version (eg: 8.4.0):
42.1021.1

### Describe your Issue:
Getting below error in logcat
FirebaseInstanceId	Failed to resolve target intent service, skipping classname enforcement
FirebaseInstanceId	Error while delivering the message: ServiceIntent not found.

### Steps to Reproduce (with link to sample solution if possible):
Add Xamarin.Firebase components to Xamarin project and Debug, shows the above error in log

### Include any relevant Exception Stack traces, build logs, adb logs:
NA

**Comment by Redth** [comment]
Not sure how to reproduce this.  Please add a new issue with more info if you're able to reproduce this with 60.1142.0-rc1 or newer.
