### ISSUE TITLE
Unable to use Fuse location provider

### ISSUE THREAD

**Issue by softlion** [xamarin/GooglePlayServicesComponents#71]
### Xamarin.Android Version (eg: 6.0):

7.4.0.21

### Operating System & Version (eg: Mac OSX 10.11):

Win10 / VS17

### Google Play Services Version (eg: 8.4.0):

Xamarin.GooglePlayServices.Location" version="57.1104.0-beta1" targetFramework="monoandroid71"

### Describe your Issue:

Unable to use Fuse location provider.

### Steps to Reproduce (with link to sample solution if possible):

            var builder = new GoogleApiClient.Builder(activity)
            builder.AddConnectionCallbacks(gc);
            builder.AddOnConnectionFailedListener(gc);
            builder.AddApi(LocationServices.API);
            var client = builder.Build(); <==== CRASH

```

      private GoogleCallbacks gc = new GoogleCallbacks();


        class GoogleCallbacks : Java.Lang.Object, GoogleApiClient.IConnectionCallbacks, GoogleApiClient.IOnConnectionFailedListener
        {
            public void OnConnected(Bundle connectionHint)
            {
            }

            public void OnConnectionSuspended(int cause)
            {
            }

            public void OnConnectionFailed(ConnectionResult result)
            {
            }
        }

```
### Include any relevant Exception Stack traces, build logs, adb logs:

`340,53 AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, an 08-29 17:56:41.517 23102 23237 E mvx     : droid.os.Looper, com.google.android.gms.common.internal.zzg, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google 08-29 17:56:41.517 23102 23237 E mvx     : .android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)" 08-29 17:56:41.517 23102 23237 E mvx     :        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d 08-29 17:56:41.517 23102 23237 E mvx     : 315ca4ba7b117efb8dacaedcf>:0 08-29 17:56:41.517 23102 23237 E mvx     :   at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMetho 08-29 17:56:41.517 23102 23237 E mvx     : dInfo method) [0x00068] in <6cd960837cc24c26bab2a0a29b597627>:0 08-29 17:56:41.517 23102 23237 E mvx     :   at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod) [0x 08-29 17:56:41.517 23102 23237 E mvx     : 0000e] in <d278c06ad5684d6882c743a94a93ebc2>:0 08-29 17:56:41.517 23102 23237 E mvx     :   at Android.Gms.Common.Apis.GoogleApiClient+Builder.Build () [0x00033] in <f2bc38c188d2451ab02a977b52544b4c>:0
`

**Comment by Redth** [comment]
Hi there, please try `60.1142.0-rc1` or newer.  Not able to reproduce this with those versions.
