### ISSUE TITLE
Support GooglePlayServices nuget packages targeting net7.0-android

### ISSUE THREAD

**Issue by vdkalyanapu** [xamarin/GooglePlayServicesComponents#717]
### Operating System & Version (eg: Mac OSX 10.11):
Windows 11. VS 2022 17.4.1

Microsoft Visual Studio Professional 2022
Version 17.4.1
VisualStudio.17.Release/17.4.1+33110.190
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Professional

C# Tools   4.4.0-6.22559.4+d7e8a398ef479a908e76bded82150c39251d0c9c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.4.19 (8c0a575)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.4.0.301 (d17-4@96af3ae)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.4.0.138 (remotes/origin/d17-4@d36bba3cc9)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.4.2 (c457c97)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.1.0.1 (d17-4/13ba222)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a96bde9
    Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
    SQLite: xamarin/sqlite/3.39.3@23e1ae7
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a

Xamarin.iOS and Xamarin.Mac SDK   16.0.0.92 (3dd3dc52c)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Google Play Services Version

*   GPS-Maps 118.1.0

### Describe your Issue

Android app is crashing when loading the map view with this error stack:

FATAL UNHANDLED EXCEPTION: System.InvalidCastException: Unable to convert instance of type 'Android.Views.View' to type 'Android.Gms.Maps.MapView'.
[mono-rt]    at Java.Interop.JavaObjectExtensions.CastClass(IJavaObject instance, Type resultType) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/JavaObjectExtensions.cs:line 86
[mono-rt]    at Java.Interop.JavaObjectExtensions._JavaCast[MapView](IJavaObject instance) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/JavaObjectExtensions.cs:line 69
[mono-rt]    at Java.Interop.JavaObjectExtensions.JavaCast[MapView](IJavaObject instance) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/JavaObjectExtensions.cs:line 52
[mono-rt]    at Android.Runtime.Extensions.JavaCast[MapView](IJavaObject instance) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/Extensions.cs:line 13
[mono-rt]    at Android.Views.View.FindViewById[MapView](Int32 id) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Views/View.cs:line 29
[mono-rt]    at TransportACE_Maui.StopsListTripMapFragment.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) in C:\Apacheta_git\TransportACE_HME\TransportACE_Maui\Platforms\Android\Source\UITasks\StopsListTripMapFragment.cs:line 78
[mono-rt]    at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/generated/androidx.fragment.fragment/obj/Release/net6.0-android/generated/src/AndroidX.Fragment.App.Fragment.cs:line 2031
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 352

### Relevant information

Packages used:

```
 <PackageReference Include="Xamarin.GooglePlayServices.Maps">
			<Version>118.1.0</Version>
		</PackageReference>
```

### Include any relevant Exception Stack traces, build logs, adb logs:

FATAL UNHANDLED EXCEPTION: System.InvalidCastException: Unable to convert instance of type 'Android.Views.View' to type 'Android.Gms.Maps.MapView'.
[mono-rt]    at Java.Interop.JavaObjectExtensions.CastClass(IJavaObject instance, Type resultType) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/JavaObjectExtensions.cs:line 86
[mono-rt]    at Java.Interop.JavaObjectExtensions._JavaCast[MapView](IJavaObject instance) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/JavaObjectExtensions.cs:line 69
[mono-rt]    at Java.Interop.JavaObjectExtensions.JavaCast[MapView](IJavaObject instance) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/JavaObjectExtensions.cs:line 52
[mono-rt]    at Android.Runtime.Extensions.JavaCast[MapView](IJavaObject instance) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/Extensions.cs:line 13
[mono-rt]    at Android.Views.View.FindViewById[MapView](Int32 id) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Views/View.cs:line 29
[mono-rt]    at TransportACE_Maui.StopsListTripMapFragment.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) in C:\Apacheta_git\TransportACE_HME\TransportACE_Maui\Platforms\Android\Source\UITasks\StopsListTripMapFragment.cs:line 78
[mono-rt]    at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/generated/androidx.fragment.fragment/obj/Release/net6.0-android/generated/src/AndroidX.Fragment.App.Fragment.cs:line 2031
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 352

**Comment by jpobst** [comment]
I highly suspect this is an error in your application.  It appears you are doing something like:
```csharp
var view = FindViewById<Android.Gms.Maps.MapView> (Resources.Layout.MyLayout)
```

However your view with the requested Id is not of type `Android.Gms.Maps.MapView`, it is `Android.Views.View`.

**Comment by vdkalyanapu** [comment]
Thanks for pointing out. I'm usually thorough with understanding the stack but somehow skipped looking at it after upgrading the project to net7.0-android.
