### ISSUE TITLE
google cloud storage stopped working on android. 

### ISSUE THREAD

**Issue by mannyvw** [xamarin/GooglePlayServicesComponents#73]
### Xamarin.Android Version (eg: 6.0):
6.0.1

### Operating System & Version (eg: Mac OSX 10.11):
Visual Studio Community 2017 for Mac
Version 7.1 (build 1297)
Installation UUID: 1c0dc94c-64de-48d1-95ea-a0568d59bc80
Runtime:
	Mono 5.2.0.215 (d15-3/da80840) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 502000215

NuGet
Version: 4.3.0.2418

.NET Core
Runtime: Not installed
SDK: Not installed
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.5.5
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Xamarin.Android
Version: 7.4.0.21 (Visual Studio Community)
Android SDK: /Volumes/DataDrive/android/sdk
	Supported Android versions:
		2.3    (API level 10)
		4.0.3  (API level 15)
		4.1    (API level 16)
		4.2    (API level 17)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)

SDK Tools Version: 
SDK Platform Tools Version: 23.1
SDK Build Tools Version: 23.0.1

Java SDK: /usr
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Apple Developer Tools
Xcode 8.3.3 (12175.1)
Build 8E3004b

Xamarin.iOS
Version: 10.12.0.20 (Visual Studio Community)
Hash: 80b8487d
Branch: d15-3
Build date: 2017-08-18 16:07:26-0400

Xamarin.Mac
Version: 3.6.0.19 (Visual Studio Community)

Xamarin Inspector
Version: 1.2.2
Hash: b71b035
Branch: d15-1
Build date: Fri, 21 Apr 2017 17:57:12 GMT

Build Information
Release ID: 701001297
Git revision: 9c5299666538b2f8baf501418a5c064d784d64da
Build date: 2017-08-07 11:29:35-04
Xamarin addins: 3bb0c32a14f1b7e368bf5ac53a84c3581c019391
Build lane: monodevelop-lion-d15-3

Operating System
Mac OS X 10.12.5
Darwin 16.6.0 Darwin Kernel Version 16.6.0
    Fri Apr 14 16:21:16 PDT 2017
    root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

### Google Play Services Version (eg: 8.4.0):
Xamarin.Firebase.Storage.Common.57.1104.0-beta1
Xamarin.GooglePlayServices.Tasks.57.1104.0-beta1
Xamarin.Firebase.Common.57.1104.0-beta1
Xamarin.Firebase.Common.57.1104.0-beta1

### Describe your Issue:
Cant get Xamarin,firebase.storage working again. I had it working on both android and ios for some time a few weeks, it was uploading files. Them bam it just stopped working on android only even builds that were working just stopped. iOS continues to work.

Have recreated the google-services.json file many times, its set to GoogleServices.json type in build, it matches the bundle id. But when i call FirebaseApp.InitializeApp(Application.Context) in activity the logs displays :-

[FirebaseInitProvider] FirebaseApp initialization unsuccessful

Am trying to build with your sample code, but cant get it build at all, but looking at code it doesn't even call FirebaseApp.InitializeApp(Application.Context) , but if i dont call it whenever i use static function to get instance it says you must call FirebaseApp.InitializeApp(Application.Context). Is the sample code really out of date.

**Comment by Redth** [comment]
I believe this was tied to https://bugzilla.xamarin.com/show_bug.cgi?id=56108 in that the google-services.json values weren't being correctly generated as resources, and so the required resource id's didn't exist when the app was run, so the initialization failed.

This should be fixed in 60.1142.0-rc1 and newer.
