### ISSUE TITLE
How to use InAppMessaging?

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [xamarin/GooglePlayServicesComponents#733]
I want to use firebase InAppMessaging in Xamarin android but I got some problems.

Note: push notification works in my sample.

When I install Xamarin.Firebase.InAppMessaging.Display package. I get this error:
JAR library references with identical file names but different contents were found: annotations.jar. Please remove any conflicting libraries from EmbeddedJar, InputJar and AndroidJavaLibrary

and when I uninstall Xamarin.Firebase.InAppMessaging.Display, only push notification works.
Do I need to install Xamarin.Firebase.InAppMessaging.Display to use firebase's in-app messaging?
How can I use the In-App messaging dialog in this sample?
thanks.
Sample URL:
https://github.com/Ali-YousefiTelori/XamarinFirebaseTestSample

**Comment by moljac** [comment]
closing issue
