### ISSUE TITLE
Missing PlacePicker.IntentBuilder in v57 beta1

### ISSUE THREAD

**Issue by tuyen-vuduc** [xamarin/GooglePlayServicesComponents#74]
### Xamarin.Android Version (eg: 6.0):
Version: 7.4.5.1 (Visual Studio Community)

### Operating System & Version (eg: Mac OSX 10.11):
Mac OS X 10.12.6

### Google Play Services Version (eg: 8.4.0):
11.04

### Describe your Issue:
Missing PlacePicker.IntentBuilder

### Steps to Reproduce (with link to sample solution if possible):
Try to create a new instance of  PlacePicker.IntentBuilder

**Comment by Redth** [comment]
Thanks, this should be back in the latest prerelease nuget packages.

**Comment by inimri** [comment]
hello,
i have Google Play Services - Location 11.4.2 and i still face this issue.
