### ISSUE TITLE
Please bind tensorflow-lite-task-audio, tensorflow-lite-task-text, and tensorflow-lite-task-vision

### ISSUE THREAD

**Issue by v-hogood** [xamarin/GooglePlayServicesComponents#755]
Looks like tensorflow-lite-task-base is already there.
Thanks!

**Comment by moljac** [comment]
@v-hogood Thanks for the feedback

packages were bound 3-4 weeks ago.

https://www.nuget.org/packages?q=Xamarin.TensorFlow.Lite.Task.&frameworks=&tfms=&packagetype=&prerel=true&sortby=relevance

Closing this issue
