### ISSUE TITLE
Google code scanner API bindings

### ISSUE THREAD

**Issue by AlexNik4** [xamarin/GooglePlayServicesComponents#758]
### Discussed in https://github.com/xamarin/GooglePlayServicesComponents/discussions/757

<div type='discussions-op-text'>

<sup>Originally posted by **AlexNik4** March 27, 2023</sup>
Hello, recently Google upgraded the [code scanner API](https://developers.google.com/ml-kit/vision/barcode-scanning/code-scanner) from beta to GA. This is something we are really interested in our .NET 7 Android app. When can Microsoft release the C# bindings to access this library? What is the best place to request something like this?

[GmsBarcodeScanner](https://developers.google.com/android/reference/com/google/mlkit/vision/codescanner/GmsBarcodeScanner)
[GmsBarcodeScannerOptions](https://developers.google.com/android/reference/com/google/mlkit/vision/codescanner/GmsBarcodeScannerOptions)

**Comment by vdiddlodka** [comment]
We are interested in this as well. Thanks.

**Comment by moljac** [comment]
Very likely in next update cycle.

https://github.com/xamarin/GooglePlayServicesComponents/issues/762#issuecomment-1538449358

**Comment by AlexNik4** [comment]
Closing. This has been released. https://www.nuget.org/packages/Xamarin.GooglePlayServices.Code.Scanner
