### ISSUE TITLE
No notification generated if targeting Android 8 because firebase messaging version is too old

### ISSUE THREAD

**Issue by guperrot** [xamarin/GooglePlayServicesComponents#76]
### Xamarin.Android Version (eg: 6.0):

Any

### Operating System & Version (eg: Mac OSX 10.11):

Any

### Google Play Services Version (eg: 8.4.0):

10.2.1 is the version pulled by the nuget packages.

### Describe your Issue:

If your application targets API level 26, no notification is generated on Android 8 devices.

### Steps to Reproduce (with link to sample solution if possible):

Integrate Firebase Messaging in an app with latest nugets for everything.
Make the app target API level 26 explicitly in Android build options.
Push a notification to your device that uses Android 8:
Instead of seeing a notification you see an error in ADB logcat.

The solution is to bind this nuget to Firebase version 11 at minimum.

### Include any relevant Exception Stack traces, build logs, adb logs:

```
10-30 12:54:57.665 797-808/? E/NotificationService: No Channel found for pkg=com.microsoft.azure.mobile.xamarin.forms.puppet, channelId=null, id=0, tag=GCM-Notification:36506881, opPkg=com.microsoft.azure.mobile.xamarin.forms.puppet, callingUid=12348, userId=0, incomingUserId=0, notificationUid=12348, notification=Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)
```

Indeed, creating a notification channel is mandatory when targeting Android 0 API level, and you need to update Firebase SDK to have the updated code using channels.

**Comment by Redth** [comment]
Are you talking about Android API Level 8? or Android 8.0?

**Comment by guperrot** [comment]
Android 8.0 which should be API level 26.

**Comment by guperrot** [comment]
Versions:

42.1021.1: does not work
60.1142.0-beta1: works, uses notification channel
60.1142.0-beta2: works, uses notification channel
60.1142.0-rc1: does not work, same error about channel not found (was firebase version downgraded in that rc?)

**Comment by Redth** [comment]
Ok, I just tested notifications being sent fine to an Android 8.1 device with 60.1142.0-rc1, with the app specifically targeting Android 8.0...  The firebase version was definitely not downgraded in that rc....

This sounds to me like it would be more related to how you're _sending_ the notifications than the Firebase Messaging library...

**Comment by guperrot** [comment]
For -rc1 I am not sure, it was working with -betaX, maybe I picked the wrong NUM-rc1.
And no it does not matter what kind of push you send.

Also did you test with "override target sdk 26" or "automatic based on framework version". The automatic is buggy and does not actually use target sdk version 26.

**Comment by Redth** [comment]
Just tried again with 60.1142.0-rc1 and made sure i explicitly set the target sdk to override as 26 (even though compile is set to 26 already - and yes sometimes that can cause issues).  Notifications are still coming through just fine for me.

**Comment by guperrot** [comment]
Ok, I guess we can close this issue once the official release is published :)

**Comment by Redth** [comment]
60.1142.0 is released :) please open a new issue if you have more problems around this with that version!
