### ISSUE TITLE
com.google.android.gms:play-services-code-scanner package?

### ISSUE THREAD

**Issue by vdiddlodka** [xamarin/GooglePlayServicesComponents#762]
Hello, what is the likelihood/timeline for a nuget package of [com.google.android.gms:play-services-code-scanner](https://maven.google.com/web/index.html?q=play-services-code-scanner#com.google.android.gms:play-services-code-scanner:16.0.0 )? This is the version that handles the UI for you which would be convenient. 

Additionally, I've seen other issues in this project mention it does not support preview releases from google, where would I see that the packages are in preview to know if I'll have issues?

**Comment by moljac** [comment]
> Oops I think this is a duplicate of https://github.com/xamarin/GooglePlayServicesComponents/issues/758

It is OK.

**Comment by moljac** [comment]
> Hello, what is the likelihood/timeline for a nuget package of [com.google.android.gms:play-services-code-scanner](https://maven.google.com/web/index.html?q=play-services-code-scanner#com.google.android.gms:play-services-code-scanner:16.0.0)? This is the version that handles the UI for you which would be convenient.
> 
> Additionally, I've seen other issues in this project mention it does not support preview releases from google, where would I see that the packages are in preview to know if I'll have issues?

Seems like library is not in preview anymore, so I might bind it soon. Maybe in next update cycle.
