### ISSUE TITLE
error: package com.google.firebase.messaging does not exist extends com.google.firebase.messaging.FirebaseMessagingService

### ISSUE THREAD

**Issue by fahms** [xamarin/GooglePlayServicesComponents#77]
### Xamarin.Android Version 
Android Version 6.0

### Operating System & Version
Mac 10.12.6

### Google Play Services Version
8.4.0

### Describe your Issue:
Using Xamarin.Firebase and Xamarin.GooglePlayServices
Build issue stating:

`error: package com.google.firebase.messaging does not exist extends com.google.firebase.messaging.FirebaseMessagingService`

though I have the packages imported correctly and no issues with the referencing to Firebase.Messaging. But during build it throws an exception.
Able to receive the Token using FirebaseInstanceIdService after commenting out the FirebaseMessagingService class.

when checked the obj/Debug/__library_projects__/Xamarin.Firebase.Messaging/library_project_imports folder - it is empty unlike the other references.

**Comment by Redth** [comment]
This sounds like a bad download cache potentially.  Try clearing out your bin/ and obj/ and packages/ folders when this happens, and do a nuget restore.  If it still doesn't help, try clearing out your Xamarin.Build.Download cache dir as well:

Mac: `~/Library/Caches/XamarinBuildDownload`
Windows: `%LOCALAPPDATA%\XamarinBuildDownloadCache`
