### ISSUE TITLE
please add other text-recognition

### ISSUE THREAD

**Issue by blackshining** [xamarin/GooglePlayServicesComponents#777]
that's beta end.

  // To recognize Latin script
  implementation 'com.google.mlkit:text-recognition:16.0.0'

  // To recognize Chinese script
  implementation 'com.google.mlkit:text-recognition-chinese:16.0.0'

  // To recognize Devanagari script
  implementation 'com.google.mlkit:text-recognition-devanagari:16.0.0'

  // To recognize Japanese script
  implementation 'com.google.mlkit:text-recognition-japanese:16.0.0'

  // To recognize Korean script
  implementation 'com.google.mlkit:text-recognition-korean:16.0.0'

**Comment by moljac** [comment]
Duplicate

https://github.com/xamarin/GooglePlayServicesComponents/issues/780

**Comment by moljac** [comment]
published

https://www.nuget.org/packages?q=Xamarin.GooglePlayServices.MLKit.Text.Recognition
