### ISSUE TITLE
Does this work with Firebase in an offline mode?

### ISSUE THREAD

**Issue by silverfox1948** [xamarin/GooglePlayServicesComponents#78]

**Comment by silverfox1948** [comment]
I'm wondering if this library supports using Firebase in an offline mode (temporarily) so the user can continue to work with data while the phone is in a disconnected state.

**Comment by Redth** [comment]
The library is a set of bindings to Google's own library, and actually does invoke their library at run time.  So, based on my limited knowledge of what Google's actual library supports, I do believe, yes it should support offline mode.
