### ISSUE TITLE
Bindings incomplete for Xamarin.Android.Google.BillingClient v6.0

### ISSUE THREAD

**Issue by tipa** [xamarin/GooglePlayServicesComponents#781]
I just updated the `Xamarin.Android.Google.BillingClient` package to v6.0.0. There seem to be at least the following problems:

- [NETWORK_ERROR](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponseCode#NETWORK_ERROR) enum is not bound to C# enum
- [SERVICE_TIMEOUT](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponseCode#SERVICE_TIMEOUT) is not marked as deprecated

Other changes might need to take place, according to [the changelog](https://developer.android.com/google/play/billing/release-notes#6-0)

I am happy to provide pull requests to fix these and other potential problems, but since my [first one](https://github.com/xamarin/GooglePlayServicesComponents/pull/747) has been ignored since a while, I am not sure if this work would be worth it

**Comment by moljac** [comment]
if you check your first PR you will see there were few comments which have been ignored for a while.

And PR did not build until latest changes from main were merged.

**Comment by mhdwaelanjo** [comment]
try use `<PackageReference Include="Anjoxam.BillingClient.Droid" Version="6.0.0" />`

**Comment by moljac** [comment]
6.1.0 published

https://www.nuget.org/packages/Xamarin.Android.Google.BillingClient

closing this issue
