### ISSUE TITLE
Java type `com.google.android.play.core.assetpacks.AssetPackManager` is generated by more than one managed type

### ISSUE THREAD

**Issue by janne-hmp** [xamarin/GooglePlayServicesComponents#786]
Hi,
I'm trying to add Xamarin.Google.Android.Play.Core nuget package to my game project GnollHack, and  I get the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The Java type `com.google.android.play.core.assetpacks.AssetPackManager` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.	GnollHackClient.Android			

```
I think this is because there is also Com.Google.Android.Play.Core in the project automatically, possibly coming with Mono.Android. How do you remove this error, or if need be, Com.Google... packages?

**Comment by moljac** [comment]
@janne-hmp 
Thanks for the feedback. Can you create repro sample, please?

**Comment by janne-hmp** [comment]
I in fact figured out the reason for the conflict. I was using James Montemagno's Plugin.StoreReview nuget package, which had the conflicting names for Java classes (in Com.Google.Android.Play.Core). When I removed Montemagno's nuget package, things started working.
