### ISSUE TITLE
Unable to build solution OS X

### ISSUE THREAD

**Issue by pfaucon** [xamarin/GooglePlayServicesComponents#80]
### Operating System & Version (eg: Mac OSX 10.11):
OSX 10.13.1
VS for Mac 7.3

### Describe your Issue:
After cloning the repository I am unable to build the projects.  Using the bootstrapper script I receive an error:
```
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.Json'.

```
After trying a few different versions it seems that I can install Cake with a newer nuget version.  I changed the dependency in both package files to 0.23.0 and it progresses. But now I receive:

```
All packages listed in <removed>/GooglePlayServicesComponents-master/tools/packages.config are already installed.
Analyzing build script...
Processing build script...
Installing tools...
Error: Value cannot be null.
Parameter name: path
```

My guess is that the nuget package introduced some breaking changes compared to 17, I also tried calling cake.exe with only the cake script and the error persists

**Comment by Redth** [comment]
Please try the 11.x branch.  This will be merged into master very soon.  Master is unfortunately not well due to changes with newer versions of cake.
