### ISSUE TITLE
Dotnet 7 Support - Will that be coming?

### ISSUE THREAD

**Issue by johnpaulsmith87** [xamarin/GooglePlayServicesComponents#806]
### Xamarin.Android Version (eg: 6.0):
Android:
Xamarin.Firebase.Analytics 121.1.0
Xamarin.GooglePlayServices.Base 117.6.0.5
iOS:
Xamarin.Firebase.iOS.Analytics 8.10.0.1

### Describe your Issue
For MAUI dotnet 6.0, we used Xamarin.Firebase.Analytics and Xamarin.Firebase.iOS.Analytics and it worked. Since we need to get a new build out to GooglePlay/AppStore and we have to update to dotnet 7 to meet the minimum version requirements, we can no longer use these packages in our build since they only appear to support dotnet 6 (we get build errors).

Will there be dotnet 7 support for these packages coming in the future?

**Comment by jpobst** [comment]
We are not producing .NET 7 packages because they would be the same as the .NET 6 packages which should work just fine.

Can you elaborate on the errors you are seeing?

**Comment by johnpaulsmith87** [comment]
I think you can close this issue. I've managed to get the build working in dotnet7 for Android - iOS is not currently working but as you stated it may not be related at all. 
https://github.com/xamarin/GoogleApisForiOSComponents/issues/608 According to this Issue, it should be able to build on macOS which I will try next. Any further issues that need to be raised will be on GoogleApisForiOSComponents repo

**Comment by petemidg32** [comment]
Hi @johnpaulsmith87 can I ask what you did to get the build working in dotnet7? I am trying to upgrade a xamarin forms app that uses push notifications via azure notification hubs and firebase, and it would be great to have as little to change as possible! 
Thanks,
Pete.

**Comment by summer-004** [comment]
I noticed that `Xamarian.Firebase.Messaging` only supports up to `net6.0-android31.0`, but my project is Android Target API version 33.0, it is showing a warning and while debug it gives a runtime build error.  So, will Microsoft update to support Android 33.0 (the version after 31.0) or .NET 7/8 in the future?
