### ISSUE TITLE
How to call API 

### ISSUE THREAD

**Issue by tobus2012** [xamarin/GooglePlayServicesComponents#817]
Hello How to call the Play Integrity API to verify the authenticity of a device with this library.
I search everywhere but nothing

**Comment by moljac** [comment]
@tobus2012 

Thanks for the feedback. Unfortunately I am not able to help you. I am not API expert. There is too many APIs to know them all. I wish I would have more time to work on samples.

I would suggest to find native sample in java and then port it to c#.
