### ISSUE TITLE
Missing PlaceAutocomplete.IntentBuilder from GooglePlayeServices.Places version 60.1142.0

### ISSUE THREAD

**Issue by AeonDave** [xamarin/GooglePlayServicesComponents#82]
### Xamarin.Android Version (eg: 6.0):
8.1

### Operating System & Version (eg: Mac OSX 10.11):
MacOsx 10.13.2

### Google Play Services Version (eg: 8.4.0):
60.1142.0

### Describe your Issue:
After the last update of NuGet package Xamarin.GooglePlayeServices.Places to version 60.1142.0,
the class PlaceAutocomplete is not exposing IntentBuilder method.
As describer here:

https://stackoverflow.com/questions/47768722/missing-placeautocomplete-intentbuilder-from-googleplayeservices-places-version

### Steps to Reproduce (with link to sample solution if possible):
Just update and try:
AutocompleteFilter autocompleteFilter = new AutocompleteFilter.Builder()
					.SetTypeFilter(Place.TypeCountry)
					.SetCountry("UK")
					.Build();
				var intent = new PlaceAutocomplete.IntentBuilder(PlaceAutocomplete.ModeFullscreen)
					.SetFilter(autocompleteFilter)
					.Build(Activity);

### Include any relevant Exception Stack traces, build logs, adb logs:
Error CS0426: The type name 'IntentBuilder' does not exist in the type 'PlaceAutocomplete'

**Comment by AeonDave** [comment]
It's almost one month since i wrote this and even on bugzilla has been reported (2 days after this):

https://bugzilla.xamarin.com/show_bug.cgi?id=61099

Please try to give to it a shot.

Thank you

**Comment by AeonDave** [comment]
reopen

**Comment by Soarc** [comment]
Any updates on this?
Are there any workarounds?

**Comment by Redth** [comment]
Fixed in 60.1142.1
