### ISSUE TITLE
version of dependencies of Ads has an error for android 8.0

### ISSUE THREAD

**Issue by cansado2930** [xamarin/GooglePlayServicesComponents#83]
### Xamarin.Android Version (eg: 6.0):
8.0

### Operating System & Version (eg: Mac OSX 10.11):
Last versión of Windows 10 FCU

### Google Play Services Version (eg: 8.4.0):
-

### Describe your Issue:
I have installed the last version of xamarin forms with Ads and when I try to compile, it show a message that I should restore nuget package because there aren't installed some. I have checked and it seems that have an error on dependency version. 

### Steps to Reproduce (with link to sample solution if possible):
Install last version of ads for Android 8.0 and try to compile the reléase version

### Include any relevant Exception Stack traces, build logs, adb logs:
..\..\..\packages\Xamarin.Android.Support.Compat.26.0.2\build\MonoAndroid80\Xamarin.Android.Support.Compat.targets.		

it should be Xamarin.Android.Support.Compact.26.0.1

**Comment by mdm687** [comment]
Hi , I am currently experiencing a similar issue . I cannot get xamarin.googleplayservices.base installed.

Error :Install failed. Rolling back...
Package 'Xamarin.GooglePlayServices.Basement.60.1142.0 : Xamarin.Android.Support.Compat [26.0.2, ), Xamarin.Android.Support.Core.UI [26.0.2, ), Xamarin.Android.Support.Core.Utils [26.0.2, ), Xamarin.Android.Support.Fragment [26.0.2, ), Xamarin.Android.Support.Media.Compat [26.0.2, ), Xamarin.Build.Download [0.4.7, )' does not exist in project 'ProjectName.Android'

**Comment by newky2k** [comment]
@cansado2930  could you update to the latest version of GPS and see if you can still replicate the issue please.  The latest stable version is 60.1142.1, but there are previews for 70.1501.0.

**Comment by cansado2930** [comment]
I have tried with 60.1142.1 and now I can compile it on release mode correctly.
Thank you
