### ISSUE TITLE
Cannot Install Google play services on Xamarin Android Nuget

### ISSUE THREAD

**Issue by mdm687** [xamarin/GooglePlayServicesComponents#84]
### Xamarin.Android Version (eg: 6.0):
Xamarin Android Version : 8.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version (eg: 8.4.0):
Google play Services V 60.1142.0

### Describe your Issue:
I am trying to install google play services into my app but recieving the following issue.

Install failed. Rolling back...
Package 'Xamarin.GooglePlayServices.Basement.60.1142.0 : Xamarin.Android.Support.Compat [26.0.2, ), Xamarin.Android.Support.Core.UI [26.0.2, ), Xamarin.Android.Support.Core.Utils [26.0.2, ), Xamarin.Android.Support.Fragment [26.0.2, ), Xamarin.Android.Support.Media.Compat [26.0.2, ), Xamarin.Build.Download [0.4.7, )' does not exist in project ProjectName.Android'

**Comment by noahjerreel** [comment]
Any solution on this? I'm having the same issue @mdm687
