### ISSUE TITLE
[Feature Request] Add Fused Orientation Provider API

### ISSUE THREAD

**Issue by janusw** [xamarin/GooglePlayServicesComponents#846]
### Describe your Issue

A new Fused Orientation Provider API was added to `play-services-location` in version 21.2.0, see

* https://android-developers.googleblog.com/2024/03/introducing-fused-orientation-provider-api.html
* https://developers.google.com/android/reference/com/google/android/gms/location/FusedOrientationProviderClient

It would be great if the bindings to this API could be added, so that one can use it in a .NET context.

**Comment by moljac** [comment]
@janusw 

Thanks for the feedback. I started updating in january, but got blocked with publishing. Namely some nuget packages for ML/AI which carry ML models exceed nuget gallery file limits...

https://github.com/xamarin/GooglePlayServicesComponents/pull/848/files

I hope update will come soon

**Comment by moljac** [comment]
In preparation 

https://github.com/xamarin/GooglePlayServicesComponents/pull/868

It had to be reverted in last PR

**Comment by janusw** [comment]
@moljac What's the status here?

> In preparation
> 
> #868

Seems this has been merged. But you say it had to be reverted?

Is `play-services-location` v21.2.0 included in https://www.nuget.org/packages/Xamarin.GooglePlayServices.Location/121.2.0?

Guessing from the version number I'd hope that it is. And if so, can this issue be closed?

**Comment by moljac** [comment]
> @moljac What's the status here?
> 
> > In preparation
> > #868

Merged. Published.

> Seems this has been merged. But you say it had to be reverted?
> 

Yes. There were problems with dependencies which are not stable.

> Is `play-services-location` v21.2.0 included in https://www.nuget.org/packages/Xamarin.GooglePlayServices.Location/121.2.0?
> 
> Guessing from the version number I'd hope that it is. 

Yes.

> And if so, can this issue be closed?

Please.

**Comment by jpobst** [comment]
Sounds like this has been completed.
