### ISSUE TITLE
Add support for MLKit Document scanner

### ISSUE THREAD

**Issue by afriscic** [xamarin/GooglePlayServicesComponents#847]
Hello.

With new update to MLKit a Dosument scanner API was added:
[https://developers.google.com/ml-kit/vision/doc-scanner/android](https://developers.google.com/ml-kit/vision/doc-scanner/android)
`com.google.android.gms:play-services-mlkit-document-scanner:16.0.0-beta1`

Could support for Document scanner be added?

**Comment by moljac** [comment]
@afriscic 

Thanks. Appreciated feedback, but our policy is not to bind previews.

Closing this one.
