### ISSUE TITLE
[Reminder] Update your apps to the latest Firebase Cloud Messaging APIs and SDKs

### ISSUE THREAD

**Issue by brzezinol** [xamarin/GooglePlayServicesComponents#854]
I would like to ask you to confirm which packages in which versions ensure that Firebase Messaging services meet Google's guidelines for updating the FCM SDK before June 20, 2024?

**Comment by jpobst** [comment]
Our readme describes how to determine which versions of Google's libraries are bound in each NuGet version:

> - The major/minor/patch version numbers are the GPS/FB/MLKit library version prefixed with a `1`. For example, the NuGet `Xamarin.GooglePlayServices.Maps 117.0.1` binds version `17.0.1` of the GPS library `com.google.android.gms:play-services-maps`.

You can use this to compare to the Google version(s) you need.

**Comment by brzezinol** [comment]
@jpobst  Thanks for answer, I saw this readme and I know what doeas mean.
Google says "Recommended FCM SDK version should be >= 23.1.2".
Xamarin.Firebase.Messaging has version 123.3.1.1 so it is updated.
But which other packages are included in Firebase SDK which should be updated?
For example Xamarin.Firebase.Iid version is 121.1.0.13 but is it ok?
I can't find exact info which component is dependend on Firebase SDK.
I affraid that Xamarin suppor will end at May 1 2024, and Firebase could fail at June 20 2024, and here will be problem.
I didn't fifnish MAUI migration yet, too big project...

**Comment by jpobst** [comment]
I'm afraid we don't have guidance for this.  These are Google's libraries so you will have to work with the guidance they provide.  All we do is provide generated wrappers to allow the libraries to be called from C#.

**Comment by AndAShape** [comment]
@brzezinol Did you find an answer to this? Does GooglePlayServicesComponents support FCM V1? If not, what did you use instead?

**Comment by brzezinol** [comment]
@AndAShape from some time I using signalr connection to deliber messages, but when client is not connected I use FCM. So I don't affraid fcm down in this context.
But I using FirebaseID for activating app, and if this will fail at 20th June I will looking for another solution asap.

Xamarin is RIP so nobody will help us, so migrating to maui or run I to another framework like flutter is inevitable...
