### ISSUE TITLE
Does not show Google play credit cards (instead asks to enter new one)

### ISSUE THREAD

**Issue by software770** [xamarin/GooglePlayServicesComponents#86]
### Xamarin.Android Version (eg: 6.0):
8

### Operating System & Version (eg: Mac OSX 10.11):
windows 10

### Google Play Services Version (eg: 8.4.0):
60

### Describe your Issue:
I developed everything from an example in JAva in android studio. When I open the google payment window it gives me the window with credit cards with Google from Google play.

Translated everything, line by line in xamarins, but, this time, the android window shows but it asks me to enter a new credit card (I guess xamarin forces the use of wallet ? and Android studio version get you the information from google play if you have anything there ?).

Now the code has been updated to the xamarins google play services version 60, but, after much effort, the same problem occurce...

**Comment by newky2k** [comment]
@software770  Have your tried the latest stable release of GPS.  version 60.1142.1 was released in March and the are previews of 70.1501.0 available on Nuget.

If you still have the issues can you please provide a small demo sample to make it easy for us to replicate.

Thanks

**Comment by newky2k** [comment]
no response for two weeks so closing
