### ISSUE TITLE
Xamarin.FireBase.Firestore NuGet package is empty

### ISSUE THREAD

**Issue by Midnayt** [xamarin/GooglePlayServicesComponents#87]
### Xamarin.Android Version (eg: 6.0):
8

### Operating System & Version (eg: Mac OSX 10.11):
Win 10

### Google Play Services Version (eg: 8.4.0):
60

### Describe your Issue:
When installing NuGet package there is no source code for working with Firestore

**Comment by Redth** [comment]
This was fixed in a newer release.
