### ISSUE TITLE
Im getting some random crashes "com.google.firebase.iid.zzc.run"

### ISSUE THREAD

**Issue by mfandre** [xamarin/GooglePlayServicesComponents#88]
**Xamarin.Android Version: 6.0**

**Operating System & Version:** windows 10

**Google Play Services Version:**  this `<package id="Xamarin.GooglePlayServices.Base" version="60.1142.0" targetFramework="monoandroid80" />`?

**Describe your Issue:**
I'm getting some random errors at AppCenter.ms. In the logs the app starts and few seconds after they crash.  

The stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
  at android.content.ContextWrapper.getSystemService(ContextWrapper.java:627)
  at com.google.firebase.iid.FirebaseInstanceIdService.zzen
  at com.google.firebase.iid.FirebaseInstanceIdService.zza
  at com.google.firebase.iid.FirebaseInstanceIdService.zza
  at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent
  at com.google.firebase.iid.zzc.run
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)

```

### Steps to Reproduce (with link to sample solution if possible):

**Include any relevant Exception Stack traces, build logs, adb logs:**
Package: magicapp.android
Version Code: 44
Version Name: 1.0.43
Android: 6.0
Android Build: MRA58K
Manufacturer: LG Electronics
Model: LG-X240
CrashReporter Key: 38e73eb5-802c-4c93-8944-8b5219c30747
Start Date: 2017-12-24T00:21:01.396Z
Date: 2017-12-24T00:21:09.95Z

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
  at android.content.ContextWrapper.getSystemService(ContextWrapper.java:627)
  at com.google.firebase.iid.FirebaseInstanceIdService.zzen
  at com.google.firebase.iid.FirebaseInstanceIdService.zza
  at com.google.firebase.iid.FirebaseInstanceIdService.zza
  at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent
  at com.google.firebase.iid.zzc.run
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)

Thread 1:
0   mono.java.lang.RunnableImplementor.n_run(RunnableImplementor.java:-2)
1   mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
2   android.os.Handler.handleCallback(Handler.java:815)
3   android.os.Handler.dispatchMessage(Handler.java:104)
4   android.os.Looper.loop(Looper.java:207)
5   android.app.ActivityThread.main(ActivityThread.java:5765)
6   java.lang.reflect.Method.invoke(Method.java:-2)
7   com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
8   com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

Thread 2778:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:164)
2   java.lang.Thread.run(Thread.java:818)

Thread 2779:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:423)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
4   java.lang.Daemons$FinalizerDaemon.run(Daemons.java:207)
5   java.lang.Thread.run(Thread.java:818)

Thread 2780:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:298)
2   java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:267)
3   java.lang.Thread.run(Thread.java:818)

Thread 2781:
0   dalvik.system.VMRuntime.runHeapTasks(VMRuntime.java:-2)
1   java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:443)
2   java.lang.Thread.run(Thread.java:818)

Thread 2787:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:423)
2   com.google.android.gms.internal.zzccv.run

Thread 2788:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
9   java.lang.Thread.run(Thread.java:818)

Thread 2790:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:580)
2   java.lang.Thread.getAllStackTraces(Thread.java:522)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:788)
4   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:753)
5   com.microsoft.appcenter.crashes.UncaughtExceptionHandler.uncaughtException(UncaughtExceptionHandler.java:15)
6   java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
7   java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

Thread 2794:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:328)
2   android.os.Looper.loop(Looper.java:164)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 2797:
0   com.android.org.conscrypt.NativeCrypto.EVP_SignFinal(NativeCrypto.java:-2)
1   com.android.org.conscrypt.OpenSSLSignature.engineSign(OpenSSLSignature.java:179)
2   java.security.Signature$SignatureImpl.engineSign(Signature.java:686)
3   java.security.Signature.sign(Signature.java:395)
4   com.google.firebase.iid.zzl.zza
5   com.google.firebase.iid.zzl.zzb
6   com.google.firebase.iid.zzl.zza
7   com.google.firebase.iid.zzj.zzb
8   com.google.firebase.iid.zzj.getToken
9   com.google.firebase.iid.FirebaseInstanceId.getToken
10  com.google.firebase.iid.FirebaseInstanceId.zzcfy
11  com.google.firebase.iid.FirebaseInstanceIdService.zza
12  com.google.firebase.iid.FirebaseInstanceIdService.handleIntent
13  com.google.firebase.iid.zzc.run
14  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
15  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
16  java.lang.Thread.run(Thread.java:818)

**My packages:**
` <package id="Xamarin.Firebase.Analytics" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Firebase.Analytics.Impl" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Firebase.Common" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Firebase.Core" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Firebase.Iid" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Firebase.Messaging" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Forms" version="2.5.0.121934" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Base" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Basement" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Tasks" version="60.1142.0" targetFramework="monoandroid80" />
<package id="Xamarin.Android.Support.v4" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="26.1.0.1" targetFramework="monoandroid80" />
... and more other xamarin.android`

**Comment by nbsoftware** [comment]
Having the exact same issue!
Didn't get it until I integrated push notifications through AppCenter.
Any update on this?
Did you also add push notification functionality?
Maybe the problem in the appcenter packages themselves... what version of those are you using?
I'm using version 1.3.0

**Comment by nbsoftware** [comment]
I've finally figured out that it was because of a device connectivity issue (my test Nexus 5X was registered on an old no longer existent WiFi network and no SIM card) hence maybe the random behavior you are seeing.

**Comment by mfandre** [comment]
@nbsoftware And how to fix?

**Comment by nbsoftware** [comment]
Well, in my case, the Firebase dependencies were introduced by older versions of the AppCenter packages. As of 1.3 (and maybe 1.2) they are no longer required. And I don't use Firebase.

I followed this article: https://docs.microsoft.com/en-us/appcenter/sdk/push/migration/xamarin-android to remove those.

And now even the Google's console is not complaining anymore in the pre-launch reports.

But your case might be different.
And that's more a workaround than a real fix...

**Comment by guperrot** [comment]
I got a report from a Galaxy S5 on Android 6.0.1 with App Center 1.8.0 which now depends on Firebase again. Version 60.1142.1 too.

**Comment by newky2k** [comment]
Appears to be an issue with AppCenter which will have a new release in the coming weeks
