### ISSUE TITLE
Update GooglePlayServices components to 11.8.0

### ISSUE THREAD

**Issue by jahmai** [xamarin/GooglePlayServicesComponents#89]
### Xamarin.Android Version (eg: 6.0):

N/A

### Operating System & Version (eg: Mac OSX 10.11):

N/A

### Google Play Services Version (eg: 8.4.0):

11.8.0

### Describe your Issue:

Please update GooglePlayServices components to version 11.8.0

### Steps to Reproduce (with link to sample solution if possible):

N/A

### Include any relevant Exception Stack traces, build logs, adb logs:

N/A

**Comment by EFinley** [comment]
Seconded - in particular, the Nearby Connections API underwent a drastic simplification, but the Xamarin bindings still reflect a pre-v11.0 (!!) version of the API.

**Comment by Redth** [comment]
We're working on newer updates, apologies for the delay.
