### ISSUE TITLE
Xamarin.Firebase.Auth AuthState Listeners Not Working As Intended

### ISSUE THREAD

**Issue by Tristan10** [xamarin/GooglePlayServicesComponents#90]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android Verison 8.1.3.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 Home 16299.192

### Google Play Services Version (eg: 8.4.0):
11.9.75 on test device

### Describe your Issue:
The latest version of Xamarin.Firebase.Auth (60.1142.0) is behaving unexpectedly. Upon `LinkWithCredentialAsync ` completing, the logs indicate that it is notifying the AuthState Listener that the user has been changed. However, the registered listener is never fired.

### Steps to Reproduce (with link to sample solution if possible):
I haven't had time to reproduce this issue on a small scale. I imagine that any project utilizing `LinkWithCredentialAsync` could replicate the issue.

Take a look at this StackOverflow question for my actual code: https://stackoverflow.com/questions/48526713/firebase-linkwithcredentialasync-not-actually-firing-auth-state-listener

### Include any relevant Exception Stack traces, build logs, adb logs:

> 01-30 10:27:41.221 D/AuthState( 5631): Signing in anonymously.
> 
> 01-30 10:27:41.450 D/AuthStateListener( 5631): Auth state was changed.
> 
> 01-30 10:27:41.451 D/Mono    ( 5631): Assembly Ref addref Xamarin.Firebase.Database[0x7f8bffefb900] -> Xamarin.GooglePlayServices.Tasks[0x7f8bffefc000]: 4
> 
> 01-30 10:27:41.457 D/AuthState( 5631): AuthCallback function called.
> 
> 01-30 10:27:43.989 D/FirebaseAuth( 5631): Notifying id token listeners about user ( 8zM08FI8PNRcWW7Zdt7QGQvkM173 ).
> 
> 01-30 10:27:43.989 D/FirebaseAuth( 5631): Notifying auth state listeners about user ( 8zM08FI8PNRcWW7Zdt7QGQvkM173 ).
> 
> 01-30 10:27:43.989 D/FirebaseApp( 5631): Notifying auth state listeners.
> 
> 01-30 10:27:43.989 D/FirebaseApp( 5631): Notified 1 auth state listeners.
> 
> 01-30 10:27:43.989 D/AuthStateListener( 5631): Auth state was changed.
> 
> 01-30 10:27:43.991 D/AuthState( 5631): AuthCallback function called.
> 
> 01-30 10:27:43.996 D/Mono    ( 5631): DllImport searching in: '__Internal' ('(null)').
> 
> 01-30 10:27:43.996 D/Mono    ( 5631): Searching for 'java_interop_jnienv_call_boolean_method'.
> 
> 01-30 10:27:43.996 D/Mono    ( 5631): Probing 'java_interop_jnienv_call_boolean_method'.
> 
> 01-30 10:27:43.996 D/Mono    ( 5631): Found as 'java_interop_jnienv_call_boolean_method'.
> 
> 01-30 10:27:45.316 D/Mono    ( 5631): Assembly Ref addref Xamarin.Firebase.Common[0x7f8bffefb700] -> Xamarin.GooglePlayServices.Basement[0x7f8bffefbf00]: 2
> 
> 01-30 10:27:45.321 D/AuthState( 5631): Linking anonymous account with credentials.
> 
> 01-30 10:27:46.344 D/FirebaseAuth( 5631): Notifying id token listeners about user ( 8zM08FI8PNRcWW7Zdt7QGQvkM173 ).
> 
> 01-30 10:27:46.346 D/FirebaseApp( 5631): Notifying auth state listeners.
> 
> 01-30 10:27:46.346 D/FirebaseApp( 5631): Notified 1 auth state listeners.

Notice that after the final log line, AuthCallback function called does not happen like after the other auth events.

**Comment by jcampana** [comment]
Hi @Tristan10? Can you solve this?
I have the problem with SignInWithCustomToken listeners which nothing happens.
I see in StackOverflow that you solve this downgrading to 42.1021.1. I can't do this because I have many dependencies....

Any solution?

Thanks!

**Comment by newky2k** [comment]
@Tristan10  @jcampana  Can you try the latest preview of GPS, 70.1501.0-preview2, to see if this fixes the issue for you.

Thank you for your patience

**Comment by newky2k** [comment]
no response for two weeks, closing
