### ISSUE TITLE
What is the alternative for GoogleApisForiOSComponents?

### ISSUE THREAD

**Issue by FANMixco** [xamarin/GooglePlayServicesComponents#901]
Fellows, this project was archived without any notification or warning:

https://github.com/xamarin/GoogleApisForiOSComponents

![image](https://github.com/user-attachments/assets/7ed5aa6b-de76-4341-b7fe-c41a9b9aaf94)

![image](https://github.com/user-attachments/assets/e4bcd45d-9ea5-4d19-a5e6-e5c5d97c0a27)

Pretty much, it impacts the .NET for iOS developers. Can someone explain if there will be a MAUI project? Or what shall the iOS devs do? Thanks.

**Comment by jpobst** [comment]
This repository is only for Android components, and our team does not know anything about Apple components.

I would suggest filing an issue in one of these repositories:

- https://github.com/xamarin/xamarin-macios
- https://github.com/dotnet/maui

**Comment by PavloLukianets** [comment]
@FANMixco the most popular alternative for now is this fork https://github.com/AdamEssenmacher/GoogleApisForiOSComponents

or use slim bindings: https://github.com/CommunityToolkit/Maui.NativeLibraryInterop

**Comment by moljac** [comment]
closing this issue
