### ISSUE TITLE
Not able to receive notifications when app is in close state in Android version 7.0

### ISSUE THREAD

**Issue by RamanathanC** [xamarin/GooglePlayServicesComponents#91]
### Xamarin.Android Version (eg: 6.0):
Android Version 7.0

### Describe your Issue:
When app is closed, not able to recieve push notifications.

### Steps to Reproduce (with link to sample solution if possible):
Samsung not working in 7.0, App is not force closed

**Comment by CesareSoldani** [comment]
hi,

I'm also not able to receive notifications once the app has been closed.

**Comment by newky2k** [comment]
@RamanathanC  @CesareSoldani  Could you please provide some more details, such as the version of GPS you are using and if possible a small demo project to make it easier to replicate.

Also can you try both the latest stable version and the preview to see if you can still replicate the issue.

**Comment by CesareSoldani** [comment]
Hi,
I was trying to use Xamarin Forms, which is not initialised when the app was in the background causing a crash. I refactored my code and it is working now.

**Comment by newky2k** [comment]
@CesareSoldani thats great news, thank you for getting back to me
