### ISSUE TITLE
Nearby Connections module uses obsolete pre-v11 API

### ISSUE THREAD

**Issue by EFinley** [xamarin/GooglePlayServicesComponents#92]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android 8.0 (though the API in question should only require 4.4+)

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version (eg: 8.4.0):
11.0.55

### Describe your Issue:
The Google Play Services API for Nearby.Connections was heavily revamped and simplified in Play Services 11.0.55 - see [Changes in v11](https://developers.google.com/nearby/connections/v11-update) - but the Xamarin module does not reflect these API changes and still uses the pre-v11.0 objects, all of which now carry obsolete/deprecated warnings.  No bindings to the new API's classes, such as the basic [ConnectionsClient](https://developers.google.com/android/reference/com/google/android/gms/nearby/connection/ConnectionsClient) or the necessary [ConnectionLifecycleCallback](https://developers.google.com/android/reference/com/google/android/gms/nearby/connection/ConnectionLifecycleCallback) are exposed.

### Steps to Reproduce (with link to sample solution if possible):
Attempt to build the [Nearby Connections sample project](https://github.com/xamarin/monodroid-samples/tree/master/google-services/Nearby/ConnectionsQuickstart), or import Android.Gms.Nearby.Connections and compare exposed methods & classes to the current Nearby Connections API.

### Include any relevant Exception Stack traces, build logs, adb logs:
n/a

**Comment by Redth** [comment]
We are working on newer bindings, apologies for the delay.
