### ISSUE TITLE
Wallet nuget package internal constructors

### ISSUE THREAD

**Issue by iannewson** [xamarin/GooglePlayServicesComponents#94]
### Xamarin.Android Version (eg: 6.0):
Mono Android v8 and 5. Xamarin Android 8.1.

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version (eg: 8.4.0):

11.4.2
--

### Describe your Issue:
Version 29.0.0.2 of the Xamarin.GooglePlayServices.Wallet nuget package seems to contain internal constructors for all the relevant objects. For example, it's currently impossible to instantiate LoyaltyWalletObject.Builder, which makes the library unusable.

**Comment by Redth** [comment]
Have you tried `LoyaltyWalletObject.NewBuilder()` ?
