### ISSUE TITLE
generated.targets

### ISSUE THREAD

**Issue by geedsen** [xamarin/GooglePlayServicesComponents#97]
Just downloaded the source and opened the solution in Visual Studio.
None of the projects can be opened because they are missing a generated.targets for import.

Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.Bindings.targets" />
  <Import Project="..\..\generated.targets" />

**Comment by Redth** [comment]
As part of the build process you need to run `sh build.sh --target=nuget-setup` which generates the generated.targets file
