### ISSUE TITLE
OssLicensesMenuActivity is missing from Xamarin.GooglePlayServices.Oss.Licenses

### ISSUE THREAD

**Issue by kjeremy** [xamarin/GooglePlayServicesComponents#98]
### Xamarin.Android Version (eg: 6.0):
4.9

### Operating System & Version (eg: Mac OSX 10.11):
Win 7

### Google Play Services Version (eg: 8.4.0):
Latest

### Describe your Issue:
Xamarin.GooglePlayServices.Oss.Licenses doesn't contain OssLicensesMenuActivity

### Steps to Reproduce (with link to sample solution if possible):
Install the nuget package and you will notice there is no code in the object browser.

**Comment by Redth** [comment]
This will be fixed in the next release.

**Comment by Redth** [comment]
This is fixed in the prerelease available and will be available in the next stable release, so closing the issue for now.

**Comment by Tviljan** [comment]
@kjeremy have they actually fixed this?

**Comment by kjeremy** [comment]
This was so long ago that I've moved on from Xamarin for newer apps.
