### ISSUE TITLE
Please enable the SceneModeBarcode mode.

### ISSUE THREAD

**Issue by daesang** [xamarin/GooglePlayServicesComponents#99]
### Xamarin.Android Version (eg: 6.0):
Oreo

### Google Play Services Version (eg: 8.4.0):
60.1142.1

### Describe your Issue:
Please enable the SceneModeBarcode mode.
ex)             prams.SceneMode = Android.Hardware.Camera.Parameters.SceneModeBarcode;

**Comment by Redth** [comment]
This sounds more like a request for ZXing.Net.Mobile?  Not sure how this fits into Google Play Services.
